### ISSUE TITLE
感知机训练对硬件的要求

### ISSUE THREAD

**Issue by Zjimily** [hankcs/HanLP#1007]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：v 1.6.8
我使用的版本是：v 1.6.8

## 问题
使用结构化感知机标注框架训练自己的词性标注模型时内存溢出。
1.新闻语料文件夹大小1.7g左右
2.使用命令：java -Xmx30720m -cp hanlp-portable-1.6.8.jar:src/main/resources com.hankcs.hanlp.model.perceptron.Main -task POS -train true -model pos.bin -reference test
3.系统性能如下：
![image](https://user-images.githubusercontent.com/18524483/47700860-e3147d80-dc52-11e8-957a-65fc6c061bb1.png)
4.运行结果如下：
![a5f85674429ccc04acaf8366e186c03](https://user-images.githubusercontent.com/18524483/47700984-50281300-dc53-11e8-9e68-a6ab27f0e81c.png)
请问：
1.词性标注模型训练对内存的要求，另外特征总数达到六亿多这正常吗？
2.您当时训练分词模型large.bin的时候的硬件环境
期望尽快得到您的赐教，谢谢！

**Comment by wchnjstar123** [comment]
我跑过特征数1亿的，速度非常慢，如果压缩就更慢了。内存还好，如果到了这个数量级，感觉要借助分布式或者自定义特征取值？期待其他高手解答。

**Comment by Zjimily** [comment]
训练了特征总数为2亿多，其他的语料尝试用增量训练的方法。
采用的方法：
PerceptronLexicalAnalyzer analyzer = new PerceptronLexicalAnalyzer(HanLP.Config.PerceptronCWSModelPath,
                                                                           HanLP.Config.PerceptronPOSModelPath,
                                                                           HanLP.Config.PerceptronNERModelPath);
 analyzer.learn("   ");
analyzer.getPerceptronPOSTagger().getModel().save(HanLP.Config.PerceptronPOSModelPath);
训练的语料大小为180M左右，句子数75w左右，循环调用learn方法最后再保存模型
出现的问题：
1.增量训练后的pos.bin大小反而比之前小了。
2.特征总数为2亿多的训练语料中有可能出现增量的语料中不存在的词性标签导致报错。信息如下：
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 249902463
	at com.hankcs.hanlp.model.perceptron.model.LinearModel.score(LinearModel.java:371)
	at com.hankcs.hanlp.model.perceptron.model.LinearModel.viterbiDecode(LinearModel.java:312)
	at com.hankcs.hanlp.model.perceptron.model.StructuredPerceptron.update(StructuredPerceptron.java:68)
	at com.hankcs.hanlp.model.perceptron.PerceptronTagger.learn(PerceptronTagger.java:58)
	at com.hankcs.hanlp.model.perceptron.PerceptronTagger.learn(PerceptronTagger.java:70)
	at com.hankcs.hanlp.model.perceptron.PerceptronLexicalAnalyzer.learn(PerceptronLexicalAnalyzer.java:163)
	at com.hankcs.hanlp.model.perceptron.PerceptronLexicalAnalyzer.learn(PerceptronLexicalAnalyzer.java:150)
	at evaluate.Update.main(Update.java:39)
3.增量训练报错后再次运行出现如下错误：
Exception in thread "main" java.lang.NullPointerException
	at com.hankcs.hanlp.corpus.io.ByteArrayFileStream.ensureAvailableBytes(ByteArrayFileStream.java:82)
	at com.hankcs.hanlp.corpus.io.ByteArrayStream.nextFloat(ByteArrayStream.java:84)
	at com.hankcs.hanlp.model.perceptron.model.LinearModel.load(LinearModel.java:439)
	at com.hankcs.hanlp.model.perceptron.model.LinearModel.load(LinearModel.java:388)
	at com.hankcs.hanlp.model.perceptron.model.LinearModel.<init>(LinearModel.java:65)
	at com.hankcs.hanlp.model.perceptron.PerceptronLexicalAnalyzer.<init>(PerceptronLexicalAnalyzer.java:70)
	at evaluate.Update.main(Update.java:27)
4.关于在线学习，在issue#783中你提到多学习几遍就可以了，这个次数可以确定吗？
以上是我的一些问题，不知道是否理解有偏差，还望指教！

**Comment by hankcs** [comment]
1. 据我所知，中文NLP界，目前应该尚不存在1.7g的标注数据。你确定语料库是人民日报格式？
1. 我在一亿字语料库上训练分词模型，特征数为`1960292`，JVM参数为`java  -Xms8g -Xmx16g -Xmn4g`
1. 词性标注提取的特征的确较多，如果加内存无法解决问题，可考虑用CRF++训练。
1. `save`方法未能复现你的问题，如果确信存在，欢迎post出你的bin。增量训练出错的问题，看上去像是模型未能完整保存。同样未能复现。
1. 可以通过循环来做：

```java
        Sentence sentence = Sentence.create("张三/nr 买了/v 张/q 三角桌/n");
        String text = sentence.text();
        PerceptronLexicalAnalyzer analyzer = new PerceptronLexicalAnalyzer();
        analyzer.enableCustomDictionary(false);
        System.out.println(analyzer.analyze(text));
        if (analyzer.analyze(text).equals(sentence))
            return;
        if (sentence.iterator().next().getLabel() == null)
            return;
        // 支持在线学习
        while (!analyzer.analyze(text).toString().equals(sentence.toString()))
        {
            analyzer.learn(sentence.toString());
//            System.out.println(analyzer.analyze(text));
        }
        // 学习到新知识
        System.out.println(analyzer.analyze(text));
```

- 在线学习是不得已而为之，不建议在线学习那么多的样本，因为该过程无法创建新特征，而是利用旧特征去“过拟合”新样本。
- 你可能需要阅读相关论文才能理解增量学习的意义，它不可能学习新标签。

**Comment by Zjimily** [comment]
多谢回复，报错的地方现在我也没有复现了，这样的语料进行词性标注训练需要64G以上内存。

**Comment by bosen365** [comment]
@Zjimily 您好，请问您使用64G以上内存训练时，训练用了多长时间？以及训练处的向量集文件有多少G？

**Comment by Zjimily** [comment]
> @Zjimily 您好，请问您使用64G以上内存训练时，训练用了多长时间？以及训练出的向量结果集文件有多少G？

训练2天左右，模型文件有1.4g

**Comment by bosen365** [comment]
@Zjimily 我分词后的文件有1.4个+G。你说的模型文件是指输入的分词文件，还是输出的vec向量集文件啊

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
