### ISSUE TITLE
感知机报错

### ISSUE THREAD

**Issue by Zjimily** [hankcs/HanLP#1031]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.6.8
我使用的版本是：1.6.8

## 我的问题
1.语料采用2014年的标注标准，用感知机训练词性标注模型，之后测试“整车可动性差"报错
日志信息如下：
Exception in thread "main" java.lang.IllegalArgumentException: 在打分时传入了非法的下标
	at com.hankcs.hanlp.model.perceptron.model.LinearModel.score(LinearModel.java:366)
	at com.hankcs.hanlp.model.perceptron.model.LinearModel.viterbiDecode(LinearModel.java:296)
	at com.hankcs.hanlp.model.perceptron.PerceptronPOSTagger.tag(PerceptronPOSTagger.java:72)
	at com.hankcs.hanlp.model.perceptron.PerceptronPOSTagger.tag(PerceptronPOSTagger.java:65)
	at com.hankcs.hanlp.tokenizer.lexical.AbstractLexicalAnalyzer.tag(AbstractLexicalAnalyzer.java:154)
	at com.hankcs.hanlp.tokenizer.lexical.AbstractLexicalAnalyzer.analyze(AbstractLexicalAnalyzer.java:193)

2.采用更多语料训练词性标注，加载模型报错
日志信息如下：
Exception in thread "main" java.lang.IllegalArgumentException
	at java.nio.ByteBuffer.allocate(ByteBuffer.java:334)
	at com.hankcs.hanlp.corpus.io.ByteArrayFileStream.ensureAvailableBytes(ByteArrayFileStream.java:83)
	at com.hankcs.hanlp.corpus.io.ByteArrayStream.nextInt(ByteArrayStream.java:56)
	at com.hankcs.hanlp.collection.trie.datrie.IntArrayList.load(IntArrayList.java:182)
	at com.hankcs.hanlp.collection.trie.datrie.MutableDoubleArrayTrieInteger.load(MutableDoubleArrayTrieInteger.java:1185)
	at com.hankcs.hanlp.model.perceptron.feature.ImmutableFeatureMDatMap.load(ImmutableFeatureMDatMap.java:93)
	at com.hankcs.hanlp.model.perceptron.model.LinearModel.load(LinearModel.java:421)
	at com.hankcs.hanlp.model.perceptron.model.LinearModel.load(LinearModel.java:388)
	at com.hankcs.hanlp.model.perceptron.model.LinearModel.<init>(LinearModel.java:65)
	at com.hankcs.hanlp.model.perceptron.PerceptronLexicalAnalyzer.<init>(PerceptronLexicalAnalyzer.java:75)

**Comment by hankcs** [comment]
看上去像是特征特别多，超出双数组所能存储的上限。你的语料库有多少字？

**Comment by hankcs** [comment]
的确，由于POS特征模板较复杂，这么大的语料提取的特征数可能超过十亿了。`ImmutableFeatureMDatMap`最大能储存的特征数是`1073741824`，超过了就会出问题。你可以试试

1. 将其替换为`com.hankcs.hanlp.model.perceptron.feature.MutableFeatureMap`。
1. 或者注释掉一些[特征](https://github.com/hankcs/HanLP/blob/48347f489316b19d75ef6a0ed8e2620a5b5de911/src/main/java/com/hankcs/hanlp/model/perceptron/instance/POSInstance.java#L52)。

**Comment by Zjimily** [comment]
多谢你的建议，我试试看再反馈

**Comment by Zjimily** [comment]
将其替换为com.hankcs.hanlp.model.perceptron.feature.MutableFeatureMap 对应我的第二个问题是修改LinearModel.load()方法？
我调用的方法是 ：
PerceptronLexicalAnalyzer analyzer = new PerceptronLexicalAnalyzer( HanLP.Config.PerceptronCWSModelPath,HanLP.Config.PerceptronPOSModelPath,HanLP.Config.PerceptronNERModelPath);
analyzer.analyze("");     
我看MutableFeatureMap里构建的TreeMap，ImmutableFeatureMDatMap最大能储存的特征数是1073741824就是DoubleArrayTrie的最大存储值，不知道DoubleArrayTrie是否可以修改其最大值。
还望赐教。

**Comment by hankcs** [comment]
应当尽量避免DoubleArrayTrie等数据结构，直接用TreeMap。你可能需要将所有试图创建其他FeatureMap的地方替换为MutableFeatureMap，包括序列化反序列化。

**Comment by huminghe** [comment]
@Zjimily 请问你有解决这个问题么？我换用了 MutableFeatureMap 依然会报错
java.lang.ArrayIndexOutOfBoundsException: 64532884
        at com.hankcs.hanlp.model.perceptron.model.LinearModel.score(LinearModel.java:372)
        at com.hankcs.hanlp.model.perceptron.model.LinearModel.viterbiDecode(LinearModel.java:313)

**Comment by huminghe** [comment]
顺便请教一下作者，我的问题是这样的：
1. 如果我在 load 模型时将 FeatureMap 转化为 MutableFeatureMap，那么还是会报 java.lang.ArrayIndexOutOfBoundsException: 64532884
at com.hankcs.hanlp.model.perceptron.model.LinearModel.score(LinearModel.java:372)
at com.hankcs.hanlp.model.perceptron.model.LinearModel.viterbiDecode(LinearModel.java:313)
的错误。
2. 如果我在训练后将模型以 MutableFeatureMap 进行保存，然后通过 FeatureMap 的 load(ByteArray byteArray) 进行读取，那么读取时会报错（MutableFeatureMap 没有重写 save 和 load 的方法）。我是否应该 override 这两个方法然后以 MutableFeatureMap 进行保存和读取加载

**Comment by hankcs** [comment]
1. load的时候读取的FeatureMap是ImmutableFeatureMap，不可能直接装入MutableFeatureMap。保存和读取时必须保证是同一种FeatureMap。
1. 是的，你可以参考ImmutableFeatureMap的save/load。

另外，2014的语料库是机器标注，其质量根本不值得拿来训练POS模型。

**Comment by huminghe** [comment]
好的，谢谢

**Comment by huminghe** [comment]
补充一下，看到 POS 模型，我发现我和原始问题还是有一些区别的，应该不涉及能够存储的特征数。我是使用 CWS 模型时出的错误，报错信息为：
java.lang.IllegalArgumentException: 在打分时传入了非法的下标
        at com.hankcs.hanlp.model.perceptron.model.LinearModel.score(LinearModel.java:366)
        at com.hankcs.hanlp.model.perceptron.model.LinearModel.viterbiDecode(LinearModel.java:312)
        at com.hankcs.hanlp.model.perceptron.PerceptronSegmenter.segment(PerceptronSegmenter.java:78)
        at com.hankcs.hanlp.model.perceptron.PerceptronSegmenter.segment(PerceptronSegmenter.java:72)
        at com.hankcs.hanlp.tokenizer.lexical.AbstractLexicalAnalyzer.segmentAfterRule(AbstractLexicalAnalyzer.java:535)
        at com.hankcs.hanlp.tokenizer.lexical.AbstractLexicalAnalyzer.segmentWithAttribute(AbstractLexicalAnalyzer.java:595)
        at com.hankcs.hanlp.tokenizer.lexical.AbstractLexicalAnalyzer.analyze(AbstractLexicalAnalyzer.java:216)
也就是说 feature 的 index < -1 || index >= featureMap.size()
这个 feature 的 index 是通过下面的方式获取的
    protected static void addFeature(CharSequence rawFeature, List<Integer> featureVector, FeatureMap featureMap)
    {
        int id = featureMap.idOf(rawFeature.toString());
        if (id != -1)
        {
            featureVector.add(id);
        }
    }
按理说这个 idOf 的方法的返回值应该是在 featureMap 的 size 范围内的。那么是不是说明 ImmutableFeatureMDatMap 的 idOf 方法可能偶尔会有这个 bug？

**Comment by hankcs** [comment]
如果你的featureMap加载不当、储存值超过限制，就会返回-1。如果你觉得有问题，欢迎单步一下。

**Comment by huminghe** [comment]
好的，感谢

**Comment by Zjimily** [comment]
@huminghe 请问你训练和加载的改为MutableFeatureMap之后可以正常运行吗

**Comment by hankcs** [comment]
早期版本是用HashMap实现的，可供参考：https://github.com/hankcs/HanLP/commit/0541b1e22e4576bc7d02fef31e086f7c497cb558

**Comment by huminghe** [comment]
> @huminghe 请问你训练和加载的改为MutableFeatureMap之后可以正常运行吗

好像不能吧
我后来在 com.hankcs.hanlp.model.perceptron.instance.Instance 中增加了一下判断条件
`    protected static void addFeature(CharSequence rawFeature, List<Integer> featureVector, FeatureMap featureMap)
    {
        int id = featureMap.idOf(rawFeature.toString());
        if (id != -1 && id < featureMap.size())
        {
            featureVector.add(id);
        }
    }`

**Comment by Zjimily** [comment]
非常感谢大家的回复

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
