### ISSUE TITLE
使用hanlp分词造成内存泄漏

### ISSUE THREAD

**Issue by xchechi123x** [hankcs/HanLP#1062]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕

## 版本号

当前最新版本号是：1.7.1
我使用的版本是：1.7.1

## 使用hanlp分词做为elasticsearch的分词器

使用hanlp 1.7.1做为elasticsearch的分词器,启动之后内存消耗上升,之后出现java.lang.OutOfMemoryError: Java heap space Java的内存分配为2g
jvm 内存分配参数 
-Xms2g
-Xmx2g

## 复现问题
暂无

### 步骤
暂无
### 触发代码
    @Override
    public boolean load(ByteArray byteArray)
    {
        if (byteArray == null)
            return false;
        featureMap = new ImmutableFeatureMDatMap();
        featureMap.load(byteArray);
        int size = featureMap.size();
        TagSet tagSet = featureMap.tagSet;
        if (tagSet.type == TaskType.CLASSIFICATION)
        {
            parameter = new float[size];
            for (int i = 0; i < size; i++)
            {
                parameter[i] = byteArray.nextFloat();
            }
        }
        else
        {
            parameter = new float[size * tagSet.size()];
            for (int i = 0; i < size; i++)
            {
                for (int j = 0; j < tagSet.size(); ++j)
                {
                    parameter[i * tagSet.size() + j] = byteArray.nextFloat();
                }
            }
        }
//        assert !byteArray.hasMore();
//        byteArray.close();
        if (!byteArray.hasMore())
            byteArray.close();
        return true;
    }
### 期望输出

```
期望输出
```

### 实际输出

```
实际输出
```

## 其他信息
错误日志信息
[2018-12-25T20:20:51,407][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [chechi] fatal error in thread [elasticsearch[chechi][masterService#updateTask][T#1]], exiting
java.lang.OutOfMemoryError: Java heap space
	at com.hankcs.hanlp.collection.trie.datrie.IntArrayList.load(IntArrayList.java:180) ~[?:?]
	at com.hankcs.hanlp.collection.trie.datrie.MutableDoubleArrayTrieInteger.load(MutableDoubleArrayTrieInteger.java:1185) ~[?:?]
	at com.hankcs.hanlp.model.perceptron.feature.ImmutableFeatureMDatMap.load(ImmutableFeatureMDatMap.java:93) ~[?:?]
	at com.hankcs.hanlp.model.perceptron.model.LinearModel.load(LinearModel.java:421) ~[?:?]
	at com.hankcs.hanlp.model.perceptron.model.LinearModel.load(LinearModel.java:388) ~[?:?]
	at com.hankcs.hanlp.model.perceptron.model.LinearModel.<init>(LinearModel.java:65) ~[?:?]
	at com.hankcs.hanlp.model.perceptron.PerceptronLexicalAnalyzer.<init>(PerceptronLexicalAnalyzer.java:70) ~[?:?]
	at com.hankcs.hanlp.model.perceptron.PerceptronLexicalAnalyzer.<init>(PerceptronLexicalAnalyzer.java:95) ~[?:?]
	at com.hankcs.hanlp.HanLP.newSegment(HanLP.java:685) ~[?:?]
	at org.elasticsearch.plugin.hanlp.conf.ConfigHelper.lambda$getSegment$0(ConfigHelper.java:149) ~[?:?]
	at org.elasticsearch.plugin.hanlp.conf.ConfigHelper$$Lambda$2916/0x0000000800aed840.run(Unknown Source) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at org.elasticsearch.plugin.hanlp.conf.ConfigHelper.getSegment(ConfigHelper.java:132) ~[?:?]
	at org.elasticsearch.plugin.hanlp.analysis.HanLPAnalyzerProvider.<init>(HanLPAnalyzerProvider.java:35) ~[?:?]
	at org.elasticsearch.plugin.hanlp.analysis.HanLPAnalyzerProvider.getPerceptronAnalyzerProvider(HanLPAnalyzerProvider.java:51) ~[?:?]
	at org.elasticsearch.plugin.hanlp.AnalysisHanLPPlugin$$Lambda$778/0x0000000800512840.get(Unknown Source) ~[?:?]
	at org.elasticsearch.index.analysis.AnalysisRegistry.buildMapping(AnalysisRegistry.java:367) ~[elasticsearch-6.5.4.jar:6.5.4]
	at org.elasticsearch.index.analysis.AnalysisRegistry.buildAnalyzerFactories(AnalysisRegistry.java:191) ~[elasticsearch-6.5.4.jar:6.5.4]
	at org.elasticsearch.index.analysis.AnalysisRegistry.build(AnalysisRegistry.java:160) ~[elasticsearch-6.5.4.jar:6.5.4]
	at org.elasticsearch.index.IndexService.<init>(IndexService.java:165) ~[elasticsearch-6.5.4.jar:6.5.4]
	at org.elasticsearch.index.IndexModule.newIndexService(IndexModule.java:397) ~[elasticsearch-6.5.4.jar:6.5.4]
	at org.elasticsearch.indices.IndicesService.createIndexService(IndicesService.java:503) ~[elasticsearch-6.5.4.jar:6.5.4]
	at org.elasticsearch.indices.IndicesService.createIndex(IndicesService.java:457) ~[elasticsearch-6.5.4.jar:6.5.4]
	at org.elasticsearch.cluster.metadata.MetaDataIndexTemplateService.validateAndAddTemplate(MetaDataIndexTemplateService.java:233) ~[elasticsearch-6.5.4.jar:6.5.4]
	at org.elasticsearch.cluster.metadata.MetaDataIndexTemplateService.access$300(MetaDataIndexTemplateService.java:64) ~[elasticsearch-6.5.4.jar:6.5.4]
	at org.elasticsearch.cluster.metadata.MetaDataIndexTemplateService$2.execute(MetaDataIndexTemplateService.java:174) ~[elasticsearch-6.5.4.jar:6.5.4]
	at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:45) ~[elasticsearch-6.5.4.jar:6.5.4]
	at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:639) ~[elasticsearch-6.5.4.jar:6.5.4]
	at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:268) ~[elasticsearch-6.5.4.jar:6.5.4]
	at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:198) ~[elasticsearch-6.5.4.jar:6.5.4]
	at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:133) ~[elasticsearch-6.5.4.jar:6.5.4]
	at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150) ~[elasticsearch-6.5.4.jar:6.5.4]

**Comment by hankcs** [comment]
1. 报错位于模型加载，请确认加载了几个模型，模型大小如何，除去业务代码还剩多少内存
1. 程序启动时报错肯定不是内存泄露
1. 本次更新没有修改感知机代码

**Comment by NikolaDai** [comment]
我想问问你用的是hanlp的elasticsearch的哪个插件？

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
