### ISSUE TITLE
DoubleArrayTrie的save和load疑问

### ISSUE THREAD

**Issue by CrazyBuug** [hankcs/HanLP#1068]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [ ] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.7.1-release
我使用的版本是：1.7.1-release

## 我的问题

DoubleArrayTrie 成功build之后save到磁盘 然后在load发现没有找到term对应的value
猜测save其实只是持久化了双数组字典树，value并没有持久化，如果想满足这种需求该如何改造？

### 步骤

1. 首先……
2. 然后……
3. 接着……

### 触发代码

```
    @org.junit.Test
    public void DoubleArrayTrie(){
        String text = "我在武汉市长江大桥上见到武汉市长le";
        TreeMap<String, String> map = new TreeMap<>();
        String[] termArray = new String[]
                {
                        "武汉,wh",
                        "武汉市长江大桥,wuhan shi chang jiang daqiao"
                };
        for (String term : termArray) {
            String[] t = StringUtils.split(term,",");
            map.put(t[0], t[1]);
            map.put(t[1], t[0]);
        }
        DoubleArrayTrie<String> act = new DoubleArrayTrie<>();
        act.build(map);
        System.out.println(act.toString());
        act.parseLongestText(text, new AhoCorasickDoubleArrayTrie.IHit<String>(){
            @Override
            public void hit(int begin, int end, String value) {
                System.out.printf("[%d:%d]=%s\n", begin, end, value);
            }
        });
        act.save("/data/trie.txt");

        DoubleArrayTrie<String> act1 = new DoubleArrayTrie<>();
        act1.load("/data/trie.txt");
        System.out.println(act1.toString());
        System.out.println(act1.get("武汉"));
    }
```

### 期望输出

```
DoubleArrayTrie{size=51791, allocSize=2097152, key=null, keySize=4, progress=4, nextCheckPos=38277, error_=0}
[2:9]=wuhan shi chang jiang daqiao
[12:14]=wh
DoubleArrayTrie{size=51791, allocSize=2097152, key=null, keySize=4, progress=4, nextCheckPos=38277, error_=0}
wh
```
### 实际输出

```
DoubleArrayTrie{size=51791, allocSize=2097152, key=null, keySize=4, progress=4, nextCheckPos=38277, error_=0}
[2:9]=wuhan shi chang jiang daqiao
[12:14]=wh
DoubleArrayTrie{size=51791, allocSize=0, key=null, keySize=0, progress=0, nextCheckPos=0, error_=0}

java.lang.NullPointerException
	at com.hankcs.hanlp.collection.trie.DoubleArrayTrie.getValueAt(DoubleArrayTrie.java:985)
	at com.hankcs.hanlp.collection.trie.DoubleArrayTrie.get(DoubleArrayTrie.java:999)
	at com.hanlp.Test.DoubleArrayTrie(Test.java:84)
```

**Comment by hankcs** [comment]
你好，感谢反馈。
由于未按要求填写，本issue被自动关闭。请按[issue模板](https://github.com/hankcs/HanLP/blob/master/.github/ISSUE_TEMPLATE.md)认真填写，然后耐心等待下周末处理。
开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
![issue](http://wx1.sinaimg.cn/large/006Fmjmcly1ft2hnlwc22j30q90bcgpe.jpg)
