### ISSUE TITLE
reload加载错误ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by cy576013581** [hankcs/HanLP#1100]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕

## 版本号

当前最新版本号是：1.7.1
我使用的版本是：1.7.1

## 我的问题
在词库进行reload操作时出现数组溢出，在1.7.0版本中没有该问题。
是否和1.7.1修改reload生成自定义词典bin文件在重新载入时抛出异常ArrayIndexOutOfBoundsException #1028该问题有关

### 步骤
`在CustomDictionary类的loadMainDictionary方法中dat.build(map);时发生异常。
经过跟踪发现在DoubleArrayTrie的

```
   private int resize(int newSize)
    {
        int[] base2 = new int[newSize];
        int[] check2 = new int[newSize];
        if (allocSize > 0)
        {
            System.arraycopy(base, 0, base2, 0, allocSize);
            System.arraycopy(check, 0, check2, 0, allocSize);
        }

        base = base2;
        check = check2;

        return allocSize = newSize;
    }
```
在System.arraycopy(base, 0, base2, 0, allocSize);中base做为拷贝源数据长度为1426181
base2的长度为2097152，而allocSize复制长度也为2097152，导致数据溢出
### 触发代码

```
   HanLP.segment("自然语言处理");
   CustomDictionary.reload();
```
### 期望输出

正常重载

### 实际输出

```
警告: 自定义词典./work/data/dictionary/custom/CustomDictionary.txt缓存失败！
java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 2097152 out of bounds for int[1426181]
	at java.base/java.lang.System.arraycopy(Native Method)
	at com.hankcs.hanlp.collection.trie.DoubleArrayTrie.resize(DoubleArrayTrie.java:94)
	at com.hankcs.hanlp.collection.trie.DoubleArrayTrie.build(DoubleArrayTrie.java:403)
	at com.hankcs.hanlp.collection.trie.DoubleArrayTrie.build(DoubleArrayTrie.java:338)
	at com.hankcs.hanlp.collection.trie.DoubleArrayTrie.build(DoubleArrayTrie.java:365)
	at com.hankcs.hanlp.collection.trie.DoubleArrayTrie.build(DoubleArrayTrie.java:378)
	at com.hankcs.hanlp.dictionary.CustomDictionary.loadMainDictionary(CustomDictionary.java:107)
	at com.hankcs.hanlp.dictionary.CustomDictionary.loadMainDictionary(CustomDictionary.java:157)
	at com.hankcs.hanlp.dictionary.CustomDictionary.reload(CustomDictionary.java:657)
	at com.gildata.removal.Test_Hanlp.main(Test_Hanlp.java:21)
```

## 其他信息
希望能够指教一下

**Comment by hankcs** [comment]
感谢反馈，已经修复，请参考上面的commit。
如果还有问题，欢迎重开issue。
