### ISSUE TITLE
WordVectorModel API加载模型出现空指针错误

### ISSUE THREAD

**Issue by duanbing** [hankcs/HanLP#1129]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：portable-1.7.2
我使用的版本是：portable-1.7.2

## 我的问题

使用
```
java  -cp ~/.m2/repository/com/hankcs/hanlp/portable-1.7.2/hanlp-portable-1.7.2.jar: com.hankcs.hanlp.mining.word2vec.Train  -input ./data/hanlp-wiki-vec-zh/hanlp-wiki-vec-zh.txt -output data/hanlp-wiki-vec-zh.model
```
训练得到模型文件之后，使用

```
DocVectorModel docVectorModel = new DocVectorModel(new WordVectorModel(MODEL_FILE_NAME));
```
加载报错如下：
```
java.lang.NullPointerException
	at com.hankcs.hanlp.mining.word2vec.WordVectorModel.loadVectorMap(WordVectorModel.java:40)
	at com.hankcs.hanlp.mining.word2vec.WordVectorModel.<init>(WordVectorModel.java:32)
```

### 步骤

1. 首先……
2. 然后……
3. 接着……

### 触发代码

```
DocVectorModel docVectorModel = new DocVectorModel(new WordVectorModel(MODEL_FILE_NAME));
float sim = docVectorModel.similarity(doc1,doc2);
...

```
### 期望输出

正常计算得到sim

### 实际输出

出现空指针错误。

**Comment by duanbing** [comment]
已解决。模型路径不能使用相对路径。
