### ISSUE TITLE
hanlp segment分词失败

### ISSUE THREAD

**Issue by cdlwhm1217096231** [hankcs/HanLP#1217]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [ ] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：hanlp-1.7.4.jar    
我使用的版本是：hanlp-1.7.4.jar    

## 我的问题

windows系统cmd命令行模式下，输入hanlp segment分词报错，输入hanlp serve在线正常
## 复现问题

将data文件夹放入D:\python35\Lib\site-packages\pyhanlp\static文件夹下，同时修改了hanlp.properties中的root路径为D:\python35\Lib\site-packages\pyhanlp\static
### 步骤

1. 首先……
2. 然后……
3. 接着……

### 触发代码

```
Traceback (most recent call last):
  File "d:\python35\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\python35\Scripts\hanlp.exe\__main__.py", line 9, in <module>
  File "d:\python35\lib\site-packages\pyhanlp\main.py", line 99, in main
    print(' '.join(term.toString() for term in segmenter.seg(any2utf8(line))))
TypeError: sequence item 0: expected str instance, java.lang.String found
```
### 期望输出

正确的分词结果
```
期望输出
```

### 实际输出

```
Traceback (most recent call last):
  File "d:\python35\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\python35\Scripts\hanlp.exe\__main__.py", line 9, in <module>
  File "d:\python35\lib\site-packages\pyhanlp\main.py", line 99, in main
    print(' '.join(term.toString() for term in segmenter.seg(any2utf8(line))))
TypeError: sequence item 0: expected str instance, java.lang.String found
```

**Comment by hankcs** [comment]
`print(' '.join(term.word for term in HanLP.segment('下雨天地面积水')))`

**Comment by cdlwhm1217096231** [comment]
也不行哦，老哥
Traceback (most recent call last):
  File "d:\python35\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\python35\Scripts\hanlp.exe\__main__.py", line 9, in <module>
  File "d:\python35\lib\site-packages\pyhanlp\main.py", line 99, in main
    print(' '.join(term.toString() for term in segmenter.seg(any2utf8(line))))
TypeError: sequence item 0: expected str instance, java.lang.String found

C:\Users\Administrator>hanlp segment
print(' '.join(term.word for term in HanLP.segment('下雨天地面积水')))
Traceback (most recent call last):
  File "d:\python35\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\python35\Scripts\hanlp.exe\__main__.py", line 9, in <module>
  File "d:\python35\lib\site-packages\pyhanlp\main.py", line 99, in main
    print(' '.join(term.toString() for term in segmenter.seg(any2utf8(line))))
TypeError: sequence item 0: expected str instance, java.lang.String found

**Comment by hankcs** [comment]
噢，你可能在用`JPype1-0.7.0`。新版本建议手动转类型，即`print(' '.join(str(term.word) for term in HanLP.segment('下雨天地面积水')))`。

```
UserWarning: 
-------------------------------------------------------------------------------
Deprecated: convertStrings was not specified when starting the JVM. The default
behavior in JPype will be False starting in JPype 0.8. The recommended setting
for new code is convertStrings=False.  The legacy value of True was assumed for
this session. If you are a user of an application that reported this warning,
please file a ticket with the developer.
-------------------------------------------------------------------------------
```

**Comment by cdlwhm1217096231** [comment]
解决了，谢谢！重新用JPype1-0.6.3-cp35-cp35m-win_amd64.whl文件安装了一下，然后java的.jar包版本一定要与data中的version.txt中的版本要一致！

**Comment by hankcs** [comment]
我觉得JPype1-0.7.0推荐的convertStrings=False不方便，还是改成自动转换吧。

**Comment by WuKong-code** [comment]
![image](https://user-images.githubusercontent.com/26157917/111901259-003f8600-8a72-11eb-8e11-f25db025f1a1.png)

**Comment by WuKong-code** [comment]
可以分词，但是... 请问怎么解决
![image](https://user-images.githubusercontent.com/26157917/111901280-25cc8f80-8a72-11eb-88c2-c1af27431b95.png)
