### ISSUE TITLE
 raise ValueError( ValueError: 配置错误: 数据包 C:/Users/15761/Anaconda3/envs/python38/Lib/site-packages/pyhanlp/static\data 不存在，请修改配置文件中的root

### ISSUE THREAD

**Issue by zengqingfa** [hankcs/HanLP#1352]
## 我的问题
报错信息：
(python38) C:\Users\15761>hanlp
Traceback (most recent call last):
  File "c:\users\15761\anaconda3\envs\python38\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\15761\anaconda3\envs\python38\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\15761\Anaconda3\envs\python38\Scripts\hanlp.exe\__main__.py", line 4, in <module>
  File "c:\users\15761\anaconda3\envs\python38\lib\site-packages\pyhanlp\__init__.py", line 145, in <module>
    _start_jvm_for_hanlp()
  File "c:\users\15761\anaconda3\envs\python38\lib\site-packages\pyhanlp\__init__.py", line 75, in _start_jvm_for_hanlp
    raise ValueError(
ValueError: 配置错误: 数据包 C:/Users/15761/Anaconda3/envs/python38/Lib/site-packages/pyhanlp/static\data 不存在，请修改配置文件中的root

我已经按下面链接里的做了,把`data`
https://github.com/hankcs/pyhanlp/wiki/%E6%89%8B%E5%8A%A8%E9%85%8D%E7%BD%AE
![image](https://user-images.githubusercontent.com/39977054/70859711-b7d21800-1f52-11ea-88f3-062572949e2c.png)

但是还是不行
![image](https://user-images.githubusercontent.com/39977054/70859720-d6381380-1f52-11ea-8fd5-6d8243eaebde.png)

**Comment by gamesir2** [comment]
把data-for-1.7.5文件夹里的data文件夹放到static目录

**Comment by zengqingfa** [comment]
@gamesir2 非常感谢！
