### ISSUE TITLE
词性分析的过程中报错

### ISSUE THREAD

**Issue by lemonsuan** [hankcs/HanLP#1378]
python 版本:3.7.4
hanlp  版本:2.0.0a5
报错信息:
`
Traceback (most recent call last):
  File "/home/cy/liunx_work_26/hanlp_eg.py", line 15, in <module>
    print(tagger.predict(['我', '的', '希望', '是', '希望', '和平']))
  File "/home/cy/anaconda3/lib/python3.7/site-packages/hanlp/components/taggers/rnn_tagger.py", line 47, in predict
    return super().predict(sents, batch_size)
  File "/home/cy/anaconda3/lib/python3.7/site-packages/hanlp/common/component.py", line 445, in predict
    for output in self.predict_batch(batch, inputs=inputs):
  File "/home/cy/anaconda3/lib/python3.7/site-packages/hanlp/common/component.py", line 455, in predict_batch
    Y = self.model.predict_on_batch(X)
  File "/home/cy/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 1240, in predict_on_batch
    return training_v2_utils.predict_on_batch(self, x, standalone=True)
  File "/home/cy/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 556, in predict_on_batch
    return predict_on_batch_fn(inputs)  # pylint: disable=not-callable
  File "/home/cy/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 822, in __call__
    outputs = self.call(cast_inputs, *args, **kwargs)
  File "/home/cy/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/sequential.py", line 267, in call
    return super(Sequential, self).call(inputs, training=training, mask=mask)
  File "/home/cy/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/network.py", line 717, in call
    convert_kwargs_to_constants=base_layer_utils.call_context().saving)
  File "/home/cy/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/network.py", line 891, in _run_internal_graph
    output_tensors = layer(computed_tensors, **kwargs)
  File "/home/cy/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/layers/wrappers.py", line 543, in __call__
    return super(Bidirectional, self).__call__(inputs, **kwargs)
  File "/home/cy/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 822, in __call__
    outputs = self.call(cast_inputs, *args, **kwargs)
  File "/home/cy/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/layers/wrappers.py", line 657, in call
    initial_state=forward_state, **kwargs)
  File "/home/cy/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/layers/recurrent.py", line 644, in __call__
    return super(RNN, self).__call__(inputs, **kwargs)
  File "/home/cy/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 822, in __call__
    outputs = self.call(cast_inputs, *args, **kwargs)
  File "/home/cy/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/layers/recurrent_v2.py", line 1147, in call
    **normal_lstm_kwargs)
  File "/home/cy/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/layers/recurrent_v2.py", line 1281, in standard_lstm
    if sequence_lengths is not None else timesteps)
  File "/home/cy/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/backend.py", line 3897, in rnn
    if mask.dtype != dtypes_module.bool:
TypeError: data type not understood
`

**Comment by lemonsuan** [comment]
报错格式化附加到文件中
[error.txt](https://github.com/hankcs/HanLP/files/4021716/error.txt)

**Comment by hankcs** [comment]
你用的TensorFlow版本正确吗？https://github.com/hankcs/HanLP/blob/master/setup.py#L37

**Comment by lemonsuan** [comment]
tensorflow                         2.1.0rc2  
tensorflow-estimator               2.1.0  
fasttext                           0.9.1     
transformers                       2.3.0

**Comment by hankcs** [comment]
奇怪，python3.6能运行吗？

**Comment by lemonsuan** [comment]
暂时没有3.6的版本 我等下去切换一下版本试一下

**Comment by hankcs** [comment]
还有一种可能，GPU版本下测试通过，但CPU版有影响。

```
$ pip3 list | grep tensorflow
tensorflow            2.1.0rc2             
tensorflow-estimator  2.1.0                
tensorflow-gpu        2.1.0rc2    
```

**Comment by hankcs** [comment]
感谢反馈，已经修复，请参考上面的commit。
如果还有问题，欢迎重开issue。
