### ISSUE TITLE
命令行输入Hanlp后出错

### ISSUE THREAD

**Issue by lambda-growth** [hankcs/HanLP#1383]
Traceback (most recent call last):
  File "e:\coding\annoconda\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "e:\coding\annoconda\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\coding\annoconda\Scripts\hanlp.exe\__main__.py", line 5, in <module>
  File "e:\coding\annoconda\lib\site-packages\pyhanlp\__init__.py", line 145, in <module>
    _start_jvm_for_hanlp()
  File "e:\coding\annoconda\lib\site-packages\pyhanlp\__init__.py", line 133, in _start_jvm_for_hanlp
    HANLP_JVM_XMX, convertStrings=True)
  File "e:\coding\annoconda\lib\site-packages\jpype\_core.py", line 219, in startJVM
    _jpype.startup(jvmpath, tuple(args), ignoreUnrecognized, convertStrings)
jpype._jclass.UnsupportedClassVersionError: org/jpype/classloader/JPypeClassLoader : Unsupported major.minor version 52.0

**Comment by hankcs** [comment]
https://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html
