### ISSUE TITLE
文件加载报错

### ISSUE THREAD

**Issue by questionlin** [hankcs/HanLP#1384]
https://file.hankcs.com/hanlp/cws/ctb6-convseg-cws_20191230_184525.zip was created with hanlp-2.0.0, but you are running 2.0.0-alpha.10. Try to upgrade hanlp with

**Comment by hankcs** [comment]
能把这句之前的报错信息也贴上吗？

**Comment by questionlin** [comment]
@hankcs 
Python 3.7.3 (default, Mar 27 2019, 16:54:48) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.6.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import hanlp                                                                               

In [2]: tokenizer = hanlp.load('CTB6_CONVSEG') 
   ...:                                                                                            
Failed to load https://file.hankcs.com/hanlp/cws/ctb6-convseg-cws_20191230_184525.zip. See stack trace below
Traceback (most recent call last):
  File "/Users/simonlin/anaconda3/lib/python3.7/site-packages/hanlp/utils/component_util.py", line 36, in load_from_meta_file
    obj.load(save_dir)
  File "/Users/simonlin/anaconda3/lib/python3.7/site-packages/hanlp/common/component.py", line 231, in load
    self.build(**merge_dict(self.config, training=False, logger=logger, **kwargs, overwrite=True, inplace=True))
  File "/Users/simonlin/anaconda3/lib/python3.7/site-packages/hanlp/common/component.py", line 242, in build
    loss=kwargs.get('loss', None)))
  File "/Users/simonlin/anaconda3/lib/python3.7/site-packages/hanlp/components/taggers/ngram_conv/ngram_conv_tagger.py", line 153, in build_model
    word_embed = build_embedding(word_embed, word_vocab, self.transform)
  File "/Users/simonlin/anaconda3/lib/python3.7/site-packages/hanlp/layers/embeddings/__init__.py", line 33, in build_embedding
    layer: tf.keras.layers.Embedding = tf.keras.utils.deserialize_keras_object(embeddings)
  File "/Users/simonlin/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/utils/generic_utils.py", line 305, in deserialize_keras_object
    return cls.from_config(cls_config)
  File "/Users/simonlin/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 519, in from_config
    return cls(**config)
  File "/Users/simonlin/anaconda3/lib/python3.7/site-packages/hanlp/layers/embeddings/word2vec.py", line 119, in __init__
    word2vec, _output_dim = load_word2vec(filepath)
  File "/Users/simonlin/anaconda3/lib/python3.7/site-packages/hanlp/utils/io_util.py", line 421, in load_word2vec
    word2vec[word] = np.array(vec, dtype=np.float32)
ValueError: could not convert string to float: '\x10%Iݝve^a25c-TS\x1f&\x13:^Lj7vx\x0bUV}\x187둅7yCLI#D(d]ֆ\x13\x06\'6\'.6cq˳K"\x06<ZYt\x19%\x03/`\x1f9\x07:70\x0e\x1d\x7fŋ5>\x1e\x0f\x10<Mru'
https://file.hankcs.com/hanlp/cws/ctb6-convseg-cws_20191230_184525.zip was created with hanlp-2.0.0, but you are running 2.0.0-alpha.10. Try to upgrade hanlp with
pip install --upgrade hanlp

**Comment by hankcs** [comment]
奇怪，你的机器上~/.hanlp/embeddings/convseg_embeddings/news_tensite.w2v200 乱码了。你能检查下md5吗？

```md5sum ~/.hanlp/embeddings/convseg_embeddings/news_tensite.w2v200 
c51678ffc3750b9a2c3fb2e64965406a```

这个文件是自动下载的还是你手动上传的？

**Comment by questionlin** [comment]
@hankcs convseg_embeddings.zip 是手动下载的，当时下载有点慢。把.hanlp 删了重新下就好了。谢谢
