### ISSUE TITLE
实体识别AttributeError: 'FullTokenizer' object has no attribute 'unk_token'

### ISSUE THREAD

**Issue by NLPpupil** [hankcs/HanLP#1393]
**Describe the bug**
实体识别输入以下文本时，会出现AttributeError: 'FullTokenizer' object has no attribute 'unk_token'

**Code to reproduce the issue**
```python
import hanlp

recognizer([list('孽债 （上海话）')])
recognizer([list('关于爱的四篇小小说《鱼头》儿子从小就记得，但凡家里吃鱼，妈妈总是把鱼头夹自己碗里，因为鱼头肉少。后来每次爸爸都把鱼头夹给她。直到妈妈老了，依旧如此。后来，妈妈病重，一天，家里又吃鱼了，妈妈跟他和爸爸说：我吃了一辈子鱼头，我要死了，让我也吃一次鱼肉吧。爸爸痛哭：“我这辈子最喜欢的就是鱼头就酒，我以为你真的爱吃，才每 次忍着口水把鱼头让给你。”《下雨》一场车祸，夺走了女孩很多东西，女孩变得又聋又瞎，男朋友也离她而去，只有妈妈一直陪在她身边。女孩从小就喜欢下雨天，她喜欢在细雨中漫步的感 觉。妈妈知道她喜欢雨，就常扶女孩出去，让她感受雨水拍打双手。所幸的是今年雨特别多。一天，又下雨了，妈妈扶女儿出去。“妈，我想回去了。”"好。”回去时女儿的耳朵突然有了剧烈的疼痛和反应，模糊中隐约听到：“看，又是那两个人，大晴天的雇人洒水，真可笑，又不是拍戏......”此刻，她强忍泪水，不让妈妈看见。 《老伴》退休在家后，老伴最爱从早到晚数落我又 老又胖好吃懒做。今早起床我突然咳嗽并吐出一口鲜血，他看到后整个上午没有说出一句话，闷闷的抽烟。中午拉我去了医院，最后得知那是我牙龈发炎口腔出的血，他立马就站在医院怒骂我：”你这个没用的胖老太婆……”只是没骂完，他的眼眶已满是泪水......《存折》老人得肺癌住院，家里几乎掏空了，最后实在没办法，家人只能眼睁睁看着老人受着病痛的折磨。老人临走前的一晚，将孙子叫到床前，小心地从怀中掏出一本存折，小声对孙子说：这是我留的一点私房钱，就知道那傻老婆子会把自己的养老钱拿出来给我看病，这钱是我偷偷藏的，等我走后就留给她养老吧……小声对孙子说：这是我留的一点私房钱，就知道那傻老婆子会把自己的养老钱拿出来给我看病，这钱是我偷偷藏的，等我走后就留给她养老吧……')])
```

**Describe the current behavior**
Traceback (most recent call last):
  File "/Users/wuhaixu/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/eager/context.py", line 1897, in execution_mode
    yield
  File "/Users/wuhaixu/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/data/ops/iterator_ops.py", line 659, in _next_internal
    output_shapes=self._flat_output_shapes)
  File "/Users/wuhaixu/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/ops/gen_dataset_ops.py", line 2479, in iterator_get_next_sync
    _ops.raise_from_not_ok_status(e, name)
  File "/Users/wuhaixu/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 6606, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.UnknownError: AttributeError: 'FullTokenizer' object has no attribute 'unk_token'
Traceback (most recent call last):

  File "/Users/wuhaixu/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/ops/script_ops.py", line 236, in __call__
    ret = func(*args)

  File "/Users/wuhaixu/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 789, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "/Users/wuhaixu/anaconda3/lib/python3.6/site-packages/hanlp/common/transform.py", line 155, in generator
    yield from samples

  File "/Users/wuhaixu/anaconda3/lib/python3.6/site-packages/hanlp/components/taggers/transformers/transformer_transform.py", line 85, in inputs_to_samples
    pad_token_label_id=pad_label_idx)

  File "/Users/wuhaixu/anaconda3/lib/python3.6/site-packages/hanlp/components/taggers/transformers/utils.py", line 43, in convert_examples_to_features
    word_tokens = [x] * len(word)

AttributeError: 'FullTokenizer' object has no attribute 'unk_token'

	 [[{{node PyFunc}}]] [Op:IteratorGetNextSync]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/wuhaixu/anaconda3/lib/python3.6/site-packages/hanlp/common/component.py", line 51, in __call__
    return self.predict(data, **kwargs)
  File "/Users/wuhaixu/anaconda3/lib/python3.6/site-packages/hanlp/common/component.py", line 441, in predict
    for idx, batch in enumerate(dataset):
  File "/Users/wuhaixu/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/data/ops/iterator_ops.py", line 630, in __next__
    return self.next()
  File "/Users/wuhaixu/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/data/ops/iterator_ops.py", line 674, in next
    return self._next_internal()
  File "/Users/wuhaixu/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/data/ops/iterator_ops.py", line 665, in _next_internal
    return structure.from_compatible_tensor_list(self._element_spec, ret)
  File "/Users/wuhaixu/anaconda3/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/wuhaixu/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/eager/context.py", line 1900, in execution_mode
    executor_new.wait()
  File "/Users/wuhaixu/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/eager/executor.py", line 67, in wait
    pywrap_tensorflow.TFE_ExecutorWaitForAllPendingNodes(self._handle)
tensorflow.python.framework.errors_impl.UnknownError: AttributeError: 'FullTokenizer' object has no attribute 'unk_token'
Traceback (most recent call last):

  File "/Users/wuhaixu/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/ops/script_ops.py", line 236, in __call__
    ret = func(*args)

  File "/Users/wuhaixu/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 789, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "/Users/wuhaixu/anaconda3/lib/python3.6/site-packages/hanlp/common/transform.py", line 155, in generator
    yield from samples

  File "/Users/wuhaixu/anaconda3/lib/python3.6/site-packages/hanlp/components/taggers/transformers/transformer_transform.py", line 85, in inputs_to_samples
    pad_token_label_id=pad_label_idx)

  File "/Users/wuhaixu/anaconda3/lib/python3.6/site-packages/hanlp/components/taggers/transformers/utils.py", line 43, in convert_examples_to_features
    word_tokens = [tokenizer.unk_token] * len(word)

AttributeError: 'FullTokenizer' object has no attribute 'unk_token'

	 [[{{node PyFunc}}]]

**Expected behavior**
期望顺利返回实体识别结果

**System information**
- MacOS 10.14.6
- python3.6.9
- 2.0.0-alpha.10

* [ ] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
感谢反馈，已经修复，请参考上面的commit。
如果还有问题，欢迎重开issue。
