### ISSUE TITLE
下载句法解析时出错

### ISSUE THREAD

**Issue by NLPpupil** [hankcs/HanLP#1394]
**Describe the bug**
下载句法解析时出错，提示https://file.hankcs.com/hanlp/dep/biaffine_ctb7_20191229_130325.zip was created with hanlp-2.0.0, but you are running 2.0.0-alpha.12. T

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```python
import hanlp
syntactic_parser = hanlp.load(hanlp.pretrained.dep.CTB7_BIAFFINE_DEP_ZH)
```

**Describe the current behavior**
```
Downloading https://file.hankcs.com/hanlp/dep/biaffine_ctb7_20191229_130325.zip to /Users/wuhaixu/.hanlp/dep/biaffine_ctb7_20191229_130325.zip
100.00%, 65.8 MB/65.8 MB, 219 KB/s, ETA 0 s          
Extracting /Users/wuhaixu/.hanlp/dep/biaffine_ctb7_20191229_130325.zip to /Users/wuhaixu/.hanlp/dep
Downloading https://github.com/SUDA-LA/CIP/archive/master.zip#BPNN/data/embed.txt to /Users/wuhaixu/.hanlp/thirdparty/github.com/SUDA-LA/CIP/archive/master.zip
100.00%, 0 KB/0 KB, 0 KB/s, ETA 0 s      
Extracting /Users/wuhaixu/.hanlp/thirdparty/github.com/SUDA-LA/CIP/archive/master.zip to /Users/wuhaixu/.hanlp/thirdparty/github.com/SUDA-LA/CIP/archive
Failed to load https://file.hankcs.com/hanlp/dep/biaffine_ctb7_20191229_130325.zip. See stack trace below
Traceback (most recent call last):
  File "/Users/wuhaixu/anaconda3/lib/python3.6/site-packages/hanlp/utils/component_util.py", line 36, in load_from_meta_file
    obj.load(save_dir)
  File "/Users/wuhaixu/anaconda3/lib/python3.6/site-packages/hanlp/common/component.py", line 231, in load
    self.build(**merge_dict(self.config, training=False, logger=logger, **kwargs, overwrite=True, inplace=True))
  File "/Users/wuhaixu/anaconda3/lib/python3.6/site-packages/hanlp/common/component.py", line 242, in build
    loss=kwargs.get('loss', None)))
  File "/Users/wuhaixu/anaconda3/lib/python3.6/site-packages/hanlp/components/parsers/biaffine_parser.py", line 35, in build_model
    self.transform) if pretrained_embed else None
  File "/Users/wuhaixu/anaconda3/lib/python3.6/site-packages/hanlp/layers/embeddings/__init__.py", line 33, in build_embedding
    layer: tf.keras.layers.Embedding = tf.keras.utils.deserialize_keras_object(embeddings)
  File "/Users/wuhaixu/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/keras/utils/generic_utils.py", line 305, in deserialize_keras_object
    return cls.from_config(cls_config)
  File "/Users/wuhaixu/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 519, in from_config
    return cls(**config)
  File "/Users/wuhaixu/anaconda3/lib/python3.6/site-packages/hanlp/layers/embeddings/word2vec.py", line 119, in __init__
    word2vec, _output_dim = load_word2vec(filepath)
  File "/Users/wuhaixu/anaconda3/lib/python3.6/site-packages/hanlp/utils/io_util.py", line 410, in load_word2vec
    with open(realpath, encoding='utf-8', errors='ignore') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/wuhaixu/.hanlp/thirdparty/github.com/SUDA-LA/CIP/archive/master/BPNN/data/embed.txt'
https://file.hankcs.com/hanlp/dep/biaffine_ctb7_20191229_130325.zip was created with hanlp-2.0.0, but you are running 2.0.0-alpha.12. Try to upgrade hanlp with
pip install --upgrade hanlp
```

**System information**
- Mac OS
- Python 3.6.9
- HanLP version: 2.0.0-alpha.12

* [x] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
感谢反馈，已经修复，请参考上面的commit。
如果还有问题，欢迎重开issue。
