### ISSUE TITLE
hanlp 2.0.0-alpha.25 加载 hanlp.pretrained.pos.CTB5_POS_RNN_FASTTEXT_ZH 出错

### ISSUE THREAD

**Issue by SoaringTiger** [hankcs/HanLP#1402]
**Describe the bug**
hanlp 2.0.0-alpha.25 加载 hanlp.pretrained.pos.CTB5_POS_RNN_FASTTEXT_ZH 出错

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```
tagger = hanlp.load(hanlp.pretrained.pos.CTB5_POS_RNN_FASTTEXT_ZH)
tagger(['我', '的', '希望', '是', '希望', '和平'])
```

**Describe the current behavior**
加载 hanlp.pretrained.pos.CTB5_POS_RNN_FASTTEXT_ZH 报错

**Expected behavior**
能够运行测试代码
**不会是内存不够吧？**

**System information**
- Ubuntu 18.04 
- Python version: 3.6
- HanLP version: 2.0.0-alpha.25

**Other info / logs**
Downloading https://file.hankcs.com/hanlp/pos/ctb5_pos_rnn_fasttext_20191230_202639.zip to /root/.hanlp/pos/ctb5_pos_rnn_fasttext_20191230_202639.zip
100.00%, 1.4 MB/1.4 MB, 677 KB/s, ETA 0 s      
Extracting /root/.hanlp/pos/ctb5_pos_rnn_fasttext_20191230_202639.zip to /root/.hanlp/pos
Downloading https://dl.fbaipublicfiles.com/fasttext/vectors-wiki/wiki.zh.zip#wiki.zh.bin to /root/.hanlp/thirdparty/dl.fbaipublicfiles.com/fasttext/vectors-wiki/wiki.zh.zip
1.68%, 53.6 MB/3.1 GB, 9.6 MB/s, ETA 5 m 27 s   
100.00%, 3.1 GB/3.1 GB, 8.0 MB/s, ETA 0 s      
Extracting /root/.hanlp/thirdparty/dl.fbaipublicfiles.com/fasttext/vectors-wiki/wiki.zh.zip to /root/.hanlp/thirdparty/dl.fbaipublicfiles.com/fasttext/vectors-wiki/wiki.zh
Failed to load https://file.hankcs.com/hanlp/pos/ctb5_pos_rnn_fasttext_20191230_202639.zip. See stack trace below
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/hanlp/utils/component_util.py", line 43, in load_from_meta_file
    obj.load(save_dir, **load_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/hanlp/common/component.py", line 244, in load
    self.build(**merge_dict(self.config, training=False, logger=logger, **kwargs, overwrite=True, inplace=True))
  File "/usr/local/lib/python3.6/dist-packages/hanlp/common/component.py", line 255, in build
    loss=kwargs.get('loss', None)))
  File "/usr/local/lib/python3.6/dist-packages/hanlp/components/taggers/rnn_tagger.py", line 34, in build_model
    embeddings = build_embedding(embeddings, self.transform.word_vocab, self.transform)
  File "/usr/local/lib/python3.6/dist-packages/hanlp/layers/embeddings/__init__.py", line 33, in build_embedding
    layer: tf.keras.layers.Embedding = tf.keras.utils.deserialize_keras_object(embeddings)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/utils/generic_utils.py", line 305, in deserialize_keras_object
    return cls.from_config(cls_config)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/base_layer.py", line 519, in from_config
    return cls(**config)
  File "/usr/local/lib/python3.6/dist-packages/hanlp/layers/embeddings/fast_text.py", line 35, in __init__
    self.model = fasttext.load_model(filepath)
  File "/usr/local/lib/python3.6/dist-packages/fasttext/FastText.py", line 350, in load_model
    return _FastText(model_path=path)
  File "/usr/local/lib/python3.6/dist-packages/fasttext/FastText.py", line 43, in __init__
    self.f.loadModel(model_path)
**MemoryError: std::bad_alloc**
**https://file.hankcs.com/hanlp/pos/ctb5_pos_rnn_fasttext_20191230_202639.zip** was created with **hanlp-2.0.0, while you are running 2.0.0-alpha.25.** Try to upgrade hanlp with
pip install --upgrade hanlp

* [x] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
对，应该就是内存不够。MemoryError: std::bad_alloc是fasttext的C++代码抛出来的。wiki模型有3个G，而且还是压缩的，加载进去保守估计可能得8个G。你可以试试`CTB5_POS_RNN`，这个应该没有依赖fasttext。
