### ISSUE TITLE
hanlp 2.0.0a26 使用 CTB5_POS_RNN 报错

### ISSUE THREAD

**Issue by SoaringTiger** [hankcs/HanLP#1404]
**Describe the bug**
hanlp 2.0.0a26 使用 CTB5_POS_RNN 报错 .

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```python
tokenizer = hanlp.load('CTB5_POS_RNN')
(tokenizer('商品和服务')
```

**Describe the current behavior**
运行上述代码出错

**Expected behavior**
能够运行测试代码

**System information**
- Ubuntu 18.04
- Python version: 3.6
- HanLP version: 2.0.0a26

**Other info / logs**
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/context.py", line 1897, in execution_mode
    yield
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/data/ops/iterator_ops.py", line 659, in _next_internal
    output_shapes=self._flat_output_shapes)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/gen_dataset_ops.py", line 2479, in iterator_get_next_sync
    _ops.raise_from_not_ok_status(e, name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 6606, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: ValueError: `generator` yielded an element of shape () where an element of shape (None,) was expected.
Traceback (most recent call last):

  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/script_ops.py", line 236, in __call__
    ret = func(*args)

  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 825, in generator_py_func
    "of shape %s was expected." % (ret_array.shape, expected_shape))

ValueError: `generator` yielded an element of shape () where an element of shape (None,) was expected.


	 [[{{node PyFunc}}]] [Op:IteratorGetNextSync]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "load-sem.py", line 5, in <module>
    tokenizer('商品和服务')
  File "/usr/local/lib/python3.6/dist-packages/hanlp/common/component.py", line 51, in __call__
    return self.predict(data, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/hanlp/components/taggers/rnn_tagger.py", line 47, in predict
    return super().predict(sents, batch_size)
  File "/usr/local/lib/python3.6/dist-packages/hanlp/common/component.py", line 454, in predict
    for idx, batch in enumerate(dataset):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/data/ops/iterator_ops.py", line 630, in __next__
    return self.next()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/data/ops/iterator_ops.py", line 674, in next
    return self._next_internal()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/data/ops/iterator_ops.py", line 665, in _next_internal
    return structure.from_compatible_tensor_list(self._element_spec, ret)
  File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/context.py", line 1900, in execution_mode
    executor_new.wait()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/executor.py", line 67, in wait
    pywrap_tensorflow.TFE_ExecutorWaitForAllPendingNodes(self._handle)
tensorflow.python.framework.errors_impl.InvalidArgumentError: ValueError: `generator` yielded an element of shape () where an element of shape (None,) was expected.
Traceback (most recent call last):

  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/script_ops.py", line 236, in __call__
    ret = func(*args)

  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 825, in generator_py_func
    "of shape %s was expected." % (ret_array.shape, expected_shape))

ValueError: `generator` yielded an element of shape () where an element of shape (None,) was expected.


	 [[{{node PyFunc}}]]
```

* [x] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
Taggers take lists of tokens as input, then outputs one tag for each token.

**Comment by SoaringTiger** [comment]
哎呀，犯了个低级错误😄
