### ISSUE TITLE
No vocab found or unambiguous vocabs found

### ISSUE THREAD

**Issue by wynla** [hankcs/HanLP#1416]
Failed to load https://file.hankcs.com/hanlp/ner/ner_bert_base_msra_20200104_185735.zip. See stack trace below
Traceback (most recent call last):
  File "E:\Anaconda\lib\site-packages\hanlp\utils\component_util.py", line 48, in load_from_meta_file
    obj.load(save_dir, **load_kwargs)
  File "E:\Anaconda\lib\site-packages\hanlp\common\component.py", line 244, in load
    self.build(**merge_dict(self.config, training=False, logger=logger, **kwargs, overwrite=True, inplace=True))
  File "E:\Anaconda\lib\site-packages\hanlp\common\component.py", line 255, in build
    loss=kwargs.get('loss', None)))
  File "E:\Anaconda\lib\site-packages\hanlp\components\taggers\transformers\transformer_tagger.py", line 36, in build_model
    model, tokenizer = build_transformer(transformer, max_seq_length, len(self.transform.tag_vocab), tagging=True)
  File "E:\Anaconda\lib\site-packages\hanlp\layers\transformers\loader.py", line 101, in build_transformer
    assert len(vocab) == 1, 'No vocab found or unambiguous vocabs found'
AssertionError: No vocab found or unambiguous vocabs found
https://file.hankcs.com/hanlp/ner/ner_bert_base_msra_20200104_185735.zip was created with hanlp-2.0.0-alpha.5, while you are running 2.0.0-alpha.36. Try to upgrade hanlp with
pip

**Comment by hankcs** [comment]
[auto-reply] Thanks for your comment. However, the essential information is required. Please carefully fill out the form then reopen it.
