### ISSUE TITLE
OSError: [WinError 1] 函数不正确。

### ISSUE THREAD

**Issue by Changgf** [hankcs/HanLP#1417]
**Describe the bug**
recognizer = hanlp.load(hanlp.pretrained.ner.MSRA_NER_BERT_BASE_ZH)
this is not working
**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
import hanlp
recognizer = hanlp.load(hanlp.pretrained.ner.MSRA_NER_BERT_BASE_ZH)
```python
```
3.6
**Describe the current behavior**
import hanlp
recognizer = hanlp.load(hanlp.pretrained.ner.MSRA_NER_BERT_BASE_ZH)
**Expected behavior**
A clear and concise description of what happened.
If the problem persists, please submit an issue to https://github.com/hankcs/HanLP/issues .
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
OSError: [WinError 1] 函数不正确。
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):win10 
- Python version:3.6
- HanLP version:2.0.0a5

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
Failed to load https://file.hankcs.com/hanlp/ner/ner_bert_base_msra_20200104_185735.zip. See stack trace below
Traceback (most recent call last):
  File "E:\Miniconda3\envs\python36\lib\site-packages\hanlp\utils\io_util.py", line 563, in stdout_redirected
    yield stdout  # allow code to be run with the redirected stdout
  File "E:\Miniconda3\envs\python36\lib\site-packages\hanlp\layers\transformers\loader.py", line 141, in build_transformer
    skipped_weight_value_tuples = bert.load_bert_weights(l_bert, ckpt)
  File "E:\Miniconda3\envs\python36\lib\site-packages\bert\loader.py", line 235, in load_stock_weights
    len(weight_value_tuples), ckpt_path, bert, prefix, skip_count, len(skipped_weight_value_tuples)))
OSError: [WinError 1] 函数不正确。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Miniconda3\envs\python36\lib\site-packages\hanlp\utils\component_util.py", line 48, in load_from_meta_file
    obj.load(save_dir, **load_kwargs)
  File "E:\Miniconda3\envs\python36\lib\site-packages\hanlp\common\component.py", line 244, in load
    self.build(**merge_dict(self.config, training=False, logger=logger, **kwargs, overwrite=True, inplace=True))
  File "E:\Miniconda3\envs\python36\lib\site-packages\hanlp\common\component.py", line 255, in build
    loss=kwargs.get('loss', None)))
  File "E:\Miniconda3\envs\python36\lib\site-packages\hanlp\components\taggers\transformers\transformer_tagger.py", line 36,
in build_model
    model, tokenizer = build_transformer(transformer, max_seq_length, len(self.transform.tag_vocab), tagging=True)
  File "E:\Miniconda3\envs\python36\lib\site-packages\hanlp\layers\transformers\loader.py", line 141, in build_transformer
    skipped_weight_value_tuples = bert.load_bert_weights(l_bert, ckpt)
  File "E:\Miniconda3\envs\python36\lib\contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "E:\Miniconda3\envs\python36\lib\site-packages\hanlp\utils\io_util.py", line 567, in stdout_redirected
    stdout.flush()
OSError: [WinError 1] 函数不正确。
https://file.hankcs.com/hanlp/ner/ner_bert_base_msra_20200104_185735.zip was created with hanlp-2.0.0-alpha.5, while you are
running 2.0.0-alpha.35. Try to upgrade hanlp with
pip install --upgrade hanlp
If the problem persists, please submit an issue to https://github.com/hankcs/HanLP/issues .
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
OSError: [WinError 1] 函数不正确。
* [ ] I've completed this form and searched the web for solutions.
no

**Comment by hankcs** [comment]
【自动回复】你好，感谢反馈。
由于未按要求填写，本issue被自动关闭。请按[issue模板](https://github.com/hankcs/HanLP/blob/master/.github/ISSUE_TEMPLATE.md)认真修改，然后耐心等待下周末处理。
咨询类的问题应该发在[论坛](https://bbs.hankcs.com/)而不是GitHub上。开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
![issue](http://wx1.sinaimg.cn/large/006Fmjmcly1ft2hnlwc22j30q90bcgpe.jpg)
