### ISSUE TITLE
jpype._jclass.UnsupportedClassVersionError (Unsupported major.minor version 52.0)

### ISSUE THREAD

**Issue by Donsmine** [hankcs/HanLP#1430]
Typing hanlp for the very first time raised jpype._jclass.UnsupportedClassVersionError. Tried with the lasted jdk version ( jdk-13.0.2.jdk), the same problem persists. 
Thanks in advance.

(base) DongdeMacBook-Pro:Downloads dongchen$ hanlp
Traceback (most recent call last):
  File "/Users/dongchen/anaconda3/bin/hanlp", line 6, in <module>
    from pyhanlp.main import main
  File "/Users/dongchen/anaconda3/lib/python3.7/site-packages/pyhanlp/__init__.py", line 145, in <module>
    _start_jvm_for_hanlp()
  File "/Users/dongchen/anaconda3/lib/python3.7/site-packages/pyhanlp/__init__.py", line 133, in _start_jvm_for_hanlp
    HANLP_JVM_XMX, convertStrings=True)
  File "/Users/dongchen/anaconda3/lib/python3.7/site-packages/jpype/_core.py", line 219, in startJVM
    _jpype.startup(jvmpath, tuple(args), ignoreUnrecognized, convertStrings)
jpype._jclass.UnsupportedClassVersionError: org/jpype/classloader/JPypeClassLoader : Unsupported major.minor version 52.0

**Comment by hankcs** [comment]
[auto-reply] Thanks for your comment. However, the essential information is required. Please carefully fill out the form then reopen it.
