### ISSUE TITLE
依存句法分析加载模型出错

### ISSUE THREAD

**Issue by menghuu** [hankcs/HanLP#1442]
**Describe the bug**
从`hanlp.pretrained.dep.CTB7_BIAFFINE_DEP_ZH`加载依存分析模型出错

**Code to reproduce the issue**
```python
import hanlp
hanlp.load(hanlp.pretrained.dep.CTB7_BIAFFINE_DEP_ZH)
```

**Describe the current behavior**
从`hanlp.pretrained.dep.CTB7_BIAFFINE_DEP_ZH`加载依存分析模型出错

**Expected behavior**
成功加载

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Python version: Linux xxx 4.15.0-72-generic #81-Ubuntu SMP Tue Nov 26 12:20:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- HanLP version: 2.0.0a39

**Other info / logs**
```bash
Failed to load https://file.hankcs.com/hanlp/dep/biaffine_ctb7_20200109_022431.zip. See stack trace below
Traceback (most recent call last):
  File "/data/humeng/projs/extract_spo/.venv/lib/python3.7/site-packages/hanlp/utils/component_util.py", line 48, in load_from_meta_file
    obj.load(save_dir, **load_kwargs)
  File "/data/humeng/projs/extract_spo/.venv/lib/python3.7/site-packages/hanlp/common/component.py", line 244, in load
    self.build(**merge_dict(self.config, training=False, logger=logger, **kwargs, overwrite=True, inplace=True))
  File "/data/humeng/projs/extract_spo/.venv/lib/python3.7/site-packages/hanlp/common/component.py", line 269, in build
    self.model(sample_inputs)
  File "/data/humeng/projs/extract_spo/.venv/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 822, in __call__
    outputs = self.call(cast_inputs, *args, **kwargs)
  File "/data/humeng/projs/extract_spo/.venv/lib/python3.7/site-packages/hanlp/components/parsers/biaffine/model.py", line 92, in call
    x = self.lstm(embed, mask=mask)
  File "/data/humeng/projs/extract_spo/.venv/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 822, in __call__
    outputs = self.call(cast_inputs, *args, **kwargs)
  File "/data/humeng/projs/extract_spo/.venv/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/sequential.py", line 281, in call
    outputs = layer(inputs, **kwargs)
  File "/data/humeng/projs/extract_spo/.venv/lib/python3.7/site-packages/tensorflow_core/python/keras/layers/wrappers.py", line 543, in __call__
    return super(Bidirectional, self).__call__(inputs, **kwargs)
  File "/data/humeng/projs/extract_spo/.venv/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 822, in __call__
    outputs = self.call(cast_inputs, *args, **kwargs)
  File "/data/humeng/projs/extract_spo/.venv/lib/python3.7/site-packages/tensorflow_core/python/keras/layers/wrappers.py", line 657, in call
    initial_state=forward_state, **kwargs)
  File "/data/humeng/projs/extract_spo/.venv/lib/python3.7/site-packages/tensorflow_core/python/keras/layers/recurrent.py", line 644, in __call__
    return super(RNN, self).__call__(inputs, **kwargs)
  File "/data/humeng/projs/extract_spo/.venv/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 822, in __call__
    outputs = self.call(cast_inputs, *args, **kwargs)
  File "/data/humeng/projs/extract_spo/.venv/lib/python3.7/site-packages/tensorflow_core/python/keras/layers/recurrent_v2.py", line 1144, in call
    **cudnn_lstm_kwargs)
  File "/data/humeng/projs/extract_spo/.venv/lib/python3.7/site-packages/tensorflow_core/python/keras/layers/recurrent_v2.py", line 1362, in cudnn_lstm
    time_major=time_major)
  File "/data/humeng/projs/extract_spo/.venv/lib/python3.7/site-packages/tensorflow_core/python/ops/gen_cudnn_rnn_ops.py", line 1906, in cudnn_rnnv3
    ctx=_ctx)
  File "/data/humeng/projs/extract_spo/.venv/lib/python3.7/site-packages/tensorflow_core/python/ops/gen_cudnn_rnn_ops.py", line 2002, in cudnn_rnnv3_eager_fallback
    attrs=_attrs, ctx=ctx, name=name)
  File "/data/humeng/projs/extract_spo/.venv/lib/python3.7/site-packages/tensorflow_core/python/eager/execute.py", line 67, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.UnknownError: Fail to find the dnn implementation. [Op:CudnnRNNV3]
https://file.hankcs.com/hanlp/dep/biaffine_ctb7_20200109_022431.zip was created with hanlp-2.0.0, while you are running 2.0.0-alpha.39. Try to upgrade hanlp with
pip install --upgrade hanlp
If the problem persists, please submit an issue to https://github.com/hankcs/HanLP/issues .
```

* [x] I've completed this form and searched the web for solutions.

**Comment by menghuu** [comment]
似乎不是hanlp的问题，是tf的问题，我将 meta.json 中的hanlp_version改成了当前版本，关于hanlp的报错没了，似乎只是tf的问题.

**Comment by GanjinZero** [comment]
这样解决了
'''
import tensorflow as tf
gpus = tf.config.experimental.list_physical_devices('GPU')
print(gpus)
for gpu in gpus:
    tf.config.experimental.set_memory_growth(gpu, True)
'''

**Comment by ShallTearchen** [comment]
再次遇到这个问题 求详解怎么解决！
