### ISSUE TITLE
was created with hanlp-2.0.0-alpha.5, while you are running 2.0.0-alpha.38.

### ISSUE THREAD

**Issue by 15236626983** [hankcs/HanLP#1444]
Failed to load https://file.hankcs.com/hanlp/ner/ner_bert_base_msra_20200104_185735.zip. See stack trace below
Traceback (most recent call last):
  File "H:\Anaconda3\envs\py36\lib\site-packages\tensorflow_core\python\training\py_checkpoint_reader.py", line 70, in get_tensor
    self, compat.as_bytes(tensor_str))
RuntimeError: Checksum does not match: stored 114360999 vs. calculated on the restored bytes 3891682082

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\PyCharmWorkspace\pwlp\pwlp-judged\hanlp\utils\component_util.py", line 48, in load_from_meta_file
    obj.load(save_dir, **load_kwargs)
  File "E:\PyCharmWorkspace\pwlp\pwlp-judged\hanlp\common\component.py", line 244, in load
    self.build(**merge_dict(self.config, training=False, logger=logger, **kwargs, overwrite=True, inplace=True))
  File "E:\PyCharmWorkspace\pwlp\pwlp-judged\hanlp\common\component.py", line 255, in build
    loss=kwargs.get('loss', None)))
  File "E:\PyCharmWorkspace\pwlp\pwlp-judged\hanlp\components\taggers\transformers\transformer_tagger.py", line 36, in build_model
    model, tokenizer = build_transformer(transformer, max_seq_length, len(self.transform.tag_vocab), tagging=True)
  File "E:\PyCharmWorkspace\pwlp\pwlp-judged\hanlp\layers\transformers\loader.py", line 141, in build_transformer
    skipped_weight_value_tuples = bert.load_bert_weights(l_bert, ckpt)
  File "H:\Anaconda3\envs\py36\lib\site-packages\bert_for_tf2-0.12.7-py3.6.egg\bert\loader.py", line 216, in load_stock_weights
    ckpt_value = ckpt_reader.get_tensor(stock_name)
  File "H:\Anaconda3\envs\py36\lib\site-packages\tensorflow_core\python\training\py_checkpoint_reader.py", line 74, in get_tensor
    error_translator(e)
  File "H:\Anaconda3\envs\py36\lib\site-packages\tensorflow_core\python\training\py_checkpoint_reader.py", line 48, in error_translator
    raise errors_impl.OpError(None, None, error_message, errors_impl.UNKNOWN)
tensorflow.python.framework.errors_impl.OpError: Checksum does not match: stored 114360999 vs. calculated on the restored bytes 3891682082
https://file.hankcs.com/hanlp/ner/ner_bert_base_msra_20200104_185735.zip was created with hanlp-2.0.0-alpha.5, while you are running 2.0.0-alpha.38. Try to upgrade hanlp with
pip install --upgrade hanlp
If the problem persists, please submit an issue to https://github.com/hankcs/HanLP/issues .
* [ ] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
[auto-reply] Thanks for your comment. However, the essential information is required. Please carefully fill out the form then reopen it.

**Comment by fxxuuu** [comment]
我也遇到了这个问题。前几天还是正常的，模型和调用方式也都没有变，今天突然加载模型就失败了。
