### ISSUE TITLE
NER模型加载失败

### ISSUE THREAD

**Issue by fxxuuu** [hankcs/HanLP#1448]
**Describe the bug**
加载 NER 模型失败，以下是报错信息：

Failed to load https://file.hankcs.com/hanlp/ner/ner_bert_base_msra_20200104_185735.zip. See stack trace below
Traceback (most recent call last):
  File "/home/t-xif/anaconda3/envs/tf2/lib/python3.7/site-packages/hanlp/utils/component_util.py", line 48, in load_from_meta_file
    obj.load(save_dir, **load_kwargs)
  File "/home/t-xif/anaconda3/envs/tf2/lib/python3.7/site-packages/hanlp/common/component.py", line 244, in load
    self.build(**merge_dict(self.config, training=False, logger=logger, **kwargs, overwrite=True, inplace=True))
  File "/home/t-xif/anaconda3/envs/tf2/lib/python3.7/site-packages/hanlp/common/component.py", line 255, in build
    loss=kwargs.get('loss', None)))
  File "/home/t-xif/anaconda3/envs/tf2/lib/python3.7/site-packages/hanlp/components/taggers/transformers/transformer_tagger.py", line 36, in build_model
    model, tokenizer = build_transformer(transformer, max_seq_length, len(self.transform.tag_vocab), tagging=True)
  File "/home/t-xif/anaconda3/envs/tf2/lib/python3.7/site-packages/hanlp/layers/transformers/loader.py", line 115, in build_transformer
    l_bert = bert.BertModelLayer.from_params(bert_params, name='albert' if albert else "bert")
  File "/home/t-xif/anaconda3/envs/tf2/lib/python3.7/site-packages/params/with_params.py", line 67, in from_params
    instance = cls(*args, **kwargs)
  File "/home/t-xif/anaconda3/envs/tf2/lib/python3.7/site-packages/params/with_params.py", line 47, in __init__
    self._construct(*args, **other_args)
TypeError: _construct() got an unexpected keyword argument 'name'
https://file.hankcs.com/hanlp/ner/ner_bert_base_msra_20200104_185735.zip was created with hanlp-2.0.0-alpha.5, while you are running 2.0.0-alpha.40. Try to upgrade hanlp with
pip install --upgrade hanlp
If the problem persists, please submit an issue to https://github.com/hankcs/HanLP/issues .

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```python
recognizer = hanlp.load(hanlp.pretrained.ner.MSRA_NER_BERT_BASE_ZH)
```

**Describe the current behavior**
几天前调用模型是正常的，模型和调用方式都没有改变，今天调模型突然失败了，按照提示将 hanlp 升级到 a5 版本也会挂。是不是内部 API 改了什么地方导致调用失败的？

**Expected behavior**
模型加载成功。

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- Python version: 3.7
- HanLP version: 2.0.0-alpha.40. (试了 2.0.0-alpha.5 也不行)

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

* [x] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
看日志 bert-for-tf2==0.12.7

**Comment by fxxuuu** [comment]
> 看日志 bert-for-tf2==0.12.7

请问这是什么意思啊，哪里的日志呀？0.12.7 指的是 tf 版本？

**Comment by hankcs** [comment]
pip install bert-for-tf2==0.12.7

**Comment by fxxuuu** [comment]
> pip install bert-for-tf2==0.12.7

你好，我的 bert-for-tf2 已经是 0.12.7 的版本了，所以应该不是这个问题导致的。

比较奇怪的是之前加载模型是 OK 的，今天才突然报错。而且我试着加载了分词和词性标注的模型，都是可以成功调用的，就是 NER 模型加载失败报了上面的错，很迷惑...

**Comment by hankcs** [comment]
感谢反馈，已经修复，请参考上面的commit。
如果还有问题，欢迎重开issue。

**Comment by Soul-Code** [comment]
我遇到了同样的问题，这个问题是由于我位于C:\Users\1234\AppData\Roaming\hanlp\thirdparty\storage.googleapis.com\bert_models\2018_11_03文件夹中的chinese_L-12_H-768_A-12文件未能成功下载，这导致模型路径识别错误。删除该目录下的downloading文件后成功解决了这个问题。

**Comment by RickChina** [comment]
楼主问题解决了吗，我的centos7 、python3.7、2.0.0-alpha.41同样遇到了这个问题。 @fxxuuu @hankcs

**Comment by hankcs** [comment]
> 楼主问题解决了吗，我的centos7 、python3.7、2.0.0-alpha.41同样遇到了这个问题。 @fxxuuu @hankcs
> TypeError: _construct() got an unexpected keyword argument 'name'
> https://file.hankcs.com/hanlp/ner/ner_bert_base_msra_20200104_185735.zip was created with hanlp-2.0.0-alpha.5, while you are running 2.0.0-alpha.41. Try to upgrade hanlp with
> pip install --upgrade hanlp

请试试刚发布的alpha.42：pip install --upgrade hanlp
最近第三方库bert-tf2升级了，造成版本不兼容。

**Comment by LIMu-zoh** [comment]
感谢Soul-Code，成功解决问题

**Comment by hongkong9771** [comment]
你好，我在加载模型的时候提示如下错误（其他模型能够正常加载）。
Failed to load https://file.hankcs.com/hanlp/ner/ner_conll03_bert_base_cased_en_20211227_121443.zip.
If the problem still persists, please submit an issue to https://github.com/hankcs/HanLP/issues
When reporting an issue, make sure to paste the FULL ERROR LOG below.
================================ERROR LOG BEGINS================================
OS: Windows-10-10.0.19044-SP0
Python: 3.8.13
PyTorch: 1.12.0
TensorFlow: 2.6.0
HanLP: 2.1.0-beta.37
Traceback (most recent call last):
  File "ner_single.py", line 218, in <module>
    main()
  File "ner_single.py", line 185, in main
    Hanlp = model_lang_select(model, lang)
  File "ner_single.py", line 165, in model_lang_select
    Hanlp = singlemodel.ner_en()
  File "ner_single.py", line 51, in ner_en
    .append(hanlp.load(hanlp.pretrained.ner.CONLL03_NER_BERT_BASE_CASED_EN), output_key='ner', input_key='tok')
  File "C:\Program Files (x86)\Miniconda3\envs\hanlp-gpu\lib\site-packages\hanlp\__init__.py", line 43, in load
    return load_from_meta_file(save_dir, 'meta.json', verbose=verbose, **kwargs)
  File "C:\Program Files (x86)\Miniconda3\envs\hanlp-gpu\lib\site-packages\hanlp\utils\component_util.py", line 175, in load_from_meta_file
    raise e from None
  File "C:\Program Files (x86)\Miniconda3\envs\hanlp-gpu\lib\site-packages\hanlp\utils\component_util.py", line 99, in load_from_meta_file
    obj.load(save_dir, verbose=verbose, **kwargs)
  File "C:\Program Files (x86)\Miniconda3\envs\hanlp-gpu\lib\site-packages\hanlp\common\keras_component.py", line 214, in load
    self.build(**merge_dict(self.config, training=False, logger=logger, **kwargs, overwrite=True, inplace=True))
  File "C:\Program Files (x86)\Miniconda3\envs\hanlp-gpu\lib\site-packages\hanlp\common\keras_component.py", line 224, in build
    self.model = self.build_model(**merge_dict(self.config, training=kwargs.get('training', None),
  File "C:\Program Files (x86)\Miniconda3\envs\hanlp-gpu\lib\site-packages\hanlp\components\taggers\transformers\transformer_tagger_tf.py", line 34, in build_model
    model, tokenizer = build_transformer(transformer, max_seq_length, len(self.transform.tag_vocab), tagging=True)
  File "C:\Program Files (x86)\Miniconda3\envs\hanlp-gpu\lib\site-packages\hanlp\layers\transformers\loader_tf.py", line 14, in build_transformer
    l_bert = TFAutoModel.from_pretrained(transformer)
  File "C:\Program Files (x86)\Miniconda3\envs\hanlp-gpu\lib\site-packages\transformers\models\auto\auto_factory.py", line 445, in from_pretrained
    model_class = _get_model_class(config, cls._model_mapping)
  File "C:\Program Files (x86)\Miniconda3\envs\hanlp-gpu\lib\site-packages\transformers\models\auto\auto_factory.py", line 359, in _get_model_class
    supported_models = model_mapping[type(config)]
  File "C:\Program Files (x86)\Miniconda3\envs\hanlp-gpu\lib\site-packages\transformers\models\auto\auto_factory.py", line 565, in __getitem__
    return self._load_attr_from_module(model_type, model_name)
  File "C:\Program Files (x86)\Miniconda3\envs\hanlp-gpu\lib\site-packages\transformers\models\auto\auto_factory.py", line 579, in _load_attr_from_module
    return getattribute_from_module(self._modules[module_name], attr)
  File "C:\Program Files (x86)\Miniconda3\envs\hanlp-gpu\lib\site-packages\transformers\models\auto\auto_factory.py", line 534, in getattribute_from_module
    if hasattr(module, attr):
  File "C:\Program Files (x86)\Miniconda3\envs\hanlp-gpu\lib\site-packages\transformers\utils\import_utils.py", line 895, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "C:\Program Files (x86)\Miniconda3\envs\hanlp-gpu\lib\site-packages\transformers\utils\import_utils.py", line 907, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.bert.modeling_tf_bert because of the following error (look up to see its traceback):
cannot import name 'py_new_vlen' from 'h5py.h5t' (C:\Users\111\AppData\Roaming\Python\Python38\site-packages\h5py\h5t.cp38-win_amd64.pyd)
=================================ERROR LOG ENDS=================================

已经使用 pip install --upgrade hanlp 命令进行更新了，但还是出现此错误。

**Comment by hankcs** [comment]
无法复现：https://colab.research.google.com/drive/1d95nzqyscZchsmZ7_GQ15J3LGWqvPjpr?usp=sharing

**Comment by Mike20230309** [comment]
我也遇到类似的问题，运行环境（Window10，Python 3.9.13  hanIP 2.1.0b45）
代码如下：
NER_1 = hanlp.pipeline() \
    .append(hanlp.utils.rules.split_sentence, output_key='sentences') \
    .append(hanlp.load('UD_TOK_MMINILMV2L12'), output_key='tok') \
    .append(hanlp.load('CONLL03_NER_BERT_BASE_CASED_EN'), output_key='ner', input_key='tok')

print(NER_1(text_EN))
报错如下：File "c:\HK_2022\Python\TestHanLP.py", line 17, in <module>
    .append(hanlp.load('CONLL03_NER_BERT_BASE_CASED_EN'), output_key='ner', input_key='tok')
  File "C:\Users\HuJM\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\hanlp\__init__.py", line 43, in load
    return load_from_meta_file(save_dir, 'meta.json', verbose=verbose, **kwargs)
  File "C:\Users\HuJM\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\hanlp\utils\component_util.py", line 115, in load_from_meta_file    raise ModuleNotFoundError(
ModuleNotFoundError: Some modules (tensorflow.python etc.) required by this model are missing. Please install the full version:

        pip install hanlp[full] -U
我已经执行了pip install hanlp[full] -U这个命令，并成功执行，但是错误一直都是这个.如果把代码中的CONLL03_NER_BERT_BASE_CASED_EN换成MSRA_NER_ELECTRA_SMALL_ZH，可以正常运行
