### ISSUE TITLE
semantic parser结果无法使用pickle进行持久化

### ISSUE THREAD

**Issue by luoy2** [hankcs/HanLP#1472]
**Describe the bug**
鉴于深度学习模型速度问题以及已知的tf2内存泄露问题， 一个解决办法是使用离线任务处理数据， 然后持久化数据后再接入下游任务。 然而， 在测试持久化过程中， 发现似乎由于`SerializableDict`类没有implement `__getstate__` method, 导致semantic analysis 结果无法被pickle持久化

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```python
import os
os.environ['CUDA_VISIBLE_DEVICES'] = "-1"
import hanlp
import pickle
import traceback
tokenizer = hanlp.load(hanlp.pretrained.cws.PKU_NAME_MERGED_SIX_MONTHS_CONVSEG)
tagger = hanlp.load(hanlp.pretrained.pos.CTB5_POS_RNN_FASTTEXT_ZH)
semantic_parser = hanlp.load(hanlp.pretrained.sdp.SEMEVAL16_NEWS_BIAFFINE_ZH)
text = """HanLP是一系列模型与算法组成的自然语言处理工具包，目标是普及自然语言处理在生产环境中的应用。
HanLP具备功能完善、性能高效、架构清晰、语料时新、可自定义的特点。内部算法经过工业界和学术界考验，配套书籍《自然语言处理入门》已经出版。"""

pipeline = hanlp.pipeline() \
    .append(hanlp.utils.rules.split_sentence, output_key='sentences') \
    .append(tokenizer, output_key='tokens') \
    .append(tagger, output_key='part_of_speech_tags') \
    .append(semantic_parser, input_key=('tokens', 'part_of_speech_tags'), output_key='semantic_dependencies')
res = pipeline(text)

x = res['semantic_dependencies'][0]

print("direct dumping result....")
try:
    with open('tests/test_hanlp.pk', 'wb') as f:
        pickle.dump(res, f)
except Exception as e:
    traceback.print_exc()

print("dumping dict(result) with semantic....")
try:
    with open('tests/test_hanlp.pk', 'wb') as f:
        pickle.dump(dict(res), f)
    print("dump succeeded")
except Exception as e:
    traceback.print_exc()

print("dumping semantic result....")
try:
    with open('tests/test_hanlp.pk', 'wb') as f:
        pickle.dump(x[0], f)
except Exception as e:
    traceback.print_exc()

print("direct dumping result without semantic....")
del res['semantic_dependencies']
try:
    with open('tests/test_hanlp.pk', 'wb') as f:
        pickle.dump(res, f)
except Exception as e:
    traceback.print_exc()

print("dumping dict(result) without semantic....")
try:
    with open('tests/test_hanlp.pk', 'wb') as f:
        pickle.dump(dict(res), f)
    print("dump succeeded")
except Exception as e:
    traceback.print_exc()
```

**Describe the current behavior**
5个实验：
- 直接pickle, 失败
- 给pipeline result 前面封装一层dict， 失败
- 只pickle semantic parser result， 失败
- 删掉result的semantic parser部分， 直接dump， 失败
- 给删掉semantic parser部分的result封装一层dict， 成功

**Expected behavior**
给result 封装一层dict后应该都可以用pickle进行序列化并dump?

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Python version: 3.7
- HanLP version: 2.0.0-alpha.43

**Other info / logs**
```
direct dumping result....
Traceback (most recent call last):
  File "<input>", line 6, in <module>
TypeError: 'list' object is not callable
dumping dict(result) with semantic....
Traceback (most recent call last):
  File "<input>", line 13, in <module>
  File "C:\ProgramData\Anaconda3\envs\tf2_gpu\lib\site-packages\hanlp\common\structure.py", line 92, in __getattr__
    return self.__getitem__(key)
KeyError: '__getstate__'
dumping semantic result....
Traceback (most recent call last):
  File "<input>", line 21, in <module>
  File "C:\ProgramData\Anaconda3\envs\tf2_gpu\lib\site-packages\hanlp\common\structure.py", line 92, in __getattr__
    return self.__getitem__(key)
KeyError: '__getstate__'
direct dumping result without semantic....
Traceback (most recent call last):
  File "<input>", line 29, in <module>
TypeError: 'list' object is not callable
dumping dict(result) without semantic....
dump succeeded
```

* [x] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
现在应该可以直接pickle了。
感谢反馈，已经修复，请参考上面的commit。
如果还有问题，欢迎重开issue。
