### ISSUE TITLE
data/model/perceptron/large/cws.bin 加载失败

### ISSUE THREAD

**Issue by bewithme** [hankcs/HanLP#1487]
**Describe the bug**
同一份代码在macos中用maven打包运行正常，但在centos7上用maven打包运行却报错，data文件夹都是在正确的位置的

**Code to reproduce the issue**

AbstractLexicalAnalyzer ANALYZER=new PerceptronLexicalAnalyzer();

**Describe the current behavior**
创建一个AbstractLexicalAnalyzer对象

**Expected behavior**
data/model/perceptron/large/cws.bin可以正确加载，对象可以成功创建。

**System information**
- Centos 7:
- Python version:
- HanLP version: portable-1.7.6

**Other info / logs**
java.io.IOException: data/model/perceptron/large/cws.bin 加载失败
	at com.hankcs.hanlp.model.perceptron.model.LinearModel.load(LinearModel.java:390) ~[hanlp-portable-1.7.6.jar:?]
	at com.hankcs.hanlp.model.perceptron.model.LinearModel.<init>(LinearModel.java:65) ~[hanlp-portable-1.7.6.jar:?]
	at com.hankcs.hanlp.model.perceptron.PerceptronLexicalAnalyzer.<init>(PerceptronLexicalAnalyzer.java:70) ~[hanlp-portable-1.7.6.jar:?]
	at com.hankcs.hanlp.model.perceptron.PerceptronLexicalAnalyzer.<init>(PerceptronLexicalAnalyzer.java:95) ~[hanlp-portable-1.7.6.jar:?]

* [ ] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
【自动回复】您好，感谢反馈。
由于未按要求填写，本issue被自动关闭。请按[issue模板](https://raw.githubusercontent.com/hankcs/HanLP/master/.github/ISSUE_TEMPLATE/bug_report.md)认真修改，然后耐心等待下周末处理。
如果您提的是bug或feature request，那么请您按模板认真改一改，reopen这个issue。
否则，咨询类的问题请先搜索一下。99.9%的问题已经反复回答过了，人类的本质是复读机。如果您确信您提了个新问题，那么欢迎写清楚前因后果发在[论坛](https://bbs.hankcs.com/)而不是GitHub上。
如果您不修改的话，恐怕没有人能够回复您，我们也会错失一次改进的机会或者一次友好的讨论。开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
