### ISSUE TITLE
2.0.0a46版本语义分析报错

### ISSUE THREAD

**Issue by jiuchang** [hankcs/HanLP#1504]
**Describe the bug**
调用说明中的例子时报错
semantic_parser = hanlp.load(hanlp.pretrained.sdp.SEMEVAL15_PAS_BIAFFINE_EN)
print(semantic_parser([('蜡烛', 'NN'), ('两', 'CD'), ('头', 'NN'), ('烧', 'VV')]))

Traceback (most recent call last):
  File "/media/ps/50a5ea37-da5a-4bf6-9787-bf2cdb400a05/anaconda3/envs/zh/lib/python3.6/site-packages/tensorflow_core/python/eager/context.py", line 1897, in execution_mode
    yield
  File "/media/ps/50a5ea37-da5a-4bf6-9787-bf2cdb400a05/anaconda3/envs/zh/lib/python3.6/site-packages/tensorflow_core/python/data/ops/iterator_ops.py", line 659, in _next_internal
    output_shapes=self._flat_output_shapes)
  File "/media/ps/50a5ea37-da5a-4bf6-9787-bf2cdb400a05/anaconda3/envs/zh/lib/python3.6/site-packages/tensorflow_core/python/ops/gen_dataset_ops.py", line 2479, in iterator_get_next_sync
    _ops.raise_from_not_ok_status(e, name)
  File "/media/ps/50a5ea37-da5a-4bf6-9787-bf2cdb400a05/anaconda3/envs/zh/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 6606, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
Traceback (most recent call last):

  File "/media/ps/50a5ea37-da5a-4bf6-9787-bf2cdb400a05/anaconda3/envs/zh/lib/python3.6/site-packages/tensorflow_core/python/ops/script_ops.py", line 236, in __call__
    ret = func(*args)

  File "/media/ps/50a5ea37-da5a-4bf6-9787-bf2cdb400a05/anaconda3/envs/zh/lib/python3.6/site-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 789, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "/media/ps/50a5ea37-da5a-4bf6-9787-bf2cdb400a05/anaconda3/envs/zh/lib/python3.6/site-packages/hanlp/components/parsers/conll.py", line 271, in generator
    yield from self.batched_inputs_to_batches(corpus, batch, shuffle)

  File "/media/ps/50a5ea37-da5a-4bf6-9787-bf2cdb400a05/anaconda3/envs/zh/lib/python3.6/site-packages/hanlp/components/parsers/conll.py", line 582, in batched_inputs_to_batches
    dtype='int64')

  File "/media/ps/50a5ea37-da5a-4bf6-9787-bf2cdb400a05/anaconda3/envs/zh/lib/python3.6/site-packages/keras_preprocessing/sequence.py", line 98, in pad_sequences
    trunc = np.asarray(trunc, dtype=dtype)

  File "/media/ps/50a5ea37-da5a-4bf6-9787-bf2cdb400a05/anaconda3/envs/zh/lib/python3.6/site-packages/numpy/core/_asarray.py", line 83, in asarray
    return array(a, dtype, copy=False, order=order)

TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

         [[{{node PyFunc}}]] [Op:IteratorGetNextSync]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_hanlp.py", line 26, in <module>
    print(semantic_parser([('蜡烛', 'NN'), ('两', 'CD'), ('头', 'NN'), ('烧', 'VV')]))
  File "/media/ps/50a5ea37-da5a-4bf6-9787-bf2cdb400a05/anaconda3/envs/zh/lib/python3.6/site-packages/hanlp/common/component.py", line 51, in __call__
    return self.predict(data, **kwargs)
  File "/media/ps/50a5ea37-da5a-4bf6-9787-bf2cdb400a05/anaconda3/envs/zh/lib/python3.6/site-packages/hanlp/common/component.py", line 455, in predict
    for idx, batch in enumerate(dataset):
  File "/media/ps/50a5ea37-da5a-4bf6-9787-bf2cdb400a05/anaconda3/envs/zh/lib/python3.6/site-packages/tensorflow_core/python/data/ops/iterator_ops.py", line 630, in __next__
    return self.next()
  File "/media/ps/50a5ea37-da5a-4bf6-9787-bf2cdb400a05/anaconda3/envs/zh/lib/python3.6/site-packages/tensorflow_core/python/data/ops/iterator_ops.py", line 674, in next
    return self._next_internal()
  File "/media/ps/50a5ea37-da5a-4bf6-9787-bf2cdb400a05/anaconda3/envs/zh/lib/python3.6/site-packages/tensorflow_core/python/data/ops/iterator_ops.py", line 665, in _next_internal
    return structure.from_compatible_tensor_list(self._element_spec, ret)
  File "/media/ps/50a5ea37-da5a-4bf6-9787-bf2cdb400a05/anaconda3/envs/zh/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/media/ps/50a5ea37-da5a-4bf6-9787-bf2cdb400a05/anaconda3/envs/zh/lib/python3.6/site-packages/tensorflow_core/python/eager/context.py", line 1900, in execution_mode
    executor_new.wait()
  File "/media/ps/50a5ea37-da5a-4bf6-9787-bf2cdb400a05/anaconda3/envs/zh/lib/python3.6/site-packages/tensorflow_core/python/eager/executor.py", line 67, in wait
    pywrap_tensorflow.TFE_ExecutorWaitForAllPendingNodes(self._handle)
tensorflow.python.framework.errors_impl.InvalidArgumentError: TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
Traceback (most recent call last):

  File "/media/ps/50a5ea37-da5a-4bf6-9787-bf2cdb400a05/anaconda3/envs/zh/lib/python3.6/site-packages/tensorflow_core/python/ops/script_ops.py", line 236, in __call__
    ret = func(*args)

  File "/media/ps/50a5ea37-da5a-4bf6-9787-bf2cdb400a05/anaconda3/envs/zh/lib/python3.6/site-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 789, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "/media/ps/50a5ea37-da5a-4bf6-9787-bf2cdb400a05/anaconda3/envs/zh/lib/python3.6/site-packages/hanlp/components/parsers/conll.py", line 271, in generator
    yield from self.batched_inputs_to_batches(corpus, batch, shuffle)

  File "/media/ps/50a5ea37-da5a-4bf6-9787-bf2cdb400a05/anaconda3/envs/zh/lib/python3.6/site-packages/hanlp/components/parsers/conll.py", line 582, in batched_inputs_to_batches
    dtype='int64')

  File "/media/ps/50a5ea37-da5a-4bf6-9787-bf2cdb400a05/anaconda3/envs/zh/lib/python3.6/site-packages/keras_preprocessing/sequence.py", line 98, in pad_sequences
    trunc = np.asarray(trunc, dtype=dtype)

  File "/media/ps/50a5ea37-da5a-4bf6-9787-bf2cdb400a05/anaconda3/envs/zh/lib/python3.6/site-packages/numpy/core/_asarray.py", line 83, in asarray
    return array(a, dtype, copy=False, order=order)

TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

         [[{{node PyFunc}}]]

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```python
```

**Describe the current behavior**
A clear and concise description of what happened.

**Expected behavior**

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04.6 LTS
- Python version: Python 3.6.10 :: Anaconda, Inc.
- HanLP version: 2.0.0a46

**Other info / logs**
tensorflow                       2.1.0

* [ ] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
【自动回复】您好，感谢反馈。
由于未按要求填写，本issue被自动关闭。请按[issue模板](https://raw.githubusercontent.com/hankcs/HanLP/master/.github/ISSUE_TEMPLATE/bug_report.md)认真修改，然后耐心等待下周末处理。
如果您提的是bug或feature request，那么请您按模板认真改一改，reopen这个issue。
否则，咨询类的问题请先搜索一下。99.9%的问题已经反复回答过了，人类的本质是复读机。如果您确信您提了个新问题，那么欢迎写清楚前因后果发在[论坛](https://bbs.hankcs.com/)而不是GitHub上。
如果您不修改的话，恐怕没有人能够回复您，我们也会错失一次改进的机会或者一次友好的讨论。开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
