### ISSUE TITLE
人名识别失败：习近平－－－git版本

### ISSUE THREAD

**Issue by StardustZhou** [hankcs/HanLP#151]
public class TestErrorSeg {
    public static void main(String[] args) {
        HanLP.Config.enableDebug();
        String str = "习近平访美为全球经济注入新动力";
        List<Term> terms = HanLP.newSegment().enableCustomDictionary(true).enableAllNamedEntityRecognize(true).enableNumberQuantifierRecognize(true).seg(
                str);
        System.out.println(terms);
    }
}

人名角色观察：[  A 22202445 ][习近平 null][访美 L 3 ][为 L 1200 K 920 C 184 D 144 M 40 E 21 ][全球 L 11 K 1 ][经济 L 19 K 2 ][注入 K 3 L 2 ][新动力 A 22202445 ][  A 22202445 ]
Exception in thread "main" java.lang.NullPointerException
	at com.hankcs.hanlp.algoritm.Viterbi.computeEnumSimply(Viterbi.java:254)
	at com.hankcs.hanlp.recognition.nr.PersonRecognition.viterbiExCompute(PersonRecognition.java:171)
	at com.hankcs.hanlp.recognition.nr.PersonRecognition.Recognition(PersonRecognition.java:50)
	at com.hankcs.hanlp.seg.Viterbi.ViterbiSegment.segSentence(ViterbiSegment.java:76)
	at com.hankcs.hanlp.seg.Segment.seg(Segment.java:422)
	at org.nlp.segment.TestErrorSeg.main(TestErrorSeg.java:12)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

**Comment by StardustZhou** [comment]
原因：自定义人名词典是：习近平 nr 3802

case nr:
                    {
                        // 有些双名实际上可以构成更长的三名
                        if (vertex.getAttribute().totalFrequency <= 1000)
                        {
                            if (vertex.realWord.length() == 2)
                            {
                                nrEnumItem = new EnumItem<NR>(NR.X, NR.G);
                            }
                            else nrEnumItem = new EnumItem<NR>(NR.A, PersonDictionary.transformMatrixDictionary.getTotalFrequency(NR.A));
                        }
                    }break;

**Comment by hankcs** [comment]
感谢反馈，的确写错了。

已经修复，如果还有问题，欢迎继续讨论。
