### ISSUE TITLE
运行HanLP-doc-zh/tests/train/zh/train_msra_ner_albert.py时出现bug

### ISSUE THREAD

**Issue by advise2009899** [hankcs/HanLP#1549]
**Describe the bug**
首先是出现Traceback (most recent call last):
  File "C:/Users/Administrator/Desktop/HanLP-doc-zh/HanLP-doc-zh/tests/train/zh/train_msra_ner_albert.py", line 14, in <module>
    metrics='f1')
  File "C:\Users\Administrator\Desktop\HanLP-doc-zh\HanLP-doc-zh\hanlp\components\ner.py", line 83, in fit
    return super().fit(**merge_locals_kwargs(locals(), kwargs))
  File "C:\Users\Administrator\Desktop\HanLP-doc-zh\HanLP-doc-zh\hanlp\components\taggers\transformers\transformer_tagger.py", line 57, in fit
    return super().fit(**merge_locals_kwargs(locals(), kwargs))
  File "C:\Users\Administrator\Desktop\HanLP-doc-zh\HanLP-doc-zh\hanlp\common\component.py", line 352, in fit
    metrics=metrics, overwrite=True))
  File "C:\Users\Administrator\Desktop\HanLP-doc-zh\HanLP-doc-zh\hanlp\components\taggers\transformers\transformer_tagger.py", line 93, in train_loop
    validation_steps=dev_steps,
  File "C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\engine\training.py", line 108, in _method_wrapper
    return method(self, *args, **kwargs)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\engine\training.py", line 1098, in fit
    tmp_logs = train_function(iterator)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\engine\training.py", line 806, in train_function
    return step_function(self, iterator)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\engine\training.py", line 796, in step_function
    outputs = model.distribute_strategy.run(run_step, args=(data,))
  File "C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\distribute\distribute_lib.py", line 1211, in run
    return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\distribute\distribute_lib.py", line 2585, in call_for_each_replica
    return self._call_for_each_replica(fn, args, kwargs)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\distribute\distribute_lib.py", line 2945, in _call_for_each_replica
    return fn(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\autograph\impl\api.py", line 275, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\engine\training.py", line 789, in run_step
    outputs = model.train_step(data)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\engine\training.py", line 749, in train_step
    y, y_pred, sample_weight, regularization_losses=self.losses)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\engine\compile_utils.py", line 187, in __call__
    self.build(y_pred)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\engine\compile_utils.py", line 140, in build
    self._losses = nest.map_structure(self._get_loss_object, self._losses)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\util\nest.py", line 635, in map_structure
    structure[0], [func(*x) for x in entries],
  File "C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\util\nest.py", line 635, in <listcomp>
    structure[0], [func(*x) for x in entries],
  File "C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\engine\compile_utils.py", line 265, in _get_loss_object
    loss_name = loss.__name__
**AttributeError: 'SparseCategoricalCrossentropyOverBatchFirstDim' object has no attribute '__name__'**

2.上述问题解决后出现
Traceback (most recent call last):
  File "C:/Users/Administrator/Desktop/HanLP-doc-zh/HanLP-doc-zh/tests/train/zh/train_msra_ner_albert.py", line 14, in <module>
    metrics='f1')
  File "C:\Users\Administrator\Desktop\HanLP-doc-zh\HanLP-doc-zh\hanlp\components\ner.py", line 83, in fit
    return super().fit(**merge_locals_kwargs(locals(), kwargs))
  File "C:\Users\Administrator\Desktop\HanLP-doc-zh\HanLP-doc-zh\hanlp\components\taggers\transformers\transformer_tagger.py", line 57, in fit
    return super().fit(**merge_locals_kwargs(locals(), kwargs))
  File "C:\Users\Administrator\Desktop\HanLP-doc-zh\HanLP-doc-zh\hanlp\common\component.py", line 352, in fit
    metrics=metrics, overwrite=True))
  File "C:\Users\Administrator\Desktop\HanLP-doc-zh\HanLP-doc-zh\hanlp\components\taggers\transformers\transformer_tagger.py", line 93, in train_loop
    validation_steps=dev_steps,
  File "C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\engine\training.py", line 108, in _method_wrapper
    return method(self, *args, **kwargs)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\engine\training.py", line 1098, in fit
    tmp_logs = train_function(iterator)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\engine\training.py", line 806, in train_function
    return step_function(self, iterator)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\engine\training.py", line 796, in step_function
    outputs = model.distribute_strategy.run(run_step, args=(data,))
  File "C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\distribute\distribute_lib.py", line 1211, in run
    return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\distribute\distribute_lib.py", line 2585, in call_for_each_replica
    return self._call_for_each_replica(fn, args, kwargs)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\distribute\distribute_lib.py", line 2945, in _call_for_each_replica
    return fn(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\autograph\impl\api.py", line 275, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\engine\training.py", line 789, in run_step
    outputs = model.train_step(data)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\engine\training.py", line 757, in train_step
    self.trainable_variables)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\engine\training.py", line 2745, in _minimize
    experimental_aggregate_gradients=False)
**TypeError: apply_gradients() got an unexpected keyword argument 'experimental_aggregate_gradients'**

**Comment by hankcs** [comment]
【自动回复】您好，感谢反馈。
由于未按要求填写，本issue被自动关闭，将在一小时内自动删除。

如果您提的是bug或feature request，请按[issue模板](https://github.com/hankcs/HanLP/tree/doc-zh/.github/ISSUE_TEMPLATE)认真修改，然后耐心等待下周末处理。

否则，[咨询类的问题GitHub概不受理](https://bbs.hankcs.com/t/topic/2245)。请先搜索一下，99.9%的问题已经反复回答过了，人类的本质是复读机。如果您确信您提了个新问题，那么欢迎写清楚前因后果发在[论坛](https://bbs.hankcs.com/)而不是GitHub上。

如果您不修改的话，恐怕没有人能够回复您，我们也会错失一次改进的机会或者一次友好的讨论。开源项目维护不易，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
