### ISSUE TITLE
词性标注载入模型时发生错误

### ISSUE THREAD

**Issue by minstrel0424** [hankcs/HanLP#1560]
**Describe the bug**
载入词性标注模型ctb5_pos_rnn_fasttext_20191230_202639.zip 时发生错误，提示版本不匹配。
前几个月使用一直正常，之前的hanlp版本是2.0.0a44。今天使用的时候突然报错，提示更新后再试。
但是更新到2.0.0a60后依然报错。

**Code to reproduce the issue**
tagger = hanlp.load(hanlp.pretrained.pos.CTB5_POS_RNN_FASTTEXT_ZH)

**Describe the current behavior**
载入时报错：MemoryError: bad allocation，
提示：https://file.hankcs.com/hanlp/pos/ctb5_pos_rnn_fasttext_20191230_202639.zip was created with hanlp-2.0.0, while you are running a lower version: 2.0.0-alpha.60. Please upgrade hanlp with:
pip install --upgrade hanlp
upgrade之后仍然存在该错误，已是最新版本。

**Expected behavior**
载入模型成功，不报错

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Windows 10 专业版 18363.1016
- Python version:3.6.5
- HanLP version:2.0.0a60

**Other info / logs**
报错信息：
Failed to load https://file.hankcs.com/hanlp/pos/ctb5_pos_rnn_fasttext_20191230_202639.zip. See traceback below:
================================ERROR LOG BEGINS================================
Traceback (most recent call last):
  File "D:\Study\NLP\pyNLP\venv\lib\site-packages\hanlp\utils\component_util.py", line 48, in load_from_meta_file
    obj.load(save_dir, **load_kwargs)
  File "D:\Study\NLP\pyNLP\venv\lib\site-packages\hanlp\common\component.py", line 244, in load
    self.build(**merge_dict(self.config, training=False, logger=logger, **kwargs, overwrite=True, inplace=True))
  File "D:\Study\NLP\pyNLP\venv\lib\site-packages\hanlp\common\component.py", line 255, in build
    loss=kwargs.get('loss', None)))
  File "D:\Study\NLP\pyNLP\venv\lib\site-packages\hanlp\components\taggers\rnn_tagger.py", line 34, in build_model
    embeddings = build_embedding(embeddings, self.transform.word_vocab, self.transform)
  File "D:\Study\NLP\pyNLP\venv\lib\site-packages\hanlp\layers\embeddings\__init__.py", line 34, in build_embedding
    custom_objects=tf.keras.utils.get_custom_objects())
  File "D:\Study\NLP\pyNLP\venv\lib\site-packages\tensorflow\python\keras\utils\generic_utils.py", line 360, in deserialize_keras_object
    return cls.from_config(cls_config)
  File "D:\Study\NLP\pyNLP\venv\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 697, in from_config
    return cls(**config)
  File "D:\Study\NLP\pyNLP\venv\lib\site-packages\hanlp\layers\embeddings\fast_text.py", line 35, in __init__
    self.model = fasttext.load_model(filepath)
  File "D:\Study\NLP\pyNLP\venv\lib\site-packages\fasttext\FastText.py", line 350, in load_model
    return _FastText(model_path=path)
  File "D:\Study\NLP\pyNLP\venv\lib\site-packages\fasttext\FastText.py", line 43, in __init__
    self.f.loadModel(model_path)
MemoryError: bad allocation
=================================ERROR LOG ENDS=================================
https://file.hankcs.com/hanlp/pos/ctb5_pos_rnn_fasttext_20191230_202639.zip was created with hanlp-2.0.0, while you are running a lower version: 2.0.0-alpha.60. 
Please upgrade hanlp with:
pip install --upgrade hanlp
If the problem still persists, please submit an issue to https://github.com/hankcs/HanLP/issues .
When reporting an issue, make sure to paste the FULL ERROR LOG above.

* [x] I've completed this form and searched the web for solutions.

**Comment by minstrel0424** [comment]
重启之后就好了。。

**Comment by hankcs** [comment]
应该是内存不足。
