### ISSUE TITLE
运行demo_cws.py时出错

### ISSUE THREAD

**Issue by SimZhou** [hankcs/HanLP#1568]
**Describe the bug**
```bash
Downloading https://file.hankcs.com/hanlp/embeddings/albert_base_zh.tar.gz to /home/yihuazhou/.hanlp/embeddings/albert_base_zh.tar.gz

97.69%, 37.0 MB/37.9 MB, 92 KB/s, ETA 10 s      Failed to load https://file.hankcs.com/hanlp/cws/large_cws_albert_base_20200828_011451.zip. See traceback below:
================================ERROR LOG BEGINS================================
Traceback (most recent call last):
  File "/home/yihuazhou/miniconda3/lib/python3.8/site-packages/hanlp/utils/io_util.py", line 201, in download
    urlretrieve(url, tmp_path, reporthook)
  File "/home/yihuazhou/miniconda3/lib/python3.8/urllib/request.py", line 286, in urlretrieve
    raise ContentTooShortError(
urllib.error.ContentTooShortError: <urlopen error retrieval incomplete: got only 38807364 out of 39731739 bytes>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yihuazhou/miniconda3/lib/python3.8/site-packages/hanlp/utils/component_util.py", line 48, in load_from_meta_file
    obj.load(save_dir, **load_kwargs)
  File "/home/yihuazhou/miniconda3/lib/python3.8/site-packages/hanlp/common/component.py", line 244, in load
    self.build(**merge_dict(self.config, training=False, logger=logger, **kwargs, overwrite=True, inplace=True))
  File "/home/yihuazhou/miniconda3/lib/python3.8/site-packages/hanlp/common/component.py", line 254, in build
    self.model = self.build_model(**merge_dict(self.config, training=kwargs.get('training', None),
  File "/home/yihuazhou/miniconda3/lib/python3.8/site-packages/hanlp/components/taggers/transformers/transformer_tagger.py", line 34, in build_model
    model, tokenizer = build_transformer(transformer, max_seq_length, len(self.transform.tag_vocab), tagging=True)
  File "/home/yihuazhou/miniconda3/lib/python3.8/site-packages/hanlp/layers/transformers/loader.py", line 39, in build_transformer
    bert_dir = get_resource(model_url)
  File "/home/yihuazhou/miniconda3/lib/python3.8/site-packages/hanlp/utils/io_util.py", line 340, in get_resource
    path = download(url=path, save_path=realpath)
  File "/home/yihuazhou/miniconda3/lib/python3.8/site-packages/hanlp/utils/io_util.py", line 214, in download
    installed_version, latest_version, latest_version_str = check_outdated()
ValueError: not enough values to unpack (expected 3, got 2)
=================================ERROR LOG ENDS=================================
When reporting an issue, make sure to paste the FULL ERROR LOG above.
```
**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```python
tokenizer = hanlp.load(hanlp.pretrained.cws.LARGE_ALBERT_BASE)
```

**Describe the current behavior**
A clear and concise description of what happened.
目前下载完albert模型后加载出错

**Expected behavior**
应该能正常加载ALbert模型

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): ubuntu 20.04
- Python version: 3.8.3
- HanLP version: __version__ = '2.0.0-alpha.61'

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

* [ ] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
【自动回复】您好，感谢反馈。
由于未按要求填写，本issue被自动关闭，将在一小时内自动删除。

如果您提的是bug或feature request，请按[issue模板](https://github.com/hankcs/HanLP/tree/doc-zh/.github/ISSUE_TEMPLATE)认真修改，然后耐心等待下周末处理。

否则，[咨询类的问题GitHub概不受理](https://bbs.hankcs.com/t/topic/2245)。请先搜索一下，99.9%的问题已经反复回答过了，人类的本质是复读机。如果您确信您提了个新问题，那么欢迎写清楚前因后果发在[论坛](https://bbs.hankcs.com/)而不是GitHub上。

如果您不修改的话，恐怕没有人能够回复您，我们也会错失一次改进的机会或者一次友好的讨论。开源项目维护不易，HanLP用户以十万计，而主要维护者只有我一人。我有自己的full-time研究工作，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
