### ISSUE TITLE
经常 Java heap space

### ISSUE THREAD

**Issue by haorendashu** [hankcs/HanLP#157]
你好，程序跑一会之后，就经常报这个

```
java.lang.OutOfMemoryError: Java heap space
        at com.hankcs.hanlp.summary.TextRankSentence.<init>(TextRankSentence.java:73)
        at com.hankcs.hanlp.summary.TextRankSentence.getSummary(TextRankSentence.java:245)
        at com.hankcs.hanlp.HanLP.getSummary(HanLP.java:472)
```

是不是还要配置什么？

**Comment by hankcs** [comment]
文本大小？
该类不储存中间结果，不可能有内存泄露。问题只可能是输入文本过大，请加一些异常处理逻辑，定位是多大的文本引发这个异常，而不是武断地说“经常”。

**Comment by haorendashu** [comment]
果然限制了文本大小之后，异常没了。

谢谢。
