### ISSUE TITLE
感知机词性标注出现java.lang.NullPointerException异常

### ISSUE THREAD

**Issue by yidasanqian** [hankcs/HanLP#1581]
**Describe the bug**
按照https://github.com/hankcs/HanLP/wiki/%E7%BB%93%E6%9E%84%E5%8C%96%E6%84%9F%E7%9F%A5%E6%9C%BA%E6%A0%87%E6%B3%A8%E6%A1%86%E6%9E%B6
训练，第二步词性标注，出现空指针异常

**Code to reproduce the issue**

```java
String posModelFile = "D:\\Develop\\hanlp\\icwb2-data\\training\\model\\perceptron\\msr_training.utf8\\pos.bin";
        PerceptronTrainer trainer = new POSTrainer();
        trainer.train(
                "D:\\Develop\\hanlp\\icwb2-data\\training\\msr_training.utf8",
                posModelFile
        );
```

**Describe the current behavior**
训练的预料是：msr_training.utf8，感知机词性标注训练出现空指针异常

**Expected behavior**
正常运行

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): win10
- Python version:
- HanLP version: portable-1.7.5

**Other info / logs**
`
开始加载训练集...

java.lang.NullPointerException
	at java.util.TreeMap.getEntry(TreeMap.java:347)
	at java.util.TreeMap.get(TreeMap.java:278)
	at com.hankcs.hanlp.model.perceptron.tagset.TagSet.add(TagSet.java:44)
	at com.hankcs.hanlp.model.perceptron.instance.POSInstance.<init>(POSInstance.java:43)
	at com.hankcs.hanlp.model.perceptron.instance.POSInstance.create(POSInstance.java:262)
	at com.hankcs.hanlp.model.perceptron.POSTrainer.createInstance(POSTrainer.java:36)
	at com.hankcs.hanlp.model.perceptron.PerceptronTrainer$1.process(PerceptronTrainer.java:288)
	at com.hankcs.hanlp.model.perceptron.utility.IOUtility.loadInstance(IOUtility.java:81)
	at com.hankcs.hanlp.model.perceptron.PerceptronTrainer.loadTrainInstances(PerceptronTrainer.java:282)
	at com.hankcs.hanlp.model.perceptron.PerceptronTrainer.train(PerceptronTrainer.java:122)
	at com.hankcs.hanlp.model.perceptron.POSTrainer.train(POSTrainer.java:43)
	at com.hankcs.hanlp.model.perceptron.PerceptronTrainer.train(PerceptronTrainer.java:320)
`

* [x] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
msr_training.utf8是分词语料，不是词性标注语料。
https://github.com/hankcs/HanLP/wiki/%E7%BB%93%E6%9E%84%E5%8C%96%E6%84%9F%E7%9F%A5%E6%9C%BA%E6%A0%87%E6%B3%A8%E6%A1%86%E6%9E%B6#%E8%AF%AD%E6%96%99%E6%A0%BC%E5%BC%8F
