### ISSUE TITLE
Fork进程中加载模型失败

### ISSUE THREAD

**Issue by BlackHacked** [hankcs/HanLP#1583]
**Describe the bug**
```bash
[2020-11-07 20:23:18,313: WARNING/ForkPoolWorker-2] Failed to load https://file.hankcs.com/hanlp/cws/large_cws_albert_base_20200828_011451.zip. See traceback below:
[2020-11-07 20:23:18,313: WARNING/ForkPoolWorker-2] ================================ERROR LOG BEGINS================================
[2020-11-07 20:23:18,316: WARNING/ForkPoolWorker-2] Traceback (most recent call last):
[2020-11-07 20:23:18,316: WARNING/ForkPoolWorker-2] File "/usr/local/lib/python3.6/dist-packages/hanlp/utils/component_util.py", line 49, in load_from_meta_file
    obj.load(save_dir, **load_kwargs)
[2020-11-07 20:23:18,317: WARNING/ForkPoolWorker-2] File "/usr/local/lib/python3.6/dist-packages/hanlp/common/component.py", line 244, in load
    self.build(**merge_dict(self.config, training=False, logger=logger, **kwargs, overwrite=True, inplace=True))
[2020-11-07 20:23:18,317: WARNING/ForkPoolWorker-2] File "/usr/local/lib/python3.6/dist-packages/hanlp/common/component.py", line 255, in build
    loss=kwargs.get('loss', None)))
[2020-11-07 20:23:18,317: WARNING/ForkPoolWorker-2] File "/usr/local/lib/python3.6/dist-packages/hanlp/components/taggers/transformers/transformer_tagger.py", line 36, in build_model
    model, tokenizer = build_transformer(transformer, max_seq_length, len(self.transform.tag_vocab), tagging=True)
[2020-11-07 20:23:18,317: WARNING/ForkPoolWorker-2] File "/usr/local/lib/python3.6/dist-packages/hanlp/layers/transformers/loader.py", line 75, in build_transformer
    with stdout_redirected(to=os.devnull):
[2020-11-07 20:23:18,317: WARNING/ForkPoolWorker-2] File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
[2020-11-07 20:23:18,317: WARNING/ForkPoolWorker-2] File "/usr/local/lib/python3.6/dist-packages/hanlp/utils/io_util.py", line 559, in stdout_redirected
    stdout_fd = fileno(stdout)
[2020-11-07 20:23:18,317: WARNING/ForkPoolWorker-2] File "/usr/local/lib/python3.6/dist-packages/hanlp/utils/io_util.py", line 540, in fileno
    raise ValueError("Expected a file (`.fileno()`) or a file descriptor")
[2020-11-07 20:23:18,317: WARNING/ForkPoolWorker-2] ValueError: Expected a file (`.fileno()`) or a file descriptor
[2020-11-07 20:23:18,318: WARNING/ForkPoolWorker-2] =================================ERROR LOG ENDS=================================
[2020-11-07 20:23:18,811: WARNING/ForkPoolWorker-2] If the problem still persists, please submit an issue to https://github.com/hankcs/HanLP/issues
When reporting an issue, make sure to paste the FULL ERROR LOG above.
```

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```python
def attr_extract(txt):
    map_path = os.path.join(os.path.dirname(__file__), "map.txt")
    regulation = load_map(map_path)
    sentenceStr = txt
    tokenizer = hanlp.load(hanlp.pretrained.cws.LARGE_ALBERT_BASE)
    wordList = tokenizer(sentenceStr)
    tagger = hanlp.load(hanlp.pretrained.pos.CTB5_POS_RNN)
    labelList = tagger(wordList)

```

**Describe the current behavior**
A clear and concise description of what happened.
```
celery后台任务处理分词时加载模型失败
```
**Expected behavior**
```
期望正常运行
```
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04.1 LTS
- Python version: Python3.6.12
- HanLP version: hanlp2.0.0a66

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

* [x] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
Hi, TF只支持spawn模式，请试试：

https://github.com/hankcs/HanLP/blob/master/tests/demo/zh/demo_multiprocess.py

**Comment by yick2232** [comment]
> **Describe the bug**
> A clear and concise description of what the bug is.
> 
> ```shell
> [2020-11-07 20:23:18,313: WARNING/ForkPoolWorker-2] Failed to load https://file.hankcs.com/hanlp/cws/large_cws_albert_base_20200828_011451.zip. See traceback below:
> [2020-11-07 20:23:18,313: WARNING/ForkPoolWorker-2] ================================ERROR LOG BEGINS================================
> [2020-11-07 20:23:18,316: WARNING/ForkPoolWorker-2] Traceback (most recent call last):
> [2020-11-07 20:23:18,316: WARNING/ForkPoolWorker-2] File "/usr/local/lib/python3.6/dist-packages/hanlp/utils/component_util.py", line 49, in load_from_meta_file
>     obj.load(save_dir, **load_kwargs)
> [2020-11-07 20:23:18,317: WARNING/ForkPoolWorker-2] File "/usr/local/lib/python3.6/dist-packages/hanlp/common/component.py", line 244, in load
>     self.build(**merge_dict(self.config, training=False, logger=logger, **kwargs, overwrite=True, inplace=True))
> [2020-11-07 20:23:18,317: WARNING/ForkPoolWorker-2] File "/usr/local/lib/python3.6/dist-packages/hanlp/common/component.py", line 255, in build
>     loss=kwargs.get('loss', None)))
> [2020-11-07 20:23:18,317: WARNING/ForkPoolWorker-2] File "/usr/local/lib/python3.6/dist-packages/hanlp/components/taggers/transformers/transformer_tagger.py", line 36, in build_model
>     model, tokenizer = build_transformer(transformer, max_seq_length, len(self.transform.tag_vocab), tagging=True)
> [2020-11-07 20:23:18,317: WARNING/ForkPoolWorker-2] File "/usr/local/lib/python3.6/dist-packages/hanlp/layers/transformers/loader.py", line 75, in build_transformer
>     with stdout_redirected(to=os.devnull):
> [2020-11-07 20:23:18,317: WARNING/ForkPoolWorker-2] File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
>     return next(self.gen)
> [2020-11-07 20:23:18,317: WARNING/ForkPoolWorker-2] File "/usr/local/lib/python3.6/dist-packages/hanlp/utils/io_util.py", line 559, in stdout_redirected
>     stdout_fd = fileno(stdout)
> [2020-11-07 20:23:18,317: WARNING/ForkPoolWorker-2] File "/usr/local/lib/python3.6/dist-packages/hanlp/utils/io_util.py", line 540, in fileno
>     raise ValueError("Expected a file (`.fileno()`) or a file descriptor")
> [2020-11-07 20:23:18,317: WARNING/ForkPoolWorker-2] ValueError: Expected a file (`.fileno()`) or a file descriptor
> [2020-11-07 20:23:18,318: WARNING/ForkPoolWorker-2] =================================ERROR LOG ENDS=================================
> [2020-11-07 20:23:18,811: WARNING/ForkPoolWorker-2] If the problem still persists, please submit an issue to https://github.com/hankcs/HanLP/issues
> When reporting an issue, make sure to paste the FULL ERROR LOG above.
> ```
> 
> **Code to reproduce the issue**
> Provide a reproducible test case that is the bare minimum necessary to generate the problem.
> 
> ```python
> def attr_extract(txt):
>     map_path = os.path.join(os.path.dirname(__file__), "map.txt")
>     regulation = load_map(map_path)
>     sentenceStr = txt
>     tokenizer = hanlp.load(hanlp.pretrained.cws.LARGE_ALBERT_BASE)
>     wordList = tokenizer(sentenceStr)
>     tagger = hanlp.load(hanlp.pretrained.pos.CTB5_POS_RNN)
>     labelList = tagger(wordList)
> ```
> 
> **Describe the current behavior**
> A clear and concise description of what happened.
> 
> ```
> celery后台任务处理分词时加载模型失败
> ```
> 
> **Expected behavior**
> A clear and concise description of what you expected to happen.
> 
> ```
> 期望正常运行
> ```
> 
> **System information**
> 
> * OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04.1 LTS
> * Python version: Python3.6.12
> * HanLP version: hanlp2.0.0a66
> 
> **Other info / logs**
> Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
> 
> * [x]  I've completed this form and searched the web for solutions.

你最后解决了问题了吗？和 Spawn模式没有关系。
