### ISSUE TITLE
程序崩溃 （hanlp.pretrained.mtl.UD_ONTONOTES_TOK_POS_LEM_FEA_NER_SRL_DEP_SDP_CON_XLMR_BASE）

### ISSUE THREAD

**Issue by pnchen** [hankcs/HanLP#1605]
**Describe the bug**
程序崩溃

**Code to reproduce the issue**
```python
import hanlp
print(hanlp.__version__)
text = 'No Apagues La Luz - Enrique Iglesias, 歌曲大合集,新整理欧美,No Apagues La Luz - Enrique Iglesias'
Sentence = hanlp.load(hanlp.pretrained.eos.UD_CTB_EOS_MUL)
sentences = Sentence(text)
print(sentences)
Tok = hanlp.load(hanlp.pretrained.mtl.UD_ONTONOTES_TOK_POS_LEM_FEA_NER_SRL_DEP_SDP_CON_XLMR_BASE) 
toks = Tok(sentences)
print(toks)
```

**Describe the current behavior**
A clear and concise description of what happened.

**Expected behavior**

**System information**
- macOS 10.15.7 (19H114))
- Python 3.6.8 (v3.6.8:3c6b436a57, Dec 24 2018, 02:04:31)
- HanLP version 2.1.0-alpha.10

**Other info / logs**
2.1.0-alpha.10
['No Apagues La Luz - Enrique Iglesias, 歌曲大合集,新整理欧美,No Apagues La Luz - Enrique Iglesias']
Traceback (most recent call last):
  File "test.py", line 29, in <module>
    toks = Tok(sentences)
  File "/Users/pnchen/workspace/projects/cnooc/awat/hanlp2.1/env/lib/python3.6/site-packages/hanlp/components/mtl/multi_task_learning.py", line 766, in __call__
    return super().__call__(data, batch_size, **kwargs)
  File "/Users/pnchen/workspace/projects/cnooc/awat/hanlp2.1/env/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "/Users/pnchen/workspace/projects/cnooc/awat/hanlp2.1/env/lib/python3.6/site-packages/hanlp/common/torch_component.py", line 631, in __call__
    **kwargs))
  File "/Users/pnchen/workspace/projects/cnooc/awat/hanlp2.1/env/lib/python3.6/site-packages/hanlp/common/component.py", line 36, in __call__
    return self.predict(data, **kwargs)
  File "/Users/pnchen/workspace/projects/cnooc/awat/hanlp2.1/env/lib/python3.6/site-packages/hanlp/components/mtl/multi_task_learning.py", line 511, in predict
    run_transform=True, cls_is_bos=cls_is_bos, sep_is_eos=sep_is_eos)
  File "/Users/pnchen/workspace/projects/cnooc/awat/hanlp2.1/env/lib/python3.6/site-packages/hanlp/components/mtl/multi_task_learning.py", line 591, in predict_task
    results[output_key].extend(task.prediction_to_result(output_dict[output_key]['prediction'], batch))
  File "/Users/pnchen/workspace/projects/cnooc/awat/hanlp2.1/env/lib/python3.6/site-packages/hanlp/components/mtl/tasks/ud.py", line 134, in prediction_to_result
    yield from UniversalDependenciesParser.prediction_to_human(self, prediction, batch)
  File "/Users/pnchen/workspace/projects/cnooc/awat/hanlp2.1/env/lib/python3.6/site-packages/hanlp/components/parsers/ud/ud_parser.py", line 339, in prediction_to_human
    lemma = [apply_lemma_rule(t, lem_vocab[r]) for t, r in zip(form, lemma)]
  File "/Users/pnchen/workspace/projects/cnooc/awat/hanlp2.1/env/lib/python3.6/site-packages/hanlp/components/parsers/ud/ud_parser.py", line 339, in <listcomp>
    lemma = [apply_lemma_rule(t, lem_vocab[r]) for t, r in zip(form, lemma)]
  File "/Users/pnchen/workspace/projects/cnooc/awat/hanlp2.1/env/lib/python3.6/site-packages/hanlp/components/parsers/ud/lemma_edit.py", line 88, in apply_lemma_rule
    casing, rule = lemma_rule.split(";", 1)
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by hankcs** [comment]
【自动回复】您好，感谢反馈。
由于未按要求填写，本issue被自动关闭，将在一小时内自动删除。

如果您提的是bug或feature request，请按[issue模板](https://github.com/hankcs/HanLP/tree/doc-zh/.github/ISSUE_TEMPLATE)认真修改，然后耐心等待下周末处理。

否则，[咨询类的问题GitHub概不受理](https://bbs.hankcs.com/t/topic/2245)。请先搜索一下，99.9%的问题已经反复回答过了，人类的本质是复读机。如果您确信您提了个新问题，那么欢迎写清楚前因后果发在[论坛](https://bbs.hankcs.com/)而不是GitHub上。

开源项目维护不易，HanLP用户以十万计，而主要维护者只有我一人。我有自己的full-time研究工作，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
