### ISSUE TITLE
1.2.9出错：java.lang.ArrayIndexOutOfBoundsException: 64

### ISSUE THREAD

**Issue by jdb110** [hankcs/HanLP#161]
代码
try{
	termList = HanLP.segment(nr.toUpperCase());
}
catch (Exception e2) {
	e2.printStackTrace();
	continue;
}

出错信息
java.lang.ArrayIndexOutOfBoundsException: 64
	at com.hankcs.hanlp.seg.Viterbi.ViterbiSegment.viterbi(ViterbiSegment.java:140)
	at com.hankcs.hanlp.seg.Viterbi.ViterbiSegment.segSentence(ViterbiSegment.java:101)
	at com.hankcs.hanlp.seg.Segment.seg(Segment.java:441)
	at com.hankcs.hanlp.tokenizer.StandardTokenizer.segment(StandardTokenizer.java:50)
	at com.hankcs.hanlp.HanLP.segment(HanLP.java:386)

**Comment by hankcs** [comment]
nr是什么内容？

**Comment by hankcs** [comment]
由于没有更具体的线索，我无法复现这个问题。欢迎在能提供详细信息的前提下，重开这个issue。
