### ISSUE TITLE
RecursionError: maximum recursion depth exceeded in comparison

### ISSUE THREAD

**Issue by withchencheng** [hankcs/HanLP#1622]
**Describe the bug**
使用readme.md示例的代码去解析20万行自然语言句子报此错误。每个句子的length限制在40以内。

**Code to reproduce the issue**
数据见 
[sg_phone40.zip](https://github.com/hankcs/HanLP/files/6042006/sg_phone40.zip)

```python
import hanlp
from tqdm import tqdm
han = hanlp.load(hanlp.pretrained.mtl.CLOSE_TOK_POS_NER_SRL_DEP_SDP_CON_ELECTRA_SMALL_ZH) # 世界最大中文语料库
#p=han(['2021年HanLPv2.1为生产环境带来次世代最先进的多语种NLP技术。', '阿婆主来到北京立方庭参观自然语义科技公司。'])
#print(type(p))#<class 'hanlp_common.document.Document'>'
#print(p)


with open('sg_phone40','r')as ifile:
    corpus = ifile.read().split('\n')     #直接输入corpus，不用下面的k做batching也会报同样的错，但是要跑到大约7万多行的时候才出错，要等很久，不方便debug

err=73072
corpus=corpus[err-2000 : err+2000]

n=len(corpus)
k=1000
ps=[]

batch=[]
for s in tqdm(corpus):
    if len(batch)<k:
        batch.append(s)
    else:
        ptmp=han(batch)
        ps.append(ptmp)
        batch=[]

if len(batch)>0:
    ptmp=han(batch)
    ps.append(ptmp)

import pickle

pickle.dump( ps, open( "phone_hanlp_pipeline20210225_2.pkl", "wb" ) )

```

**Describe the current behavior**
报错退出
```
(base) [cc@localhost sg_phone]$ python parse2.py 
 50%|██████████████████████████████████████████████▌                                              | 2001/4000 [00:17<00:17, 111.90it/s]
Traceback (most recent call last):
  File "parse2.py", line 24, in <module>
    ptmp=han(batch)
  File "/home1/data/cc/opt/anaconda3/lib/python3.8/site-packages/hanlp/components/mtl/multi_task_learning.py", line 768, in __call__
    return super().__call__(data, batch_size, **kwargs)
  File "/home1/data/cc/opt/anaconda3/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "/home1/data/cc/opt/anaconda3/lib/python3.8/site-packages/hanlp/common/torch_component.py", line 629, in __call__
    return super().__call__(data, **merge_dict(self.config, overwrite=True,
  File "/home1/data/cc/opt/anaconda3/lib/python3.8/site-packages/hanlp/common/component.py", line 36, in __call__
    return self.predict(data, **kwargs)
  File "/home1/data/cc/opt/anaconda3/lib/python3.8/site-packages/hanlp/components/mtl/multi_task_learning.py", line 512, in predict
    output_dict = self.predict_task(self.tasks[task_name], task_name, batch, results, output_dict,
  File "/home1/data/cc/opt/anaconda3/lib/python3.8/site-packages/hanlp/components/mtl/multi_task_learning.py", line 592, in predict_task
    self.decode_output(output_dict, batch, output_key)
  File "/home1/data/cc/opt/anaconda3/lib/python3.8/site-packages/hanlp/components/mtl/multi_task_learning.py", line 728, in decode_output
    output_per_task['prediction'] = self.tasks[task_name].decode_output(
  File "/home1/data/cc/opt/anaconda3/lib/python3.8/site-packages/hanlp/components/mtl/tasks/constituency.py", line 135, in decode_output
    return CRFConstituencyParser.decode_output(self, out, mask, batch, output.get('span_probs', None),
  File "/home1/data/cc/opt/anaconda3/lib/python3.8/site-packages/hanlp/components/parsers/constituency/crf_constituency_parser.py", line 127, in decode_output
    chart_preds = decoder.decode(s_span, s_label, mask)
  File "/home1/data/cc/opt/anaconda3/lib/python3.8/site-packages/hanlp/components/parsers/constituency/crf_constituency_model.py", line 189, in decode
    span_preds = cky(s_span, mask)
  File "/home1/data/cc/opt/anaconda3/lib/python3.8/site-packages/hanlp/components/parsers/alg.py", line 313, in cky
    trees = [backtrack(p[i], 0, length) for i, length in enumerate(lens.tolist())]
  File "/home1/data/cc/opt/anaconda3/lib/python3.8/site-packages/hanlp/components/parsers/alg.py", line 313, in <listcomp>
    trees = [backtrack(p[i], 0, length) for i, length in enumerate(lens.tolist())]
  File "/home1/data/cc/opt/anaconda3/lib/python3.8/site-packages/hanlp/components/parsers/alg.py", line 308, in backtrack
    ltree = backtrack(p, i, split)
  File "/home1/data/cc/opt/anaconda3/lib/python3.8/site-packages/hanlp/components/parsers/alg.py", line 308, in backtrack
    ltree = backtrack(p, i, split)
  File "/home1/data/cc/opt/anaconda3/lib/python3.8/site-packages/hanlp/components/parsers/alg.py", line 308, in backtrack
    ltree = backtrack(p, i, split)
  [Previous line repeated 982 more times]
  File "/home1/data/cc/opt/anaconda3/lib/python3.8/site-packages/hanlp/components/parsers/alg.py", line 305, in backtrack
    if j == i + 1:
RecursionError: maximum recursion depth exceeded in comparison
```

**Expected behavior**
正常跑完

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CentOS Linux release 7.6.1810 (Core)
- Python version: 3.8.3
- HanLP version: 2.1.0-alpha.23

**Other info / logs**
复现错误的代码不设置`k`做batching，直接跑也会出错的。

* [x] I've completed this form and searched the web for solutions.

**Comment by withchencheng** [comment]
`k`设置为1就正常跑完了，但是慢3倍左右

**Comment by hankcs** [comment]
感谢反馈，已经修复，请参考上面的commit。
如果还有问题，欢迎重开issue。

原因是你的文件中有空白行，触发了一个边界case 的 error，现在已经增加了针对性的处理，请升级。

另外，你不需要手动batching，默认已经按32个句子batching了。
