### ISSUE TITLE
IndexError: The shape of the mask [86, 39, 39] at index 1 does not match the shape of the indexed tensor [86, 41, 41, 19] at index 1

### ISSUE THREAD

**Issue by withchencheng** [hankcs/HanLP#1624]
**Describe the bug**
Error when parsing 33082 english sentences.

**Code to reproduce the issue**
data here:  
[qtitles.zip](https://github.com/hankcs/HanLP/files/6056254/qtitles.zip)

```python
import hanlp
han = hanlp.load(hanlp.pretrained.mtl.UD_ONTONOTES_TOK_POS_LEM_FEA_NER_SRL_DEP_SDP_CON_MT5_SMALL) # 'mt5 small version of joint tok, pos, lem, fea, ner, srl, dep, sdp and con model trained on UD and OntoNotes5 corpus.'

with open('/home1/qtitles','r')as ifile:
    corpus = ifile.read().split('\n')

ps=han(corpus)
```

**Describe the current behavior**
Error & Exit with the following output:

```
Traceback (most recent call last):
  File "parse2.py", line 14, in <module>
    ps=han(corpus)
  File "/home1/data/cc/opt/anaconda3/lib/python3.8/site-packages/hanlp/components/mtl/multi_task_learning.py", line 768, in __call__
    return super().__call__(data, batch_size, **kwargs)
  File "/home1/data/cc/opt/anaconda3/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "/home1/data/cc/opt/anaconda3/lib/python3.8/site-packages/hanlp/common/torch_component.py", line 629, in __call__
    return super().__call__(data, **merge_dict(self.config, overwrite=True,
  File "/home1/data/cc/opt/anaconda3/lib/python3.8/site-packages/hanlp/common/component.py", line 36, in __call__
    return self.predict(data, **kwargs)
  File "/home1/data/cc/opt/anaconda3/lib/python3.8/site-packages/hanlp/components/mtl/multi_task_learning.py", line 512, in predict
    output_dict = self.predict_task(self.tasks[task_name], task_name, batch, results, output_dict,
  File "/home1/data/cc/opt/anaconda3/lib/python3.8/site-packages/hanlp/components/mtl/multi_task_learning.py", line 590, in predict_task
    output_dict, batch = self.feed_batch(batch, output_key, output_dict, run_transform, cls_is_bos, sep_is_eos,
  File "/home1/data/cc/opt/anaconda3/lib/python3.8/site-packages/hanlp/components/mtl/multi_task_learning.py", line 682, in feed_batch
    'output': task.feed_batch(h,
  File "/home1/data/cc/opt/anaconda3/lib/python3.8/site-packages/hanlp/components/mtl/tasks/__init__.py", line 182, in feed_batch
    return decoder(h, batch=batch, mask=mask)
  File "/home1/data/cc/opt/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home1/data/cc/opt/anaconda3/lib/python3.8/site-packages/hanlp/components/ner/biaffine_ner/biaffine_ner_model.py", line 82, in forward
    return self.decode(contextualized_embeddings, gold_starts, gold_ends, gold_labels, mask,
  File "/home1/data/cc/opt/anaconda3/lib/python3.8/site-packages/hanlp/components/ner/biaffine_ner/biaffine_ner_model.py", line 116, in decode
    candidate_ner_scores = candidate_ner_scores[candidate_scores_mask]
IndexError: The shape of the mask [86, 39, 39] at index 1 does not match the shape of the indexed tensor [86, 41, 41, 19] at index 1

```

**Expected behavior**
no output

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  CentOS Linux release 7.6.1810 (Core) 
- Python version: 3.8.3
- HanLP version: '2.1.0-alpha.25'

**Other info / logs**

* [x] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
无法复现，完全正常：
[qtitles.hanlp.json.zip](https://github.com/hankcs/HanLP/files/6056278/qtitles.hanlp.json.zip)

请使用最新版：`pip install hanlp -U`

**Comment by withchencheng** [comment]
非常感谢何老师，还提供了parse结果给我。


我发现我这里出的错误跟数据也没关系。
我找了两台机器，在centos，Python3下使用最新版本的 hanlp'2.1.0-alpha.28'，运行如下简单的英文parse代码：


```
import hanlp
han = hanlp.load(hanlp.pretrained.mtl.UD_ONTONOTES_TOK_POS_LEM_FEA_NER_SRL_DEP_SDP_CON_MT5_SMALL) #从file.hankcs.com自动下载的
ps=han(['I will give it back someday.', 'It rains cats and dogs.'])
print(ps)

```


报同样的错：
```
Traceback (most recent call last):
&nbsp; File "parse2.py", line 14, in <module&gt;
&nbsp; &nbsp; ps=han(['I will give it back someday.', 'It rains cats and dogs.'])
&nbsp; File "/home/u2017000613/.conda/envs/p37/lib/python3.7/site-packages/hanlp/components/mtl/multi_task_learning.py", line 768, in __call__
&nbsp; &nbsp; return super().__call__(data, batch_size, **kwargs)
&nbsp; File "/home/u2017000613/.conda/envs/p37/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
&nbsp; &nbsp; return func(*args, **kwargs)
&nbsp; File "/home/u2017000613/.conda/envs/p37/lib/python3.7/site-packages/hanlp/common/torch_component.py", line 632, in __call__
&nbsp; &nbsp; **kwargs))
&nbsp; File "/home/u2017000613/.conda/envs/p37/lib/python3.7/site-packages/hanlp/common/component.py", line 36, in __call__
&nbsp; &nbsp; return self.predict(data, **kwargs)
&nbsp; File "/home/u2017000613/.conda/envs/p37/lib/python3.7/site-packages/hanlp/components/mtl/multi_task_learning.py", line 513, in predict
&nbsp; &nbsp; run_transform=True, cls_is_bos=cls_is_bos, sep_is_eos=sep_is_eos)
&nbsp; File "/home/u2017000613/.conda/envs/p37/lib/python3.7/site-packages/hanlp/components/mtl/multi_task_learning.py", line 591, in predict_task
&nbsp; &nbsp; results)
&nbsp; File "/home/u2017000613/.conda/envs/p37/lib/python3.7/site-packages/hanlp/components/mtl/multi_task_learning.py", line 685, in feed_batch
&nbsp; &nbsp; decoder=self.model.decoders[task_name]),
&nbsp; File "/home/u2017000613/.conda/envs/p37/lib/python3.7/site-packages/hanlp/components/mtl/tasks/__init__.py", line 182, in feed_batch
&nbsp; &nbsp; return decoder(h, batch=batch, mask=mask)
&nbsp; File "/home/u2017000613/.conda/envs/p37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
&nbsp; &nbsp; result = self.forward(*input, **kwargs)
&nbsp; File "/home/u2017000613/.conda/envs/p37/lib/python3.7/site-packages/hanlp/components/ner/biaffine_ner/biaffine_ner_model.py", line 84, in forward
&nbsp; &nbsp; num_sentences, sent_lengths)
&nbsp; File "/home/u2017000613/.conda/envs/p37/lib/python3.7/site-packages/hanlp/components/ner/biaffine_ner/biaffine_ner_model.py", line 116, in decode
&nbsp; &nbsp; candidate_ner_scores = candidate_ner_scores[candidate_scores_mask]
IndexError: The shape of the mask [2, 6, 6] at index 1 does not match the shape of the indexed tensor [2, 8, 8, 19] at index 1

```


------------------&nbsp;Original&nbsp;------------------

**Comment by hankcs** [comment]
感谢反馈，已经修复，请参考上面的commit。
如果还有问题，欢迎重开issue。

我的本地模型跟网络上的不一样，现在重新发布了。

https://colab.research.google.com/drive/1DIv-LJy_I-GyU0lWLdcloYaRKk6DWkgS?usp=sharing
