### ISSUE TITLE
M

### ISSUE THREAD

**Issue by alice1ma** [hankcs/HanLP#1636]
Downloading https://file.hankcs.com/hanlp/ner/ner_bert_base_msra_20200104_185735.zip to C:\Users\xinlian\AppData\Roaming\hanlp\hanlp\ner\ner_bert_base_msra_20200104_185735.zip
100% 360.3 MiB 403.3 KiB/s ETA:  0 s [=========================================]
Extracting C:\Users\xinlian\AppData\Roaming\hanlp\hanlp\ner\ner_bert_base_msra_20200104_185735.zip to C:\Users\xinlian\AppData\Roaming\hanlp\hanlp\ner
2021-03-25 16:45:11.924483: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2021-03-25 16:45:11.924971: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-03-25 16:45:14.395992: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'nvcuda.dll'; dlerror: nvcuda.dll not found
2021-03-25 16:45:14.396319: W tensorflow/stream_executor/cuda/cuda_driver.cc:312] failed call to cuInit: UNKNOWN ERROR (303)
2021-03-25 16:45:14.399318: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: xl123
2021-03-25 16:45:14.399709: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: xl123
Failed to load https://file.hankcs.com/hanlp/ner/ner_bert_base_msra_20200104_185735.zip. See traceback below:
================================ERROR LOG BEGINS================================
Traceback (most recent call last):
  File "C:\Users\xinlian\AppData\Local\Programs\Python\Python38\lib\site-packages\hanlp\utils\component_util.py", line 74, in load_from_meta_file
    obj: Component = object_from_classpath(cls)
  File "C:\Users\xinlian\AppData\Local\Programs\Python\Python38\lib\site-packages\hanlp_common\reflection.py", line 27, in object_from_classpath
    classpath = str_to_type(classpath)
  File "C:\Users\xinlian\AppData\Local\Programs\Python\Python38\lib\site-packages\hanlp_common\reflection.py", line 44, in str_to_type
    cls = getattr(importlib.import_module(module_name), class_name)
  File "C:\Users\xinlian\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\xinlian\AppData\Local\Programs\Python\Python38\lib\site-packages\hanlp\components\ner_tf.py", line 15, in <module>
    from hanlp.components.taggers.transformers.transformer_tagger_tf import TransformerTaggerTF
  File "D:\PyCharm Community Edition 2020.3.4\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\xinlian\AppData\Local\Programs\Python\Python38\lib\site-packages\hanlp\components\taggers\transformers\transformer_tagger_tf.py", line 11, in <module>
    from hanlp.layers.transformers.loader_tf import build_transformer
  File "D:\PyCharm Community Edition 2020.3.4\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\xinlian\AppData\Local\Programs\Python\Python38\lib\site-packages\hanlp\layers\transformers\loader_tf.py", line 9, in <module>
    from bert import albert_models_tfhub, fetch_tfhub_albert_model, load_stock_weights
ImportError: cannot import name 'albert_models_tfhub' from 'bert' (C:\Users\xinlian\AppData\Local\Programs\Python\Python38\lib\site-packages\bert\__init__.py)
=================================ERROR LOG ENDS=================================
If the problem still persists, please submit an issue to https://github.com/hankcs/HanLP/issues
When reporting an issue, make sure to paste the FULL ERROR LOG above.

**Comment by hankcs** [comment]
[auto-reply] Thanks for your comment. However, the essential information is required. Please carefully fill out the form when open a new issue.
