### ISSUE TITLE
ValueError: invalid literal for int() with base 8: 'uild_ten'

### ISSUE THREAD

**Issue by zhangguanqun** [hankcs/HanLP#1647]
**Describe the bug**
Run failed with simple code after hanlp pip installed.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
```
import hanlp
HanLP = hanlp.load(hanlp.pretrained.mtl.CLOSE_TOK_POS_NER_SRL_DEP_SDP_CON_ELECTRA_SMALL_ZH) # 世界最大中文语料库
HanLP(['2021年HanLPv2.1为生产环境带来次世代最先进的多语种NLP技术。', '阿婆主来到北京立方庭参观自然语义科技公司。'])
```

**Describe the current behavior**
Run failed with exceptions.

**Expected behavior**
Run success with ouputs as readme.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Python version: python 3.6.9
- HanLP version: 2.1.0a38 (pip install)

**Other info / logs**
```
Downloading https://file.hankcs.com/hanlp/mtl/close_tok_pos_ner_srl_dep_sdp_con_electra_small_20210111_124159.zip to /home/zhangguanqun/.hanlp/mtl/close_tok_pos_ner_srl_dep_sdp_con_electra_small_20210111_124159.zip
100% 114.3 MiB   2.7 MiB/s ETA:  0 s [=============================================================]
Decompressing /home/zhangguanqun/.hanlp/mtl/close_tok_pos_ner_srl_dep_sdp_con_electra_small_20210111_124159.zip to /home/zhangguanqun/.hanlp/mtl
Downloading: 100%|██████████| 627/627 [00:00<00:00, 409kB/s]
Downloading: 100%|██████████| 110k/110k [00:00<00:00, 151kB/s]  
Downloading: 100%|██████████| 269k/269k [00:00<00:00, 277kB/s] 
Downloading: 100%|██████████| 2.00/2.00 [00:00<00:00, 1.53kB/s]
Downloading: 100%|██████████| 112/112 [00:00<00:00, 81.4kB/s]
Downloading: 100%|██████████| 19.0/19.0 [00:00<00:00, 15.1kB/s]
Failed to load https://file.hankcs.com/hanlp/mtl/close_tok_pos_ner_srl_dep_sdp_con_electra_small_20210111_124159.zip. See traceback below:
================================ERROR LOG BEGINS================================
Traceback (most recent call last):
  File "/usr/lib/python3.6/tarfile.py", line 189, in nti
    n = int(s.strip() or "0", 8)
ValueError: invalid literal for int() with base 8: 'uild_ten'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/tarfile.py", line 2299, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "/usr/lib/python3.6/tarfile.py", line 1093, in fromtarfile
    obj = cls.frombuf(buf, tarfile.encoding, tarfile.errors)
  File "/usr/lib/python3.6/tarfile.py", line 1035, in frombuf
    chksum = nti(buf[148:156])
  File "/usr/lib/python3.6/tarfile.py", line 191, in nti
    raise InvalidHeaderError("invalid header")
tarfile.InvalidHeaderError: invalid header

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 555, in _load
    return legacy_load(f)
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 466, in legacy_load
    with closing(tarfile.open(fileobj=f, mode='r:', format=tarfile.PAX_FORMAT)) as tar, \
  File "/usr/lib/python3.6/tarfile.py", line 1591, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/usr/lib/python3.6/tarfile.py", line 1621, in taropen
    return cls(name, mode, fileobj, **kwargs)
  File "/usr/lib/python3.6/tarfile.py", line 1484, in __init__
    self.firstmember = self.next()
  File "/usr/lib/python3.6/tarfile.py", line 2311, in next
    raise ReadError(str(e))
tarfile.ReadError: invalid header

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhangguanqun/venv_tfnightly_2.5_210325/lib/python3.6/site-packages/hanlp/utils/component_util.py", line 81, in load_from_meta_file
    obj.load(save_dir, verbose=verbose, **kwargs)
  File "/home/zhangguanqun/venv_tfnightly_2.5_210325/lib/python3.6/site-packages/hanlp/common/torch_component.py", line 182, in load
    self.load_weights(save_dir, **kwargs)
  File "/home/zhangguanqun/venv_tfnightly_2.5_210325/lib/python3.6/site-packages/hanlp/common/torch_component.py", line 100, in load_weights
    self.model_.load_state_dict(torch.load(filename, map_location='cpu'), strict=False)
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 386, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 559, in _load
    raise RuntimeError("{} is a zip archive (did you mean to use torch.jit.load()?)".format(f.name))
RuntimeError: /home/zhangguanqun/.hanlp/mtl/close_tok_pos_ner_srl_dep_sdp_con_electra_small_20210111_124159/model.pt is a zip archive (did you mean to use torch.jit.load()?)
=================================ERROR LOG ENDS=================================
If the problem still persists, please submit an issue to https://github.com/hankcs/HanLP/issues
When reporting an issue, make sure to paste the FULL ERROR LOG above.
```

* [x] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
You must be using torch<=1.5 which is agains our requirement. See https://github.com/pytorch/pytorch/issues/43766

**Comment by hstk30** [comment]
```
Downloading https://file.hankcs.com/hanlp/mtl/close_tok_pos_ner_srl_dep_sdp_con_electra_small_20210111_124159.zip to /home/hstk/.hanlp/mtl/close_tok_pos_ner_srl_dep_sdp_con_electra_small_20210111_124159.zip
100% 114.3 MiB 227.4 KiB/s ETA:  0 s [=============================================================]
Decompressing /home/hstk/.hanlp/mtl/close_tok_pos_ner_srl_dep_sdp_con_electra_small_20210111_124159.zip to /home/hstk/.hanlp/mtl

Downloading https://file.hankcs.com/hanlp/transformers/electra_zh_small_20210706_125427.zip to /home/hstk/.hanlp/transformers/electra_zh_small_20210706_125427.zip
100%  41.2 KiB  41.2 KiB/s ETA:  0 s [=============================================================]
Decompressing /home/hstk/.hanlp/transformers/electra_zh_small_20210706_125427.zip to /home/hstk/.hanlp/transformers
Downloading https://file.hankcs.com/corpus/char_table.json.zip to /home/hstk/.hanlp/thirdparty/file.hankcs.com/corpus/char_table.json.zip


100%  19.4 KiB   4.9 KiB/s ETA:  0 s [=============================================================]
Decompressing /home/hstk/.hanlp/thirdparty/file.hankcs.com/corpus/char_table.json.zip to /home/hstk/.hanlp/thirdparty/file.hankcs.com/corpus
Failed to load https://file.hankcs.com/hanlp/mtl/close_tok_pos_ner_srl_dep_sdp_con_electra_small_20210111_124159.zip. See traceback below:
================================ERROR LOG BEGINS================================
Traceback (most recent call last):
  File "/usr/lib64/python3.6/tarfile.py", line 189, in nti
    n = int(s.strip() or "0", 8)
ValueError: invalid literal for int() with base 8: 'uild_ten'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.6/tarfile.py", line 2297, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "/usr/lib64/python3.6/tarfile.py", line 1093, in fromtarfile
    obj = cls.frombuf(buf, tarfile.encoding, tarfile.errors)
  File "/usr/lib64/python3.6/tarfile.py", line 1035, in frombuf
    chksum = nti(buf[148:156])
  File "/usr/lib64/python3.6/tarfile.py", line 191, in nti
    raise InvalidHeaderError("invalid header")
tarfile.InvalidHeaderError: invalid header

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hstk/gitProject/venv/siren/lib64/python3.6/site-packages/torch/serialization.py", line 595, in _load
    return legacy_load(f)
  File "/home/hstk/gitProject/venv/siren/lib64/python3.6/site-packages/torch/serialization.py", line 506, in legacy_load
    with closing(tarfile.open(fileobj=f, mode='r:', format=tarfile.PAX_FORMAT)) as tar, \
  File "/usr/lib64/python3.6/tarfile.py", line 1589, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/usr/lib64/python3.6/tarfile.py", line 1619, in taropen
    return cls(name, mode, fileobj, **kwargs)
  File "/usr/lib64/python3.6/tarfile.py", line 1482, in __init__
    self.firstmember = self.next()
  File "/usr/lib64/python3.6/tarfile.py", line 2309, in next
    raise ReadError(str(e))
tarfile.ReadError: invalid header

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hstk/gitProject/venv/siren/lib64/python3.6/site-packages/hanlp/utils/component_util.py", line 81, in load_from_meta_file
    obj.load(save_dir, verbose=verbose, **kwargs)
  File "/home/hstk/gitProject/venv/siren/lib64/python3.6/site-packages/hanlp/common/torch_component.py", line 182, in load
    self.load_weights(save_dir, **kwargs)
  File "/home/hstk/gitProject/venv/siren/lib64/python3.6/site-packages/hanlp/common/torch_component.py", line 100, in load_weights
    self.model_.load_state_dict(torch.load(filename, map_location='cpu'), strict=False)
  File "/home/hstk/gitProject/venv/siren/lib64/python3.6/site-packages/torch/serialization.py", line 426, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/home/hstk/gitProject/venv/siren/lib64/python3.6/site-packages/torch/serialization.py", line 599, in _load
    raise RuntimeError("{} is a zip archive (did you mean to use torch.jit.load()?)".format(f.name))
RuntimeError: /home/hstk/.hanlp/mtl/close_tok_pos_ner_srl_dep_sdp_con_electra_small_20210111_124159/model.pt is a zip archive (did you mean to use torch.jit.load()?)
=================================ERROR LOG ENDS=================================
If the problem still persists, please submit an issue to https://github.com/hankcs/HanLP/issues
When reporting an issue, make sure to paste the FULL ERROR LOG above and the system info below.
OS: Linux-3.10.0-1127.18.2.el7.x86_64-x86_64-with-centos-7.8.2003-Core
Python: 3.6.8
PyTorch: 1.3.0
HanLP: 2.1.0-alpha.53
ERROR:root:Internal Python error in the inspect module.
```

Hi, 我也遇到了这个问题

**Comment by hstk30** [comment]
> You must be using torch<=1.5 which is against our requirement. See [pytorch/pytorch#43766](https://github.com/pytorch/pytorch/issues/43766)

新的分支上的torch 要求是1.6.0 以上？
https://github.com/hankcs/HanLP/blob/c8e51f56b07266464a7efe6984172442bcaf5bd1/setup.py#L44

**Comment by hstk30** [comment]
> > You must be using torch<=1.5 which is against our requirement. See [pytorch/pytorch#43766](https://github.com/pytorch/pytorch/issues/43766)
> 
> 新的分支上的torch 要求是1.6.0 以上？
> https://github.com/hankcs/HanLP/blob/c8e51f56b07266464a7efe6984172442bcaf5bd1/setup.py#L44

我把torch 版本升到1.6.0是没问题的
