### ISSUE TITLE
本机装有transformer, 可能与hanlp所需版本不同，导致的bug

### ISSUE THREAD

**Issue by CodeShaoNian** [hankcs/HanLP#1648]
**Describe the bug**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```python
HanLP = hanlp.load(hanlp.pretrained.mtl.CLOSE_TOK_POS_NER_SRL_DEP_SDP_CON_ELECTRA_SMALL_ZH) # 世界最大中文语料库
```

**Describe the current behavior**
A clear and concise description of what happened.

**Expected behavior**

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Python version:
- HanLP version:

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

Failed to load https://file.hankcs.com/hanlp/mtl/close_tok_pos_ner_srl_dep_sdp_con_electra_small_20210111_124159.zip. See traceback below:
================================ERROR LOG BEGINS================================
Traceback (most recent call last):
  File "/home/***/.conda/envs/test/lib/python3.6/site-packages/hanlp/utils/component_util.py", line 81, in load_from_meta_file
    obj.load(save_dir, verbose=verbose, **kwargs)
  File "/home/***/.conda/envs/test/lib/python3.6/site-packages/hanlp/common/torch_component.py", line 173, in load
    self.load_config(save_dir, **kwargs)
  File "/home/***/.conda/envs/test/lib/python3.6/site-packages/hanlp/common/torch_component.py", line 125, in load_config
    self.config[k] = Configurable.from_config(v)
  File "/home/***/.conda/envs/test/lib/python3.6/site-packages/hanlp_common/configurable.py", line 30, in from_config
    return cls(**deserialized_config)
  File "/home/***/.conda/envs/test/lib/python3.6/site-packages/hanlp/layers/embeddings/contextual_word_embedding.py", line 143, in __init__
    do_basic_tokenize=do_basic_tokenize)
  File "/home/***/.conda/envs/test/lib/python3.6/site-packages/hanlp/layers/transformers/encoder.py", line 124, in build_transformer_tokenizer
    return AutoTokenizer.from_pretrained(transformer, use_fast=use_fast, do_basic_tokenize=do_basic_tokenize)
  File "/home/***/.conda/envs/test/lib/python3.6/site-packages/transformers/models/auto/tokenization_auto.py", line 390, in from_pretrained
    config = AutoConfig.from_pretrained(pretrained_model_name_or_path, **kwargs)
  File "/home/***/.conda/envs/test/lib/python3.6/site-packages/transformers/models/auto/configuration_auto.py", line 398, in from_pretrained
    config_dict, _ = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/***/.conda/envs/test/lib/python3.6/site-packages/transformers/configuration_utils.py", line 466, in get_config_dict
    user_agent=user_agent,
  File "/home/***/.conda/envs/test/lib/python3.6/site-packages/transformers/file_utils.py", line 1173, in cached_path
    local_files_only=local_files_only,
  File "/home/***/.conda/envs/test/lib/python3.6/site-packages/transformers/file_utils.py", line 1389, in get_from_cache
    "Connection error, and we cannot find the requested files in the cached path."
ValueError: Connection error, and we cannot find the requested files in the cached path. Please try again or make sure your Internet connection is on.
=================================ERROR LOG ENDS=================================
If the problem still persists, please submit an issue to https://github.com/hankcs/HanLP/issues
When reporting an issue, make sure to paste the FULL ERROR LOG above.
ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

* [ ] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
【自动回复】您好，感谢反馈。
由于未按要求填写，本issue被自动关闭，将在一小时内自动删除。

如果您提的是bug或feature request，请按[issue模板](https://github.com/hankcs/HanLP/tree/doc-zh/.github/ISSUE_TEMPLATE)认真修改，然后耐心等待下周末处理。

否则，[咨询类的问题GitHub概不受理](https://bbs.hankcs.com/t/topic/2245)。请先搜索一下，99.9%的问题已经反复回答过了，人类的本质是复读机。如果您确信您提了个新问题，那么欢迎写清楚前因后果发在[论坛](https://bbs.hankcs.com/)而不是GitHub上。

开源项目维护不易，HanLP用户以十万计，而主要维护者只有我一人。我有自己的full-time研究工作，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
