### ISSUE TITLE
執行分詞會產生 RuntimeError: cannot perform reduction function argmax on a tensor with no elements because the operation does not have an identity

### ISSUE THREAD

**Issue by u8621011** [hankcs/HanLP#1651]
**Describe the bug**
某個字串使用執行分詞會產生 exception。

**Code to reproduce the issue**
```python
import hanlp
import re


HanLP = hanlp.load(hanlp.pretrained.mtl.CLOSE_TOK_POS_NER_SRL_DEP_SDP_CON_ELECTRA_SMALL_ZH) # 這個不會有 exception
#HanLP = hanlp.load(hanlp.pretrained.mtl.CLOSE_TOK_POS_NER_SRL_DEP_SDP_CON_ELECTRA_BASE_ZH) # 這個會有 exception


def segmenter_for_report(sentence):
    import re

    regex_patterns = {}
    regex_patterns['patter1'] = re.compile('\s+')
    regex_patterns['patter2'] = re.compile('[^\s]+')

    tokens = []

    s = sentence
    cur_pos = 0
    token_start_pos_base = cur_pos
    while True:
        max_matched_len = 0
        next_token = None
        token_type = None

        # greedy search for the longest pattern from the beginning of 's'
        print('Segmenting sentence: %s' % s)
        for k, p in regex_patterns.items():
            # return matchobject if matches
            m = p.match(s)
            if m:
                print('【%s】 matched pattern: %s, start: %d, end: %d' %(s, k, m.start(0), m.end(0)))
                cur_matched_len = m.end(0) - m.start(0)
                if max_matched_len < cur_matched_len:
                    max_matched_len = cur_matched_len
                    next_token = m.group(0)
                    token_type = k

        if token_type:
            print('longest matched pattern type: %s, token: %s' % (token_type, next_token))
        else:
            print('Cannot find the matched pattern. sentence: %s' % s)

        # split off the longest token we found.
        if next_token:
            string_left = s[max_matched_len:]
            string_left_trimmed = s[max_matched_len:].lstrip()

            # process the token we found
            token_start_pos = token_start_pos_base
            token_end_pos = token_start_pos_base + max_matched_len
            tokens.append(next_token)

            s = string_left_trimmed
            token_start_pos_base = token_end_pos + (
                        len(string_left) - len(string_left_trimmed))  # the next base
                
        else:
            if len(s.strip()) > 0:
                print('Unprocessed substring: %s' % s)
                break

        if len(s) == 0:
            break
    return tokens


test_cases = [
    '( ͡° ͜ʖ ͡ °)',
]    

for c in test_cases:
    seg_phrases = segmenter_for_report(c)
    for seg_text in seg_phrases:
        tok_results = HanLP(seg_text, tasks=['tok/fine', 'pos/ctb'])
        print('result: %s' % tok_results)
```

**Describe the current behavior**
而且以上狀況只有使用 hanlp.pretrained.mtl.CLOSE_TOK_POS_NER_SRL_DEP_SDP_CON_ELECTRA_BASE_ZH 才會發生
使用 hanlp.pretrained.mtl.CLOSE_TOK_POS_NER_SRL_DEP_SDP_CON_ELECTRA_SMALL_ZH 不會發生

**Expected behavior**
至少正常返回。

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): windows 10
- Python version: Python 3.7.3
- HanLP version: 2.1.0a38

**Other info / logs**
```
Segmenting sentence: ( ͡° ͜ʖ ͡ °)
【( ͡° ͜ʖ ͡ °)】 matched pattern: patter2, start: 0, end: 1
longest matched pattern type: patter2, token: (
Segmenting sentence: ͡° ͜ʖ ͡ °)
【͡° ͜ʖ ͡ °)】 matched pattern: patter2, start: 0, end: 2
longest matched pattern type: patter2, token: ͡°
Segmenting sentence: ͜ʖ ͡ °)
【͜ʖ ͡ °)】 matched pattern: patter2, start: 0, end: 2
longest matched pattern type: patter2, token: ͜ʖ
Segmenting sentence: ͡ °)
【͡ °)】 matched pattern: patter2, start: 0, end: 1
longest matched pattern type: patter2, token: ͡
Segmenting sentence: °)
【°)】 matched pattern: patter2, start: 0, end: 2
longest matched pattern type: patter2, token: °)
result: {
  "tok/fine": [
    "("
  ],
  "pos/ctb": [
    "PU"
  ]
}
result: {
  "tok/fine": [
    "°"
  ],
  "pos/ctb": [
    "PU"
  ]
}
result: {
  "tok/fine": [
    "ʖ"
  ],
  "pos/ctb": [
    "NN"
  ]
}
Traceback (most recent call last):
  File "tests\report_hanlp.py", line 75, in <module>
    tok_results = HanLP(seg_text, tasks=['tok/fine', 'pos/ctb'])
  File "D:\MyProjects\boxservice\env\lib\site-packages\hanlp\components\mtl\multi_task_learning.py", line 768, in __call__
    return super().__call__(data, batch_size, **kwargs)
  File "D:\MyProjects\boxservice\env\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "D:\MyProjects\boxservice\env\lib\site-packages\hanlp\common\torch_component.py", line 633, in __call__
    **kwargs))
  File "D:\MyProjects\boxservice\env\lib\site-packages\hanlp\common\component.py", line 36, in __call__
    return self.predict(data, **kwargs)
  File "D:\MyProjects\boxservice\env\lib\site-packages\hanlp\components\mtl\multi_task_learning.py", line 505, in predict
    cls_is_bos=cls_is_bos, sep_is_eos=sep_is_eos)
  File "D:\MyProjects\boxservice\env\lib\site-packages\hanlp\components\mtl\multi_task_learning.py", line 592, in predict_task
    self.decode_output(output_dict, batch, output_key)
  File "D:\MyProjects\boxservice\env\lib\site-packages\hanlp\components\mtl\multi_task_learning.py", line 732, in decode_output
    self.model.decoders[task_name])
  File "D:\MyProjects\boxservice\env\lib\site-packages\hanlp\components\mtl\tasks\tok\tag_tok.py", line 123, in decode_output
    return TransformerTaggingTokenizer.decode_output(self, output, mask, batch, decoder)
  File "D:\MyProjects\boxservice\env\lib\site-packages\hanlp\components\tokenizers\transformer.py", line 97, in decode_output
    output = super().decode_output(logits, mask, batch, model)
  File "D:\MyProjects\boxservice\env\lib\site-packages\hanlp\components\taggers\tagger.py", line 64, in decode_output
    return logits.argmax(-1)
RuntimeError: cannot perform reduction function argmax on a tensor with no elements because the operation does not have an identity
```

* [x] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
感谢反馈，已经修复，请参考上面的commit。
如果还有问题，欢迎重开issue。

[`'͡'`字符](https://www.compart.com/en/unicode/U+0361)被huggingface的BERT tokenizer直接删掉了，导致了这个问题。现在将其视作UNK处理，能够避免crash。不过大多数情况下UNK不会被准确地处理，这属于OOV引起的准确率问题因此不再视作bug，可以通过自定义词典来解决。

**Comment by u8621011** [comment]
怪怪，我這邊測試還是不行呢。

hanlp 已經 pip install --upgrade hanlp ,  升版到 21.0a43。

甚至整個 virutalenv & model file 都移除後 重新建立 virutalenv 環境。都還是會出現以下 exception


```
Downloading https://file.hankcs.com/hanlp/mtl/close_tok_pos_ner_srl_dep_sdp_con_electra_base_20210111_124519.zip to C:\Users\u8621\AppData\Roaming\hanlp\hanlp\mtl\close_tok_pos_ner_srl_dep_sdp_con_electra_base_20210111_124519.zip
100% 467.9 MiB   4.6 MiB/s ETA:  0 s [=============================================================]
Decompressing C:\Users\u8621\AppData\Roaming\hanlp\hanlp\mtl\close_tok_pos_ner_srl_dep_sdp_con_electra_base_20210111_124519.zip to C:\Users\u8621\AppData\Roaming\hanlp\hanlp\mtl
Downloading https://file.hankcs.com/hanlp/transformers/electra_zh_base_20210520_124523.zip to C:\Users\u8621\AppData\Roaming\hanlp\hanlp\transformers\electra_zh_base_20210520_124523.zip
100%  40.6 KiB  40.6 KiB/s ETA:  0 s [=============================================================]
Decompressing C:\Users\u8621\AppData\Roaming\hanlp\hanlp\transformers\electra_zh_base_20210520_124523.zip to C:\Users\u8621\AppData\Roaming\hanlp\hanlp\transformers
Downloading https://file.hankcs.com/corpus/char_table.json.zip to C:\Users\u8621\AppData\Roaming\hanlp\thirdparty\file.hankcs.com\corpus\char_table.json.zip
100%  19.4 KiB  19.4 KiB/s ETA:  0 s [=============================================================]
Decompressing C:\Users\u8621\AppData\Roaming\hanlp\thirdparty\file.hankcs.com\corpus\char_table.json.zip to C:\Users\u8621\AppData\Roaming\hanlp\thirdparty\file.hankcs.com\corpus
Segmenting sentence: ( ͡° ͜ʖ ͡ °)
【( ͡° ͜ʖ ͡ °)】 matched pattern: patter2, start: 0, end: 1
longest matched pattern type: patter2, token: (
Segmenting sentence: ͡° ͜ʖ ͡ °)
【͡° ͜ʖ ͡ °)】 matched pattern: patter2, start: 0, end: 2
longest matched pattern type: patter2, token: ͡°
Segmenting sentence: ͜ʖ ͡ °)
【͜ʖ ͡ °)】 matched pattern: patter2, start: 0, end: 2
longest matched pattern type: patter2, token: ͜ʖ
Segmenting sentence: ͡ °)
【͡ °)】 matched pattern: patter2, start: 0, end: 1
longest matched pattern type: patter2, token: ͡
Segmenting sentence: °)
【°)】 matched pattern: patter2, start: 0, end: 2
longest matched pattern type: patter2, token: °)
result: {
  "tok/fine": [
    "("
  ],
  "pos/ctb": [
    "PU"
  ]
}
result: {
  "tok/fine": [
    "͡",
    "°"
  ],
  "pos/ctb": [
    "PU",
    "PU"
  ]
}
result: {
  "tok/fine": [
    "͜ʖ"
  ],
  "pos/ctb": [
    "PU"
  ]
}
Traceback (most recent call last):
  File "tests\report_hanlp.py", line 75, in <module>
    tok_results = HanLP(seg_text, tasks=['tok/fine', 'pos/ctb'])
  File "D:\MyProjects\boxservice\env\lib\site-packages\hanlp\components\mtl\multi_task_learning.py", line 769, in __call__
    return super().__call__(data, batch_size, **kwargs)
  File "D:\MyProjects\boxservice\env\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "D:\MyProjects\boxservice\env\lib\site-packages\hanlp\common\torch_component.py", line 633, in __call__
    **kwargs))
  File "D:\MyProjects\boxservice\env\lib\site-packages\hanlp\common\component.py", line 36, in __call__
    return self.predict(data, **kwargs)
  File "D:\MyProjects\boxservice\env\lib\site-packages\hanlp\components\mtl\multi_task_learning.py", line 506, in predict
    cls_is_bos=cls_is_bos, sep_is_eos=sep_is_eos)
  File "D:\MyProjects\boxservice\env\lib\site-packages\hanlp\components\mtl\multi_task_learning.py", line 593, in predict_task
    self.decode_output(output_dict, batch, output_key)
  File "D:\MyProjects\boxservice\env\lib\site-packages\hanlp\components\mtl\multi_task_learning.py", line 733, in decode_output
    self.model.decoders[task_name])
  File "D:\MyProjects\boxservice\env\lib\site-packages\hanlp\components\mtl\tasks\tok\tag_tok.py", line 123, in decode_output
    return TransformerTaggingTokenizer.decode_output(self, output, mask, batch, decoder)
  File "D:\MyProjects\boxservice\env\lib\site-packages\hanlp\components\tokenizers\transformer.py", line 97, in decode_output
    output = super().decode_output(logits, mask, batch, model)
  File "D:\MyProjects\boxservice\env\lib\site-packages\hanlp\components\taggers\tagger.py", line 64, in decode_output
    return logits.argmax(-1)
RuntimeError: cannot perform reduction function argmax on a tensor with no elements because the operation does not have an identity
```

**Comment by hankcs** [comment]
感谢反馈，的确有一个edge case我没考虑到，现在已经修复了，请`pip install hanlp -U`

没有问题了：https://colab.research.google.com/drive/1MlTMufOTv6Aa5Fse6eeZaTaiOl53w4uw?usp=sharing
