### ISSUE TITLE
ModuleNotFoundError: No module named 'alnlp'

### ISSUE THREAD

**Issue by turkeymz** [hankcs/HanLP#1653]
刚克隆的代码，本地python跑了一个demo，发现缺少alnlp这个包。demo_classifier.py
看了一下日志，主要原因是加载bert的基础包时报了缺少这个模块
但是模块我已经pip安装成功了，具体pip日志如下
pip install alnlp
Requirement already satisfied: alnlp in c:\env\anaconda\lib\site-packages\alnlp-1.0.0rc27-py3.8.egg (1.0.0rc27)
Requirement already satisfied: torch in c:\env\anaconda\lib\site-packages (from alnlp) (1.8.1)
Requirement already satisfied: typing-extensions in c:\env\anaconda\lib\site-packages (from torch->alnlp) (3.7.4.3)
Requirement already satisfied: numpy in c:\env\anaconda\lib\site-packages (from torch->alnlp) (1.18.5)

然后跟着错误提示也安装和更新pip，还是执行错误。请问这个是什么原因？

Failed to load https://file.hankcs.com/hanlp/classification/chnsenticorp_bert_base_20200104_164655.zip. See traceback below:
================================ERROR LOG BEGINS================================
Traceback (most recent call last):
  File "E:\Project\开源产品调研\HanLP\hanlp\utils\component_util.py", line 74, in load_from_meta_file
    obj: Component = object_from_classpath(cls)
  File "C:\env\anaconda\lib\site-packages\hanlp_common\reflection.py", line 27, in object_from_classpath
    classpath = str_to_type(classpath)
  File "C:\env\anaconda\lib\site-packages\hanlp_common\reflection.py", line 44, in str_to_type
    cls = getattr(importlib.import_module(module_name), class_name)
  File "C:\env\anaconda\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "E:\Project\开源产品调研\HanLP\hanlp\components\classifiers\transformer_classifier_tf.py", line 9, in <module>
    from hanlp.common.keras_component import KerasComponent
  File "E:\Project\开源产品调研\HanLP\hanlp\common\keras_component.py", line 19, in <module>
    from hanlp.metrics.chunking.iobes_tf import IOBES_F1_TF
  File "E:\Project\开源产品调研\HanLP\hanlp\metrics\chunking\iobes_tf.py", line 6, in <module>
    from hanlp.metrics.chunking.conlleval import SpanF1
  File "E:\Project\开源产品调研\HanLP\hanlp\metrics\chunking\conlleval.py", line 17, in <module>
    from alnlp.metrics.span_utils import bio_tags_to_spans
ModuleNotFoundError: No module named 'alnlp'
=================================ERROR LOG ENDS=================================
Some modules required by this model are missing. Please install the full version:
pip install hanlp[full]
Please upgrade hanlp with:
pip install --upgrade hanlp

If the problem still persists, please submit an issue to https://github.com/hankcs/HanLP/issues
When reporting an issue, make sure to paste the FULL ERROR LOG above and the system info below.
OS: Windows-10-10.0.19041-SP0
Python: 3.8.5
PyTorch: 1.8.1+cpu
HanLP: 2.1.0-alpha.42

感谢HanLP

**Comment by hankcs** [comment]
【自动回复】您好，感谢反馈。
由于未按要求填写，本issue被自动关闭，将在一小时内自动删除。

如果您提的是bug或feature request，请按[issue模板](https://github.com/hankcs/HanLP/tree/doc-zh/.github/ISSUE_TEMPLATE)认真修改，然后耐心等待下周末处理。

否则，[咨询类的问题GitHub概不受理](https://bbs.hankcs.com/t/topic/2245)。请先搜索一下，99.9%的问题已经反复回答过了，人类的本质是复读机。如果您确信您提了个新问题，那么欢迎写清楚前因后果发在[论坛](https://bbs.hankcs.com/)而不是GitHub上。

开源项目维护不易，HanLP用户以十万计，而主要维护者只有我一人。我有自己的full-time研究工作，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
