### ISSUE TITLE
ModuleNotFoundError: No module named 'alnlp'

### ISSUE THREAD

**Issue by turkeymz** [hankcs/HanLP#1654]
**Describe the bug**
执行demo代码时，出现ModuleNotFoundError: No module named 'alnlp'

**Code to reproduce the issue**
from hanlp.datasets.classification.sentiment import CHNSENTICORP_ERNIE_TEST

import hanlp

classifier = hanlp.load('CHNSENTICORP_BERT_BASE_ZH')
print(classifier.predict('前台客房服务态度非常好！早餐很丰富，房价很干净。再接再厉！'))

# predict a whole file in batch mode
outputs = classifier.predict(classifier.transform.file_to_inputs(CHNSENTICORP_ERNIE_TEST), gold=True)
print(outputs[:5])

```python
```

**Describe the current behavior**
1. 克隆项目，按照需求安装包
2. 随机跑一个demo_classifier.py，出现出现加载bert失败
3. 具体问题是：ModuleNotFoundError: No module named 'alnlp'
4. 根据异常提示，更新并安装pip和hanlp[full]还是报错
5. 手动安装alnlp，显示已存在此包，但依然运行失败

**Expected behavior**
控制台出现demo代码的对应成功日志

**System information**
OS: Windows-10-10.0.19041-SP0
Python: 3.8.5
PyTorch: 1.8.1+cpu
HanLP: 2.1.0-alpha.42

**Other info / logs**
代码错误日志
2021-05-21 10:04:49.377334: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2021-05-21 10:04:49.377688: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Failed to load https://file.hankcs.com/hanlp/classification/chnsenticorp_bert_base_20200104_164655.zip. See traceback below:
================================ERROR LOG BEGINS================================
Traceback (most recent call last):
  File "E:\Project\Python\HanLP\hanlp\utils\component_util.py", line 74, in load_from_meta_file
    obj: Component = object_from_classpath(cls)
  File "C:\env\anaconda\lib\site-packages\hanlp_common\reflection.py", line 27, in object_from_classpath
    classpath = str_to_type(classpath)
  File "C:\env\anaconda\lib\site-packages\hanlp_common\reflection.py", line 44, in str_to_type
    cls = getattr(importlib.import_module(module_name), class_name)
  File "C:\env\anaconda\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "E:\Project\Python\HanLP\hanlp\components\classifiers\transformer_classifier_tf.py", line 9, in <module>
    from hanlp.common.keras_component import KerasComponent
  File "E:\Project\Python\HanLP\hanlp\common\keras_component.py", line 19, in <module>
    from hanlp.metrics.chunking.iobes_tf import IOBES_F1_TF
  File "E:\Project\Python\HanLP\hanlp\metrics\chunking\iobes_tf.py", line 6, in <module>
    from hanlp.metrics.chunking.conlleval import SpanF1
  File "E:\Project\Python\HanLP\hanlp\metrics\chunking\conlleval.py", line 17, in <module>
    from alnlp.metrics.span_utils import bio_tags_to_spans
ModuleNotFoundError: No module named 'alnlp'
=================================ERROR LOG ENDS=================================
Some modules required by this model are missing. Please install the full version:
pip install hanlp[full]
Please upgrade hanlp with:
pip install --upgrade hanlp

If the problem still persists, please submit an issue to https://github.com/hankcs/HanLP/issues
When reporting an issue, make sure to paste the FULL ERROR LOG above and the system info below.
OS: Windows-10-10.0.19041-SP0
Python: 3.8.5
PyTorch: 1.8.1+cpu
HanLP: 2.1.0-alpha.42

alnlp包安装日志
pip install alnlp
Requirement already satisfied: alnlp in c:\env\anaconda\lib\site-packages\alnlp-1.0.0rc27-py3.8.egg (1.0.0rc27)
Requirement already satisfied: torch in c:\env\anaconda\lib\site-packages (from alnlp) (1.8.1)
Requirement already satisfied: typing-extensions in c:\env\anaconda\lib\site-packages (from torch->alnlp) (3.7.4.3)
Requirement already satisfied: numpy in c:\env\anaconda\lib\site-packages (from torch->alnlp) (1.18.5)

* [ ] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
【自动回复】您好，感谢反馈。
由于未按要求填写，本issue被自动关闭，将在一小时内自动删除。

如果您提的是bug或feature request，请按[issue模板](https://github.com/hankcs/HanLP/tree/doc-zh/.github/ISSUE_TEMPLATE)认真修改，然后耐心等待下周末处理。

否则，[咨询类的问题GitHub概不受理](https://bbs.hankcs.com/t/topic/2245)。请先搜索一下，99.9%的问题已经反复回答过了，人类的本质是复读机。如果您确信您提了个新问题，那么欢迎写清楚前因后果发在[论坛](https://bbs.hankcs.com/)而不是GitHub上。

开源项目维护不易，HanLP用户以十万计，而主要维护者只有我一人。我有自己的full-time研究工作，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
