### ISSUE TITLE
本地hanlp初次load失败

### ISSUE THREAD

**Issue by JunyuanQiu** [hankcs/HanLP#1659]
**Describe the bug**
初次Load失败

**Code to reproduce the issue**

```
import hanlp
HanLP = hanlp.load(hanlp.pretrained.mtl.CLOSE_TOK_POS_NER_SRL_DEP_SDP_CON_ELECTRA_SMALL_ZH)
```

**Describe the current behavior**
```
Downloading https://file.hankcs.com/hanlp/mtl/close_tok_pos_ner_srl_dep_sdp_con_electra_small_20210111_124159.zip to C:\Users\USER\AppData\Roaming\hanlp\hanlp\mtl\close_tok_pos_ner_srl_dep_sdp_con_electra_small_20210111_124159.zip
100% 114.3 MiB 221.4 KiB/s ETA:  0 s [=========================================]
Decompressing C:\Users\USER\AppData\Roaming\hanlp\hanlp\mtl\close_tok_pos_ner_srl_dep_sdp_con_electra_small_20210111_124159.zip to C:\Users\USER\AppData\Roaming\hanlp\hanlp\mtl
Downloading https://file.hankcs.com/hanlp/transformers/electra_zh_small_20210520_124451.zip to C:\Users\USER\AppData\Roaming\hanlp\hanlp\transformers\electra_zh_small_20210520_124451.zip
100%  40.6 KiB  40.6 KiB/s ETA:  0 s [=========================================]
Decompressing C:\Users\USER\AppData\Roaming\hanlp\hanlp\transformers\electra_zh_small_20210520_124451.zip to C:\Users\USER\AppData\Roaming\hanlp\hanlp\transformers
Failed to load https://file.hankcs.com/hanlp/mtl/close_tok_pos_ner_srl_dep_sdp_con_electra_small_20210111_124159.zip. See traceback below:
================================ERROR LOG BEGINS================================
Traceback (most recent call last):
  File "C:\Users\USER\anaconda3\envs\nlp\lib\site-packages\hanlp\utils\component_util.py", line 81, in load_from_meta_file
    obj.load(save_dir, verbose=verbose, **kwargs)
  File "C:\Users\USER\anaconda3\envs\nlp\lib\site-packages\hanlp\common\torch_component.py", line 173, in load
    self.load_config(save_dir, **kwargs)
  File "C:\Users\USER\anaconda3\envs\nlp\lib\site-packages\hanlp\common\torch_component.py", line 125, in load_config
    self.config[k] = Configurable.from_config(v)
  File "C:\Users\USER\anaconda3\envs\nlp\lib\site-packages\hanlp_common\configurable.py", line 30, in from_config
    return cls(**deserialized_config)
  File "C:\Users\USER\anaconda3\envs\nlp\lib\site-packages\hanlp\layers\embeddings\contextual_word_embedding.py", line 143, in __init__
    do_basic_tokenize=do_basic_tokenize)
  File "C:\Users\USER\anaconda3\envs\nlp\lib\site-packages\hanlp\layers\transformers\pt_imports.py", line 66, in from_pretrained
    **additional_config)
  File "C:\Users\USER\AppData\Roaming\Python\Python37\site-packages\transformers\models\auto\tokenization_auto.py", line 523, in from_pretrained
    tokenizer_config = get_tokenizer_config(pretrained_model_name_or_path, **kwargs)
  File "C:\Users\USER\AppData\Roaming\Python\Python37\site-packages\transformers\models\auto\tokenization_auto.py", line 423, in get_tokenizer_config
    use_auth_token=use_auth_token,
  File "C:\Users\USER\AppData\Roaming\Python\Python37\site-packages\transformers\file_utils.py", line 1347, in cached_path
    raise ValueError(f"unable to parse {url_or_filename} as a URL or as a local path")
ValueError: unable to parse C:\Users\USER\AppData\Roaming\hanlp\hanlp\transformers\electra_zh_small_20210520_124451\tokenizer_config.json as a URL or as a local path
```

**Expected behavior**
当第二个文件被解压后，错误出现了

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows-10-10.0.19041-SP0
- Python version: 3.7.10
- HanLP version: 2.1.0-alpha.50

**Other info / logs**
```
ValueError: unable to parse C:\Users\USER\AppData\Roaming\hanlp\hanlp\transformers\electra_zh_small_20210520_124451\tokenizer_config.json as a URL or as a local path
```
他后面的错误提示这个，并且我也确实没在对应的文件夹下找到该文件

* [ ] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
【自动回复】您好，感谢反馈。
由于未按要求填写，本issue被自动关闭，将在一小时内自动删除。

如果您提的是bug或feature request，请按[issue模板](https://github.com/hankcs/HanLP/tree/doc-zh/.github/ISSUE_TEMPLATE)认真修改，然后耐心等待下周末处理。

否则，[咨询类的问题GitHub概不受理](https://bbs.hankcs.com/t/topic/2245)。请先搜索一下，99.9%的问题已经反复回答过了，人类的本质是复读机。如果您确信您提了个新问题，那么欢迎写清楚前因后果发在[论坛](https://bbs.hankcs.com/)而不是GitHub上。

开源项目维护不易，HanLP用户以十万计，而主要维护者只有我一人。我有自己的full-time研究工作，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
