### ISSUE TITLE
Failed to load model

### ISSUE THREAD

**Issue by asd8095075** [hankcs/HanLP#1661]
**Describe the bug**
Failed to load model

**Code to reproduce the issue**
HanLP = hanlp.load(hanlp.pretrained.classifiers.CHNSENTICORP_BERT_BASE_ZH)

**Describe the current behavior**
Failed to load model

**Expected behavior**
Failed to load model

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Windows-10-10.0.19041-SP0
- Python version:3.8.3
- HanLP version:2.1.0-alpha.50

**Other info / logs**
Failed to load https://file.hankcs.com/hanlp/classification/chnsenticorp_bert_base_20200104_164655.zip. See traceback below:
================================ERROR LOG BEGINS================================
Traceback (most recent call last):
  File "c:\users\admin\envs\work\lib\site-packages\hanlp\utils\component_util.py", line 81, in load_from_meta_file
    obj.load(save_dir, verbose=verbose, **kwargs)
  File "c:\users\admin\envs\work\lib\site-packages\hanlp\common\keras_component.py", line 214, in load
    self.build(**merge_dict(self.config, training=False, logger=logger, **kwargs, overwrite=True, inplace=True))
  File "c:\users\admin\envs\work\lib\site-packages\hanlp\common\keras_component.py", line 223, in build
    self.transform.build_config()
  File "c:\users\admin\envs\work\lib\site-packages\hanlp\common\transform_tf.py", line 54, in build_config
    self.output_types, self.output_shapes, self.padding_values = self.create_types_shapes_values()
  File "c:\users\admin\envs\work\lib\site-packages\hanlp\components\classifiers\transformer_classifier_tf.py", line 78, in create_types_shapes_values
    shapes = ([max_length], [max_length], [max_length]), [None, ] if self.config.multi_label else []
  File "c:\users\admin\envs\work\lib\site-packages\hanlp_common\structure.py", line 95, in __getattr__
    return self.__getitem__(key)
KeyError: 'multi_label'
=================================ERROR LOG ENDS=================================
Please upgrade hanlp with:
pip install --upgrade hanlp

If the problem still persists, please submit an issue to https://github.com/hankcs/HanLP/issues
When reporting an issue, make sure to paste the FULL ERROR LOG above and the system info below.
OS: Windows-10-10.0.19041-SP0
Python: 3.8.3
PyTorch: 1.8.1+cu102
HanLP: 2.1.0-alpha.50
ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

* [x] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
Thanks, now fixed. Please `pip install hanlp -U`
