### ISSUE TITLE
ImportError: cannot import name 'TFAutoModel'

### ISSUE THREAD

**Issue by yx179971** [hankcs/HanLP#1667]
**Describe the bug**
ImportError: cannot import name 'TFAutoModel'

**Code to reproduce the issue**
from transformers import BertTokenizer, BertConfig, PretrainedConfig, TFAutoModel, \

**Describe the current behavior**
ImportError: cannot import name 'TFAutoModel'

**Expected behavior**
ImportError: cannot import name 'TFAutoModel'

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Darwin-19.6.0-x86_64-i386-64bit
- Python version:3.6.9
- HanLP version:2.1.0-alpha.53

**Other info / logs**
Failed to load https://file.hankcs.com/hanlp/tok/pku98_6m_conv_ngram_20200110_134736.zip. See traceback below:
================================ERROR LOG BEGINS================================
Traceback (most recent call last):
  File "/Users/yuanxiao/.pyenv/versions/3.6.9/lib/python3.6/site-packages/hanlp/utils/component_util.py", line 74, in load_from_meta_file
    obj: Component = object_from_classpath(cls)
  File "/Users/yuanxiao/.pyenv/versions/3.6.9/lib/python3.6/site-packages/hanlp_common/reflection.py", line 27, in object_from_classpath
    classpath = str_to_type(classpath)
  File "/Users/yuanxiao/.pyenv/versions/3.6.9/lib/python3.6/site-packages/hanlp_common/reflection.py", line 44, in str_to_type
    cls = getattr(importlib.import_module(module_name), class_name)
  File "/Users/yuanxiao/.pyenv/versions/3.6.9/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/yuanxiao/.pyenv/versions/3.6.9/lib/python3.6/site-packages/hanlp/components/tok_tf.py", line 12, in <module>
    from hanlp.components.taggers.transformers.transformer_tagger_tf import TransformerTaggerTF
  File "/Users/yuanxiao/.pyenv/versions/3.6.9/lib/python3.6/site-packages/hanlp/components/taggers/transformers/transformer_tagger_tf.py", line 11, in <module>
    from hanlp.layers.transformers.loader_tf import build_transformer
  File "/Users/yuanxiao/.pyenv/versions/3.6.9/lib/python3.6/site-packages/hanlp/layers/transformers/loader_tf.py", line 12, in <module>
    from hanlp.layers.transformers.tf_imports import zh_albert_models_google, bert_models_google
  File "/Users/yuanxiao/.pyenv/versions/3.6.9/lib/python3.6/site-packages/hanlp/layers/transformers/tf_imports.py", line 5, in <module>
    from transformers import BertTokenizer, BertConfig, PretrainedConfig, TFAutoModel, \
ImportError: cannot import name 'TFAutoModel'
=================================ERROR LOG ENDS=================================
If the problem still persists, please submit an issue to https://github.com/hankcs/HanLP/issues
When reporting an issue, make sure to paste the FULL ERROR LOG above and the system info below.
OS: Darwin-19.6.0-x86_64-i386-64bit
Python: 3.6.9
PyTorch: 1.9.0
HanLP: 2.1.0-alpha.53

* [x] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
无法复现：https://colab.research.google.com/drive/1RFEnbZX2c8lQOpVwKS8fdbCz3B2K-l35?usp=sharing

请认真读文档！https://hanlp.hankcs.com/docs/install.html
