### ISSUE TITLE
你好，我有个很棘手的问题，一个50M的String，给hanlp进行分词，hanlp的所有分词方法都试过了，总是报内存溢出，JVM设置的是1G，怎么办？

### ISSUE THREAD

**Issue by ykyk33** [hankcs/HanLP#167]
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at com.hankcs.hanlp.seg.CRF.CRFSegment.atomSegmentToTable(CRFSegment.java:251)
	at com.hankcs.hanlp.seg.CRF.CRFSegment.segSentence(CRFSegment.java:48)
	at com.hankcs.hanlp.seg.Segment.seg(Segment.java:422)
	at Test.main(Test.java:70)

**Comment by YangliAtGitHub** [comment]
请问50M的语句是自然语言吗？不是自然语言找HanLP干啥？

**Comment by hankcs** [comment]
这么大的文本，读到内存里都够呛，给谁都会崩溃的，你试试用notepad打开一个10MB的txt？。
就不能一行行读，或者按换行符拆成行一行行处理吗？
