### ISSUE TITLE
failed to load a pretrained model

### ISSUE THREAD

**Issue by SleepyRoy** [hankcs/HanLP#1693]
**Describe the bug**
Failed to load a pretrained model.

**Code to reproduce the issue**
(first do _pip install hanlp[full]_)
```python
import hanlp
hanlp.load(hanlp.pretrained.tok.CTB6_CONVSEG)
```

**Describe the current behavior**
```
2021-11-07 23:34:22.992023: E tensorflow/core/lib/monitoring/collection_registry.cc:77] Cannot register 2 metrics with the same name: /tensorflow/api/keras/optimizers
Failed to load https://file.hankcs.com/hanlp/tok/ctb6_convseg_nowe_nocrf_20200110_004046.zip.
If the problem still persists, please submit an issue to https://github.com/hankcs/HanLP/issues
When reporting an issue, make sure to paste the FULL ERROR LOG below.
```

**Expected behavior**
Successful loading.

**System information**
OS: Windows-10-10.0.22000-SP0
Python: 3.9.7
PyTorch: 1.9.1
HanLP: 2.1.0-alpha.63

**Other info / logs**
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Programming\miniconda3\lib\site-packages\hanlp\__init__.py", line 43, in load
    return load_from_meta_file(save_dir, 'meta.json', verbose=verbose, **kwargs)
  File "C:\Programming\miniconda3\lib\site-packages\hanlp\utils\component_util.py", line 126, in load_from_meta_file
    raise e from None
  File "C:\Programming\miniconda3\lib\site-packages\hanlp\utils\component_util.py", line 74, in load_from_meta_file
    obj: Component = object_from_classpath(cls)
  File "C:\Programming\miniconda3\lib\site-packages\hanlp_common\reflection.py", line 27, in object_from_classpath
    classpath = str_to_type(classpath)
  File "C:\Programming\miniconda3\lib\site-packages\hanlp_common\reflection.py", line 44, in str_to_type
    cls = getattr(importlib.import_module(module_name), class_name)
  File "C:\Programming\miniconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Programming\miniconda3\lib\site-packages\hanlp\components\tok_tf.py", line 9, in <module>
    from hanlp.common.keras_component import KerasComponent
  File "C:\Programming\miniconda3\lib\site-packages\hanlp\common\keras_component.py", line 15, in <module>
    from hanlp.callbacks.fine_csv_logger import FineCSVLogger
  File "C:\Programming\miniconda3\lib\site-packages\hanlp\callbacks\fine_csv_logger.py", line 33, in <module>
    class FineCSVLogger(tf.keras.callbacks.History):
  File "C:\Programming\miniconda3\lib\site-packages\tensorflow\python\util\lazy_loader.py", line 62, in __getattr__
    module = self._load()
  File "C:\Programming\miniconda3\lib\site-packages\tensorflow\python\util\lazy_loader.py", line 45, in _load
    module = importlib.import_module(self.__name__)
  File "C:\Programming\miniconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Programming\miniconda3\lib\site-packages\keras\__init__.py", line 25, in <module>
    from keras import models
  File "C:\Programming\miniconda3\lib\site-packages\keras\models.py", line 20, in <module>
    from keras import metrics as metrics_module
  File "C:\Programming\miniconda3\lib\site-packages\keras\metrics.py", line 26, in <module>
    from keras import activations
  File "C:\Programming\miniconda3\lib\site-packages\keras\activations.py", line 20, in <module>
    from keras.layers import advanced_activations
  File "C:\Programming\miniconda3\lib\site-packages\keras\layers\__init__.py", line 23, in <module>
    from keras.engine.input_layer import Input
  File "C:\Programming\miniconda3\lib\site-packages\keras\engine\input_layer.py", line 21, in <module>
    from keras.engine import base_layer
  File "C:\Programming\miniconda3\lib\site-packages\keras\engine\base_layer.py", line 43, in <module>
    from keras.mixed_precision import loss_scale_optimizer
  File "C:\Programming\miniconda3\lib\site-packages\keras\mixed_precision\loss_scale_optimizer.py", line 18, in <module>
    from keras import optimizers
  File "C:\Programming\miniconda3\lib\site-packages\keras\optimizers.py", line 26, in <module>
    from keras.optimizer_v2 import adadelta as adadelta_v2
  File "C:\Programming\miniconda3\lib\site-packages\keras\optimizer_v2\adadelta.py", line 22, in <module>
    from keras.optimizer_v2 import optimizer_v2
  File "C:\Programming\miniconda3\lib\site-packages\keras\optimizer_v2\optimizer_v2.py", line 36, in <module>
    keras_optimizers_gauge = tf.__internal__.monitoring.BoolGauge(
  File "C:\Programming\miniconda3\lib\site-packages\tensorflow\python\eager\monitoring.py", line 360, in __init__
    super(BoolGauge, self).__init__('BoolGauge', _bool_gauge_methods,
  File "C:\Programming\miniconda3\lib\site-packages\tensorflow\python\eager\monitoring.py", line 135, in __init__
    self._metric = self._metric_methods[self._label_length].create(*args)
tensorflow.python.framework.errors_impl.AlreadyExistsError: Another metric with the same name already exists.
```

* [x] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
Unable to reproduce, see: https://colab.research.google.com/drive/1abIr0mAk4ePjCwrGSSwv_IPTVwyXJvQI?usp=sharing

What's your tensorflow version?

**Comment by hankcs** [comment]
TensorFlow screwed Keras dependency, you'll need to

```
pip install keras==2.6.*
```

See https://stackoverflow.com/questions/58012741/error-importing-tensorflow-alreadyexistserror-another-metric-with-the-same-nam
