### ISSUE TITLE
CUDA error: out of memory

### ISSUE THREAD

**Issue by DgCtRbt** [hankcs/HanLP#1694]
================================ERROR LOG BEGINS================================
OS: Linux-3.10.0-1160.6.1.el7.x86_64-x86_64-with-centos-7.9.2009-Core
Python: 3.6.13
PyTorch: 1.9.1+cu102
HanLP: 2.1.0-alpha.63
Traceback (most recent call last):
  File "zhihu_srl10.py", line 12, in <module>
    HanLP = hanlp.load(hanlp.pretrained.mtl.CLOSE_TOK_POS_NER_SRL_DEP_SDP_CON_ELECTRA_BASE_ZH,devices=[0,1]) # 世界最大中文语料库
  File "/home/user48/.conda/envs/hanlp/lib/python3.6/site-packages/hanlp/__init__.py", line 43, in load
    return load_from_meta_file(save_dir, 'meta.json', verbose=verbose, **kwargs)
  File "/home/user48/.conda/envs/hanlp/lib/python3.6/site-packages/hanlp/utils/component_util.py", line 126, in load_from_meta_file
    raise e from None
  File "/home/user48/.conda/envs/hanlp/lib/python3.6/site-packages/hanlp/utils/component_util.py", line 81, in load_from_meta_file
    obj.load(save_dir, verbose=verbose, **kwargs)
  File "/home/user48/.conda/envs/hanlp/lib/python3.6/site-packages/hanlp/common/torch_component.py", line 183, in load
    self.to(devices, verbose=verbose)
  File "/home/user48/.conda/envs/hanlp/lib/python3.6/site-packages/hanlp/common/torch_component.py", line 528, in to
    self.model = self.model.to(devices[0])
  File "/home/user48/.conda/envs/hanlp/lib/python3.6/site-packages/torch/nn/modules/module.py", line 852, in to
    return self._apply(convert)
  File "/home/user48/.conda/envs/hanlp/lib/python3.6/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)
  File "/home/user48/.conda/envs/hanlp/lib/python3.6/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)
  File "/home/user48/.conda/envs/hanlp/lib/python3.6/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "/home/user48/.conda/envs/hanlp/lib/python3.6/site-packages/torch/nn/modules/module.py", line 552, in _apply
    param_applied = fn(param)
  File "/home/user48/.conda/envs/hanlp/lib/python3.6/site-packages/torch/nn/modules/module.py", line 850, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
=================================ERROR LOG ENDS=================================

**Describe the bug**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```python
```

**Describe the current behavior**
A clear and concise description of what happened.

**Expected behavior**

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Python version:
- HanLP version:

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

* [ ] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
【自动回复】您好，感谢反馈。
由于未按要求填写，本issue被自动关闭，将在一小时内自动删除。

如果您提的是bug或feature request，请按[issue模板](https://github.com/hankcs/HanLP/tree/doc-zh/.github/ISSUE_TEMPLATE)认真修改，然后耐心等待下周末处理。

否则，[咨询类的问题GitHub概不受理](https://bbs.hankcs.com/t/topic/2245)。请先搜索一下，99.9%的问题已经反复回答过了，人类的本质是复读机。如果您确信您提了个新问题，那么欢迎写清楚前因后果发在[论坛](https://bbs.hankcs.com/)而不是GitHub上。

开源项目维护不易，HanLP用户以十万计，而主要维护者只有我一人。我有自己的full-time研究工作，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
