### ISSUE TITLE
加载模型失败

### ISSUE THREAD

**Issue by sjhm131** [hankcs/HanLP#1707]
2022-01-20 17:11:53.994120: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Failed to load https://file.hankcs.com/hanlp/ner/ner_bert_base_msra_20211227_114712.zip.
Please upgrade HanLP with:

	pip install --upgrade hanlp

If the problem still persists, please submit an issue to https://github.com/hankcs/HanLP/issues
When reporting an issue, make sure to paste the FULL ERROR LOG below.
================================ERROR LOG BEGINS================================
OS: Linux-3.10.0-1160.el7.x86_64-x86_64-with-glibc2.17
Python: 3.8.12
PyTorch: 1.10.1+cu102
TensorFlow: 2.3.0
HanLP: 2.1.0-beta.1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/data/python/python3/lib/python3.8/site-packages/hanlp/__init__.py", line 43, in load
    return load_from_meta_file(save_dir, 'meta.json', verbose=verbose, **kwargs)
  File "/home/data/python/python3/lib/python3.8/site-packages/hanlp/utils/component_util.py", line 155, in load_from_meta_file
    raise e from None
  File "/home/data/python/python3/lib/python3.8/site-packages/hanlp/utils/component_util.py", line 99, in load_from_meta_file
    obj.load(save_dir, verbose=verbose, **kwargs)
  File "/home/data/python/python3/lib/python3.8/site-packages/hanlp/common/keras_component.py", line 214, in load
    self.build(**merge_dict(self.config, training=False, logger=logger, **kwargs, overwrite=True, inplace=True))
  File "/home/data/python/python3/lib/python3.8/site-packages/hanlp/common/keras_component.py", line 224, in build
    self.model = self.build_model(**merge_dict(self.config, training=kwargs.get('training', None),
  File "/home/data/python/python3/lib/python3.8/site-packages/hanlp/components/taggers/transformers/transformer_tagger_tf.py", line 34, in build_model
    model, tokenizer = build_transformer(transformer, max_seq_length, len(self.transform.tag_vocab), tagging=True)
  File "/home/data/python/python3/lib/python3.8/site-packages/hanlp/layers/transformers/loader_tf.py", line 11, in build_transformer
    tokenizer = AutoTokenizer_.from_pretrained(transformer)
  File "/home/data/python/python3/lib/python3.8/site-packages/hanlp/layers/transformers/pt_imports.py", line 66, in from_pretrained
    tokenizer = cls.from_pretrained(get_tokenizer_mirror(transformer), use_fast=use_fast,
  File "/home/data/python/python3/lib/python3.8/site-packages/transformers/models/auto/tokenization_auto.py", line 481, in from_pretrained
    tokenizer_config = get_tokenizer_config(pretrained_model_name_or_path, **kwargs)
  File "/home/data/python/python3/lib/python3.8/site-packages/transformers/models/auto/tokenization_auto.py", line 343, in get_tokenizer_config
    resolved_config_file = cached_path(
  File "/home/data/python/python3/lib/python3.8/site-packages/transformers/file_utils.py", line 1776, in cached_path
    output_path = get_from_cache(
  File "/home/data/python/python3/lib/python3.8/site-packages/transformers/file_utils.py", line 2000, in get_from_cache
    raise ValueError(
ValueError: Connection error, and we cannot find the requested files in the cached path. Please try again or make sure your Internet connection is on.

服务器因业务需求无法联网的情况如何解决

**Comment by hankcs** [comment]
【自动回复】您好，感谢反馈。
由于未按要求填写，本issue被自动关闭，将在一小时内自动删除。

如果您提的是bug或feature request，请按[issue模板](https://github.com/hankcs/HanLP/tree/doc-zh/.github/ISSUE_TEMPLATE)认真修改，然后耐心等待下周末处理。

否则，[咨询类的问题GitHub概不受理](https://bbs.hankcs.com/t/topic/2245)。请先搜索一下，99.9%的问题已经反复回答过了，人类的本质是复读机。如果您确信您提了个新问题，那么欢迎写清楚前因后果发在[论坛](https://bbs.hankcs.com/)而不是GitHub上。

开源项目维护不易，HanLP用户以十万计，而主要维护者只有我一人。我有自己的full-time研究工作，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
