### ISSUE TITLE
Failed to load https://file.hankcs.com/hanlp/tok/ctb9_electra_small_20220204_184813.zip

### ISSUE THREAD

**Issue by wangzhaod** [hankcs/HanLP#1710]
**Describe the bug**
下载好模型压缩包之后显示无法加载
报错显示packing包版本需要>=20.0,
但是我目前的版本是21.0

**Code to reproduce the issue**

```import hanlp
HanLP = hanlp.pipeline() \
    .append(hanlp.utils.rules.split_sentence, output_key='sentences') \
    .append(hanlp.load('CTB9_TOK_ELECTRA_SMALL'), output_key='tok') \
    .append(hanlp.load('CTB9_POS_ELECTRA_SMALL'), output_key='pos') \
    .append(hanlp.load('MSRA_NER_ELECTRA_SMALL_ZH'), output_key='ner', input_key='tok') \
    .append(hanlp.load('CTB9_DEP_ELECTRA_SMALL', conll=0), output_key='dep', input_key='tok')\
    .append(hanlp.load('CTB9_CON_ELECTRA_SMALL'), output_key='con', input_key='tok')
HanLP('2021年HanLPv2.1为生产环境带来次世代最先进的多语种NLP技术。阿婆主来到北京立方庭参观自然语义科技公司。')
```

**Describe the current behavior**
已经安装HanLP[full],按照readme进行尝试运行

**Expected behavior**
Failed to load https://file.hankcs.com/hanlp/tok/ctb9_electra_small_20220204_184813.zip.
If the problem still persists, please submit an issue to https://github.com/hankcs/HanLP/issues

**System information**
================================ERROR LOG BEGINS================================
OS: Windows-10-10.0.19041-SP0
Python: 3.7.0
PyTorch: 1.10.2+cpu
HanLP: 2.1.0-beta.15
packaging=21.3

**Other info / logs**
Failed to load https://file.hankcs.com/hanlp/tok/ctb9_electra_small_20220204_184813.zip.
If the problem still persists, please submit an issue to https://github.com/hankcs/HanLP/issues
When reporting an issue, make sure to paste the FULL ERROR LOG below.
================================ERROR LOG BEGINS================================
OS: Windows-10-10.0.19041-SP0
Python: 3.7.0
PyTorch: 1.10.2+cpu
HanLP: 2.1.0-beta.15
Traceback (most recent call last):
  File "D:/work/human/try2.py", line 4, in <module>
    .append(hanlp.load('CTB9_TOK_ELECTRA_SMALL'), output_key='tok') \
  File "C:\ProgramData\Anaconda3\lib\site-packages\hanlp\__init__.py", line 43, in load
    return load_from_meta_file(save_dir, 'meta.json', verbose=verbose, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\hanlp\utils\component_util.py", line 170, in load_from_meta_file
    raise e from None
  File "C:\ProgramData\Anaconda3\lib\site-packages\hanlp\utils\component_util.py", line 91, in load_from_meta_file
    obj: Component = object_from_classpath(cls)
  File "C:\ProgramData\Anaconda3\lib\site-packages\hanlp_common\reflection.py", line 27, in object_from_classpath
    classpath = str_to_type(classpath)
  File "C:\ProgramData\Anaconda3\lib\site-packages\hanlp_common\reflection.py", line 44, in str_to_type
    cls = getattr(importlib.import_module(module_name), class_name)
  File "C:\ProgramData\Anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\ProgramData\Anaconda3\lib\site-packages\hanlp\components\tokenizers\transformer.py", line 10, in <module>
    from hanlp.components.taggers.transformers.transformer_tagger import TransformerTagger
  File "C:\ProgramData\Anaconda3\lib\site-packages\hanlp\components\taggers\transformers\transformer_tagger.py", line 15, in <module>
    from hanlp.components.classifiers.transformer_classifier import TransformerComponent
  File "C:\ProgramData\Anaconda3\lib\site-packages\hanlp\components\classifiers\transformer_classifier.py", line 19, in <module>
    from hanlp.layers.transformers.encoder import TransformerEncoder
  File "C:\ProgramData\Anaconda3\lib\site-packages\hanlp\layers\transformers\encoder.py", line 12, in <module>
    from hanlp.layers.transformers.pt_imports import PreTrainedModel, PreTrainedTokenizer, AutoTokenizer, AutoModel_, \
  File "C:\ProgramData\Anaconda3\lib\site-packages\hanlp\layers\transformers\pt_imports.py", line 13, in <module>
    from transformers import BertTokenizer, BertConfig, PretrainedConfig, \
  File "C:\ProgramData\Anaconda3\lib\site-packages\transformers\__init__.py", line 30, in <module>
    from . import dependency_versions_check
  File "C:\ProgramData\Anaconda3\lib\site-packages\transformers\dependency_versions_check.py", line 41, in <module>
    require_version_core(deps[pkg])
  File "C:\ProgramData\Anaconda3\lib\site-packages\transformers\utils\versions.py", line 120, in require_version_core
    return require_version(requirement, hint)
  File "C:\ProgramData\Anaconda3\lib\site-packages\transformers\utils\versions.py", line 114, in require_version
    _compare_versions(op, got_ver, want_ver, requirement, pkg, hint)
  File "C:\ProgramData\Anaconda3\lib\site-packages\transformers\utils\versions.py", line 50, in _compare_versions
    f"{requirement} is required for a normal functioning of this module, but found {pkg}=={got_ver}.{hint}"
ImportError: packaging>=20.0 is required for a normal functioning of this module, but found packaging==17.1.
Try: pip install transformers -U or pip install -e '.[dev]' if you're working with git master

* [ ] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
【自动回复】您好，感谢反馈。
由于未按要求填写，本issue被自动关闭，将在一小时内自动删除。

如果您提的是bug或feature request，请按[issue模板](https://github.com/hankcs/HanLP/tree/doc-zh/.github/ISSUE_TEMPLATE)认真修改，然后耐心等待下周末处理。

否则，[咨询类的问题GitHub概不受理](https://bbs.hankcs.com/t/topic/2245)。请先搜索一下，99.9%的问题已经反复回答过了，人类的本质是复读机。如果您确信您提了个新问题，那么欢迎写清楚前因后果发在[论坛](https://bbs.hankcs.com/)而不是GitHub上。

开源项目维护不易，HanLP用户以十万计，而主要维护者只有我一人。我有自己的full-time研究工作，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
