### ISSUE TITLE
加载模型失败

### ISSUE THREAD

**Issue by 962209699** [hankcs/HanLP#1730]
**Describe the bug**

Failed to load https://file.hankcs.com/hanlp/dep/ctb9_dep_electra_small_20220216_100306.zip.
Please upgrade HanLP with:

        pip install --upgrade hanlp

If the problem still persists, please submit an issue to https://github.com/hankcs/HanLP/issues
When reporting an issue, make sure to paste the FULL ERROR LOG below.
================================ERROR LOG BEGINS================================
OS: Linux-3.10.0-957.el7.x86_64-x86_64-with-glibc2.17
Python: 3.8.5
PyTorch: 1.11.0+cu102
HanLP: 2.1.0-beta.17
Traceback (most recent call last):
  File "meta_field_service.py", line 35, in <module>
    dep = hanlp.load(hanlp.pretrained.dep.CTB9_DEP_ELECTRA_SMALL)
  File "/usr/local/python3/lib/python3.8/site-packages/hanlp/__init__.py", line 43, in load
    return load_from_meta_file(save_dir, 'meta.json', verbose=verbose, **kwargs)
  File "/usr/local/python3/lib/python3.8/site-packages/hanlp/utils/component_util.py", line 170, in load_from_meta_file
    raise e from None
  File "/usr/local/python3/lib/python3.8/site-packages/hanlp/utils/component_util.py", line 98, in load_from_meta_file
    obj.load(save_dir, verbose=verbose, **kwargs)
  File "/usr/local/python3/lib/python3.8/site-packages/hanlp/common/torch_component.py", line 173, in load
    self.load_config(save_dir, **kwargs)
  File "/usr/local/python3/lib/python3.8/site-packages/hanlp/common/torch_component.py", line 126, in load_config
    self.on_config_ready(**self.config, save_dir=save_dir)
  File "/usr/local/python3/lib/python3.8/site-packages/hanlp/components/parsers/biaffine/biaffine_dep.py", line 562, in on_config_ready
    self.build_transformer_tokenizer()  # We have to build tokenizer before building the dataloader and model
  File "/usr/local/python3/lib/python3.8/site-packages/hanlp/components/parsers/biaffine/biaffine_dep.py", line 285, in build_transformer_tokenizer
    transformer_tokenizer: PreTrainedTokenizer = AutoTokenizer.from_pretrained(transformer, use_fast=True)
  File "/usr/local/python3/lib/python3.8/site-packages/transformers/mode

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```python
```

**Describe the current behavior**
A clear and concise description of what happened.

**Expected behavior**

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Python version:
- HanLP version:

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
Failed to load https://file.hankcs.com/hanlp/dep/ctb9_dep_electra_small_20220216_100306.zip.
Please upgrade HanLP with:

        pip install --upgrade hanlp

If the problem still persists, please submit an issue to https://github.com/hankcs/HanLP/issues
When reporting an issue, make sure to paste the FULL ERROR LOG below.
================================ERROR LOG BEGINS================================
OS: Linux-3.10.0-957.el7.x86_64-x86_64-with-glibc2.17
Python: 3.8.5
PyTorch: 1.11.0+cu102
HanLP: 2.1.0-beta.17
Traceback (most recent call last):
  File "meta_field_service.py", line 35, in <module>
    dep = hanlp.load(hanlp.pretrained.dep.CTB9_DEP_ELECTRA_SMALL)
  File "/usr/local/python3/lib/python3.8/site-packages/hanlp/__init__.py", line 43, in load
    return load_from_meta_file(save_dir, 'meta.json', verbose=verbose, **kwargs)
  File "/usr/local/python3/lib/python3.8/site-packages/hanlp/utils/component_util.py", line 170, in load_from_meta_file
    raise e from None
  File "/usr/local/python3/lib/python3.8/site-packages/hanlp/utils/component_util.py", line 98, in load_from_meta_file
    obj.load(save_dir, verbose=verbose, **kwargs)
  File "/usr/local/python3/lib/python3.8/site-packages/hanlp/common/torch_component.py", line 173, in load
    self.load_config(save_dir, **kwargs)
  File "/usr/local/python3/lib/python3.8/site-packages/hanlp/common/torch_component.py", line 126, in load_config
    self.on_config_ready(**self.config, save_dir=save_dir)
  File "/usr/local/python3/lib/python3.8/site-packages/hanlp/components/parsers/biaffine/biaffine_dep.py", line 562, in on_config_ready
    self.build_transformer_tokenizer()  # We have to build tokenizer before building the dataloader and model
  File "/usr/local/python3/lib/python3.8/site-packages/hanlp/components/parsers/biaffine/biaffine_dep.py", line 285, in build_transformer_tokenizer
    transformer_tokenizer: PreTrainedTokenizer = AutoTokenizer.from_pretrained(transformer, use_fast=True)
  File "/usr/local/python3/lib/python3.8/site-packages/transformers/mode

* [ ] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
【自动回复】您好，感谢反馈。
由于未按要求填写，本issue被自动关闭，将在一小时内自动删除。

如果您提的是bug或feature request，请按[issue模板](https://github.com/hankcs/HanLP/tree/doc-zh/.github/ISSUE_TEMPLATE)认真修改，然后耐心等待下周末处理。

否则，[咨询类的问题GitHub概不受理](https://bbs.hankcs.com/t/topic/2245)。请先搜索一下，99.9%的问题已经反复回答过了，人类的本质是复读机。如果您确信您提了个新问题，那么欢迎写清楚前因后果发在[论坛](https://bbs.hankcs.com/)而不是GitHub上。

开源项目维护不易，HanLP用户以十万计，而主要维护者只有我一人。我有自己的full-time研究工作，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
