### ISSUE TITLE
Failed to load https://file.hankcs.com/hanlp/tok/coarse_electra_small_20220220_013548.zip.

### ISSUE THREAD

**Issue by roclins** [hankcs/HanLP#1732]
**Describe the bug**
模型加载失败

**Code to reproduce the issue**
hanlp已升级到最新版本
```
tok = hanlp.load(hanlp.pretrained.tok.COARSE_ELECTRA_SMALL_ZH)
```

**Describe the current behavior**
模型已下载完成，但加载失败

**Expected behavior**
希望完成加载模型

**System information**
报错信息仅提供了以下三行，无额外其他信息
OS: macOS-10.15.5-x86_64-i386-64bit
Python: 3.8.12
PyTorch: 1.11.0
HanLP: 2.1.0-beta.27

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

* [x] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
这不可能，加载函数在失败时永远都会抛出一个异常：

https://github.com/hankcs/HanLP/blob/53179223de8daa474ea786c29a6c6e495c2ab339/hanlp/utils/component_util.py#L171

需要你提供这个异常才能帮你。

**Comment by Hubotcoder** [comment]
Building model ...Failed to load https://file.hankcs.com/hanlp/mtl/close_tok_pos_ner_srl_dep_sdp_con_electra_small_20210111_124159.zip
If the problem still persists, please submit an issue to https://github.com/hankcs/HanLP/issues
When reporting an issue, make sure to paste the FULL ERROR LOG below.
================================ERROR LOG BEGINS================================
OS: Windows-10-10.0.19043-SP0
Python: 3.10.8
PyTorch: 1.12.1
HanLP: 2.1.0-beta.45
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\JetBrains\PyCharmCE2021.3\scratches\scratch.py", line 21, in <module>
    HanLP = hanlp.load(hanlp.pretrained.mtl.CLOSE_TOK_POS_NER_SRL_DEP_SDP_CON_ELECTRA_SMALL_ZH) # 世界最大中文语料库
  File "C:\ProgramData\Anaconda3\envs\hanlp\lib\site-packages\hanlp\__init__.py", line 43, in load
    return load_from_meta_file(save_dir, 'meta.json', verbose=verbose, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\hanlp\lib\site-packages\hanlp\utils\component_util.py", line 182, in load_from_meta_file
    raise e from None
  File "C:\ProgramData\Anaconda3\envs\hanlp\lib\site-packages\hanlp\utils\component_util.py", line 106, in load_from_meta_file
    obj.load(save_dir, verbose=verbose, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\hanlp\lib\site-packages\hanlp\common\torch_component.py", line 178, in load
    self.model = self.build_model(
  File "C:\ProgramData\Anaconda3\envs\hanlp\lib\site-packages\hanlp\components\mtl\multi_task_learning.py", line 447, in build_model
    decoder = task.build_model(encoder_size, training=training, **task.config)
  File "C:\ProgramData\Anaconda3\envs\hanlp\lib\site-packages\hanlp\components\mtl\tasks\constituency.py", line 144, in build_model
    return CRFConstituencyDecoder(n_labels=len(self.vocabs.chart), n_hidden=encoder_size)
  File "C:\ProgramData\Anaconda3\envs\hanlp\lib\site-packages\hanlp\components\parsers\constituency\crf_constituency_model.py", line 108, in __init__
    self.mlp_span_l = MLP(n_in=n_hidden, n_out=n_mlp_span, dropout=mlp_dropout)
  File "C:\ProgramData\Anaconda3\envs\hanlp\lib\site-packages\hanlp\components\parsers\biaffine\mlp.py", line 55, in __init__
    self.reset_parameters()
  File "C:\ProgramData\Anaconda3\envs\hanlp\lib\site-packages\hanlp\components\parsers\biaffine\mlp.py", line 65, in reset_parameters
    nn.init.orthogonal_(self.linear.weight)
  File "C:\ProgramData\Anaconda3\envs\hanlp\lib\site-packages\torch\nn\init.py", line 483, in orthogonal_
    q, r = torch.linalg.qr(flattened)
RuntimeError: Calling torch.geqrf on a CPU tensor requires compiling PyTorch with LAPACK. Please use PyTorch built with LAPACK support.
=================================ERROR LOG ENDS=================================

你好，请问这个问题怎么解决？

**Comment by Hubotcoder** [comment]
> 

你好，安装了cpu版pytorch，问题解决了
