### ISSUE TITLE
word2vec[word] = np.array(vec, dtype=np.float32) ValueError: could not convert string to float: ']ܱ=

### ISSUE THREAD

**Issue by KangChou** [hankcs/HanLP#1739]
**Describe the bug**

```
22-05-28 03:15:53 INFO Hyperparameter:
{
  "min_freq": 2,
  "n_tokens_per_batch": 5000,
  "n_buckets": 32,
  "lower": true,
  "run_eagerly": false,
  "epochs": 2,
  "batch_size": 100,
  "punct": false,
  "tree": false,
  "early_stopping_patience": 100,
  "metrics": [
    "UAS",
    "LAS"
  ],
  "rel_loss": "sparse_categorical_crossentropy",
  "arc_loss": "sparse_categorical_crossentropy",
  "patience": 100,
  "decay_steps": 5000,
  "decay": 0.75,
  "clip": 5.0,
  "epsilon": 1e-12,
  "nu": 0.9,
  "mu": 0.9,
  "lr": 0.002,
  "optimizer": "adam",
  "mlp_dropout": 0.33,
  "n_mlp_rel": 100,
  "n_mlp_arc": 500,
  "lstm_dropout": 0.33,
  "n_lstm_layers": 3,
  "n_lstm_hidden": 400,
  "embed_dropout": 0.33,
  "pretrained_embed": {
    "class_name": "HanLP>Word2VecEmbedding",
    "config": {
      "trainable": false,
      "embeddings_initializer": "zero",
      "filepath": "/data/my_project/nlp_text/HanLP//embeddings/ctb.fasttext.300.txt.zip",
      "expand_vocab": true,
      "lowercase": true,
      "normalize": true
    }
  },
  "n_embed": 100
}
22-05-28 03:15:54 INFO Vocab summary:
form_vocab[17547] = ['<pad>', '<unk>', '<root>', '上海', '浦东', '开发', '与', '法制', '建设', '同步', '新华社', '二月', '十日', '电', '（', '记者', '谢金虎', '、', '张持坚', '）', '近年', '来', '颁布', '实行', '了', '涉及', '经济', '贸易', '规划', '科技', '文教', '等', '领域', '的', '七十一', '件', '法规性', '文件', '，', '确保', '有序', '进行', '。', '开放', '是', '一', '项', '振兴', '现代化', '金融']
cpos_vocab[33] = ['<root>', 'NR', 'NN', 'CC', 'VV', 'NT', 'PU', 'LC', 'AS', 'ETC', 'DEC', 'CD', 'M', 'DEG', 'JJ', 'VC', 'AD', 'P', 'PN', 'VA', 'DEV', 'DT', 'SB', 'OD', 'VE', 'CS', 'MSP', 'BA', 'FW', 'LB', 'DER', 'SP', 'IJ']
rel_vocab[13] = ['<root>', 'NMOD', 'SUB', 'ROOT', 'DEP', 'P', 'VMOD', 'VC', 'SBAR', 'OBJ', 'AMOD', 'PRD', 'PMOD']
22-05-28 03:15:54 INFO Building...
realpath==== /data/my_project/nlp_text/HanLP/depsparer_zk/datastes_zk/embeddings/ctb.fasttext.300.txt.zip
word:}?ӓ8N0fD[YnI*"J/V/HOl-օkc|RQŠ3A`ǩ<ՙL''JtݷGqr:8#ތǬP<%9{2ӣ¾ħY++Bs6Q%M6
                                                                         , vec:[']ܱ=', '(\x04zTO\x1cҚ\x18\x1f0c', 'l}e\x12', 'U}\x0fyܤ\x1f9"\x07M`j\x00P`\x03G\x07\x190#VS\\ͨ\x0ek\x19N&o=Y\x1f^\x08f;*tء9Ua\t\x0e\x89\x06\x1e[#\x13w?\x1feW\x06}\x07b_Qi<\x0eǼ\x0f)Ϣ']==
Traceback (most recent call last):
  File "train.py", line 74, in <module>
    training_parameters(CTB5_DEP_TRAIN,CTB5_DEP_VALID,save_dir)
  File "train.py", line 69, in training_parameters
    run_eagerly=False, logger=None, verbose=True
  File "/data/my_project/nlp_text/HanLP/depsparer_zk/hanlp/components/parsers/biaffine_parser.py", line 80, in fit
    return super().fit(**merge_locals_kwargs(locals(), kwargs))
  File "/data/my_project/nlp_text/HanLP/depsparer_zk/hanlp/common/component.py", line 334, in fit
    model, optimizer, loss, metrics = self.build(**merge_dict(self.config, logger=logger, training=True))
  File "/data/my_project/nlp_text/HanLP/depsparer_zk/hanlp/common/component.py", line 255, in build
    loss=kwargs.get('loss', None)))
  File "/data/my_project/nlp_text/HanLP/depsparer_zk/hanlp/components/parsers/biaffine_parser.py", line 35, in build_model
    self.transform) if pretrained_embed else None
  File "/data/my_project/nlp_text/HanLP/depsparer_zk/hanlp/layers/embeddings/__init__.py", line 34, in build_embedding
    custom_objects=tf.keras.utils.get_custom_objects())
  File "/opt/conda/lib/python3.6/site-packages/tensorflow_core/python/keras/utils/generic_utils.py", line 193, in deserialize_keras_object
    return cls.from_config(cls_config)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 594, in from_config
    return cls(**config)
  File "/data/my_project/nlp_text/HanLP/depsparer_zk/hanlp/layers/embeddings/word2vec.py", line 119, in __init__
    word2vec, _output_dim = load_word2vec(filepath)
  File "/data/my_project/nlp_text/HanLP/depsparer_zk/hanlp/utils/io_util.py", line 446, in load_word2vec
    word2vec[word] = np.array(vec, dtype=np.float32)
ValueError: could not convert string to float: ']ܱ='
```

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```python
```

**Describe the current behavior**
A clear and concise description of what happened.

**Expected behavior**

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):ubuntu16.04
- Python version:3.6
- HanLP version:2.1

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

* [ ] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
【自动回复】您好，感谢反馈。
由于未按要求填写，本issue被自动关闭，将在一小时内自动删除。

如果您提的是bug或feature request，请按[issue模板](https://github.com/hankcs/HanLP/tree/doc-zh/.github/ISSUE_TEMPLATE)认真修改，然后耐心等待下周末处理。

否则，[咨询类的问题GitHub概不受理](https://bbs.hankcs.com/t/topic/2245)。请先搜索一下，99.9%的问题已经反复回答过了，人类的本质是复读机。如果您确信您提了个新问题，那么欢迎写清楚前因后果发在[论坛](https://bbs.hankcs.com/)而不是GitHub上。

开源项目维护不易，HanLP用户以十万计，而主要维护者只有我一人。我有自己的full-time研究工作，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
