### ISSUE TITLE
多卡跑tok模型的解码报错

### ISSUE THREAD

**Issue by leileilin** [hankcs/HanLP#1776]
**Describe the bug**
多卡跑tok模型的解码报错：RuntimeError: Input tensor at index 1 has invalid shape [8, 6077], but expected [8, 23030]。

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
import hanlp

Hanlp = hanlp.load(hanlp.pretrained.tok.COARSE_ELECTRA_SMALL_ZH, devices=[0, 1, 2, 3])

sents = []
filename = "data/dev.txt"

with open(filename, "r", encoding="utf-8") as file:
    for line in file.readlines():
        if len(line.strip()) > 0:
            sents.append(line)

file.close()

doc_tok = Hanlp(sents)

print("finished ...")

```python
```
python 3.7

**Describe the current behavior**
A clear and concise description of what happened.

**Expected behavior**

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Python version: 3.7
- HanLP version: 2.1.0b39

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
具体的报错信息如下：
Traceback (most recent call last):   
  File "prepare_to_tok.py", line 15, in <module>
    doc_tok = Hanlp(sents)
  File "/cephfs/linlei/work/anaconda3/envs/bert_further_pretrain/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/cephfs/linlei/work/anaconda3/envs/bert_further_pretrain/lib/python3.7/site-packages/hanlp/common/torch_component.py", line 638, in __call__
    return super().__call__(*args, **merge_dict(self.config, overwrite=True, **kwargs))
  File "/cephfs/linlei/work/anaconda3/envs/bert_further_pretrain/lib/python3.7/site-packages/hanlp/common/component.py", line 36, in __call__
    return self.predict(*args, **kwargs)
  File "/cephfs/linlei/work/anaconda3/envs/bert_further_pretrain/lib/python3.7/site-packages/hanlp/components/taggers/tagger.py", line 151, in predict
    outputs = self.predict_data(tokens, batch_size, **kwargs)
  File "/cephfs/linlei/work/anaconda3/envs/bert_further_pretrain/lib/python3.7/site-packages/hanlp/components/taggers/tagger.py", line 169, in predict_data
    out, mask = self.feed_batch(batch)
  File "/cephfs/linlei/work/anaconda3/envs/bert_further_pretrain/lib/python3.7/site-packages/hanlp/components/tokenizers/transformer.py", line 298, in feed_batch
    x, mask = super().feed_batch(batch)
  File "/cephfs/linlei/work/anaconda3/envs/bert_further_pretrain/lib/python3.7/site-packages/hanlp/components/taggers/transformers/transformer_tagger.py", line 262, in feed_batch
    batch=batch)
  File "/cephfs/linlei/work/anaconda3/envs/bert_further_pretrain/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/cephfs/linlei/work/anaconda3/envs/bert_further_pretrain/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 168, in forward
    return self.gather(outputs, self.output_device)
  File "/cephfs/linlei/work/anaconda3/envs/bert_further_pretrain/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 180, in gather
    return gather(outputs, output_device, dim=self.dim)
  File "/cephfs/linlei/work/anaconda3/envs/bert_further_pretrain/lib/python3.7/site-packages/torch/nn/parallel/scatter_gather.py", line 76, in gather
    res = gather_map(outputs)
  File "/cephfs/linlei/work/anaconda3/envs/bert_further_pretrain/lib/python3.7/site-packages/torch/nn/parallel/scatter_gather.py", line 71, in gather_map
    return type(out)(map(gather_map, zip(*outputs)))
  File "/cephfs/linlei/work/anaconda3/envs/bert_further_pretrain/lib/python3.7/site-packages/torch/nn/parallel/scatter_gather.py", line 63, in gather_map
    return Gather.apply(target_device, dim, *outputs)
  File "/cephfs/linlei/work/anaconda3/envs/bert_further_pretrain/lib/python3.7/site-packages/torch/nn/parallel/_functions.py", line 72, in forward
    return comm.gather(inputs, ctx.dim, ctx.target_device)
  File "/cephfs/linlei/work/anaconda3/envs/bert_further_pretrain/lib/python3.7/site-packages/torch/nn/parallel/comm.py", line 235, in gather
    return torch._C._gather(tensors, dim, destination)
RuntimeError: Input tensor at index 1 has invalid shape [8, 6077], but expected [8, 23030]

* [ ] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
【自动回复】您好，感谢反馈。
由于未按要求填写，本issue被自动关闭，将在一小时内自动删除。

如果您提的是bug或feature request，请按[issue模板](https://github.com/hankcs/HanLP/tree/doc-zh/.github/ISSUE_TEMPLATE)认真修改，然后耐心等待下周末处理。

否则，[咨询类的问题GitHub概不受理](https://bbs.hankcs.com/t/topic/2245)。请先搜索一下，99.9%的问题已经反复回答过了，人类的本质是复读机。如果您确信您提了个新问题，那么欢迎写清楚前因后果发在[论坛](https://bbs.hankcs.com/)而不是GitHub上。

开源项目维护不易，HanLP用户以十万计，而主要维护者只有我一人。我有自己的full-time研究工作，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
