### ISSUE TITLE
依存句法分析问题

### ISSUE THREAD

**Issue by sunningboy** [hankcs/HanLP#180]
试运行了一下1.2.7版本的demo，发现有问题。请看看怎么解决？
Exception in thread "main" java.lang.ExceptionInInitializerError
	at com.hankcs.hanlp.dependency.nnparser.NeuralNetworkDependencyParser.parse(NeuralNetworkDependencyParser.java:53)
	at com.hankcs.hanlp.dependency.AbstractDependencyParser.parse(AbstractDependencyParser.java:46)
	at com.hankcs.hanlp.dependency.nnparser.NeuralNetworkDependencyParser.compute(NeuralNetworkDependencyParser.java:93)
	at com.hankcs.hanlp.HanLP.parseDependency(HanLP.java:407)
	at com.hankcs.demo.DemoDependencyParser.main(DemoDependencyParser.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.NullPointerException at com.hankcs.hanlp.dependency.nnparser.NeuralNetworkParser.read_matrix(NeuralNetworkParser.java:294)at com.hankcs.hanlp.dependency.nnparser.NeuralNetworkParser.loadTxt(NeuralNetworkParser.java:166)
	at com.hankcs.hanlp.dependency.nnparser.NeuralNetworkParser.load(NeuralNetworkParser.java:136)
	at com.hankcs.hanlp.dependency.nnparser.parser_dll.<clinit>(parser_dll.java:34)
	... 10 more

**Comment by hankcs** [comment]
配置文件错了。

**Comment by 9vivian88** [comment]
hanlp-portable-1.3.1jar.包parser_dll  类出现问题
Exception in thread "main" java.lang.NullPointerException
	at com.hankcs.hanlp.corpus.io.ByteArrayOtherStream.createByteArrayOtherStream(ByteArrayOtherStream.java:57)
	at com.hankcs.hanlp.corpus.io.ByteArrayStream.createByteArrayStream(ByteArrayStream.java:44)
	at com.hankcs.hanlp.dependency.nnparser.NeuralNetworkParser.load(NeuralNetworkParser.java:132)
	at com.hankcs.hanlp.dependency.nnparser.parser_dll.<init>(parser_dll.java:42)
	at com.hankcs.hanlp.dependency.nnparser.parser_dll.<init>(parser_dll.java:32)
	at com.hankcs.hanlp.dependency.nnparser.NeuralNetworkDependencyParser.<init>(NeuralNetworkDependencyParser.java:39)
	at com.hankcs.hanlp.HanLP.parseDependency(HanLP.java:598)
	at com.whty.nlp.DependencyTree.main(DependencyTree.java:11)

**Comment by hankcs** [comment]
@9vivian88 你的配置文件和data有问题。本来此处应该提示你这一点的，已经做了改进。
