### ISSUE TITLE
HanLP2.1 加载模型时报错：Failed to load https://file.hankcs.com/hanlp/mtl/close_tok_pos_ner_srl_dep_sdp_con_electra_small_20210111_124159.zip

### ISSUE THREAD

**Issue by hanyufeng2005** [hankcs/HanLP#1804]
**Describe the bug**
HanLP2.1 加载模型时报错：Failed to load https://file.hankcs.com/hanlp/mtl/close_tok_pos_ner_srl_dep_sdp_con_electra_small_20210111_124159.zip

**Code to reproduce the issue**
安装好hanlp后，编写文件：

init_hanlp.py
```
import hanlp
HanLP = hanlp.load(hanlp.pretrained.mtl.CLOSE_TOK_POS_NER_SRL_DEP_SDP_CON_ELECTRA_SMALL_ZH) # 世界最大中文语料库
HanLP(['2021年HanLPv2.1为生产环境带来次世代最先进的多语种NLP技术。', '阿婆主来到北京立方庭参观自然语义科技公司。'])
```

运行时报错：

```(base) [root@ebs ~]# python init_hanlp.py 
Decompressing /root/.hanlp/mtl/close_tok_pos_ner_srl_dep_sdp_con_electra_small_20210111_124159.zip to /root/.hanlp/mtl
Failed to load https://file.hankcs.com/hanlp/mtl/close_tok_pos_ner_srl_dep_sdp_con_electra_small_20210111_124159.zip
If the problem still persists, please submit an issue to https://github.com/hankcs/HanLP/issues
When reporting an issue, make sure to paste the FULL ERROR LOG below.
```

**Describe the current behavior**
初始化准备分词时，加载模型这一步报错
文件确定已经下载并解压了

**Expected behavior**
还请教作者如何解决，非常感谢！

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux CentOS 7, Linux-4.15.4-1.el7.elrepo.x86_64-x86_64-with-glibc2.17
- Python version: 3.9.13  (Anaconda)
- HanLP version: 2.1.0-beta.45
- PyTorch: 1.13.1+cu117

**Other info / logs**
================================ERROR LOG BEGINS================================
OS: Linux-4.15.4-1.el7.elrepo.x86_64-x86_64-with-glibc2.17
Python: 3.9.13
PyTorch: 1.13.1+cu117
HanLP: 2.1.0-beta.45
Traceback (most recent call last):
  File "/root/init_hanlp.py", line 2, in <module>
    HanLP = hanlp.load(hanlp.pretrained.mtl.CLOSE_TOK_POS_NER_SRL_DEP_SDP_CON_ELECTRA_SMALL_ZH) # 世界最大中文语料库
  File "/home/anaconda3/lib/python3.9/site-packages/hanlp/__init__.py", line 43, in load
    return load_from_meta_file(save_dir, 'meta.json', verbose=verbose, **kwargs)
  File "/home/anaconda3/lib/python3.9/site-packages/hanlp/utils/component_util.py", line 182, in load_from_meta_file
    raise e from None
  File "/home/anaconda3/lib/python3.9/site-packages/hanlp/utils/component_util.py", line 99, in load_from_meta_file
    obj: Component = object_from_classpath(cls)
  File "/home/anaconda3/lib/python3.9/site-packages/hanlp_common/reflection.py", line 27, in object_from_classpath
    classpath = str_to_type(classpath)
  File "/home/anaconda3/lib/python3.9/site-packages/hanlp_common/reflection.py", line 44, in str_to_type
    cls = getattr(importlib.import_module(module_name), class_name)
  File "/home/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/anaconda3/lib/python3.9/site-packages/hanlp/components/mtl/multi_task_learning.py", line 27, in <module>
    from hanlp.components.mtl.tasks import Task
  File "/home/anaconda3/lib/python3.9/site-packages/hanlp/components/mtl/tasks/__init__.py", line 23, in <module>
    from hanlp.transform.transformer_tokenizer import TransformerSequenceTokenizer
  File "/home/anaconda3/lib/python3.9/site-packages/hanlp/transform/transformer_tokenizer.py", line 9, in <module>
    from hanlp.layers.transformers.pt_imports import PreTrainedTokenizer, PretrainedConfig, AutoTokenizer_
  File "/home/anaconda3/lib/python3.9/site-packages/hanlp/layers/transformers/pt_imports.py", line 13, in <module>
    from transformers import BertTokenizer, BertConfig, PretrainedConfig, \
  File "<frozen importlib._bootstrap>", line 1055, in _handle_fromlist
  File "/home/anaconda3/lib/python3.9/site-packages/transformers/utils/import_utils.py", line 1101, in __getattr__
    value = getattr(module, name)
  File "/home/anaconda3/lib/python3.9/site-packages/transformers/utils/import_utils.py", line 1100, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/home/anaconda3/lib/python3.9/site-packages/transformers/utils/import_utils.py", line 1112, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.bert.configuration_bert because of the following error (look up to see its traceback):
Failed to import transformers.onnx.config because of the following error (look up to see its traceback):
/lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /home/anaconda3/lib/python3.9/site-packages/PIL/../../.././libLerc.so)
=================================ERROR LOG ENDS=================================

* [ ] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
【自动回复】您好，感谢反馈。
由于未按要求填写，本issue被自动关闭，将在一小时内自动删除。

如果您提的是bug或feature request，请按[issue模板](https://github.com/hankcs/HanLP/tree/doc-zh/.github/ISSUE_TEMPLATE)认真修改，然后耐心等待下周末处理。

否则，[咨询类的问题GitHub概不受理](https://bbs.hankcs.com/t/topic/2245)。请先搜索一下，99.9%的问题已经反复回答过了，人类的本质是复读机。如果您确信您提了个新问题，那么欢迎写清楚前因后果发在[论坛](https://bbs.hankcs.com/)而不是GitHub上。

开源项目维护不易，HanLP用户以十万计，而主要维护者只有我一人。我有自己的full-time研究工作，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
