### ISSUE TITLE
Hanlp DynamicCustomDictionary如何使用自定义路径

### ISSUE THREAD

**Issue by samafantasy** [hankcs/HanLP#1807]
**Describe the bug**
如何使用自定义路径，实现多个实例各自执行独立分词，每个实例使用不同的自定义词典，词典路径能否配置化。

使用的demo提供的示例代码无法执行成功，是否能提供一个可用的示例代码。

**Code to reproduce the issue**
代码如下：
```java
public static void main(String[] args) {
    String text = "攻城狮逆袭单身狗，迎娶白富美，走上人生巅峰";
    // 标准分词
    System.out.println(HanLP.segment(text));
    // 系统默认的词典
    // 每个分词器都有一份词典，默认公用 CustomDictionary.DEFAULT，你可以为任何分词器指定一份不同的词典
    DynamicCustomDictionary dictionary = new DynamicCustomDictionary( "data/dictionary/custom/机构名词典.txt");
    StandardTokenizer.SEGMENT.enableCustomDictionary(dictionary);
    StandardTokenizer.SEGMENT.customDictionary.add("走上", "def1");
    StandardTokenizer.SEGMENT.customDictionary.add("人生", "def2");
    System.out.println(HanLP.segment(text));
}
```

**Describe the current behavior**
执行代码，报错如下：
```java
三月 01, 2023 4:30:03 下午 com.hankcs.hanlp.corpus.io.IOUtil readBytes
警告: 读取data/dictionary/custom/机构名词典.txt.bin时发生异常java.io.FileNotFoundException: 资源文件/data/dictionary/custom/机构名词典.txt.bin不存在于jar中
三月 01, 2023 4:30:03 下午 com.hankcs.hanlp.dictionary.DynamicCustomDictionary load
严重: 自定义词典data/dictionary/custom/机构名词典.txt读取错误！java.io.FileNotFoundException: 资源文件/data/dictionary/custom/机构名词典.txt不存在于jar中
三月 01, 2023 4:30:03 下午 com.hankcs.hanlp.dictionary.DynamicCustomDictionary loadMainDictionary
警告: 失败：data/dictionary/custom/机构名词典.txt
三月 01, 2023 4:30:03 下午 com.hankcs.hanlp.dictionary.DynamicCustomDictionary loadMainDictionary
警告: 没有加载到任何词条
三月 01, 2023 4:30:03 下午 com.hankcs.hanlp.dictionary.DynamicCustomDictionary loadMainDictionary
警告: 自定义词典data/dictionary/custom/机构名词典.txt缓存失败！
java.lang.IllegalArgumentException: 不支持写入jar包资源路径data/dictionary/custom/机构名词典.txt.bin
	at com.hankcs.hanlp.corpus.io.ResourceIOAdapter.create(ResourceIOAdapter.java:30)
	at com.hankcs.hanlp.corpus.io.IOUtil.newOutputStream(IOUtil.java:697)
	at com.hankcs.hanlp.dictionary.DynamicCustomDictionary.loadMainDictionary(DynamicCustomDictionary.java:171)
	at com.hankcs.hanlp.dictionary.DynamicCustomDictionary.load(DynamicCustomDictionary.java:100)
	at com.hankcs.hanlp.dictionary.DynamicCustomDictionary.<init>(DynamicCustomDictionary.java:87)
	at com.hankcs.hanlp.dictionary.DynamicCustomDictionary.<init>(DynamicCustomDictionary.java:71)
	at com.jetvoice.soft.nlp.DemoCustomDictionary.main(DemoCustomDictionary.java:20)
```

**Expected behavior**
程序正常运行，多实例分词正常

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 
- Java version: 1.8
- HanLP version: 1.8.4

* [ ] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
【自动回复】您好，感谢反馈。
由于未按要求填写，本issue被自动关闭，将在一小时内自动删除。

如果您提的是bug或feature request，请按[issue模板](https://github.com/hankcs/HanLP/tree/doc-zh/.github/ISSUE_TEMPLATE)认真修改，然后耐心等待下周末处理。

否则，[咨询类的问题GitHub概不受理](https://bbs.hankcs.com/t/topic/2245)。请先搜索一下，99.9%的问题已经反复回答过了，人类的本质是复读机。如果您确信您提了个新问题，那么欢迎写清楚前因后果发在[论坛](https://bbs.hankcs.com/)而不是GitHub上。

开源项目维护不易，HanLP用户以十万计，而主要维护者只有我一人。我有自己的full-time研究工作，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
