### ISSUE TITLE
Failed to load https://file.hankcs.com/hanlp/ner/ner_conll03_bert_base_cased_en_20211227_121443.zip

### ISSUE THREAD

**Issue by Mike20230309** [hankcs/HanLP#1808]
OS: Windows-10-10.0.19041-SP0
Python: 3.9.0
PyTorch: 1.13.1+cpu
Traceback (most recent call last):
  File "C:\Users\HuJM\AppData\Local\Programs\Python\Python39\lib\site-packages\hanlp\utils\component_util.py", line 99, in load_from_meta_file
    obj: Component = object_from_classpath(cls)
  File "C:\Users\HuJM\AppData\Local\Programs\Python\Python39\lib\site-packages\hanlp_common\reflection.py", line 27, in object_from_classpath
    classpath = str_to_type(classpath)
  File "C:\Users\HuJM\AppData\Local\Programs\Python\Python39\lib\site-packages\hanlp_common\reflection.py", line 44, in str_to_type
    cls = getattr(importlib.import_module(module_name), class_name)
  File "C:\Users\HuJM\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\HuJM\AppData\Local\Programs\Python\Python39\lib\site-packages\hanlp\components\ner\ner_tf.py", line 7, in <module>
    import tensorflow as tf
  File "C:\Users\HuJM\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\HuJM\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\python\__init__.py", line 40, in <module>
    from tensorflow.python.eager import context
  File "C:\Users\HuJM\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\python\eager\context.py", line 32, in <module>
    from tensorflow.core.framework import function_pb2
  File "C:\Users\HuJM\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\core\framework\function_pb2.py", line 16, in <module>
    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
  File "C:\Users\HuJM\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\core\framework\attr_value_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
  File "C:\Users\HuJM\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\core\framework\tensor_pb2.py", line 16, in <module>
    from tensorflow.core.framework import resource_handle_pb2 as tensorflow_dot_core_dot_framework_dot_resource__handle__pb2
  File "C:\Users\HuJM\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\core\framework\resource_handle_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_shape_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2
  File "C:\Users\HuJM\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\core\framework\tensor_shape_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "C:\Users\HuJM\AppData\Local\Programs\Python\Python39\lib\site-packages\google\protobuf\descriptor.py", line 561, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\HK_2022\Python\Testhanlp2.py", line 13, in <module>
    .append(hanlp.load('CONLL03_NER_BERT_BASE_CASED_EN'), output_key='ner', input_key='tok')
  File "C:\Users\HuJM\AppData\Local\Programs\Python\Python39\lib\site-packages\hanlp\__init__.py", line 43, in load
    return load_from_meta_file(save_dir, 'meta.json', verbose=verbose, **kwargs)
  File "C:\Users\HuJM\AppData\Local\Programs\Python\Python39\lib\site-packages\hanlp\utils\component_util.py", line 165, in load_from_meta_file
  File "C:\Users\HuJM\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\HuJM\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\python\__init__.py", line 40, in <module>
    from tensorflow.python.eager import context
    from tensorflow.core.framework import function_pb2
  File "C:\Users\HuJM\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\core\framework\function_pb2.py", line 16, in <module>
    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
  File "C:\Users\HuJM\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\core\framework\attr_value_pb2.py", line 16, in <module>
  File "C:\Users\HuJM\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\core\framework\tensor_pb2.py", line 16, in <module>
    from tensorflow.core.framework import resource_handle_pb2 as tensorflow_dot_core_dot_framework_dot_resource__handle__pb2
  File "C:\Users\HuJM\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\core\framework\resource_handle_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_shape_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2
  File "C:\Users\HuJM\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\core\framework\tensor_shape_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "C:\Users\HuJM\AppData\Local\Programs\Python\Python39\lib\site-packages\google\protobuf\descriptor.py", line 561, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

**Comment by hankcs** [comment]
[auto-reply] Thanks for your comment. However, the essential information is required. Please carefully fill out the form when open a new issue.
