### ISSUE TITLE
python3.8

### ISSUE THREAD

**Issue by dongjie-shi** [hankcs/HanLP#1856]
Traceback (most recent call last):
  File "/Users/shidongjie/Documents/code/dongao_code/Subjective/rule/subjective_rule_tool.py", line 62, in <module>
    dep = hanlp.load(hanlp.pretrained.dep.CTB9_DEP_ELECTRA_SMALL)
  File "/Users/shidongjie/miniconda3/envs/subjective/lib/python3.8/site-packages/hanlp/__init__.py", line 43, in load
    return load_from_meta_file(save_dir, 'meta.json', verbose=verbose, **kwargs)
  File "/Users/shidongjie/miniconda3/envs/subjective/lib/python3.8/site-packages/hanlp/utils/component_util.py", line 134, in load_from_meta_file
    raise version.NotCompatible(you_installed_wrong_versions + '\nPlease reinstall HanLP in the proper way:' +
hanlp.version.NotCompatible: The 'tensorflow>=2.8.0; extra == "tf"' distribution was not found and is required by the application
Please reinstall HanLP in the proper way:

	pip install --upgrade hanlp[amr,fasttext,full,tf]

**Comment by hankcs** [comment]
[auto-reply] Thanks for your comment. However, the essential information is required. Please carefully fill out the form when open a new issue.
