### ISSUE TITLE
Could not find cuda drivers on your machine, GPU will not be used

### ISSUE THREAD

**Issue by wxq21** [hankcs/HanLP#1867]
================================ERROR LOG BEGINS================================
OS: Linux-3.10.0-1160.90.1.el7.x86_64-x86_64-with-glibc2.35
Python: 3.8.3
PyTorch: 2.1.2+cu121
TensorFlow: 2.13.1
HanLP: 2.1.0-beta.55
Traceback (most recent call last):
  File "entity_extract.py", line 3, in <module>
    recognizer = hanlp.load(hanlp.pretrained.ner.MSRA_NER_BERT_BASE_ZH)
  File "/usr/local/python3.8/lib/python3.8/site-packages/hanlp/__init__.py", line 43, in load
    return load_from_meta_file(save_dir, 'meta.json', verbose=verbose, **kwargs)
  File "/usr/local/python3.8/lib/python3.8/site-packages/hanlp/utils/component_util.py", line 186, in load_from_meta_file
    raise e from None
  File "/usr/local/python3.8/lib/python3.8/site-packages/hanlp/utils/component_util.py", line 106, in load_from_meta_file
    obj.load(save_dir, verbose=verbose, **kwargs)
  File "/usr/local/python3.8/lib/python3.8/site-packages/hanlp/common/keras_component.py", line 215, in load
    self.build(**merge_dict(self.config, training=False, logger=logger, **kwargs, overwrite=True, inplace=True))
  File "/usr/local/python3.8/lib/python3.8/site-packages/hanlp/common/keras_component.py", line 225, in build
    self.model = self.build_model(**merge_dict(self.config, training=kwargs.get('training', None),
  File "/usr/local/python3.8/lib/python3.8/site-packages/hanlp/components/taggers/transformers/transformer_tagger_tf.py", line 34, in build_model
    model, tokenizer = build_transformer(transformer, max_seq_length, len(self.transform.tag_vocab), tagging=True)
  File "/usr/local/python3.8/lib/python3.8/site-packages/hanlp/layers/transformers/loader_tf.py", line 11, in build_transformer
    tokenizer = AutoTokenizer_.from_pretrained(transformer)
  File "/usr/local/python3.8/lib/python3.8/site-packages/hanlp/layers/transformers/pt_imports.py", line 65, in from_pretrained
    tokenizer = cls.from_pretrained(get_tokenizer_mirror(transformer), use_fast=use_fast,
  File "/usr/local/python3.8/lib/python3.8/site-packages/transformers/models/auto/tokenization_auto.py", line 752, in from_pretrained
    config = AutoConfig.from_pretrained(
  File "/usr/local/python3.8/lib/python3.8/site-packages/transformers/models/auto/configuration_auto.py", line 1082, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/usr/local/python3.8/lib/python3.8/site-packages/transformers/configuration_utils.py", line 644, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/usr/local/python3.8/lib/python3.8/site-packages/transformers/configuration_utils.py", line 699, in _get_config_dict
    resolved_config_file = cached_file(
  File "/usr/local/python3.8/lib/python3.8/site-packages/transformers/utils/hub.py", line 429, in cached_file
    raise EnvironmentError(
OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like bert-base-chinese is not the path to a directory containing a file named config.json.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.
=================================ERROR LOG ENDS=================================

**Comment by hankcs** [comment]
[auto-reply] Thanks for your comment. However, the essential information is required. Please carefully fill out the form when open a new issue.
