### ISSUE TITLE
已经解压的模型加载失败，这个怎么解决啊，急死啦

### ISSUE THREAD

**Issue by TNightmare** [hankcs/HanLP#1893]
Failed to load https://file.hankcs.com/hanlp/tok/ctb6_convseg_nowe_nocrf_20200110_004046.zip
If the problem still persists, please submit an issue to https://github.com/hankcs/HanLP/issues
When reporting an issue, make sure to paste the FULL ERROR LOG below.
================================ERROR LOG BEGINS================================
OS: Windows-10-10.0.19041-SP0
Python: 3.9.1
PyTorch: 1.12.0+cpu
TensorFlow cannot be imported due to TypeError: unhashable type: 'list'. Note this is not a bug of HanLP, but rather a compatability issue caused by TensorFlow.
HanLP: 2.1.0-beta.57
Traceback (most recent call last):
  File "D:\PythonProject\PatentAnalysis\hanlpTest.py", line 19, in <module>
    tokenizer = hanlp.load('CTB6_CONVSEG')
  File "D:\Python\lib\site-packages\hanlp\__init__.py", line 43, in load
    return load_from_meta_file(save_dir, 'meta.json', verbose=verbose, **kwargs)
  File "D:\Python\lib\site-packages\hanlp\utils\component_util.py", line 186, in load_from_meta_file
    raise e from None
  File "D:\Python\lib\site-packages\hanlp\utils\component_util.py", line 99, in load_from_meta_file
    obj: Component = object_from_classpath(cls)
  File "D:\Python\lib\site-packages\hanlp_common\reflection.py", line 27, in object_from_classpath
    classpath = str_to_type(classpath)
  File "D:\Python\lib\site-packages\hanlp_common\reflection.py", line 44, in str_to_type
    cls = getattr(importlib.import_module(module_name), class_name)
  File "D:\Python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "D:\Python\lib\site-packages\hanlp\components\tokenizers\tok_tf.py", line 7, in <module>
    import tensorflow as tf
  File "D:\Python\lib\site-packages\tensorflow\__init__.py", line 45, in <module>
    from tensorflow._api.v2 import __internal__
  File "D:\Python\lib\site-packages\tensorflow\_api\v2\__internal__\__init__.py", line 8, in <module>
    from tensorflow._api.v2.__internal__ import autograph
  File "D:\Python\lib\site-packages\tensorflow\_api\v2\__internal__\autograph\__init__.py", line 8, in <module>
    from tensorflow.python.autograph.core.ag_ctx import control_status_ctx # line: 34
  File "D:\Python\lib\site-packages\tensorflow\python\autograph\core\ag_ctx.py", line 21, in <module>
    from tensorflow.python.autograph.utils import ag_logging
  File "D:\Python\lib\site-packages\tensorflow\python\autograph\utils\__init__.py", line 17, in <module>
    from tensorflow.python.autograph.utils.context_managers import control_dependency_on_returns
  File "D:\Python\lib\site-packages\tensorflow\python\autograph\utils\context_managers.py", line 19, in <module>
    from tensorflow.python.framework import ops
  File "D:\Python\lib\site-packages\tensorflow\python\framework\ops.py", line 5906, in <module>
    ) -> Optional[Callable[[Any], message.Message]]:
  File "D:\Python\lib\typing.py", line 262, in inner
    return func(*args, **kwds)
  File "D:\Python\lib\typing.py", line 339, in __getitem__
    return self._getitem(self, parameters)
  File "D:\Python\lib\typing.py", line 463, in Optional
    return Union[arg, type(None)]
  File "D:\Python\lib\typing.py", line 262, in inner
    return func(*args, **kwds)
  File "D:\Python\lib\typing.py", line 339, in __getitem__
    return self._getitem(self, parameters)
  File "D:\Python\lib\typing.py", line 451, in Union
    parameters = _remove_dups_flatten(parameters)
  File "D:\Python\lib\typing.py", line 231, in _remove_dups_flatten
    return tuple(_deduplicate(params))
  File "D:\Python\lib\typing.py", line 205, in _deduplicate
    all_params = set(params)
TypeError: unhashable type: 'list'
=================================ERROR LOG ENDS=================================

进程已结束,退出代码1

**Comment by hankcs** [comment]
【自动回复】您好，感谢反馈。
由于未按要求填写，本issue被自动关闭，将在一小时内自动删除。

如果您提的是bug或feature request，请按[issue模板](https://github.com/hankcs/HanLP/tree/doc-zh/.github/ISSUE_TEMPLATE)认真修改，然后耐心等待下周末处理。

否则，[咨询类的问题GitHub概不受理](https://bbs.hankcs.com/t/topic/2245)。请先搜索一下，99.9%的问题已经反复回答过了，人类的本质是复读机。如果您确信您提了个新问题，那么欢迎写清楚前因后果发在[论坛](https://bbs.hankcs.com/)而不是GitHub上。

开源项目维护不易，HanLP用户以十万计，而主要维护者只有我一人。我有自己的full-time研究工作，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
