### ISSUE TITLE
Failed to load https://file.hankcs.com/hanlp/ner/ner_conll03_bert_base_cased_en_20211227_121443.zip

### ISSUE THREAD

**Issue by 9393ming** [hankcs/HanLP#1905]
================================ERROR LOG BEGINS================================
OS: Windows-10-10.0.22631-SP0
Python: 3.9.18
PyTorch: 1.13.1+cu116
TensorFlow: 2.13.1
HanLP: 2.1.0-beta.60
Traceback (most recent call last):
  File "C:\Users\liunaiming\OneDrive\桌面\机器学习\黑马程序员nlp\文本预处理\文本预处理hanlp.py", line 18, in <module>
    recognizer = hanlp.load(hanlp.pretrained.ner.CONLL03_NER_BERT_BASE_CASED_EN)
  File "C:\Users\liunaiming\anaconda3\envs\pythonProject1\lib\site-packages\hanlp\__init__.py", line 43, in load
    return load_from_meta_file(save_dir, 'meta.json', verbose=verbose, **kwargs)
  File "C:\Users\liunaiming\anaconda3\envs\pythonProject1\lib\site-packages\hanlp\utils\component_util.py", line 186, in load_from_meta_file
    raise e from None
  File "C:\Users\liunaiming\anaconda3\envs\pythonProject1\lib\site-packages\hanlp\utils\component_util.py", line 106, in load_from_meta_file
    obj.load(save_dir, verbose=verbose, **kwargs)
  File "C:\Users\liunaiming\anaconda3\envs\pythonProject1\lib\site-packages\hanlp\common\keras_component.py", line 215, in load
    self.build(**merge_dict(self.config, training=False, logger=logger, **kwargs, overwrite=True, inplace=True))
  File "C:\Users\liunaiming\anaconda3\envs\pythonProject1\lib\site-packages\hanlp\common\keras_component.py", line 225, in build
    self.model = self.build_model(**merge_dict(self.config, training=kwargs.get('training', None),
  File "C:\Users\liunaiming\anaconda3\envs\pythonProject1\lib\site-packages\hanlp\components\taggers\transformers\transformer_tagger_tf.py", line 34, in build_model
    model, tokenizer = build_transformer(transformer, max_seq_length, len(self.transform.tag_vocab), tagging=True)
  File "C:\Users\liunaiming\anaconda3\envs\pythonProject1\lib\site-packages\hanlp\layers\transformers\loader_tf.py", line 18, in build_transformer
    output = l_bert(input_ids=l_input_ids, token_type_ids=l_token_type_ids, attention_mask=l_mask_ids).last_hidden_state
  File "C:\Users\liunaiming\anaconda3\envs\pythonProject1\lib\site-packages\tf_keras\src\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\liunaiming\anaconda3\envs\pythonProject1\lib\site-packages\transformers\modeling_tf_utils.py", line 437, in run_call_with_unpacked_inputs
    return func(self, **unpacked_inputs)
  File "C:\Users\liunaiming\anaconda3\envs\pythonProject1\lib\site-packages\transformers\models\bert\modeling_tf_bert.py", line 1209, in call
    outputs = self.bert(
  File "C:\Users\liunaiming\anaconda3\envs\pythonProject1\lib\site-packages\transformers\modeling_tf_utils.py", line 437, in run_call_with_unpacked_inputs
    return func(self, **unpacked_inputs)
  File "C:\Users\liunaiming\anaconda3\envs\pythonProject1\lib\site-packages\transformers\models\bert\modeling_tf_bert.py", line 887, in call
    embedding_output = self.embeddings(
  File "C:\Users\liunaiming\anaconda3\envs\pythonProject1\lib\site-packages\transformers\models\bert\modeling_tf_bert.py", line 181, in call
    check_embeddings_within_bounds(input_ids, self.config.vocab_size)
  File "C:\Users\liunaiming\anaconda3\envs\pythonProject1\lib\site-packages\transformers\tf_utils.py", line 190, in check_embeddings_within_bounds
    tf.debugging.assert_less(
  File "C:\Users\liunaiming\anaconda3\envs\pythonProject1\lib\site-packages\keras\src\layers\core\tf_op_layer.py", line 119, in handle
    return TFOpLambda(op)(*args, **kwargs)
  File "C:\Users\liunaiming\anaconda3\envs\pythonProject1\lib\site-packages\keras\src\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
TypeError: Exception encountered when calling layer 'embeddings' (type TFBertEmbeddings).

Could not build a TypeSpec for name: "tf.debugging.assert_less/assert_less/Assert/Assert"
op: "Assert"
input: "tf.debugging.assert_less/assert_less/All"
input: "tf.debugging.assert_less/assert_less/Assert/Assert/data_0"
input: "tf.debugging.assert_less/assert_less/Assert/Assert/data_1"
input: "tf.debugging.assert_less/assert_less/Assert/Assert/data_2"
input: "Placeholder"
input: "tf.debugging.assert_less/assert_less/Assert/Assert/data_4"
input: "tf.debugging.assert_less/assert_less/y"
attr {
  key: "T"
  value {
    list {
      type: DT_STRING
      type: DT_STRING
      type: DT_STRING
      type: DT_INT32
      type: DT_STRING
      type: DT_INT32
    }
  }
}
attr {
  key: "summarize"
  value {
    i: 3
  }
}
 of unsupported type <class 'tensorflow.python.framework.ops.Operation'>.

Call arguments received by layer 'embeddings' (type TFBertEmbeddings):
  • input_ids=<KerasTensor: shape=(None, 128) dtype=int32 (created by layer 'input_ids')>
  • position_ids=None
  • token_type_ids=<KerasTensor: shape=(None, 128) dtype=int32 (created by layer 'token_type_ids')>
  • inputs_embeds=None
  • past_key_values_length=0
  • training=False
=================================ERROR LOG ENDS=================================

**Comment by hankcs** [comment]
【自动回复】您好，感谢反馈。
由于未按要求填写，本issue被自动关闭，将在一小时内自动删除。

如果您提的是bug或feature request，请按[issue模板](https://github.com/hankcs/HanLP/tree/doc-zh/.github/ISSUE_TEMPLATE)认真修改，然后耐心等待下周末处理。

否则，[咨询类的问题GitHub概不受理](https://bbs.hankcs.com/t/topic/2245)。请先搜索一下，99.9%的问题已经反复回答过了，人类的本质是复读机。如果您确信您提了个新问题，那么欢迎写清楚前因后果发在[论坛](https://bbs.hankcs.com/)而不是GitHub上。

开源项目维护不易，HanLP用户以十万计，而主要维护者只有我一人。我有自己的full-time研究工作，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
