### ISSUE TITLE
Describe the bug

### ISSUE THREAD

**Issue by liusw02** [hankcs/HanLP#1912]
Describe the bug
 安装 Hanlp2.0 ERRO
Code to reproduce the issue
conda install hanlp[full] 
pip3 install hanlp[full]
pip install -i https://pypi.douban.com/simple/ hanlp[full]

Describe the current behavior
Error while loading conda entry point: conda-content-trust (No module named '_cffi_backend')
Error while loading conda entry point: conda-libmamba-solver (No module named 'libmambapy.bindings')
F:\Anaconda3\Lib\site-packages\conda_package_streaming\package_streaming.py:25: UserWarning: zstandard could not be imported. Running without .conda support.
  warnings.warn("zstandard could not be imported. Running without .conda support.")
Z:\Anaconda3\Lib\site-packages\conda_package_handling\api.py:29: UserWarning: Install zstandard Python bindings for .conda support
  _warnings.warn("Install zstandard Python bindings for .conda support")
Retrieving notices: ...working... done
CondaValueError: You have chosen a non-default solver backend (libmamba) but it was not recognized. Choose one of: classic

DEPRECATION: Loading egg at Z:\Anaconda3\lib\site-packages\audio_to_midi-2020.7-py3.8.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at Z:\Anaconda3\lib\site-packages\pomegranate-1.0.4-py3.8.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at Z:\Anaconda3\lib\site-packages\progressbar2-3.50.0-py3.8.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at Z:\Anaconda3\lib\site-packages\pycparser-2.19-py3.8.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at Z:\Anaconda3\lib\site-packages\python3_midi-0.2.5-py3.8.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at Z:\Anaconda3\lib\site-packages\soundfile-0.10.2-py3.8-win-amd64.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at Z:\Anaconda3\lib\site-packages\spacy-3.7.5-py3.8-win-amd64.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at Z:\Anaconda3\lib\site-packages\spacy_pkuseg-0.0.33-py3.8-win-amd64.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at Z:\Anaconda3\lib\site-packages\srsly-2.4.8-py3.8-win-amd64.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at Z:\Anaconda3\lib\site-packages\tspiral-0.3.0-py3.8.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at Z:\Anaconda3\lib\site-packages\weasel-0.4.1-py3.8.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at Z:\Anaconda3\lib\site-packages\zh_core_web_sm-3.7.0-py3.8.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
Collecting hanlp[full]
  Using cached hanlp-2.1.0b61-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: hanlp-common>=0.0.20 in Z:\Anaconda3\lib\site-packages (from hanlp[full]) (0.0.20)
Requirement already satisfied: hanlp-downloader in Z:\Anaconda3\lib\site-packages (from hanlp[full]) (0.0.25)
Collecting hanlp-trie>=0.0.4 (from hanlp[full])
  Using cached hanlp_trie-0.0.5.tar.gz (6.7 kB)
  Preparing metadata (setup.py) ... done
Collecting pynvml (from hanlp[full])
  Using cached pynvml-11.5.3-py3-none-any.whl.metadata (8.8 kB)
Collecting sentencepiece>=0.1.91 (from hanlp[full])
  Using cached sentencepiece-0.2.0-cp312-cp312-win_amd64.whl.metadata (8.3 kB)
Requirement already satisfied: termcolor in Z:\Anaconda3\lib\site-packages (from hanlp[full]) (1.1.0)
Collecting toposort==1.5 (from hanlp[full])
  Using cached toposort-1.5-py2.py3-none-any.whl.metadata (5.7 kB)
Requirement already satisfied: torch>=1.6.0 in Z:\Anaconda3\lib\site-packages (from hanlp[full]) (2.4.0)
Requirement already satisfied: transformers>=4.1.1 in Z:\Anaconda3\lib\site-packages (from hanlp[full]) (4.44.0)
Collecting fasttext-wheel==0.9.2 (from hanlp[full])
  Using cached fasttext_wheel-0.9.2-cp312-cp312-win_amd64.whl.metadata (16 kB)
Requirement already satisfied: networkx>=2.5.1 in Z:\Anaconda3\lib\site-packages (from hanlp[full]) (3.1)
Collecting penman==1.2.1 (from hanlp[full])
  Using cached Penman-1.2.1-py3-none-any.whl.metadata (7.8 kB)
Collecting perin-parser>=0.0.12 (from hanlp[full])
  Using cached perin_parser-0.0.14.tar.gz (232 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: tensorflow<2.14,>=2.6.0 in Z:\Anaconda3\lib\site-packages (from hanlp[full]) (2.13.0)
Requirement already satisfied: pybind11>=2.2 in Z:\Anaconda3\lib\site-packages (from fasttext-wheel==0.9.2->hanlp[full]) (2.13.5)
Requirement already satisfied: setuptools>=0.7.0 in Z:\Anaconda3\lib\site-packages (from fasttext-wheel==0.9.2->hanlp[full]) (69.1.1)
Requirement already satisfied: numpy in Z:\Anaconda3\lib\site-packages (from fasttext-wheel==0.9.2->hanlp[full]) (1.26.4)
Requirement already satisfied: phrasetree>=0.0.9 in Z:\Anaconda3\lib\site-packages (from hanlp-common>=0.0.20->hanlp[full]) (0.0.9)
Requirement already satisfied: scipy in Z:\Anaconda3\lib\site-packages (from perin-parser>=0.0.12->hanlp[full]) (1.13.1)
Requirement already satisfied: tensorflow-intel==2.13.0 in Z:\Anaconda3\lib\site-packages (from tensorflow<2.14,>=2.6.0->hanlp[full]) (2.13.0)
Requirement already satisfied: absl-py>=1.0.0 in Z:\Anaconda3\lib\site-packages (from tensorflow-intel==2.13.0->tensorflow<2.14,>=2.6.0->hanlp[full]) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in Z:\Anaconda3\lib\site-packages (from tensorflow-intel==2.13.0->tensorflow<2.14,>=2.6.0->hanlp[full]) (1.6.3)
Requirement already satisfied: flatbuffers>=23.1.21 in Z:\Anaconda3\lib\site-packages (from tensorflow-intel==2.13.0->tensorflow<2.14,>=2.6.0->hanlp[full]) (23.5.26)
Requirement already satisfied: gast<=0.4.0,>=0.2.1 in Z:\Anaconda3\lib\site-packages (from tensorflow-intel==2.13.0->tensorflow<2.14,>=2.6.0->hanlp[full]) (0.3.3)
Requirement already satisfied: google-pasta>=0.1.1 in Z:\Anaconda3\lib\site-packages (from tensorflow-intel==2.13.0->tensorflow<2.14,>=2.6.0->hanlp[full]) (0.2.0)
Requirement already satisfied: h5py>=2.9.0 in Z:\Anaconda3\lib\site-packages (from tensorflow-intel==2.13.0->tensorflow<2.14,>=2.6.0->hanlp[full]) (2.10.0)
Requirement already satisfied: libclang>=13.0.0 in Z:\Anaconda3\lib\site-packages (from tensorflow-intel==2.13.0->tensorflow<2.14,>=2.6.0->hanlp[full]) (16.0.6)
Collecting numpy (from fasttext-wheel==0.9.2->hanlp[full])
  Using cached numpy-1.24.3.tar.gz (10.9 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      Traceback (most recent call last):
        File "Z:\Anaconda3\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "Z:\Anaconda3\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "Z:\Anaconda3\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 112, in get_requires_for_build_wheel
          backend = _build_backend()
                    ^^^^^^^^^^^^^^^^
        File "Z:\Anaconda3\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 77, in _build_backend
          obj = import_module(mod_path)
                ^^^^^^^^^^^^^^^^^^^^^^^
        File "Z:\Anaconda3\Lib\importlib\__init__.py", line 90, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 995, in exec_module
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "T:\HHH\AppData\Local\Temp\pip-build-env-azo38kv9\overlay\Lib\site-packages\setuptools\__init__.py", line 16, in <module>
          import setuptools.version
        File "T:\HHH\AppData\Local\Temp\pip-build-env-azo38kv9\overlay\Lib\site-packages\setuptools\version.py", line 1, in <module>
          import pkg_resources
        File "T:\HHH\AppData\Local\Temp\pip-build-env-azo38kv9\overlay\Lib\site-packages\pkg_resources\__init__.py", line 2172, in <module>
          register_finder(pkgutil.ImpImporter, find_on_path)
                          ^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

DEPRECATION: Loading egg at Z:\Anaconda3\lib\site-packages\audio_to_midi-2020.7-py3.8.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at Z:\Anaconda3\lib\site-packages\pomegranate-1.0.4-py3.8.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at Z:\Anaconda3\lib\site-packages\progressbar2-3.50.0-py3.8.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at Z:\Anaconda3\lib\site-packages\pycparser-2.19-py3.8.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at Z:\Anaconda3\lib\site-packages\python3_midi-0.2.5-py3.8.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at Z:\Anaconda3\lib\site-packages\soundfile-0.10.2-py3.8-win-amd64.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at Z:\Anaconda3\lib\site-packages\spacy-3.7.5-py3.8-win-amd64.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at Z:\Anaconda3\lib\site-packages\spacy_pkuseg-0.0.33-py3.8-win-amd64.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at Z:\Anaconda3\lib\site-packages\srsly-2.4.8-py3.8-win-amd64.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at Z:\Anaconda3\lib\site-packages\tspiral-0.3.0-py3.8.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at Z:\Anaconda3\lib\site-packages\weasel-0.4.1-py3.8.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at Z:\Anaconda3\lib\site-packages\zh_core_web_sm-3.7.0-py3.8.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
Looking in indexes: https://pypi.douban.com/simple/
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /simple/hanlp/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /simple/hanlp/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /simple/hanlp/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /simple/hanlp/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /simple/hanlp/
ERROR: Could not find a version that satisfies the requ

Expected behavior
pip  Hanlp2.0 

System information
python   Python 3.12.4
Anaconda3  conda 24.7.1
 WIN10 

Other info / logs
----- 
I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
【自动回复】您好，感谢反馈。
由于未按要求填写，本issue被自动关闭，将在一小时内自动删除。

如果您提的是bug或feature request，请按[issue模板](https://github.com/hankcs/HanLP/tree/doc-zh/.github/ISSUE_TEMPLATE)认真修改，然后耐心等待下周末处理。

否则，[咨询类的问题GitHub概不受理](https://bbs.hankcs.com/t/topic/2245)。请先搜索一下，99.9%的问题已经反复回答过了，人类的本质是复读机。如果您确信您提了个新问题，那么欢迎写清楚前因后果发在[论坛](https://bbs.hankcs.com/)而不是GitHub上。

开源项目维护不易，HanLP用户以十万计，而主要维护者只有我一人。我有自己的full-time研究工作，只能在周末受理[友好的提问](https://github.com/hankcs/HanLP/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E9%97%AE)，造成不便还望海涵。
