### ISSUE TITLE
一个bug如果把机构名和数字识别同时打开

### ISSUE THREAD

**Issue by lijianbo0130** [hankcs/HanLP#193]
切分下面这句话的时候会出exception
以每台约200元的价格送到苹果售后维修中心换新机（苹果的保修基本是免费换新机）

**Comment by hankcs** [comment]
[以/p, 每/rz, 台/q, 约/d, 200元/mq, 的/ude1, 价格/n, 送到/v, 苹果售后维修中心/nt, 换新/nz, 机/ng, （/w, 苹果/nf, 的/ude1, 保修/vn, 基本/a, 是/vshi, 免费/vd, 换新/nz, 机/ng, ）/w]

**Comment by hankcs** [comment]
请使用最新版。

**Comment by lijianbo0130** [comment]
我使用的代码如下，确实是1.29.
如果你那里不会报错就算了。
		/*
		 * 机构识别和数字识别同时打开会出现bug
		 * 只对某些句子有用
		 */
		String[] testCase = new String[] {
				"以每台约200元的价格送到苹果售后维修中心换新机（苹果的保修基本是免费换新机）" };
		Segment segment2 = HanLP.newSegment().enableOrganizationRecognize(true).enableNumberQuantifierRecognize(true);
		for (String sentence : testCase) {
			List<Term> termList = segment2.seg(sentence);
			System.out.println(termList);
		}
异常如下
以每台约200元的价格送到苹果售后维修中心换新机（苹果的保修基本是免费换新机）
Exception in thread "main" java.util.NoSuchElementException
	at java.util.LinkedList.getFirst(LinkedList.java:242)
	at com.hankcs.hanlp.seg.Viterbi.ViterbiSegment.viterbi(ViterbiSegment.java:146)
	at com.hankcs.hanlp.seg.Viterbi.ViterbiSegment.segSentence(ViterbiSegment.java:101)
	at com.hankcs.hanlp.seg.Segment.seg(Segment.java:425)
	at basic.BugOrganizationRecognition.main(BugOrganizationRecognition.java:37)

**Comment by hankcs** [comment]
感谢反馈详情 是否修改了任何词典？

**Comment by lijianbo0130** [comment]
词典改过很多，我刚刚下了一个最新版本的hanlp测试还是有这个问题。其实也不是啥很大的问题，我就是想知道我是不是真的发现了一个bug.毕竟这是我发现的第一个bug.└(^o^)┘。

**Comment by hankcs** [comment]
感谢大家指正，确认问题的确存在，与https://github.com/hankcs/HanLP/issues/150 是同一个问题。当时以为修复了，事实上没有。
@StardustZhou 能否提交一份patch，你的解决方案是正确的。

**Comment by hankcs** [comment]
```
        HanLP.Config.enableDebug();
        Segment segment = new ViterbiSegment().enableOrganizationRecognize(true).enableNumberQuantifierRecognize(true);
        System.out.println(segment.seg(
                "以每台约200元的价格送到苹果售后维修中心换新机（苹果的保修基本是免费换新机）"
        ));
```

[以/p, 每/rz, 台/q, 约/d, 200元/mq, 的/ude1, 价格/n, 送到/v, 苹果售后维修中心/nt, 换新/nz, 机/ng, （/w, 苹果/nf, 的/ude1, 保修/vn, 基本/a, 是/vshi, 免费/vd, 换新/nz, 机/ng, ）/w]

**Comment by lijianbo0130** [comment]
我觉得我成了bug挖掘机了。代码如下：

		/*
		 * 机构识别和数字识别同时打开会出现bug
		 * 只对某些句子有用
		 */
		String[] testCase = new String[] {
				"以每台约200元的价格送到苹果售后维修中心换新机（苹果的保修基本是免费换新机）" ,
				"可能以2500~2800元的价格回收"
				};
		Segment segment2 = HanLP.newSegment().enableOrganizationRecognize(true).enableNumberQuantifierRecognize(true);
		for (String sentence : testCase) {
			List<Term> termList = segment2.seg(sentence);
			System.out.println(termList);
		}
结果如下：
[以/p, 每/rz, 台/q, 约/d, 200元/mq, 的/ude1, 价格/n, 送到/v, 苹果售后维修中心/nt, 换/v, 新/a, 机/ng, （/w, 苹果/nf, 的/ude1, 保修/vn, 基本/a, 是/vshi, 免费/vd, 换/v, 新/a, 机/ng, ）/w]Exception in thread "main" 
java.lang.ArrayIndexOutOfBoundsException: 20
	at com.hankcs.hanlp.seg.common.WordNet.add(WordNet.java:101)
	at com.hankcs.hanlp.seg.common.WordNet.addAll(WordNet.java:201)
	at com.hankcs.hanlp.seg.Viterbi.ViterbiSegment.segSentence(ViterbiSegment.java:95)
	at com.hankcs.hanlp.seg.Segment.seg(Segment.java:428)
	at com.ljbRead.cut.orgrec.BugOrganizationRecognition.main(BugOrganizationRecognition.java:37)

**Comment by hankcs** [comment]
干得漂亮，我马上处理。

**Comment by lijianbo0130** [comment]
经过我不间断的测试好像还是有点问题。

		/*
		 * 机构识别和数字识别同时打开会出现bug
		 * 只对某些句子有用
		 */
		String[] testCase = new String[] {
				"以每台约200元的价格送到苹果售后维修中心换新机（苹果的保修基本是免费换新机）" ,
				"可能以2500~2800元的价格回收",
				"3700个益农信息社打通服务“最后一公里”"
				};
		Segment segment2 = HanLP.newSegment().enableOrganizationRecognize(true).enableNumberQuantifierRecognize(true);
		for (String sentence : testCase) {
			List<Term> termList = segment2.seg(sentence);
			System.out.println(termList);
		}
	
异常
[以/p, 每/rz, 台/q, 约/d, 200元/mq, 的/ude1, 价格/n, 送到/v, 苹果售后维修中心/nt, 换/v, 新/a, 机/ng, （/w, 苹果/nf, 的/ude1, 保修/vn, 基本/a, 是/vshi, 免费/vd, 换/v, 新/a, 机/ng, ）/w]
[可能/v, 以/p, 2500/m, ~/nx, 2800元/mq, 的/ude1, 价格/n, 回收/vn]
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 23
	at com.hankcs.hanlp.seg.common.WordNet.add(WordNet.java:101)
	at com.hankcs.hanlp.seg.common.WordNet.addAll(WordNet.java:201)
	at com.hankcs.hanlp.seg.Viterbi.ViterbiSegment.segSentence(ViterbiSegment.java:95)
	at com.hankcs.hanlp.seg.Segment.seg(Segment.java:437)
	at com.hankcs.test.BugOrganizationRecognition.main(BugOrganizationRecognition.java:38)

其他出错过的句子
有一些可能是因为，数字开头的句子。
3700个益农信息社打通服务“最后一公里”
一位李先生给高政留言说上周五可以帮忙献血
一位浩宁达高层透露
五和万科长阳天地5个普宅项目
以1974点低点和5178点高点作江恩角度线
纳入统计的18家京系基金公司
华夏基金与嘉实基金两家京系基金公司

**Comment by hankcs** [comment]
感谢指正，这下应该解决了。

**Comment by lijianbo0130** [comment]
又出现了一个新的句子。 则应从排名第八的投标人开始依次递补三名投标人

**Comment by hankcs** [comment]
感谢反馈，已经解决。
