### ISSUE TITLE
hanlp.load(hanlp.pretrained.tok.LARGE_ALBERT_BASE) 报错

### ISSUE THREAD

**Issue by marianasignal** [hankcs/HanLP#1934]
**Describe the bug**
tok = hanlp.load(hanlp.pretrained.tok.LARGE_ALBERT_BASE)
Failed to load https://file.hankcs.com/hanlp/tok/large_corpus_cws_albert_base_20211228_160926.zip
Please upgrade HanLP with:

        pip install --upgrade hanlp

If the problem still persists, please submit an issue to https://github.com/hankcs/HanLP/issues
When reporting an issue, make sure to paste the FULL ERROR LOG below.
hanlp 已升级

**Code to reproduce the issue**
import hanlp
tok = hanlp.load(hanlp.pretrained.tok.LARGE_ALBERT_BASE)

```python
```

**Describe the current behavior**
================================ERROR LOG BEGINS================================
OS: Windows-10-10.0.22631-SP0
Python: 3.8.10
PyTorch: 2.1.2+cpu
TensorFlow: 2.13.0
HanLP: 2.1.0-beta.64
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\project\03-HisRecLab\.venv\lib\site-packages\hanlp\__init__.py", line 43, in load
    return load_from_meta_file(save_dir, 'meta.json', verbose=verbose, **kwargs)
  File "D:\project\03-HisRecLab\.venv\lib\site-packages\hanlp\utils\component_util.py", line 186, in load_from_meta_file
    raise e from None
  File "D:\project\03-HisRecLab\.venv\lib\site-packages\hanlp\utils\component_util.py", line 106, in load_from_meta_file
    obj.load(save_dir, verbose=verbose, **kwargs)
  File "D:\project\03-HisRecLab\.venv\lib\site-packages\hanlp\common\keras_component.py", line 215, in load
    self.build(**merge_dict(self.config, training=False, logger=logger, **kwargs, overwrite=True, inplace=True))
  File "D:\project\03-HisRecLab\.venv\lib\site-packages\hanlp\common\keras_component.py", line 225, in build
    self.model = self.build_model(**merge_dict(self.config, training=kwargs.get('training', None),
  File "D:\project\03-HisRecLab\.venv\lib\site-packages\hanlp\components\taggers\transformers\transformer_tagger_tf.py", line 34, in build_model
    model, tokenizer = build_transformer(transformer, max_seq_length, len(self.transform.tag_vocab), tagging=True)
  File "D:\project\03-HisRecLab\.venv\lib\site-packages\hanlp\layers\transformers\loader_tf.py", line 11, in build_transformer
    tokenizer = AutoTokenizer_.from_pretrained(transformer)
  File "D:\project\03-HisRecLab\.venv\lib\site-packages\hanlp\layers\transformers\pt_imports.py", line 65, in from_pretrained
    tokenizer = cls.from_pretrained(get_tokenizer_mirror(transformer), use_fast=use_fast,
  File "D:\project\03-HisRecLab\.venv\lib\site-packages\transformers\tokenization_utils_base.py", line 2197, in from_pretrained
    raise EnvironmentError(
OSError: Can't load tokenizer for 'uer/albert-base-chinese-cluecorpussmall'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'uer/albert-base-chinese-cluecorpussmall' is the correct path to a directory containing all relevant files for a BertTokenizer tokenizer.
=================================ERROR LOG ENDS=================================

**Expected behavior**

**System information**
OS: Windows-10-10.0.22631-SP0
Python: 3.8.10
PyTorch: 2.1.2+cpu
TensorFlow: 2.13.0
HanLP: 2.1.0-beta.64

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

* [x] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
Not a bug caused by HanLP.

Your Internet needs to support you:

```python
# Load model directly
from transformers import AutoTokenizer, AutoModelForMaskedLM

tokenizer = AutoTokenizer.from_pretrained("uer/albert-base-chinese-cluecorpussmall")
model = AutoModelForMaskedLM.from_pretrained("uer/albert-base-chinese-cluecorpussmall")
```

**Comment by marianasignal** [comment]
Yes thanks, I fixed it by downgrade urllib
