### ISSUE TITLE
v1.2.9 DemoCRFSegment error

### ISSUE THREAD

**Issue by wanqulou** [hankcs/HanLP#216]
严重: 字符正规化表加载失败，原因如下：
java.io.FileNotFoundException: data\dictionary\other\CharTable.bin.yes (系统找不到指定的路径。)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at com.hankcs.hanlp.seg.CRF.CRFSegment$CharTable.<clinit>(CRFSegment.java:368)
	at com.hankcs.hanlp.seg.CRF.CRFSegment.segSentence(CRFSegment.java:46)
	at com.hankcs.hanlp.seg.Segment.seg(Segment.java:425)
	at com.madhouse.dsp.HanlpMain$$anonfun$1.apply(HanlpMain.scala:49)
	at com.madhouse.dsp.HanlpMain$$anonfun$1.apply(HanlpMain.scala:48)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at com.madhouse.dsp.HanlpMain$.delayedEndpoint$com$madhouse$dsp$HanlpMain$1(HanlpMain.scala:48)
	at com.madhouse.dsp.HanlpMain$delayedInit$body.apply(HanlpMain.scala:18)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at com.madhouse.dsp.HanlpMain$.main(HanlpMain.scala:18)
	at com.madhouse.dsp.HanlpMain.main(HanlpMain.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

**Comment by hankcs** [comment]
java.io.FileNotFoundException: data\dictionary\other\CharTable.bin.yes (系统找不到指定的路径。)
请检查自己的路径。
