### ISSUE TITLE
GC overhead limit exceeded

### ISSUE THREAD

**Issue by T-baby** [hankcs/HanLP#231]
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at com.hankcs.hanlp.corpus.io.ByteArray.nextString(ByteArray.java:113)
	at com.hankcs.hanlp.model.maxent.MaxEntModel.create(MaxEntModel.java:328)
	at com.hankcs.hanlp.dependency.MaxEntDependencyParser.<clinit>(MaxEntDependencyParser.java:45)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.jfinal.ext.kit.Reflect.forName(Reflect.java:692)
	at com.jfinal.ext.kit.Reflect.on(Reflect.java:85)
	at com.jfinal.ext.kit.ClassSearcher.extraction(ClassSearcher.java:49)
	at com.jfinal.ext.kit.ClassSearcher.search(ClassSearcher.java:144)
	at com.jfinal.ext.route.AutoBindRoutes.config(AutoBindRoutes.java:73)
	at com.jfinal.config.Routes.add(Routes.java:40)
	at config.JfinalConfig.configRoute(JfinalConfig.java:36)
	at com.jfinal.core.Config.configJFinal(Config.java:47)
	at com.jfinal.core.JFinal.init(JFinal.java:65)
	at com.jfinal.core.JFinalFilter.init(JFinalFilter.java:49)
	at org.eclipse.jetty.servlet.FilterHolder.initialize(FilterHolder.java:137)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:831)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:300)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1341)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1334)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:744)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:497)
	at org.eclipse.jetty.maven.plugin.JettyWebAppContext.doStart(JettyWebAppContext.java:281)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:60)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:154)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:60)

这是什么原因引起的呢？

**Comment by hankcs** [comment]
请参考注释：https://github.com/hankcs/HanLP/blob/master/src/test/java/com/hankcs/demo/DemoDependencyParser.java

**Comment by T-baby** [comment]
你是说缺少句法模型文件？还是？我本地是一切正常的

**Comment by hankcs** [comment]
**
 * 依存句法分析（CRF句法模型需要-Xms512m -Xmx512m -Xmn256m，MaxEnt和神经网络句法模型需要-Xms1g -Xmx1g -Xmn512m）
 * @author hankcs
 */

**Comment by T-baby** [comment]
现在又Java heap space

**Comment by hankcs** [comment]
你必须保证-Xms1g -Xmx1g -Xmn512m，这是句法分析器最低的配置，也是你的工作。

**Comment by T-baby** [comment]
已经按照这个参数调整过，但是jetty启动失败

**Comment by hankcs** [comment]
jetty自身也要吃掉不少内存，我要1g内存，而你没有给我，问题就是这么简单。
