### ISSUE TITLE
NLPTokenizer分词时用到的核心词典转移矩阵

### ISSUE THREAD

**Issue by liuyunfanng** [hankcs/HanLP#272]
我现在用NLPTokenizer分词方法进行分词，在Nature中添加词性text，把核心词典中合肥市的词性标注为text，但是会出现下面的错误，
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 148
    at com.hankcs.hanlp.algoritm.Viterbi.compute(Viterbi.java:121)
    at com.hankcs.hanlp.seg.WordBasedGenerativeModelSegment.speechTagging(WordBasedGenerativeModelSegment.java:531)
    at com.hankcs.hanlp.seg.Viterbi.ViterbiSegment.segSentence(ViterbiSegment.java:118)
    at com.hankcs.hanlp.seg.Segment.seg(Segment.java:454)
    at com.hankcs.hanlp.tokenizer.NLPTokenizer.segment(NLPTokenizer.java:37)
    at com.hankcs.test.seg.Test.main(Test.java:11)

显示应该是核心词典转移矩阵的问题，核心矩阵中不包含新的词性，那这样的话，核心词典转移矩阵需要重新生成吗，要怎么生成啊

**Comment by hankcs** [comment]
你已经提过相同的问题了，难道我没有说明白？

这个问题已经解决了，你把GitHub上最新的代码编译一下不就行了吗？

**Comment by liuyunfanng** [comment]
我出现这个问题的时候用的就是Github上最新的代码，不知道是什么地方出问题了，还是会报错！

**Comment by liuyunfanng** [comment]
代码下载下来后，就直接修改核心词典，然后调用接口NLPTokenizer.segment(text)进行分词处理，结果在Nature中新添加的词性，在核心词典中使用时会报错，不会生效， HanLP.segment(text)则会生效。报错显示应该是转移矩阵里面不包含这个词性，不知道要怎么改，希望帮忙看下，谢谢！

**Comment by hankcs** [comment]
抱歉我没有复现这个问题，麻烦你把GitHub中的代码fork一份，在这份代码的基础上复现你说的问题，然后提交一下，之后我就能马上处理了。

**Comment by liuyunfanng** [comment]
恩恩，好的，谢谢哈！

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
