### ISSUE TITLE
运行自定义词性Demo，NoSuchFieldException:$VALUES

### ISSUE THREAD

**Issue by yueritian** [hankcs/HanLP#279]
您好，使用MacBook Pro 10.11，Eclipse Mars.1 ，JDK1.7，运行1.2.10版本的DemoCustomNature.java后如下报错：
七月 24, 2016 6:55:03 下午 com.hankcs.hanlp.corpus.util.CustomNatureUtility <clinit>
警告: 已激活自定义词性功能,由于采用了反射技术,用户需对本地环境的兼容性和稳定性负责!
如果用户代码X.java中有switch(nature)语句,需要调用CustomNatureUtility.registerSwitchClass(X.class)注册X这个类
Exception in thread "main" java.lang.IllegalArgumentException: Could not create enum
    at com.hankcs.hanlp.corpus.util.EnumBuster.make(EnumBuster.java:99)
    at com.hankcs.hanlp.corpus.util.EnumBuster.make(EnumBuster.java:68)
    at com.hankcs.hanlp.corpus.util.CustomNatureUtility.addNature(CustomNatureUtility.java:58)
    at com.hankcs.hanlp.corpus.tag.Nature.create(Nature.java:829)
    at com.hankcs.demo.DemoCustomNature.main(DemoCustomNature.java:41)
Caused by: java.lang.IllegalArgumentException: Could not create the class
    at com.hankcs.hanlp.corpus.util.EnumBuster$Memento.<init>(EnumBuster.java:453)
    at com.hankcs.hanlp.corpus.util.EnumBuster$Memento.<init>(EnumBuster.java:439)
    at com.hankcs.hanlp.corpus.util.EnumBuster.make(EnumBuster.java:91)
    ... 4 more
Caused by: java.lang.NoSuchFieldException: $VALUES
    at java.lang.Class.getDeclaredField(Class.java:1961)
    at com.hankcs.hanlp.corpus.util.EnumBuster.findValuesField(EnumBuster.java:349)
    at com.hankcs.hanlp.corpus.util.EnumBuster.values(EnumBuster.java:429)
    at com.hankcs.hanlp.corpus.util.EnumBuster.access$0(EnumBuster.java:426)
    at com.hankcs.hanlp.corpus.util.EnumBuster$Memento.<init>(EnumBuster.java:443)

**Comment by hankcs** [comment]
感谢反馈，

0. 由于采用了反射技术,用户需对本地环境的兼容性和稳定性负责
0. 我仅在Oracle jdk 1.8上做过测试
0. 如果你想在你的环境中用这项功能，请查阅一些反射相关的知识，无非就是jdk版本变迁带来的变化，很机械的工作。如果你解决了，欢迎提交pr。

**Comment by yueritian** [comment]
谢谢您的回馈，我换用1.8也报相同的错误，估计和系统有关。我试试看如何解决。

**Comment by yueritian** [comment]
调整com.hankcs.hanlp.corpus.util.EnumBuster类，可解决以上报错。
`   private Field findValuesField() throws NoSuchFieldException
    {
        // first we find the static final array that holds
        // the values in the enum class
    	// 注释掉的代码
        //Field valuesField = clazz.getDeclaredField(VALUES_FIELD);
    	// chenph jdk1.7 2016/7/25 开始
        Field valuesField = null;
	   	Field[] fields = clazz.getDeclaredFields();
	   	for(Field field : fields){
	   		if(field.getName().contains(VALUES_FIELD)){
	   			valuesField = field;
	   			break;
	   		}
	   	}
	   	// 结束
        // we mark it to be public
        valuesField.setAccessible(true);
        return valuesField;
    }`
运行Demo后，苹果电脑的例子可运行（需要将苹果修改为苹果电脑，否则不识别）
`LexiconUtility.setAttribute("苹果", pcNature);`
但是，第二个阿尔法狗的例子会报数组越界，查看了您的博客，有可能是添加枚举值得时候出现问题。此时将苹果电脑的例子删掉后，阿尔法狗的例子可正常运行。原因待查。

**Comment by hankcs** [comment]
感谢patch，已经整合到版本库中了。

关于数组越界，在com.hankcs.hanlp.corpus.util.CustomNatureUtility#addNature中对enum数组进行了一次扩容。请确认新加入的词性在你的JVM中被分配的ordinal是否能放入扩容后的数组，我猜测有些JVM分配的ordinal不是连续的。

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
