### ISSUE TITLE
CRFSegment的字符正规化表加载失败

### ISSUE THREAD

**Issue by tigerich** [hankcs/HanLP#287]
下面这行代码
`ObjectInputStream in = new ObjectInputStream(new FileInputStream(HanLP.Config.CharTablePath));
`
直接导致了下面问题：
```
Aug 03, 2016 2:12:18 PM com.hankcs.hanlp.seg.CRF.CRFSegment$CharTable <clinit>
SEVERE: 字符正规化表加载失败，原因如下：
java.io.StreamCorruptedException: invalid stream header: 003D200A
	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:806)
	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:299)
	at com.hankcs.hanlp.seg.CRF.CRFSegment$CharTable.<clinit>(CRFSegment.java:370)
	at com.hankcs.hanlp.seg.CRF.CRFSegment.segSentence(CRFSegment.java:47)
	at com.hankcs.hanlp.seg.Segment.seg(Segment.java:454)
	at com.hankcs.demo.DemoCRFSegment.main(DemoCRFSegment.java:62)
```

请帮忙查看一下。

**Comment by hankcs** [comment]
感谢反馈，已经修复。
