### ISSUE TITLE
求助：ViterbiSegment个别句子机构识别异常，报NoSuchElementException

### ISSUE THREAD

**Issue by flystarhe** [hankcs/HanLP#290]
```
val txt = "而其他肢解出去的七个贝尔公司如西南贝尔、太平洋贝尔、大西洋贝尔、南方贝尔等只能经营短途电话业务。"
val seg_viterbi = new ViterbiSegment().enablePartOfSpeechTagging(true).enableOffset(true).enableNameRecognize(true).enablePlaceRecognize(true).enableOrganizationRecognize(true).enableNumberQuantifierRecognize(true)
println(seg_viterbi.seg(txt))
```

```
Exception in thread "main" java.util.NoSuchElementException
	at java.util.LinkedList.getFirst(LinkedList.java:244)
	at com.hankcs.hanlp.seg.Viterbi.ViterbiSegment.viterbi(ViterbiSegment.java:127)
	at com.hankcs.hanlp.seg.Viterbi.ViterbiSegment.segSentence(ViterbiSegment.java:90)
	at com.hankcs.hanlp.seg.Segment.seg(Segment.java:401)
	at cn.com.cetc.lab.test.TestMulti$.main(TestMulti.scala:17)
	at cn.com.cetc.lab.test.TestMulti.main(TestMulti.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```

看了代码，没太看明白，不知道哪儿的问题。一般句子没有问题，个别句子会这样。

**Comment by flystarhe** [comment]
```
val txt = "而其他肢解出去的七个贝尔公司如西南贝尔、太平洋贝尔、大西洋贝尔、南方贝尔等只能经营短途电话业务。"
val seg_viterbi = new ViterbiSegment().enablePartOfSpeechTagging(true).enableOffset(true).enableNameRecognize(true).enablePlaceRecognize(true).enableOrganizationRecognize(true).enableNumberQuantifierRecognize(false)
```

奇怪的是，关闭数词和量词识别，又不报错了。
但是问题还是不知道出在哪儿

**Comment by hankcs** [comment]
感谢反馈，

0. 已经修复：https://github.com/hankcs/HanLP/commit/bf8eb0ceb09c37709a8e7f247cfe761c34068420
0. 请删除用户词典缓存使其生效。

**Comment by flystarhe** [comment]
非常感谢。

**Comment by duolahaitun** [comment]
@hankcs ，我这边遇到和他一模一样的问题；使用的是1.6.2版本；关闭enableNumberQuantifierRecognize之后就可以正常分词；

**Comment by hankcs** [comment]
@duolahaitun 请给出触发代码，谢谢。

**Comment by duolahaitun** [comment]
@hankcs 代码如下：

**Comment by duolahaitun** [comment]
谢谢
