### ISSUE TITLE
自定义词性错误

### ISSUE THREAD

**Issue by finanshow** [hankcs/HanLP#301]
版本：HANLP-1.2.10 
环境: JDK 1.8.0_45 64位 WIN10
新增的功能自定义词性DEMO第一个可以正常运行，但是尝试将词性赋予到某个词的时候报错
比如：
Nature myNature = Nature.create("DEFINED");
 LexiconUtility.setAttribute("某个词", myNature );
从词性来看，不知道对这个词有没有特殊要求

DEMO第二部分插入到用户词典也报错
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 148
	at com.hankcs.hanlp.algoritm.Viterbi.compute(Viterbi.java:121)
	at com.hankcs.hanlp.seg.WordBasedGenerativeModelSegment.speechTagging(WordBasedGenerativeModelSegment.java:531)
	at com.hankcs.hanlp.seg.Viterbi.ViterbiSegment.segSentence(ViterbiSegment.java:118)
	at com.hankcs.hanlp.seg.Segment.seg(Segment.java:470)
	at com.hankcs.hanlp.tokenizer.StandardTokenizer.segment(StandardTokenizer.java:50)
	at com.hankcs.hanlp.HanLP.segment(HanLP.java:386)
	at MainServer.main(MainServer.java:71)

**Comment by hankcs** [comment]
版本号？

**Comment by finanshow** [comment]
HANLP-1.2.10 
环境: JDK 1.8.0_45 64位 WIN10

**Comment by hankcs** [comment]
是版本库master代码，还是release中的jar包？

**Comment by finanshow** [comment]
release 中的JAR包

**Comment by hankcs** [comment]
版本库代码应该已经修复了该问题，
已在jdk1.8 Windows和macos下通过测试，不妨试试自己打个包。

**Comment by hankcs** [comment]
see：https://github.com/hankcs/HanLP/issues/279

**Comment by hankcs** [comment]
and https://github.com/hankcs/HanLP/commit/ffb02692b38416ec4a32fe33e3d5b5dc69ab1303

**Comment by finanshow** [comment]
非常感谢！DATA里面的核心词典、2元词典有办法可以自己定义吗？

**Comment by finanshow** [comment]
自己怎么样可以训练词典呢？

**Comment by hankcs** [comment]
https://github.com/hankcs/HanLP/wiki/%E8%AE%AD%E7%BB%83%E5%88%86%E8%AF%8D%E6%A8%A1%E5%9E%8B
