### ISSUE TITLE
WordNet数组越界异常

### ISSUE THREAD

**Issue by chenying99** [hankcs/HanLP#358]
大神好 我从git上clone了今天的版本，昨天那多线程异常没出现
今天抛出一个更重大的Exception

java.lang.ArrayIndexOutOfBoundsException: 43
	at com.hankcs.hanlp.seg.common.WordNet.get(WordNet.java:214)
	at com.hankcs.hanlp.seg.common.WordNet.insert(WordNet.java:166)
	at com.hankcs.hanlp.dictionary.nt.OrganizationDictionary$1.hit(OrganizationDictionary.java:3777)
	at com.hankcs.hanlp.dictionary.nt.OrganizationDictionary$1.hit(OrganizationDictionary.java:3754)
	at com.hankcs.hanlp.collection.AhoCorasick.AhoCorasickDoubleArrayTrie.parseText(AhoCorasickDoubleArrayTrie.java:101)
	at com.hankcs.hanlp.dictionary.nt.OrganizationDictionary.parsePattern(OrganizationDictionary.java:3753)
	at com.hankcs.hanlp.recognition.nt.OrganizationRecognition.Recognition(OrganizationRecognition.java:70)
	at com.hankcs.hanlp.seg.Viterbi.ViterbiSegment.segSentence(ViterbiSegment.java:99)
	at com.hankcs.hanlp.seg.Segment.seg(Segment.java:558)

执行代码：

public static void main(String[] args) {
		
		String str="受约束，需要遵守心理学会所定的道德原则，所需要时须说明该实验与所能得到的知识的关系";
		
		Segment defaultSegment = StandardTokenizer.SEGMENT
				.enablePartOfSpeechTagging(true).enableOffset(true)
				.enableNameRecognize(true).enablePlaceRecognize(true)
				.enableOrganizationRecognize(true);
		
		try {
			List<Term> list = defaultSegment.seg(str);
		} catch (Exception e) {
			// TODO: handle exception
			
			e.printStackTrace();
			LOGGER.error("分词异常",e);
		}
		
		
	}

**Comment by hankcs** [comment]
感谢指正，两个trie的参数不兼容，已修复。
