### ISSUE TITLE
jdk 1.7正常分词，jdk1.8分词数组越界

### ISSUE THREAD

**Issue by GZJackCai** [hankcs/HanLP#376]
jar版本1.3.2，我看其他人的issue 好像很多人也有这个问题
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 149
	at com.hankcs.hanlp.seg.common.Vertex.compileRealWord(Vertex.java:115)
	at com.hankcs.hanlp.seg.common.Vertex.<init>(Vertex.java:99)
	at com.hankcs.hanlp.seg.common.Vertex.<init>(Vertex.java:91)
	at com.hankcs.hanlp.seg.common.Vertex.<init>(Vertex.java:196)
	at com.hankcs.hanlp.seg.Segment.combineWords(Segment.java:380)
	at com.hankcs.hanlp.seg.Segment.combineByCustomDictionary(Segment.java:221)
	at com.hankcs.hanlp.seg.Viterbi.ViterbiSegment.segSentence(ViterbiSegment.java:57)
	at com.hankcs.hanlp.seg.Segment.seg(Segment.java:574)
	at com.hankcs.hanlp.tokenizer.StandardTokenizer.segment(StandardTokenizer.java:40)
	at test.main(test.java:8)

**Comment by hankcs** [comment]
请仿照示例给出触发代码

```
    public void testIssue1234() throws Exception
    {
        CustomDictionary.add("用户词语");
        System.out.println(StandardTokenizer.segment("触发问题的句子"));
    }
```

**Comment by hankcs** [comment]
另外，根据你提供的不完全信息，此问题与你开启了自定义词性有关，与历史issue无关。因为每个人jdk和系统环境千差万别，目前的策略是，由于采用了反射技术,用户需对本地环境的兼容性和稳定性负责，上游只能说尽量提供一些通用的建议。如果你对反射技术很了解，有debug能力，欢迎继续交流，否则请用常规方法修改Nature类来实现自定义词性。
http://www.hankcs.com/program/java/enum-java-examples-of-dynamic-modification.html

**Comment by GZJackCai** [comment]
懂了，非常感谢回复。
