### ISSUE TITLE
NLPTokenizer.segment 多线程异常

### ISSUE THREAD

**Issue by debug2012** [hankcs/HanLP#390]
java.lang.NullPointerException
	at com.hankcs.hanlp.algoritm.ahocorasick.trie.Trie.getState(Trie.java:209)
	at com.hankcs.hanlp.algoritm.ahocorasick.trie.Trie.parseText(Trie.java:140)
	at com.hankcs.hanlp.dictionary.nt.OrganizationDictionary.parsePattern(OrganizationDictionary.java:3749)
	at com.hankcs.hanlp.recognition.nt.OrganizationRecognition.Recognition(OrganizationRecognition.java:70)
	at com.hankcs.hanlp.seg.Viterbi.ViterbiSegment.segSentence(ViterbiSegment.java:97)
	at com.hankcs.hanlp.seg.Segment.seg(Segment.java:466)
	at com.hankcs.hanlp.tokenizer.NLPTokenizer.segment(NLPTokenizer.java:37)

hanlp-1.3.1 在多线程情况下，出现空指针异常。
NLPTokenizer.segment应该不是线程安全的吧，有没有线程安全的替代方法？

**Comment by hankcs** [comment]
https://github.com/hankcs/HanLP/issues/357#issuecomment-264044575

请使用最新版。

**Comment by debug2012** [comment]
多谢， 问题解决。

**Comment by YanJiamei** [comment]
java.lang.NullPointerException 	
at com.hankcs.hanlp.algorithm.ahocorasick.trie.Trie.getState(Trie.java:214) 	
at com.hankcs.hanlp.algorithm.ahocorasick.trie.Trie.parseText(Trie.java:145)

v1.7.8 仍然出现多线程的情况下空指针异常：在线上高并发情况下trie.parseText()抛出空指针异常。
