### ISSUE TITLE
加载用户词典时出现数组溢出错误，我加载了自己的路径为root=D:/LearnHanLP/data/ CustomDictionaryPath=dictionary/custom/CustomDictionary.txt; economic.txt; stork.txt; 

### ISSUE THREAD

**Issue by rouchtime** [hankcs/HanLP#399]
二月 13, 2017 5:38:41 下午 com.hankcs.hanlp.HanLP$Config$1 getProperty
警告: root=D:/LearnHanLP/data/ 这个目录下没有data
二月 13, 2017 5:38:41 下午 com.hankcs.hanlp.corpus.io.IOUtil readBytes
警告: 读取D:/LearnHanLP/data/dictionary/custom/CustomDictionary.txt.bin时发生异常java.io.FileNotFoundException: D:\LearnHanLP\data\dictionary\custom\CustomDictionary.txt.bin (系统找不到指定的文件。)
二月 13, 2017 5:38:41 下午 com.hankcs.hanlp.corpus.util.CustomNatureUtility <clinit>
警告: 已激活自定义词性功能,由于采用了反射技术,用户需对本地环境的兼容性和稳定性负责!
如果用户代码X.java中有switch(nature)语句,需要调用CustomNatureUtility.registerSwitchClass(X.class)注册X这个类
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 148
	at com.hankcs.hanlp.seg.common.Vertex.compileRealWord(Vertex.java:115)
	at com.hankcs.hanlp.seg.common.Vertex.<init>(Vertex.java:99)
	at com.hankcs.hanlp.seg.common.Vertex.<init>(Vertex.java:91)
	at com.hankcs.hanlp.seg.common.Vertex.<init>(Vertex.java:196)
	at com.hankcs.hanlp.seg.Segment.combineWords(Segment.java:288)
	at com.hankcs.hanlp.seg.Segment.combineByCustomDictionary(Segment.java:221)
	at com.hankcs.hanlp.seg.Viterbi.ViterbiSegment.segSentence(ViterbiSegment.java:55)
	at com.hankcs.hanlp.seg.Segment.seg(Segment.java:466)
	at com.nlp.ner.Ner.main(Ner.java:29)

**Comment by hankcs** [comment]
警告已经说得一清二楚了，“谨遵医嘱”即可。
