### ISSUE TITLE
elasticsearch-analysis-hanlp添加自定义停用词影响了正常词汇的分词效果

### ISSUE THREAD

**Issue by yayawcx** [hankcs/HanLP#415]
我看这个插件，用的好像是hanlp的维特比算法进行分词的？
我修改了停用词库，删除了默认文件内容，添加了自己定义的几个词，为啥原来能分的词（不包含自定义停用词）加完这个之后就分不了了呢

**Comment by chenruiSundun** [comment]
请问一下，你集成成功了么。
在分词时报错：你遇到过么？
RemoteTransportException[[Spirit of '76][127.0.0.1:9300][indices:admin/analyze[s]]]; nested: NoClassDefFoundError[Could not initialize class com.hankcs.hanlp.seg.common.Vertex];
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.hankcs.hanlp.seg.common.Vertex
	at com.hankcs.hanlp.seg.common.WordNet.<init>(WordNet.java:71)
	at com.hankcs.hanlp.seg.Viterbi.ViterbiSegment.segSentence(ViterbiSegment.java:40)
	at com.hankcs.hanlp.seg.Segment.seg(Segment.java:558)
	at com.hankcs.lucene.SegmentWrapper.next(SegmentWrapper.java:76)
	at com.hankcs.lucene.HanLPTokenizer.incrementToken(HanLPTokenizer.java:67)
	at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.simpleAnalyze(TransportAnalyzeAction.java:247)
	at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.shardOperation(TransportAnalyzeAction.java:225)
	at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.shardOperation(TransportAnalyzeAction.java:63)
	at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$ShardTransportHandler.messageReceived(TransportSingleShardAction.java:282)
	at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$ShardTransportHandler.messageReceived(TransportSingleShardAction.java:275)
	at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:77)
	at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:378)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by hankcs** [comment]
这个插件不是我写的，所以我也不知道详情。但我也许可以提供一些帮助，只要你fork一份，用JUnit代码把你的问题复现出来，然后@我。
@chenruiSundun 很明显找不到hanlp的jar包。

**Comment by yayawcx** [comment]
@chenruiSundun 集成成功了的，es-hanlp插件要和ES版本对应上，本地编译es-hanlp插件把.zip包放到ES的plugin目录下解压，然后重启ES即可

**Comment by chenruiSundun** [comment]
两位大神，官方文档说 protable 版可以挂载自定义词典，按照以前的方法不能加载成功，请问怎样实现呢。

**Comment by yayawcx** [comment]
@chenruiSundun 你生成.bin了吗 我在本地把词库文件生成.bin, 再替换portable是可以的

**Comment by chenruiSundun** [comment]
你怎么替换的啊，

**Comment by hankcs** [comment]
zip解压缩jar包

**Comment by chenruiSundun** [comment]
两位大神，你们好之前一段时间忙别的去了，现在问题还没解决。能否给篇文档呢，谢谢

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
