### ISSUE TITLE
在集成elasticsearch 2.4.4 时 报错，Could not initialize class com.hankcs.hanlp.seg.common.Vertex

### ISSUE THREAD

**Issue by chenruiSundun** [hankcs/HanLP#422]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.hankcs.hanlp.seg.common.Vertex
	at com.hankcs.hanlp.seg.common.WordNet.<init>(WordNet.java:71)
	at com.hankcs.hanlp.seg.Viterbi.ViterbiSegment.segSentence(ViterbiSegment.java:40)
	at com.hankcs.hanlp.seg.Segment.seg(Segment.java:558)
	at com.hankcs.lucene.SegmentWrapper.next(SegmentWrapper.java:76)
	at com.hankcs.lucene.HanLPTokenizer.incrementToken(HanLPTokenizer.java:67)
	at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.simpleAnalyze(TransportAnalyzeAction.java:247)
	at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.shardOperation(TransportAnalyzeAction.java:225)
	at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.shardOperation(TransportAnalyzeAction.java:63)
	at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$ShardTransportHandler.messageReceived(TransportSingleShardAction.java:282)
	at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$ShardTransportHandler.messageReceived(TransportSingleShardAction.java:275)
	at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:77)
	at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:378)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by hankcs** [comment]
https://github.com/hankcs/HanLP/issues/309
