### ISSUE TITLE
索引分词缺少词

### ISSUE THREAD

**Issue by gxy0451** [hankcs/HanLP#519]
hi hankcs, 又遇到个问题想向你请教。
## 版本号
master分支
当前最新版本号是：221d2a9e152763afe77b6ffc966b570ee308fb6e
我使用的版本是：221d2a9e152763afe77b6ffc966b570ee308fb6e

## 我的问题
“评审委员会”的索引分词中带有“评审委员会”这个词，但是“商标评审委员会”的索引分词就没有“评审委员会”这个词。作为全切分的索引模式，我觉得对于“商标评审委员会”的切分应该将“评审委员会”也切出来。否则搜索"评审委员会"将会搜不到。

### 触发代码

```
        List<Term> termList = IndexTokenizer.segment("评审委员会");
        for (Term term : termList)
        {
            System.out.println(term + " [" + term.offset + ":" + (term.offset + term.word.length()) + "]");
        }
评审委员会/nt [0:5]
评审/vn [0:2]
委员会/nis [2:5]
委员/nnt [2:4]

        List<Term> termList2 = IndexTokenizer.segment("商标评审委员会");
        for (Term term : termList2)
        {
            System.out.println(term + " [" + term.offset + ":" + (term.offset + term.word.length()) + "]");
        }
商标评审委员会/nt [0:7]
商标/n [0:2]
评审/vn [2:4]
委员会/nis [4:7]
委员/nnt [4:6]

```

## 其他信息
我查看了一下，感觉应该是在“使用用户词典合并粗分结果”这个部分出的问题。在Segment.java的384行将已经合并的词置空了，然后在Segment.java的302行将循环变量直接跳过了已合并的几项，导致了“商标评审委员会”这个词提出来之后，没有再继续判断是否有“评审委员会”，所以合并完用户词典后，词图里面没有“评审委员会”这个词，后面的索引模式全切分方法decorateResultForIndexMode也没办法识别这个词。

同理，只要是用户词典中存在两个互相包含的词，就只有一个能出来，例如：
```
铁道部运输局营运部货运营销计划处/nt [0:16]
铁道部/nis [0:3]
铁道/n [0:2]
运输局/nis [3:6]
运输/vn [3:5]
营运部/nz [6:9]
营运/vn [6:8]
货运/n [9:11]
运营/vn [10:12]
营销/vn [11:13]
计划处/nis [13:16]
计划/n [13:15]

铁道部运输局/nto [0:6]
铁道部/nis [0:3]
铁道/n [0:2]
运输局/nis [3:6]
运输/vn [3:5]

```

我试着改了几行代码，但是直接就报数组越界了，所以还是来向你求助了。

**Comment by hankcs** [comment]
感谢建议，现在应该是完整的结果了：

```
评审委员会
评审委员会/nt [0:5]
评审委员/n [0:4]
评审/vn [0:2]
委员会/nis [2:5]
委员/nnt [2:4]

商标评审委员会
商标评审委员会/nt [0:7]
商标/n [0:2]
评审委员会/nt [2:7]
评审委员/n [2:6]
评审/vn [2:4]
委员会/nis [4:7]
委员/nnt [4:6]

铁道部运输局
铁道部运输局/nto [0:6]
铁道部/nis [0:3]
铁道/n [0:2]
运输局/nis [3:6]
运输/vn [3:5]

铁道部运输局营运部货运营销计划处
铁道部运输局营运部货运营销计划处/nt [0:16]
铁道部运输局/nto [0:6]
铁道部/nis [0:3]
铁道/n [0:2]
运输局/nis [3:6]
运输/vn [3:5]
营运部/nz [6:9]
营运/vn [6:8]
货运/n [9:11]
运营/vn [10:12]
营销/vn [11:13]
计划处/nis [13:16]
计划/n [13:15]
```

如果还有问题，欢迎重开issue。

**Comment by wallacexia** [comment]
@hankcs 我觉得还是有问题。
分词 `江苏路369号`
结果`[江苏路/nz, 江苏/ns, 369/m, 号/q]`,
我认为正确的应该有`路`这个字，
`[江苏路/nz, 江苏/ns, 路/n, 369/m, 号/q]`

当前我在使用solr检索时无法检索 `"江苏路"`，
但搜索 `江苏路`（无双引号）可以。

**Comment by gxy0451** [comment]
你索引的分词和搜索的分词方式一致么？如果使用全词匹配的方式搜索，那么需要索引和搜索时候的分词保持一致，要不都全切分，要不都最粗粒度切分。

**Comment by hankcs** [comment]
请自行设置颗粒度:com.hankcs.hanlp.seg.Segment#enableIndexMode(int)

**Comment by wallacexia** [comment]
@gxy0451 分词方式一致，tokenizer类均是`com.hankcs.lucene.HanLPTokenizerFactory`，分词是`HanLP.newSegment()`构建的`ViterbiSegment`。

@hankcs 这里设置`segment.enableIndexMode(1)` 遇到一个问题，
`segment.seg("江苏路369号兆丰世贸1楼");`
报错：
`
java.lang.ArrayIndexOutOfBoundsException: 150
	at com.hankcs.hanlp.seg.common.Vertex.compileRealWord(Vertex.java:106)
	at com.hankcs.hanlp.seg.common.Vertex.<init>(Vertex.java:90)
	at com.hankcs.hanlp.seg.common.Vertex.<init>(Vertex.java:82)
	at com.hankcs.hanlp.seg.common.Vertex.<init>(Vertex.java:189)
	at com.hankcs.hanlp.seg.Segment$1.hit(Segment.java:293)
	at com.hankcs.hanlp.seg.Segment$1.hit(Segment.java:1)
	at com.hankcs.hanlp.dictionary.CustomDictionary.parseText(CustomDictionary.java:517)
	at com.hankcs.hanlp.seg.Segment.combineByCustomDictionary(Segment.java:287)
	at com.hankcs.hanlp.seg.Viterbi.ViterbiSegment.segSentence(ViterbiSegment.java:56)
	at com.hankcs.hanlp.seg.Segment.seg(Segment.java:557)
	at com.hankcs.hanlp.seg.SegmentTest.testFactory(SegmentTest.java:125)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:255)
	at junit.framework.TestSuite.run(TestSuite.java:250)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:539)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:761)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:461)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:207)
`

上述的报错在`SegmentTest.testIssue193`中的一些字符串中没有报错，
却在我测试分词`江苏路369号兆丰世贸1楼`时报出来的。


这里另外向你请教一个solr搜索的问题：
之前提的问题，solr phrase query `"江苏路"`实际上经过查询分词变成 `江苏`+`路`词组合查询，
而在索引库里有词`江苏路`、`江苏`，（没有路）；
在我phrase query`"江苏路"`的时候应该能匹配到库中`江苏路`这个整词，但是没有。
所以想问问是不是我搜索的问题；如果是那么就没必要设置`enableIndexMode(1)`了，因为很多单字的词的确影响搜索效果。

**Comment by gxy0451** [comment]
@wallacexia  我说的是指如果索引是设置enableIndexMode（0）那么搜索时也要设置enableIndexMode（0），否则全词匹配搜索的话会有很大可能性搜不到。如果你索引设置0，搜索时设置1，那么索引和搜索时分词的方式不一致，如果使用短语搜索，就会出现你所说的搜不到的问题。

**Comment by wallacexia** [comment]
@gxy0451 我想我描述的不够清楚。
在使用solr时的插件`hanlp-lucene-plugin`，我没有修改源代码，配置项`enableIndexMode`是boolean，index时为true，search时为false。

之前提到的`segment. enableIndexMode(1)`是我在HanLP源码的SegmentTest测试用例上试的。

**Comment by gxy0451** [comment]
@wallacexia index时true，search为false，所以你全词匹配的时候搜不到。因为这个变量会导致分词方式不一致，短语搜索的时候会搜不到。如果想用短语搜索，你只能search也设置为true。但如果search时也设置为true，不用短语搜索的话，搜索结果就可能会有问题，会导致结果集变大。

**Comment by hankcs** [comment]
@wallacexia 

最新版本库是正常的，请确认：

```
        String[] testCase = new String[]{
            "江苏路369号兆丰世贸1楼",
        };
        Segment segment = HanLP.newSegment().enableOrganizationRecognize(true).enableNumberQuantifierRecognize(true).enableIndexMode(1);
        for (String sentence : testCase)
        {
            List<Term> termList = segment.seg(sentence);
        }
```
