### ISSUE TITLE
在自定义词库中增加一个词后，在某些特殊字符串分词时报错ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by panhaidong** [hankcs/HanLP#522]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

使用的Maven仓库：
    <dependency>
      <groupId>com.hankcs</groupId>
      <artifactId>hanlp</artifactId>
      <version>portable-1.3.2</version>
    </dependency>

JDK1.8.0_20
当前最新版本号是：portable-1.3.2
我使用的版本是：portable-1.3.2

## 我的问题
增加自定义词库之后，并开启人名识别，在某些文本的分词时会报错ArrayIndexOutOfBoundsException。

## 复现问题
自定义词典中增加一个词：
CustomDictionary.add("第一季", "n 1")

并不是所有的词都会触发这个Exception，后面的代码中是找到的一个。

### 步骤
执行下面的触发代码即可。

### 触发代码

```

import com.hankcs.hanlp.HanLP;
import com.hankcs.hanlp.dictionary.CustomDictionary;
import com.hankcs.hanlp.seg.Segment;
import com.hankcs.hanlp.seg.common.Term;


import java.util.List;

public class Main {
    public static void main(String[] args){
        CustomDictionary.add("第一季", "n 1");

        Segment seg = HanLP.newSegment().enableIndexMode(true)
                .enableNameRecognize(true)
                .enableNumberQuantifierRecognize(false)
                .enableCustomDictionary(true)
                .enableTranslatedNameRecognize(false)
                .enableJapaneseNameRecognize(false)
                .enableOrganizationRecognize(false)
                .enablePlaceRecognize(false);

        HanLP.Config.enableDebug();
        List<Term> termList = seg.seg("乘龙怪婿第一季");
        for (Term term : termList)
        {
            System.out.println(term + " [" + term.offset + ":" + (term.offset + term.word.length()) + "]");
        }
    }
}
```

### 实际输出
```
May 05, 2017 5:55:11 PM com.hankcs.hanlp.dictionary.CoreDictionary load
INFO: 核心词典开始加载:data/dictionary/CoreNatureDictionary.mini.txt
May 05, 2017 5:55:12 PM com.hankcs.hanlp.dictionary.CoreDictionary <clinit>
INFO: data/dictionary/CoreNatureDictionary.mini.txt加载成功，85585个词条，耗时232ms
粗分词网：
0:[ ]
1:[乘]
2:[龙]
3:[怪]
4:[婿]
5:[第, 第一]
6:[]
7:[季]
8:[ ]

May 05, 2017 5:55:12 PM com.hankcs.hanlp.dictionary.CoreBiGramTableDictionary <clinit>
INFO: 开始加载二元词典data/dictionary/CoreNatureDictionary.ngram.mini.txt.table
粗分结果[乘/v, 龙/n, 怪/a, 婿/ng, 第一季/n]
May 05, 2017 5:55:12 PM com.hankcs.hanlp.dictionary.CoreBiGramTableDictionary <clinit>
INFO: data/dictionary/CoreNatureDictionary.ngram.mini.txt.table加载成功，耗时136ms
May 05, 2017 5:55:12 PM com.hankcs.hanlp.dictionary.common.CommonDictionary load
INFO: 加载值data/dictionary/person/nr.txt.value.dat成功，耗时64ms
May 05, 2017 5:55:12 PM com.hankcs.hanlp.dictionary.common.CommonDictionary load
INFO: 加载键data/dictionary/person/nr.txt.trie.dat成功，耗时78ms
May 05, 2017 5:55:12 PM com.hankcs.hanlp.dictionary.nr.PersonDictionary <clinit>
INFO: data/dictionary/person/nr.txt加载成功，耗时274ms
人名角色观察：[  A 22202445 ][乘 K 15 C 7 L 5 E 1 M 1 ][龙 D 1350 E 924 B 498 C 325 L 17 M 8 K 1 ][怪 D 10 E 1 K 1 L 1 ][婿 E 2 K 1 ][第一季 K 1 U 1 ][  A 22202445 ]
人名角色标注：[ /A ,乘/K ,龙/B ,怪/E ,婿/E ,第一季/U , /A]
识别出人名：龙怪 BE
识别出人名：怪婿 EE
识别出人名：龙怪婿 BEE
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 9
	at com.hankcs.hanlp.seg.Viterbi.ViterbiSegment.viterbi(ViterbiSegment.java:142)
	at com.hankcs.hanlp.seg.Viterbi.ViterbiSegment.segSentence(ViterbiSegment.java:103)
	at com.hankcs.hanlp.seg.Segment.seg(Segment.java:558)
	at com.douban.solr.Main.main(Main.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

```

**Comment by hankcs** [comment]
感谢反馈，hanlp-portable-1.3.2.jar确认有这个bug，是由索引分词引起的。但GitHub仓库中的最新版 8e4cad08fd3889604156aa82cbff9d93a99538d1 采用了新的索引分词算法，已经消除了这个问题。经过试验，解决方法有

1. 编译使用版本库最新版
1. 暂时不使用enableIndexMode

近期将尽快发布1.3.3版本。

**Comment by hankcs** [comment]
如果还有问题，欢迎重开issue。
