### ISSUE TITLE
核心字典增加自定义词性

### ISSUE THREAD

**Issue by hx78** [hankcs/HanLP#545]
版本1.3.2
增加了一个称谓词性 ncw

        modified:   src/main/java/com/hankcs/hanlp/corpus/tag/Nature.java
        modified:   src/main/java/com/hankcs/hanlp/dependency/common/Node.java
        modified:   src/main/java/com/hankcs/hanlp/dependency/common/POSUtil.java
        modified:   src/main/java/com/hankcs/hanlp/dependency/nnparser/util/PosTagUtil.java

在上面的文件加入了ncw

在测试“外公”（外公 ncw 10)时出错

五月 25, 2017 11:16:40 上午 com.hankcs.hanlp.dictionary.CoreDictionaryTransformMatrixDictionary <clinit>
信息: 加载核心词典词性转移矩阵/C:/code/github/segmentation/src/main/resources/hanlp/data/dictionary/core/CoreNatureDictionary.tr.txt成功，耗时：60 ms
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 151
	at com.hankcs.hanlp.algoritm.Viterbi.compute(Viterbi.java:121)
	at com.hankcs.hanlp.seg.WordBasedGenerativeModelSegment.speechTagging(WordBasedGenerativeModelSegment.java:531)
	at com.hankcs.hanlp.seg.NShort.NShortSegment.segSentence(NShortSegment.java:133)
	at com.hankcs.hanlp.seg.Segment.segAndCheckNature(Segment.java:588)
	at com.hankcs.hanlp.seg.Segment.seg(Segment.java:566)
	at com.twsz.creative.seg.service.HanlpOriginalTest.main(HanlpOriginalTest.java:173)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

看着是转移矩阵出了错，CoreNatureDictionary.tr.txt没有ncw的相关信息，[训练分词模型](https://github.com/hankcs/HanLP/wiki/%E8%AE%AD%E7%BB%83%E5%88%86%E8%AF%8D%E6%A8%A1%E5%9E%8B) 中说到通过训练输出的这个文件，但我没有语料，无法训练。有什么别的办法可以处理吗？（不启用自定义字典条件下）

**Comment by hankcs** [comment]
建议通过com.hankcs.hanlp.corpus.util.CustomNatureUtility加，否则必须模拟该Utility的原理修改矩阵维度等。
