### ISSUE TITLE
关于版权问题

### ISSUE THREAD

**Issue by Tony-Wang** [hankcs/HanLP#62]
hankcs，你好。
之前我一直使用python+jpype的方式，使用你的HanLP。我的工作中所有的代码全部是基于python开发，并且考虑以后要在hadoop平台上使用。所以我用python实现了一个HanLP的子集。等成熟后也希望放到github上。python版本直接使用了data目录下的数据文件，希望可以得到你的授权。根据你的要求，我会在项目首页注明字典数据的来源，以及python版本与HanLP的关系。

**Comment by hankcs** [comment]
Tony-Wang，你好

没问题，本来就是Apache授权，能注明项目主页 https://github.com/hankcs/HanLP 就更好了。
感谢你的辛勤工作，我非常期待看到你的开源项目。

**Comment by Tony-Wang** [comment]
你好，今天发布了原始版本，持续发布中。没有测试你的最新字典里做了哪些改变，仍然使用1.2.4的字典
https://github.com/Tony-Wang/YaYaNLP

**Comment by hankcs** [comment]
感谢你的开源工作，这很有可能成为一个流行的Pure Python NLP包。
新版词典并没有实质性的变化，只调整了少数词条，格式维持不变，可以放心使用。

**Comment by jesuisluc** [comment]
你好 我使用yayanlp 加载数据1.2.4 老是无法初始化 请问应该怎么解决啊 谢谢

**Comment by jesuisluc** [comment]
你好 我使用yayanlp 加载hanlp数据1.2.4 老是无法初始化 请问应该怎么解决啊 谢谢。 python 是2.7.10. IDE winpython 。 现在在Windows下，路径没有问题 
![image](https://cloud.githubusercontent.com/assets/16183064/11617990/53f6df86-9cd0-11e5-8ec3-3b6f1c104565.png)

**Comment by jesuisluc** [comment]
你好 我使用yayanlp 加载hanlp数据1.2.4 老是无法初始化 请问应该怎么解决啊 谢谢。 python 是2.7.10. IDE winpython 。 现在在Windows下，路径没有问题。 数据文件夹和在源代码在一起

runfile('D:/pyworkplace/yaya/yayanlp.py', wdir='D:/pyworkplace/yaya')
Traceback (most recent call last):

  File "<ipython-input-2-68c11395b86b>", line 1, in <module>
    runfile('D:/pyworkplace/yaya/yayanlp.py', wdir='D:/pyworkplace/yaya')

  File "D:\Program Files (x86)\WinPython-64bit-2.7.10.2\python-2.7.10.amd64\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 685, in runfile
    execfile(filename, namespace)

  File "D:\Program Files (x86)\WinPython-64bit-2.7.10.2\python-2.7.10.amd64\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 71, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)

  File "D:/pyworkplace/yaya/yayanlp.py", line 4, in <module>
    from yaya.seg import segment

  File "D:\Program Files (x86)\WinPython-64bit-2.7.10.2\python-2.7.10.amd64\lib\site-packages\yayanlp-0.1.1-py2.7.egg\yaya\seg\segment.py", line 2, in <module>
    from yaya.collection.dict import CustomDict

  File "D:\Program Files (x86)\WinPython-64bit-2.7.10.2\python-2.7.10.amd64\lib\site-packages\yayanlp-0.1.1-py2.7.egg\yaya\collection\dict.py", line 483, in <module>
    PERSON_WORD_ID, PERSON_ATTRIBUTE = __split_id_attribute(CoreDict().trie.get(TAG_PEOPLE))

  File "D:\Program Files (x86)\WinPython-64bit-2.7.10.2\python-2.7.10.amd64\lib\site-packages\yayanlp-0.1.1-py2.7.egg\yaya\utility\singleton.py", line 9, in get_instance
    instances[class_] = class_(*args, **kwargs)

  File "D:\Program Files (x86)\WinPython-64bit-2.7.10.2\python-2.7.10.amd64\lib\site-packages\yayanlp-0.1.1-py2.7.egg\yaya\collection\dict.py", line 470, in __init__
    self.trie = DoubleArrayTrie.load(config.CORE_DICT_NAME)

  File "D:\Program Files (x86)\WinPython-64bit-2.7.10.2\python-2.7.10.amd64\lib\site-packages\yayanlp-0.1.1-py2.7.egg\yaya\collection\dict.py", line 322, in load
    return DoubleArrayTrie.load_bin(filename + dict_bin_ext)

  File "D:\Program Files (x86)\WinPython-64bit-2.7.10.2\python-2.7.10.amd64\lib\site-packages\yayanlp-0.1.1-py2.7.egg\yaya\collection\dict.py", line 284, in load_bin
    trie = Pickle.load(f)

EOFError

**Comment by hankcs** [comment]
我也遇到类似的加载问题，麻烦@Tony-Wang 帮忙看看。

首次加载

```
Traceback (most recent call last):
  File "/YaYaNLP/demo/demo_segment.py", line 33, in <module>
    main()
  File "/YaYaNLP/demo/demo_segment.py", line 15, in main
    terms = segment.seg(text)
  File "\YaYaNLP\yaya\seg\segment.py", line 49, in seg
    word_net = WordNet(text)
  File "\YaYaNLP\yaya\seg\wordnet.py", line 194, in __init__
    self.vertexs[0] = [new_tag_vertex(TAG_BIGIN)]
  File "\YaYaNLP\yaya\seg\wordnet.py", line 251, in new_tag_vertex
    vertex = Vertex(chr(32), attribute=attribute[1:], word=tag, word_id=word_id)
  File "\YaYaNLP\yaya\seg\wordnet.py", line 28, in __init__
    self.attribute = attribute if isinstance(attribute, Attribute) else Attribute(attribute)
  File "\YaYaNLP\yaya\collection\dict.py", line 26, in __init__
    self._nature[cls[self.attr[i]]] = int(self.attr[i + 1])
IndexError: list index out of range
```

调试了一下，发现是 始##始	begin	2324388 这个词条导致了下标越界，特别地，这个词条被分割为始|##始|begin|2324388。

之后加载

```
Traceback (most recent call last):
  File "/YaYaNLP/demo/demo_segment.py", line 2, in <module>
    from yaya.seg import segment
  File "\YaYaNLP\yaya\seg\segment.py", line 2, in <module>
    from yaya.collection.dict import CustomDict
  File "\YaYaNLP\yaya\collection\dict.py", line 483, in <module>
    PERSON_WORD_ID, PERSON_ATTRIBUTE = __split_id_attribute(CoreDict().trie.get(TAG_PEOPLE))
  File "\YaYaNLP\yaya\utility\singleton.py", line 9, in get_instance
    instances[class_] = class_(*args, **kwargs)
  File "\YaYaNLP\yaya\collection\dict.py", line 470, in __init__
    self.trie = DoubleArrayTrie.load(config.CORE_DICT_NAME)
  File "\YaYaNLP\yaya\collection\dict.py", line 322, in load
    return DoubleArrayTrie.load_bin(filename + dict_bin_ext)
  File "\YaYaNLP\yaya\collection\dict.py", line 284, in load_bin
    trie = Pickle.load(f)
EOFError
```

**Comment by Tony-Wang** [comment]
这里我犯了一个错误，为了缩小ya字典的大小，我写了一个野蛮的算法。目前的版本应该没有问题了。需要清理一下已经生成的ya文件。

**Comment by arthurtalkgoal** [comment]
我也是為了Hadoop 的應用而走到這裡。我一直關注nltk + hadoop. 但HanLP 太贊了。省卻我很多時間，還有一大群中文文本高手。

@Tony-Wang , 請問在Hadoop 運作HanLP 有困難嗎？我想把HanLP  連在 hdfs 去運作。 yayalp 能直接連hdfs 嗎？

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
