### ISSUE TITLE
运行Demo中的DemoCustomNature.java出现NoSuchMethodError错误

### ISSUE THREAD

**Issue by mengyingzhou** [hankcs/HanLP#656]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [ √] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：jar包-1.3.4
我使用的版本是：jar包-1.3.4

## 我的问题
您好！
我在运行demo中的DemoCustomNature.java时，出现了在下面“实际输出”中的报错。
操作系统是archlinux，java版本1.9和1.8都尝试过，均出现报错。
参考过[#279](!https://github.com/hankcs/HanLP/issues/279#ref-issue-170997234)的问题，但是无法解决。
请问如何才能正常运行代码？谢谢！

## 复现问题
直接运行了demo

### 触发代码
demo代码中的DemoCustomNature.java

### 实际输出

```
n
null
10月 22, 2017 11:08:47 上午 com.hankcs.hanlp.corpus.util.CustomNatureUtility <clinit>
警告: 已激活自定义词性功能,由于采用了反射技术,用户需对本地环境的兼容性和稳定性负责!
如果用户代码X.java中有switch(nature)语句,需要调用CustomNatureUtility.registerSwitchClass(X.class)注册X这个类
Exception in thread "main" java.lang.NoSuchMethodError: sun.reflect.ReflectionFactory.newConstructorAccessor(Ljava/lang/reflect/Constructor;)Lsun/reflect/ConstructorAccessor;
	at com.hankcs.hanlp.corpus.util.EnumBuster.findConstructorAccessor(EnumBuster.java:255)
	at com.hankcs.hanlp.corpus.util.EnumBuster.make(EnumBuster.java:92)
	at com.hankcs.hanlp.corpus.util.EnumBuster.make(EnumBuster.java:68)
	at com.hankcs.hanlp.corpus.util.CustomNatureUtility.addNature(CustomNatureUtility.java:58)
	at com.hankcs.hanlp.corpus.tag.Nature.create(Nature.java:829)
	at demo.DemoCustomNature.main(DemoCustomNature.java:41)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)

```

**Comment by hankcs** [comment]
需要你针对自己的平台或jdk（似乎是openjdk）debug，看上去是openjdk里面没有sun的反射接口。

**Comment by NullAerber** [comment]
可是我装的是oracle的jdk，主要还是需要自己debug是吗？

**Comment by hankcs** [comment]
反射是平台相关的，由于我并没有你的环境，所以无法复现问题。看上去是该jdk里没有这个接口，你不妨找找这个接口或类似的接口，然后按http://www.hankcs.com/program/java/enum-java-examples-of-dynamic-modification.html 的原理debug。如果解决了，欢迎提交pr。

**Comment by NullAerber** [comment]
好的，感谢

**Comment by yaoleo** [comment]
同样的问题 请问解决了吗

**Comment by NullAerber** [comment]
@yaoleo 
我后来排除的结果是，当时我系统里面有openJDK1.8，Oracle1.8，Oracle1.9，后来我把除了Oracle1.8都删掉了，重新配置了Oracle1.8的jdk，idea从2017.3装回2017.2就可以用了。
我觉得可能最有可能的是jdk环境出了问题。

**Comment by yaoleo** [comment]
@NullAerber 
嗯 是jdk的问题 非常感谢

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
