### ISSUE TITLE
添加用户自定义词后报viterbi数组越界

### ISSUE THREAD

**Issue by nedved1990** [hankcs/HanLP#674]
Hi：
我在分词的时候遇到了添加用户自定义词后报viterbi数组越界的问题，麻烦帮忙看下。
报错信息：
**java.lang.ArrayIndexOutOfBoundsException: 72
	at com.hankcs.hanlp.seg.Viterbi.ViterbiSegment.viterbi(ViterbiSegment.java:154)
	at com.hankcs.hanlp.seg.Viterbi.ViterbiSegment.segSentence(ViterbiSegment.java:103)
	at com.hankcs.hanlp.seg.Segment.seg(Segment.java:521)
	at com.hankcs.hanlp.tokenizer.NotionalTokenizer.segment(NotionalTokenizer.java:48)
	at com.hankcs.hanlp.tokenizer.NotionalTokenizer.segment(NotionalTokenizer.java:37)
	at com.mig.ml.mlplatform.segment$$anonfun$2.apply(segment.scala:398)
	at com.mig.ml.mlplatform.segment$$anonfun$2.apply(segment.scala:341)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:785)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:785)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:283)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:283)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:70)
	at org.apache.spark.scheduler.Task.run(Task.scala:86)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)**

触发版本：master分支最新版**1.5.0**
触发代码：
```
 public static String readFile(String filePath) throws IOException {
        StringBuffer sb = new StringBuffer();
        fileUtils.readToBuffer(sb, filePath);
        return sb.toString();
    }
public static void readToBuffer(StringBuffer buffer, String filePath) throws IOException {
        InputStream is = new FileInputStream(filePath);
        String line; // 用来保存每行读取的内容
        BufferedReader reader = new BufferedReader(new InputStreamReader(is));
        line = reader.readLine(); // 读取第一行
        while (line != null) { // 如果 line 为空说明读完了
            buffer.append(line); // 将读到的内容添加到 buffer 中
            buffer.append("\n"); // 添加换行符
            line = reader.readLine(); // 读取下一行
        }
        reader.close();
        is.close();
    }

     try {
            String dic_word = readFile("d:\\dic_word");
            String[] split_dic_word = dic_word.split("\n");
            for(String sp: split_dic_word){
                CustomDictionary.add(sp);
            }

        } catch (IOException e) {
            e.printStackTrace();
        }

        System.out.println(NotionalTokenizer.segment("【仁创】倒计时1天 武汉糖酒会在汉口武展明天盛大开幕，您准备好了吗？找产品、了解市场，高规格行业活动等你来，不容错过18171482672黄"));
```

词库dic_word文件如下：

**Comment by nedved1990** [comment]
[dic_word.zip](https://github.com/hankcs/HanLP/files/1469872/dic_word.zip)

**Comment by nedved1990** [comment]
@hankcs

**Comment by nedved1990** [comment]
@hankcs 
初步定位一下问题，把最后一句“不容错过18171482672黄”的“黄”字去掉就不报错了。
求问下怎么解决这种问题？

**Comment by hankcs** [comment]
https://github.com/hankcs/HanLP/commit/e50be032dcad637223e4e662f3c8c44fbb16939c
词条中空格要trim一下，或者用配置文件直接挂载。
下次发issue请严格按模板填写，勾选注意事项，谢谢合作。
