### ISSUE TITLE
lucene-core-7.0.1与hanlp1.52 hanlp-index存在分词兼容问题

### ISSUE THREAD

**Issue by xchechi123x** [hankcs/HanLP#705]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.52
我使用的版本是：1.52

## 我的问题
通过hanlp-ext 编译整合进elasticsearch6.0 做文档类型的分词映射，映射的分词是hanlp-index
elasticsearch6.0 文档映射部分代码如下
```
PUT test_2017_11_12 
{
    "mappings":
    {
        "meal":
        {
            "properties":
            {
                "city":
                {
                    "type": "text",
                    "fields":
                    {
                        "keyword":
                        {
                            "type": "keyword",
                            "ignore_above": 32
                        }
                    }
                },
                "name":
                {
                    "type": "text",
                    "analyzer": ""hanlp-index",
                    "fields":
                    {
                        "keyword":
                        {
                            "type": "keyword",
                            "ignore_above": 256
                        }
                    }
                },
                "address":
                {
                    "type": "text",
                    "analyzer": "hanlp-index",
                    "fields":
                    {
                        "keyword":
                        {
                            "type": "keyword",
                            "ignore_above": 512
                        }
                    }
                },
                "tags":
                {
                    "type": "text",
                    "analyzer": ""hanlp-index",
                    "fields":
                    {
                        "keyword":
                        {
                            "type": "keyword",
                            "ignore_above": 256
                        }
                    }
                },
                "price":
                {
                    "type": "float"
                },
                "phone":
                {
                    "type": "text",
                    "fields":
                    {
                        "keyword":
                        {
                            "type": "keyword",
                            "ignore_above": 32
                        }
                    }

                },
                "images":
                {
                    "type": "text",
                    "index": false
                },
                "recommendations":
                {
                    "type": "text",
                    "analyzer": ""hanlp-index"
                },
                "facilities":
                {
                    "type": "text",
                    "fields":
                    {
                        "keyword":
                        {
                            "type": "keyword",
                            "ignore_above": 128
                        }
                    }
                },
                "uriSign":
                {
                    "type": "text",
                    "index": false
                },
                "uri":
                {
                    "type": "text",
                    "index": false
                },
                "createTime":
                {
                    "type": "date",
                    "format": "epoch_millis"
                },
                "updateTime":
                {
                    "type": "date",
                    "format": "epoch_millis"
                },
                "syncTime": 
                {
                    "type": "date",
                    "format": "epoch_millis"
                }
            }
        }
    }
}
```
通过google搜索相关资料显示是hanlp-index 分词的方式与lucene-core-7.0.1存在兼容问题
DefaultIndexingChain.java:767  lucene 默认的索处理链文件
java.lang.IllegalArgumentException: startOffset must be non-negative, and endOffset must be >= startOffset, and offsets must not go backwards startOffset=1,endOffset=3,lastStartOffset=9 for field 'recommendations'
这是针对elasticsearch文档映射的字段

报错的Java错误堆栈信息如下
```
java.lang.IllegalArgumentException: startOffset must be non-negative, and endOffset must be >= startOffset, and offsets must not go backwards startOffset=1,endOffset=3,lastStartOffset=9 for field 'recommendations'
	at org.apache.lucene.index.DefaultIndexingChain$PerField.invert(DefaultIndexingChain.java:767) ~[lucene-core-7.0.1.jar:7.0.1 8d6c3889aa543954424d8ac1dbb3f03bf207140b - sarowe - 2017-10-02 14:36:35]
	at org.apache.lucene.index.DefaultIndexingChain.processField(DefaultIndexingChain.java:430) ~[lucene-core-7.0.1.jar:7.0.1 8d6c3889aa543954424d8ac1dbb3f03bf207140b - sarowe - 2017-10-02 14:36:35]
	at org.apache.lucene.index.DefaultIndexingChain.processDocument(DefaultIndexingChain.java:392) ~[lucene-core-7.0.1.jar:7.0.1 8d6c3889aa543954424d8ac1dbb3f03bf207140b - sarowe - 2017-10-02 14:36:35]
	at org.apache.lucene.index.DocumentsWriterPerThread.updateDocument(DocumentsWriterPerThread.java:239) ~[lucene-core-7.0.1.jar:7.0.1 8d6c3889aa543954424d8ac1dbb3f03bf207140b - sarowe - 2017-10-02 14:36:35]
	at org.apache.lucene.index.DocumentsWriter.updateDocument(DocumentsWriter.java:481) ~[lucene-core-7.0.1.jar:7.0.1 8d6c3889aa543954424d8ac1dbb3f03bf207140b - sarowe - 2017-10-02 14:36:35]
	at org.apache.lucene.index.IndexWriter.updateDocument(IndexWriter.java:1717) ~[lucene-core-7.0.1.jar:7.0.1 8d6c3889aa543954424d8ac1dbb3f03bf207140b - sarowe - 2017-10-02 14:36:35]
	at org.apache.lucene.index.IndexWriter.addDocument(IndexWriter.java:1462) ~[lucene-core-7.0.1.jar:7.0.1 8d6c3889aa543954424d8ac1dbb3f03bf207140b - sarowe - 2017-10-02 14:36:35]
```

### 步骤

1. 首先建立elasticsearch 文档映射
2. 然后通过elasticsearch存储文reset文档接口存储文档
3. 接着elasticsearch日志报错，错误堆栈已经写在文档上，见上文

### 触发代码

```
 PUT test_2017_11_12/meal/5a098a920f3f766cdebf4767
{ 
    "city" : "长沙", 
    "name" : "盟重烧烤", 
    "address" : "冬瓜山裕南街85号", 
    "tags" : [
        "书院路", 
        "其它"
    ], 
    "priceText" : "68/人", 
    "price" : 68, 
    "phone" : "15116157770", 
    "images" : [
        "http://test.com/host/2017/07/30/1501392633001415.jpg-ssq75"
    ], 
    "recommendations" : [
        "星城最正宗的湘西味烤串", 
        "主打牛油由湘西直接供货", 
        "时尚潮人聚集的深夜食堂"
    ], 
    "facilities" : [
        "Wi-Fi", 
        "适合小聚"
    ], 
    "uriSign" : "cd5fb379260756ae50ac9ceb1c2e2331", 
    "uri" : "http://test/hotel/203381", 
    "syncTime" : 1510669453830, 
    "createTime" :1510584054604, 
    "updateTime" : 1510584054604
}

```
### 期望输出

```
期望输出
```

### 实际输出

```
实际输出
```

**Comment by xchechi123x** [comment]
文档的映射分词类型修改为hanlp不会有上述问题出现。

**Comment by xchechi123x** [comment]
通过kiaban6.0 的分词请求
```
GET /_analyze?pretty
{
  "analyzer" : "hanlp-index",
  "text" :  [
        "星城最正宗的湘西味烤串", 
        "主打牛油由湘西直接供货", 
        "时尚潮人聚集的深夜食堂"
    ]
}

CURL 代码
curl -X POST \
  'http://localhost:9200/_analyze?pretty=' \
  -H 'Cache-Control: no-cache' \
  -H 'Content-Type: application/json' \
  -H 'Postman-Token: 9a56b55e-118b-41df-4e7d-64051946a9e4' \
  -d '{
  "analyzer" : "hanlp-index",
  "text" :  [
        "星城最正宗的湘西味烤串", 
        "主打牛油由湘西直接供货", 
        "时尚潮人聚集的深夜食堂"
    ]
}'

请求结果
{
    "tokens": [
        {
            "token": "星城",
            "start_offset": 0,
            "end_offset": 2,
            "type": "nz",
            "position": 0
        },
        {
            "token": "最",
            "start_offset": 2,
            "end_offset": 3,
            "type": "d",
            "position": 1
        },
        {
            "token": "正宗",
            "start_offset": 3,
            "end_offset": 5,
            "type": "b",
            "position": 2
        },
        {
            "token": "的",
            "start_offset": 5,
            "end_offset": 6,
            "type": "ude1",
            "position": 3
        },
        {
            "token": "湘西",
            "start_offset": 6,
            "end_offset": 8,
            "type": "ns",
            "position": 4
        },
        {
            "token": "味",
            "start_offset": 8,
            "end_offset": 9,
            "type": "ng",
            "position": 5
        },
        {
            "token": "烤串",
            "start_offset": 9,
            "end_offset": 11,
            "type": "nz",
            "position": 6
        },
        {
            "token": "主打",
            "start_offset": 1,
            "end_offset": 3,
            "type": "v",
            "position": 7
        },
        {
            "token": "牛油",
            "start_offset": 3,
            "end_offset": 5,
            "type": "nf",
            "position": 8
        },
        {
            "token": "由",
            "start_offset": 5,
            "end_offset": 6,
            "type": "p",
            "position": 9
        },
        {
            "token": "湘西",
            "start_offset": 6,
            "end_offset": 8,
            "type": "ns",
            "position": 10
        },
        {
            "token": "直接",
            "start_offset": 8,
            "end_offset": 10,
            "type": "ad",
            "position": 11
        },
        {
            "token": "供货",
            "start_offset": 10,
            "end_offset": 12,
            "type": "vn",
            "position": 12
        },
        {
            "token": "时尚",
            "start_offset": 2,
            "end_offset": 4,
            "type": "n",
            "position": 13
        },
        {
            "token": "潮人",
            "start_offset": 4,
            "end_offset": 6,
            "type": "nz",
            "position": 14
        },
        {
            "token": "聚集",
            "start_offset": 6,
            "end_offset": 8,
            "type": "v",
            "position": 15
        },
        {
            "token": "的",
            "start_offset": 8,
            "end_offset": 9,
            "type": "ude1",
            "position": 16
        },
        {
            "token": "深夜",
            "start_offset": 9,
            "end_offset": 11,
            "type": "t",
            "position": 17
        },
        {
            "token": "食堂",
            "start_offset": 11,
            "end_offset": 13,
            "type": "n",
            "position": 18
        }
    ]
}
```

**Comment by hankcs** [comment]
不好意思，hanlp-ext并不是我写的，所以我也不知道详情。建议向hanlp-ext的维护者提供反馈，如有需要可以艾特我参与讨论。

另，我维护了一个 https://github.com/hankcs/hanlp-lucene-plugin ，应该可以兼容elasticsearch，欢迎测试。

**Comment by xchechi123x** [comment]
看了一下 hanlp-ext 的实现代码,直接调用了hanlp的分词方法.
startOffset must be non-negative, and endOffset must be >= startOffset, and offsets must not go backwards startOffset=1,endOffset=3,lastStartOffset=9 for field 'recommendations' 异常的提示
是分词之后不能满足 lucene-core-7.0.1 的分词要求,您写的hanlp-lucene-plugin如果基于lucene-core-7.0.1也会出现这样的问题

**Comment by xchechi123x** [comment]
lucene-core-7.0.1, endOffset must be >= startOffset 经过hanlp分词之后 结束的偏移量 大于起始的偏移量,所以lucene-core-7.0.1报了错误.是不是hanlp1.5.2 分词的时候偏移量出现什么问题?

**Comment by xchechi123x** [comment]
```
 "recommendations" : [
        "星城最正宗的湘西味烤串", 
        "主打牛油由湘西直接供货", 
        "时尚潮人聚集的深夜食堂"
    ]
``` 
这是要分词的数据

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
