### ISSUE TITLE
报错：enableNumberQuantifierRecognize 和 enableAllNamedEntityRecognize 同时用, 版本1.2.4

### ISSUE THREAD

**Issue by jkl5515** [hankcs/HanLP#71]
Segment segment = HanLP.newSegment();
segment = segment.enableAllNamedEntityRecognize(true);
segment = segment.enableNumberQuantifierRecognize(true);
System.out.println(segment.seg("曾幻想过，若干年后的我就是这个样子的吗"));

Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 21
	at com.hankcs.hanlp.seg.common.WordNet.add(WordNet.java:101)
	at com.hankcs.hanlp.seg.common.WordNet.addAll(WordNet.java:201)
	at com.hankcs.hanlp.seg.Viterbi.ViterbiSegment.segSentence(ViterbiSegment.java:95)
	at com.hankcs.hanlp.seg.Segment.seg(Segment.java:420)
	at hanlpdemo.HanlpDemo.main(HanlpDemo.java:41)

**Comment by hankcs** [comment]
感谢反馈，这个问题是因为二次维特比没有清空前向节点的引用所致。目前采取了迂回但是更高效的“清空”方式解决了问题。

欢迎继续提出宝贵意见。

**Comment by hankcs** [comment]
这个问题应该解决了，如果还有问题，欢迎再开issue。

**Comment by jkl5515** [comment]
谢谢。用1.2.5版本就好了吗？

**Comment by hankcs** [comment]
1.2.5是老版本，今天刚修复的问题还没打包，你可以自行打一个。
