### ISSUE TITLE
训练最新中文wiki问题

### ISSUE THREAD

**Issue by zhengzhuangjie** [hankcs/HanLP#718]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.5.2
我使用的版本是：1.5.2

## 我的问题

训练最新的zh wiki抛出数组越界异常
## 复现问题

[hadoop@LOCAL-202-89 new]$ java -cp hanlp-portable-1.5.2.jar com.hankcs.hanlp.mining.word2vec.Train -input zhwiki-latest-pages-articles.xml.simplified -output zhwiki.txt

Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: -3
	at com.hankcs.hanlp.mining.word2vec.TextFileCorpus.reduceVocab(TextFileCorpus.java:69)
	at com.hankcs.hanlp.mining.word2vec.TextFileCorpus.learnVocab(TextFileCorpus.java:142)
	at com.hankcs.hanlp.mining.word2vec.Word2VecTraining.trainModel(Word2VecTraining.java:326)
	at com.hankcs.hanlp.mining.word2vec.Train.execute(Train.java:33)
	at com.hankcs.hanlp.mining.word2vec.Train.main(Train.java:38)

**Comment by hankcs** [comment]
感谢反馈，已经修复，请参考上面的commit。
如果还有问题，欢迎重开issue。
