### ISSUE TITLE
在Android上使用外挂字典遇到sun.reflect.ReflectionFactory类找不到的问题

### ISSUE THREAD

**Issue by junjunxia** [hankcs/HanLP#736]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：portable-1.5.3
我使用的版本是：portable-1.3.5

## 我的问题
在Android使用hanlp.properties配置外挂字典时，遇到问题：
01-04 21:49:47.031 1196-2513/com.nio.nlu W/HanLP: 已激活自定义词性功能,由于采用了反射技术,用户需对本地环境的兼容性和稳定性负责!
                                                  如果用户代码X.java中有switch(nature)语句,需要调用CustomNatureUtility.registerSwitchClass(X.class)注册X这个类
                                                  
                                                  --------- beginning of crash
01-04 21:49:47.033 1196-2513/com.nio.nlu E/AndroidRuntime: FATAL EXCEPTION: Thread-66
                                                           Process: com.nio.nlu, PID: 1196
                                                           Theme: themes:{}
                                                           java.lang.NoClassDefFoundError: Failed resolution of: Lsun/reflect/ReflectionFactory;
                                                               at com.hankcs.hanlp.corpus.util.EnumBuster.<init>(EnumBuster.java:34)
                                                               at com.hankcs.hanlp.corpus.util.CustomNatureUtility.<clinit>(CustomNatureUtility.java:43)
                                                               at com.hankcs.hanlp.corpus.tag.Nature.create(Nature.java:838)
                                                               at com.hankcs.hanlp.dictionary.CustomDictionary.loadDat(CustomDictionary.java:306)
                                                               at com.hankcs.hanlp.dictionary.CustomDictionary.loadMainDictionary(CustomDictionary.java:63)
                                                               at com.hankcs.hanlp.dictionary.CustomDictionary.<clinit>(CustomDictionary.java:50)
                                                               at com.hankcs.hanlp.seg.Segment.combineByCustomDictionary(Segment.java:202)
                                                               at com.hankcs.hanlp.seg.Viterbi.ViterbiSegment.segSentence(ViterbiSegment.java:57)
                                                               at com.hankcs.hanlp.seg.Segment.seg(Segment.java:505)
                                                               at com.nextev.nlu.segment.Segmentation.tokenizationPropertyList(Segmentation.java:561)
                                                               at com.nio.nlu.service.NluService.initSegmentTool(NluService.java:105)
                                                               at com.nio.nlu.service.NluService.-wrap0(NluService.java)
                                                               at com.nio.nlu.service.NluService$1.run(NluService.java:95)
                                                               at java.lang.Thread.run(Thread.java:818)
                                                            Caused by: java.lang.ClassNotFoundException: Didn't find class "sun.reflect.ReflectionFactory" on path: DexPathList[[zip file "/system/app/NluService/NluService.apk"],nativeLibraryDirectories=[/system/app/NluService/lib/arm, /system/app/NluService/NluService.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
                                                               at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                               at com.hankcs.hanlp.corpus.util.EnumBuster.<init>(EnumBuster.java:34) 
                                                               at com.hankcs.hanlp.corpus.util.CustomNatureUtility.<clinit>(CustomNatureUtility.java:43) 
                                                               at com.hankcs.hanlp.corpus.tag.Nature.create(Nature.java:838) 
                                                               at com.hankcs.hanlp.dictionary.CustomDictionary.loadDat(CustomDictionary.java:306) 
                                                               at com.hankcs.hanlp.dictionary.CustomDictionary.loadMainDictionary(CustomDictionary.java:63) 
                                                               at com.hankcs.hanlp.dictionary.CustomDictionary.<clinit>(CustomDictionary.java:50) 
                                                               at com.hankcs.hanlp.seg.Segment.combineByCustomDictionary(Segment.java:202) 
                                                               at com.hankcs.hanlp.seg.Viterbi.ViterbiSegment.segSentence(ViterbiSegment.java:57) 
                                                               at com.hankcs.hanlp.seg.Segment.seg(Segment.java:505) 
                                                               at com.nextev.nlu.segment.Segmentation.tokenizationPropertyList(Segmentation.java:561) 
                                                               at com.nio.nlu.service.NluService.initSegmentTool(NluService.java:105) 
                                                               at com.nio.nlu.service.NluService.-wrap0(NluService.java) 
                                                               at com.nio.nlu.service.NluService$1.run(NluService.java:95) 
                                                               at java.lang.Thread.run(Thread.java:818) 
                                                           	Suppressed: java.lang.ClassNotFoundException: sun.reflect.ReflectionFactory
                                                               at java.lang.Class.classForName(Native Method)
                                                               at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                               at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                               		... 15 more
                                                            Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

## 其他信息
是否是Android的java平台平台本身就不包含这个类，是否可以用java.lang.reflect替代sun.reflect？

**Comment by hankcs** [comment]
应该是的，但java.lang里面没有ReflectionFactory。
你一定要用自定义词性吗？https://github.com/hankcs/HanLP/wiki/FAQ#%E4%B8%BA%E4%BB%80%E4%B9%88%E8%87%AA%E5%AE%9A%E4%B9%89%E8%AF%8D%E5%85%B8%E5%8A%A0%E8%BD%BD%E5%A4%B1%E8%B4%A5

**Comment by junjunxia** [comment]
@hankcs 恩，是的，需要用到自定义词性，其实现在sun.*的package使用的好像蛮少了，不知道是否可以考虑使用java.lang.reflect来实现现在的功能？

**Comment by newlandlty** [comment]
complie com.github.panga:java-beans-lite:1.0.1

java-beans相关的类整体替换成这个包

**Comment by hankcs** [comment]
Dear All，自v1.6.5开始不再使用反射了，应该跨平台稳定。

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
