### ISSUE TITLE
分词问题：自定义词典有时会失效

### ISSUE THREAD

**Issue by kjdongzh** [hankcs/HanLP#739]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：hanlp-portable-1.5.3
我使用的版本是：hanlp-portable-1.3.2

## 我的问题

自定义词典在某种情况下会失效，对“海南省海口市龙华区春来早市场”进行分词，结果正常，但是增加一个方位词内字之后会出现分词异常的情况

## 复现问题
我自定义的词典：
```
海南省 dictrict1 1000
海口市 dictrict2 1000
龙华区 dictrict3 1000
春来早市场 resrge 1000
```
```
   List<Term> termList = HanLP.segment("海南省海口市龙华区春来早市场");
    //分词结果：海南省/dictrict1, 海口市/dictrict2, 龙华区/dictrict3, 春来早市场/resrge
```
此时说明 “春来早市场”是正确加载的了

### 触发代码

```
   List<Term> termList = HanLP.segment("海南省海口市龙华区春来早市场内");
```
### 期望输出

```
海南省/dictrict1, 海口市/dictrict2, 龙华区/dictrict3, 春来早市场/resrge, 内/s
```

### 实际输出

```
海南省/dictrict1, 海口市/dictrict2, 龙华区/dictrict3, 春/tg, 来/v, 早市/n, 场内/s
```
增加了“内”字，重新分词，发现分词效果与预期的差别比较大，这种情况应该怎么处理呢

**Comment by hankcs** [comment]
这种歧义要么改ngram，要么开启enableCustomDictionaryForcing了。

**Comment by kjdongzh** [comment]
@hankcs 
你好，我再请教个问题，我现在想屏蔽掉核心词典，从而只使用我自己的词典，我根据下面地址进行代码修改
https://github.com/hankcs/HanLP/blob/master/src/test/java/com/hankcs/demo/DemoUseAhoCorasickDoubleArrayTrieSegment.java#L17，
当我第一执行的时候报错，提示Nature枚举中缺少对应的词性，然后我编译了源码，向其中添加了我想要的词性，现在执行没有问题，
这是添加的词性：
```
public enum Nature {
	dictrict1, dictrict2, dictrict3, dictrict4, dictrict5, street, resrge, place, region, building,
	/**
	 * 区别语素
	 */
	bg,

	/**
	 * 数语素
	 */
	mg,
....
```
这是我的程序
```
AhoCorasickDoubleArrayTrieSegment segment = new AhoCorasickDoubleArrayTrieSegment();
segment.loadDictionary(HanLP.Config.CustomDictionaryPath);
segment.seg("秀英区长流镇");
```

现在我屏蔽掉上面的代码，使用之前Hanlp.segemnt分词方法的的时候报了这样的错，将Nature源码编译回之前版本又可以运行了：
```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: -1
	at com.hankcs.hanlp.collection.trie.DoubleArrayTrie.get(DoubleArrayTrie.java:1237)
	at com.hankcs.hanlp.dictionary.CoreDictionary.get(CoreDictionary.java:185)
	at com.hankcs.hanlp.seg.common.Vertex.compileRealWord(Vertex.java:139)
	at com.hankcs.hanlp.seg.common.Vertex.<init>(Vertex.java:99)
	at com.hankcs.hanlp.seg.common.Vertex.<init>(Vertex.java:201)
	at com.hankcs.hanlp.seg.WordBasedGenerativeModelSegment.GenerateWordNet(WordBasedGenerativeModelSegment.java:436)
	at com.hankcs.hanlp.seg.Viterbi.ViterbiSegment.segSentence(ViterbiSegment.java:42)
	at com.hankcs.hanlp.seg.Segment.seg(Segment.java:574)
	at com.hankcs.hanlp.tokenizer.StandardTokenizer.segment(StandardTokenizer.java:50)
	at com.hankcs.hanlp.HanLP.segment(HanLP.java:594)
	at com.geoway.ime.search.support.AddressParser.main(AddressParser.java:378)

```
我想问两个问题：1、怎样才能不修改Nature的情况下，使加载词典成功，2、修改Nature枚举就不兼容Hanlp.segemnt分词器了，怎么才能兼容

**Comment by hankcs** [comment]
1. 不建议改代码
1. 遵守词典格式，HanLP内部的反射机制会帮你创建新的Nature

**Comment by kjdongzh** [comment]
@hankcs 
我刚才试了一下，如果不改代码的话会提示这样的错误：
```
警告: root=C:/Users/lenovo/Desktop/IMEV2-HN/data/geocode/dictionary/ 这个目录下没有data
Exception in thread "main" java.lang.IllegalArgumentException: No enum constant com.hankcs.hanlp.corpus.tag.Nature.dictrict1
	at java.lang.Enum.valueOf(Enum.java:238)
	at com.hankcs.hanlp.corpus.io.IOUtil.loadDictionary(IOUtil.java:659)
	at com.hankcs.hanlp.corpus.io.IOUtil.loadDictionary(IOUtil.java:637)
	at com.hankcs.hanlp.seg.Other.AhoCorasickDoubleArrayTrieSegment.loadDictionary(AhoCorasickDoubleArrayTrieSegment.java:134)
	at com.geoway.ime.search.support.AddressParser.main(AddressParser.java:380)
```
这是我的代码
```
AhoCorasickDoubleArrayTrieSegment segment = new AhoCorasickDoubleArrayTrieSegment();
segment.loadDictionary("C:\\Users\\lenovo\\Desktop\\IMEV2-HN\\data\\geocode\\dictionary\\dictrict1.txt");
System.out.println(segment.seg("海南省"));
```
我的字典是按照词典格式写的，txt扩展名，utf-8无BOM格式，分隔符为空格
```
海南省 dictrict1 1000
```
但是我在程序里像这样加载就没有问题
```
AhoCorasickDoubleArrayTrie<Attribute> trie = new AhoCorasickDoubleArrayTrie<>();
TreeMap<String, Attribute> map = new TreeMap<>();
 map.put("海南省", Attribute.create("dictrict1 1000"));
 trie.build(map);
 AhoCorasickDoubleArrayTrieSegment segment = newAhoCorasickDoubleArrayTrieSegment();
 segment.setTrie(trie);
```
现在比较困惑，感觉还是我的词典格式有问题，但之前使用Hanlp.segment分词的时候自定义词典又能用，我有几万条单词，不想这样一个一个的加载，希望能给我一些解决的建议

**Comment by hankcs** [comment]
请使用最新版，旧版loadDictionary没有考虑用户词性。

**Comment by hankcs** [comment]
感谢您对HanLP1.x的支持，我一直为没有时间回复所有issue感到抱歉，希望您提的问题已经解决。或者，您可以从[《自然语言处理入门》](http://nlp.hankcs.com/book.php)中找到答案。

时光飞逝，HanLP1.x感谢您的一路相伴。我于东部标准时间2019年12月31日发布了HanLP1.x在上一个十年最后一个版本，代号为最后的武士。此后[1.x分支](https://github.com/hankcs/HanLP/tree/1.x)将提供稳定性维护，但不是未来开发的焦点。

值此2020新年之际，我很高兴地宣布，**HanLP2.0发布了**。HanLP2.0的愿景是下一个十年的前沿NLP技术。为此，HanLP2.0采用TensorFlow2.0实现了最前沿的深度学习模型，通过精心设计的框架支撑下游NLP任务，在海量语料库上取得了最前沿的准确率。作为第一个alpha版本，HanLP 2.0.0a0支持分词、词性标注、命名实体识别、依存句法分析、语义依存分析以及文本分类。而且，这些功能并不仅限中文，而是面向全人类语种设计。HanLP2.0提供许多预训练模型，而终端用户仅需两行代码即可部署，深度学习落地不再困难。更多详情，欢迎观看[HanLP2.0的介绍视频](https://od.hankcs.com/hanlp/hanlp2.0-announcement/HanLP_2.0_released.mp4)，或参与[论坛讨论](https://bbs.hankcs.com/)。

展望未来，HanLP2.0将集成1.x时代继承下来的高效率务实风范，同时冲刺前沿研究，做工业界和学术界的两栖战舰，请诸君继续多多指教，谢谢。
