### ISSUE TITLE
默认分词器开关设置异常

### ISSUE THREAD

**Issue by godfatherzzx** [hankcs/HanLP#790]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x ] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：portable-1.6.2
我使用的版本是：portable-1.6.2

## 我的问题

在利用HanLP默认的维特比分词器分词时，系统抛出java.util.NoSuchElementException。

### 步骤

1. 下面的代码，enableNumberQuantifierRecognize打开时会抛出上述异常。
2. 把其他开关都去掉，只打开enableNumberQuantifierRecognize时，程序正常运行。

### 触发代码

```
 public static void main(String[] args) {
        Segment seg = HanLP.newSegment();
        seg.enablePartOfSpeechTagging(true);
        seg.enableMultithreading(8);
        seg.enableAllNamedEntityRecognize(true);
        seg.enableNameRecognize(true);
        seg.enableOrganizationRecognize(true);
        seg.enablePlaceRecognize(true);
        seg.enableNumberQuantifierRecognize(true);

        String raw="余姚日报电子版余姚卫生计生事业单位公开招聘121名卫技人员2018年余姚市卫生计生事业单位公开招聘卫生技术人员简章根据有关规定和卫生计生事业发展需要，经研究决定，我市卫生计生事业单位公开招聘卫技人员121名。现将有关事项公告如下：一、招聘职位及指标招聘单位及招聘指标 职位编码 单位 职位 学历 数量 职位要求及其他 1 市人民医院 临床 研究生 1 肾内科方向 2 市中医医院 临床 研究生 1 心血管内科方向 3 市中医医院 临床 研究生 1 内分泌科方向 4 市二院 临床 研究生 1 儿科学专业 5 市三院 临床 研究生 1 临床医学、精神病与精神卫生学专业 6 市人民医院 临床 本科及以上 8 临床医学专业，第一批次入学 7 市人民医院 临床（从事麻醉） 本科及以上 1 临床医学、麻醉学专业，第一批次入学 8 市中医医院 临床 本科及以上 1 临床医学专业，第一批次入学 9 市二院 临床 本科及以上 1 临床医学专业，具有相应执业医师资格，执业注册范围为重症医学 10 市二院 临床（从事皮肤科） 本科及以上 1 临床医学专业，具有相应执业医师资格 11 市二院 临床（从事视光门诊） 本科及以上 1 临床医学、眼视光专业 12 市三院 临床（从事精神科） 本科及以上 2 临床医学、精神医学专业，男性 13 市三院 临床（从事精神科） 本科及以上 2 精神医学专业，具有相应执业医师资格，执业注册范围为精神卫生 14 市四院 临床（从事骨科） 本科及以上 1 临床医学专业，具有相应执业医师资格 15 市四院 临床（从事麻醉） 本科及以上 1 临床医学专业，具有相应执业医师资格 16 市急救站 临床 本科及以上 2 临床医学专业，男性 17 市卫校 临床（从事解剖教学） 本科及以上 1 临床医学专业，适合男性 18 市人民医院医共体成员单位 临床 本科及以上 3 临床医学专业 19 市四院黄家埠分院（黄家埠镇卫生院） 临床 本科及以上 1 临床医学专业 20 市四院（下属社区卫生服务站） 临床（从事儿保） 大专及以上 1 临床医学、医学影像学专业，具有相应执业（助理）医师资格 21 市四院（下属社区卫生服务站） 临床（从事B超） 大专及以上 1 临床医学、医学影像学专业，具有相应执业（助理）医师资格 22 市急救站 临床 大专及以上 4 临床医学专业，具有相应执业（助理）医师资格，适合男性 23 市人民医院梁弄分院（梁弄中心卫生院） 临床（从事妇儿保） 大专及以上 1 临床医学专业 24 市四院医共体成员单位 临床（从事医学影像诊断） 大专及以上 3 临床医学、医学影像学专业 25 市四院黄家埠分院（黄家埠镇卫生院） 临床 大专及以上 1 临床医学专业 26 市中医医院三七市分院（三七市镇卫生院） 临床（从事医学影像诊断） 大专及以上 1 临床医学、医学影像学专业 27 市中医医院大隐分院（大隐镇卫生院） 临床（从事儿保） 大专及以上 1 临床医学专业，具有相应执业（助理）医师资格，执业注册范围为全科医学或儿科 28 市二院大岚分院（大岚镇卫生院） 临床（从事医学影像诊断） 大专及以上 1 临床医学、医学影像学专业 29 市人民医院 临床（从事耳鼻咽喉科） 本科及以上 1 定向职位，临床医学专业，具有相应主治医师及以上资格 30 市四院 临床 本科及以上 1 定向职位，临床医学专业，具有相应主治医师及以上资格 31 市四院小曹娥分院（小曹娥镇卫生院） 临床 本科及以上 1 定向职位，临床医学专业 32 市人民医院马渚分院（马渚中心卫生院） 临床（从事妇保） 大专及以上 1 定向职位，临床医学专业，女性 33 市二院牟山分院（牟山镇卫生院） 临床（从事妇儿保） 大专及以上 1 定向职位，临床医学专业，女性 34 市四院小曹娥分院（小曹娥镇卫生院） 临床 大专及以上 1 定向职位，临床医学专业 35 市中医医院 中医 研究生 1 中医外科学专业 36 市中医医院 中医 研究生 1 中医骨伤科学专业 37 市中医医院 中医 研究生 1 中医妇科学专业 38 市中医医院 中医 研究生 1 针灸推拿学专业 39 市中医医院 中医 研究生 1 中医肿瘤学方向 40 市中医医院 中医 本科及以上 7 中医学专业，第一批次入学 41 市四院 中医 本科及以上 1 中医学专业 42 市人民医院阳明街道分院（阳明街道卫生院） 中医 本科及以上 1 中医学专业 43 市四院黄家埠分院（黄家埠镇卫生院） 中医 本科及以上 1 中医学专业 44 市四院 中医（从事骨伤） 本科及以上 1 定向职位，中医学专业 45 市人民医院 针灸推拿（从事推拿） 本科及以上 1 针灸推拿专业，适合男性 46 其他市级医院 针灸推拿 本科及以上 2 针灸推拿专业 47 市二院 口腔 研究生 1 口腔临床医学专业 48 市二院 口腔 本科及以上 1 口腔医学专业 49 市四院 口腔 本科及以上 1 口腔医学专业 50 市人民医院丈亭分院（丈亭中心卫生院） 口腔 本科及以上 1 口腔医学专业 51 市四院朗霞街道分院（朗霞街道卫生院） 口腔 本科及以上 1 口腔医学专业 52 市中医医院三七市分院（三七市镇卫生院） 口腔 大专及以上 1 口腔医学专业，具有相应执业（助理）医师资格 53 市二院鹿亭分院（鹿亭乡卫生院） 口腔 大专及以上 1 口腔医学专业，具有相应执业（助理）医师资格 54 市梨洲医院（康复医院） 口腔 本科及以上 1 定向职位，口腔医学专业 55 市二院大岚分院（大岚镇卫生院） 口腔 大专及以上 1 定向职位，口腔医学专业，年龄放宽至1978年1月1日及以后出生 56 市人民医院医共体成员单位 公共卫生 本科及以上 3 预防医学、临床医学专业 57 市四院黄家埠分院（黄家埠镇卫生院） 公共卫生 本科及以上 1 预防医学、临床医学专业 58 市二院四明山分院（四明山镇卫生院） 公共卫生 大专及以上 1 定向职位，预防医学、临床医学专业 59 市人民医院 医学影像诊断 本科及以上 1 医学影像学、临床医学专业 60 市人民医院 DSA介入医师 本科及以上 1 医学影像学、临床医学专业，适合男性 61 市中医医院 医学影像诊断 本科及以上 1 医学影像学、临床医学专业 62 市三院 医学影像诊断（从事B超） 本科及以上 1 医学影像学专业 63 市人民医院医共体成员单位 医学影像诊断 本科及以上 4 医学影像学、临床医学专业 64 市人民医院阳明街道分院（阳明街道卫生院） 医学影像诊断（从事妇科B超） 本科及以上 1 医学影像学、临床医学专业，女性 65 市四院 医学影像诊断（从事放射） 本科及以上 1 定向职位，医学影像学、临床医学专业 66 市人民医院陆埠分院（陆埠中心卫生院） 医学影像诊断（从事妇科B超） 大专及以上 1 定向职位，医学影像学、临床医学专业，女性 67 市人民医院 DSA介入技师 本科及以上 1 医学影像技术、医学影像学专业，适合男性 68 市人民医院 ECT技师 本科及以上 1 医学影像技术、医学影像学专业，适合男性 69 市人民医院 放疗技师 本科及以上 1 医学影像技术、医学影像学专业，适合男性 70 市中医医院 医学影像技术 大专及以上 1 医学影像技术专业 71 市人民医院丈亭分院（丈亭中心卫生院） 医学检验 本科及以上 1 医学检验、临床医学专业 72 市四院小曹娥分院（小曹娥镇卫生院） 医学检验 本科及以上 1 医学检验、临床医学专业 73 市人民医院 药剂 研究生 1 药剂学专业 74 市中医医院 药剂 本科及以上 1 临床药学专业 75 市人民医院梁弄分院（梁弄中心卫生院） 药剂 本科及以上 1 药学专业 76 市中医医院大隐分院（大隐镇卫生院） 药剂 本科及以上 1 药学专业 77 市二院 中药 本科及以上 1 中药学专业 78 市人民医院梁弄分院（梁弄中心卫生院） 中药 大专及以上 1 中药学专业 79 市人民医院 护理 本科及以上 1 护理学、助产士专业 80 其他市级医院 护理 本科及以上 2 护理学、助产士专业 81 市中医医院 护理 大专及以上 1 护理学、助产士专业 82 市二院医共体成员单位 护理 大专及以上 2 护理学、助产士专业；具有护士执业资格者，学历放宽至中专 83 市三院 护理（从事精神科） 大专及以上 2 护理学专业，男性 84 市二院 助产 大专及以上 1 助产士专业或具有全日制本科学历的护理学（助产方向）专业 85 市人民医院 放疗物理师 本科及以上 1 医学物理、核物理、物理学专业，第一批次入学，适合男性 86 市二院 生物医学工程 本科及以上 2 生物医学工程专业，高空作业，适合男性 87 市中医医院 康复医学 本科及以上 1 康复医学、临床医学专业 88 市梨洲医院（康复医院） 康复治疗 本科及以上 1 康复治疗学专业 合计 121 注：1.应聘者应具有与招聘职位对口或相应专业文凭，所学专业适合招聘职位工作需要，并与参加执业资格考试、专业技术资格考试的专业要求相匹配，不强调专业名称字面完全一致；2.临床职位根据单位需要从事临床类别各专业。二、招聘对象和条件(一)招聘对象1.全日制普通高校毕业的研究生，以及全日制普通高校医学影像学、麻醉学、医学物理、核物理、物理学专业本科学历的毕业生。2.浙江省生源或浙江省常住户口的全日制普通高校第一批次入学的临床医学专业本科学历的毕业生、全日制普通高校预防医学、医学影像技术专业本科学历的毕业生、具有临床或公共卫生类别执业医师资格的毕业生。3.宁波大市生源2018年全日制普通高校(含普通中等专业学校)应届毕业生或宁波大市常住户口的国民教育系列毕业生(我市定向培养为农村社区医生的毕业生限报除余姚市级医疗卫生单位以外的单位)。4.在我市各类医疗卫生计生机构连续工作满两年并现在岗(工作时间算至2018年4月4日，下同)、按规定签订劳动合同和缴纳养老保险，且具有执业(助理)医师、执业护士、初级(士)及以上资格的人员户籍不限。全日制普通高校毕业生包括2018年应届毕业生和历届毕业生。招聘职位另有规定的，从其规定；常住户口入户时间截止2018年4月4日。余姚市卫生计生系统在编和已被确定为拟聘用、录用人员不列入本次招聘对象范围。(二)招聘条件1.拥护党的路线、方针、政策，遵纪守法，品行端正，爱岗敬业。2.1988年1月1日及以后出生，身体健康。3.具有符合招聘职位要求的学历、专业〔报考者所持的学历证书须符合招聘职位参加相应的执业(助理)医师资格考试、执业护士资格考试、专业技术资格考试对文凭的相关要求〕。4.国外、港澳台留学回国(境)人员应聘时，须已取得国家教育部认定的学历(学位)证书，专业相近的以所学课程专业名称为准。5.对2016年8月31日及之前毕业的报考者应持有与招聘职位相对应的执业资格证书(专业技术资格证书)。6.对报考市级医疗卫生单位学历要求为本科及以上职位者(报考定向职位者除外)，要求为全日制普通高校毕业生，并具有相应专业的学士及以上学位和外语国家四级及以上成绩合格单。7.报考定向职位者，须具有相应的执业(助理)医师等资格，其中报考市级医疗单位临床、中医、口腔、医学影像诊断等定向职位者须具有相应的执业医师资格。8.对下列报考者年龄可放宽：具有硕士及以上学位的全日制普通高校毕业的研究生或具有相应的资格并报考定向职位者，年龄可放宽至1983年1月1日及以后出生；具有相应副主任医师(药师、技师、护师)及以上资格者，年龄可放宽至1973年1月1日及以后出生。招聘职位另有规定的，从其规定。三、招聘程序、办法招聘工作贯彻公开、平等、竞争、择优原则，采取公开报名、统一考试、体检、考察、择优聘用的办法进行。具体程序和办法：(一)报名时间：4月10日―4月11日(上午8：45 ～11：45，下午13：45～16：45)。地点：市卫生进修学校内(世南西路139号)。办法：持本人户口簿(或户籍证明)、身份证、毕业证书(应届毕业生需持学生证、高校核发的就业推荐表、就业协议书)和职位招聘条件所要求的相关证书(证明)原件及复印件，近期免冠1寸照片3张，并填写《余姚市招聘卫生技术人员报名登记表》。到报名现场报名并接受资格初审，初审合格者，缴纳考务费100元。仅符合招聘对象第4点即在我市各类医疗卫生计生机构连续工作满两年并现在岗、按规定签订劳动合同和缴纳养老保险，且具有执业(助理)医师、执业护士、初级(士)及以上资格的报名对象，还需提供工作证明、劳动合同和缴纳养老保险证明。每人限报一个职位，多报无效。准考证发放：报名者凭本人身份证到市卫生和计划生育局阳明东路办公区(阳明东路127号)组织人事科领取。准考证领取时间报名当天另行告知，逾期不领视作放弃考试。(二)考试(包括笔试和面试)1.笔试：笔试科目为卫生相关综合基础知识和相应职位专业知识两门，每门满分按100分计算。卫生相关综合基础知识内容包括卫生法律法规、医学伦理学等知识；相应职位专业知识内容为招聘职位所要求的相关专业知识。笔试采取闭卷形式。笔试具体时间、地点以准考证为准。应聘者若笔试成绩不足48分(折合分)，且低于同类职位所有实际参加笔试并取得有效分数人员平均成绩(折合分)的90%〔市急救站临床大专及以上(职位22)放宽至60%，保留小数点后两位〕，则淘汰，取消面试资格。2.面试：按照招聘职位先根据折算后的笔试成绩从高分到低分进行排名，再按以下比例确定排名在前的应聘者为面试对象：招聘职位需求人数为1人的按职位指标以1：3的比例确定面试对象，招聘职位需求人数为2至4人的按职位指标以1：2的比例确定面试对象，招聘职位需求人数在5人及以上的按职位指标以1：1.5的比例确定面试对象(按四舍五入保留整数，比例内最后一名分数并列者全部入闱面试)，不足规定比例的按实际人数确定。护理职位的面试以实践考试形式进行；其它职位的面试主要测评应聘者口头表达能力、现场应变能力、综合分析能力、回答问题准确性、知识面和举止仪表等。面试成绩满分为100分，不足60分者淘汰。面试时间、地点另行通知。考试成绩=卫生相关综合基础知识成绩×10%+相应职位专业知识成绩×70%+面试成绩×20%。(三)体检根据考试成绩，从高分到低分(同一招聘职位应聘者考试成绩并列的，依次按笔试成绩、相应职位专业知识笔试成绩高者排名在先。仍不能区分排名的，则另行增加测试内容，测试成绩高者排名在先，下同)按招聘职位指标以1：1的比例确定体检对象。同类职位实际参加笔试仅有1人的，若应聘者考试成绩未达到60分，取消体检资格。体检参照宁波市考录公务员的相关办法和标准执行(如有补充规定，则在体检前另行公布)。放弃体检或体检结果不合格者淘汰，体检时间、地点另行通知。(四)考察体检合格者为考察对象，主要考察被考察对象的德才表现和应聘资格条件等情况，考察结果为不宜聘用为事业人员者淘汰(详见附件2)。考察对象为2018年应届毕业的，须在2018年7月30日前将本人的毕业证书、学位证书、外语成绩合格单、入学批次证明等相应材料交至余姚市卫生和计划生育局进行验证，逾期视为放弃聘用资格。(五)聘用考察合格者为拟聘用对象，经公示7天无异议的，按权限批准后予以聘用(已参加工作的拟聘用对象，须按有关规定办理好与原单位终止人事关系的手续)，并办理报到聘用手续；有异议的，经核实如不宜聘用为事业人员的，取消聘用资格。体检合格人员因个人原因在规定时间内不能提供个人档案或拟聘用人员逾期不按规定报到的，取消聘用资格。本次招聘，因考生主动放弃体检出现的空缺按考试成绩从高分到低分依次递补，其它原因出现空缺不进行递补；如无合适对象，允许招聘不足或空缺。招聘工作相关通知、考试成绩、体检结果及拟聘用对象名单将在余姚人才网( www.yyrc.com )和余姚市卫生和计划生育局网站 ( www.yy.gov.cn/col/col73829/index.html) 上公布。新聘用的事业单位工作人员，按有关规定实行人事代理和试用期(见习期)，并按规定签订聘用合同。经试用期或见习期满并经考核合格后予以正式聘用，考核不合格者取消聘用资格。2016年9月1日及之后毕业未取得执业资格、专业技术资格的应聘者，按照正常的执业资格考试、专业技术资格考试的时间规定，聘用后在2019年12月31日前未能通过相应的执业资格考试、专业技术资格考试的，作待岗处理；在2020年12月31日前仍未能通过相应的执业资格考试、专业技术资格考试的，则解除聘用合同。定向职位录用人员必须在录用单位服务七年以上。工资福利待遇按有关规定执行。本简章中所称的市级医疗卫生单位是指市人民医院、市中医医院、市第二人民医院、市第三人民医院、市第四人民医院、市梨洲医院(康复医院)、市卫校、市急救站。其他市级医院是指市中医医院、市二院、市三院、市梨洲医院(康复医院)。本简章中所称的同类职位分为临床类职位、中医类职位、针灸推拿类职位、口腔类职位、公共卫生类职位、医学影像(DSA介入医师、DSA介入技师、ECT技师、放疗技师、医学影像技术)类职位、医学检验类职位、药剂类职位、中药类职位、护理(助产)类职位、生物医学工程(放疗物理师)类职位、康复医学类职位、康复治疗类职位。本简章及附件不再在报名现场发放，应聘者请在余姚人才网或余姚市卫生和计划生育局网站上自行下载。本简章由余姚市卫生和计划生育局负责解释。咨询电话(工作日)：62686886、62672605；监督电话：62682597。余姚市人力资源和社会保障局余姚市卫生和计划生育局二零一八年四月四日";
        StringBuilder sb = new StringBuilder();
        for (Term term : seg.seg(raw)) {
            sb.append(term.word).append(" ");
        }
        System.out.println(sb.toString());
    }
```
### 期望输出

```
打印出正常的分词结果
```

### 实际输出

```
抛出异常
```

## 其他信息

Exception in thread "main" java.util.NoSuchElementException
	at java.util.LinkedList.getFirst(LinkedList.java:244)
	at com.hankcs.hanlp.seg.Viterbi.ViterbiSegment.viterbi(ViterbiSegment.java:148)
	at com.hankcs.hanlp.seg.Viterbi.ViterbiSegment.segSentence(ViterbiSegment.java:103)
	at com.hankcs.hanlp.seg.Segment.seg(Segment.java:507)

**Comment by AnyListen** [comment]
Duplicate of #489

**Comment by hankcs** [comment]
问题确认，修复中。

**Comment by godfatherzzx** [comment]
非常感谢。 @AnyListen   @hankcs

**Comment by hankcs** [comment]
感谢反馈，已经修复，请参考上面的commit。
如果还有问题，欢迎重开issue。
