### ISSUE TITLE
触发异常  java.lang.AssertionError: 构造空白节点会导致死循环！

### ISSUE THREAD

**Issue by hhxx2015** [hankcs/HanLP#831]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.6.3
我使用的版本是：1.6.3

切分以下句子报错
```
最大唐感女声双笙本人真正的照片 双笙子是谁双笙的真名叫什么
```

### 触发代码

```
   @Test
    public void errTest(){
        String eStr = "最大唐感女声双笙本人真正的照片 双笙子是谁双笙的真名叫什么";
        Segment seg = HanLP.newSegment().enableMultithreading(8);
        System.out.println(seg.seg(eStr));
    }
```

### 实际输出

```
java.lang.AssertionError: 构造空白节点会导致死循环！

	at com.hankcs.hanlp.seg.common.Vertex.<init>(Vertex.java:91)
	at com.hankcs.hanlp.seg.common.Vertex.<init>(Vertex.java:82)
	at com.hankcs.hanlp.seg.common.Vertex.<init>(Vertex.java:214)
	at com.hankcs.hanlp.dictionary.nr.PersonDictionary.parsePattern(PersonDictionary.java:109)
	at com.hankcs.hanlp.recognition.nr.PersonRecognition.Recognition(PersonRecognition.java:67)
	at com.hankcs.hanlp.seg.Viterbi.ViterbiSegment.segSentence(ViterbiSegment.java:78)
	at com.hankcs.hanlp.seg.Segment.seg(Segment.java:557)
	at hanlp.CutWord.errTest(CutWord.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

**Comment by amoxu** [comment]
同 1.6.3 单独把触发错误的句子提出来提取关键词不会出现，放在程序里调用就会发生，看了下源码也没有明白怎么会触发的，说是安全起见

**Comment by hankcs** [comment]
感谢指正，已经修复，明天提交代码。也可参考如下patch：

Index: data/dictionary/person/nr.txt
<+>UTF-8
===================================================================
--- data/dictionary/person/nr.txt	(date 1526098756000)
+++ data/dictionary/person/nr.txt	(date 1526811331000)
@@ -9754,7 +9754,6 @@
 意识 L 1
 意识到 L 20 M 2
 愚 D 47 E 7 C 3 L 2
-感
 感伤 L 1
 感兴趣 L 1
 感冒 L 2

**Comment by linfenliang** [comment]
```
java.lang.AssertionError: 构造空白节点会导致死循环！

	at com.hankcs.hanlp.seg.common.Vertex.<init>(Vertex.java:91)
	at com.hankcs.hanlp.seg.common.Vertex.<init>(Vertex.java:82)
	at com.hankcs.hanlp.seg.common.Vertex.<init>(Vertex.java:197)
	at com.hankcs.hanlp.dictionary.nr.PersonDictionary.parsePattern(PersonDictionary.java:134)
	at com.hankcs.hanlp.recognition.nr.PersonRecognition.recognition(PersonRecognition.java:71)
	at com.hankcs.hanlp.seg.Viterbi.ViterbiSegment.segSentence(ViterbiSegment.java:78)
	at com.hankcs.hanlp.seg.Segment.seg(Segment.java:557)
	at com.hankcs.hanlp.summary.TextRankKeyword.getTermAndRank(TextRankKeyword.java:71)
	at com.hankcs.hanlp.summary.TextRankKeyword.getTermAndRank(TextRankKeyword.java:84)
	at com.hankcs.hanlp.summary.TextRankKeyword.getKeyword(TextRankKeyword.java:53)
	at com.hankcs.hanlp.summary.TextRankKeyword.getKeywordList(TextRankKeyword.java:42)
	at com.hankcs.hanlp.HanLP.extractKeyword(HanLP.java:787)

```
`
**HanLP.extractKeyword("真石漆，仿石质感涂料研发，生产，销售及涂料施工",Byte.MAX_VALUE);**`

**Comment by hankcs** [comment]
@linfenliang 1.6.5测试版的问题已修复：https://github.com/hankcs/HanLP/issues/870
