### ISSUE TITLE
Bug Hanlp.segment() 分词报错，java.lang.ArrayIndexOutOfBoundsException: 148

### ISSUE THREAD

**Issue by wenfeixiang1991** [hankcs/HanLP#868]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x ] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.6.4
我使用的版本是：hanlp-1.6.4.jar、hanlp-1.6.4-sources.jar、hanlp.properties、data 版

## 我的问题
先说现象：
1. 在以代码的方式自定义词典加入一些词后，如`CustomDictionary.insert("地产业或某个词", "Industry 1");`后，单独运行测试`HanLP.segment(“任意内容”)`时，切分正常且都不会出现问题。
2. 但经过一系列的数据预处理以及连续的`CustomDictionary.insert("某词", "Industry 1");`处理后，再进行`HanLP.segment(“某些内容”)`时就会报错，错如：
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 148
	at com.hankcs.hanlp.seg.common.Vertex.compileRealWord(Vertex.java:106)
	at com.hankcs.hanlp.seg.common.Vertex.<init>(Vertex.java:90)
	at com.hankcs.hanlp.seg.common.Vertex.<init>(Vertex.java:82)
	at com.hankcs.hanlp.seg.common.Vertex.<init>(Vertex.java:189)
	at com.hankcs.hanlp.seg.Segment.combineWords(Segment.java:325)
	at com.hankcs.hanlp.seg.Segment.combineByCustomDictionary(Segment.java:227)
	at com.hankcs.hanlp.seg.Viterbi.ViterbiSegment.segSentence(ViterbiSegment.java:57)
	at com.hankcs.hanlp.seg.Segment.seg(Segment.java:573)
	at com.hankcs.hanlp.tokenizer.StandardTokenizer.segment(StandardTokenizer.java:50)
	at com.hankcs.hanlp.HanLP.segment(HanLP.java:601)
3. 报错后再 debug 时，加入的断点可以越过，也就是又不报错了，可以执行完，但不 debug 执行就会报错。
4. 反复执行后发现偶尔有时候可以运行成功，且不报错，但多数时候是会报错的。
5. 将`CustomDictionary.insert("某词", "Industry 1");`改为`CustomDictionary.insert("某词");`后，去掉词性和词频，就不会报错了。
==============以上是一类错误================
==============以下是一类错误================
1. 在利用 Spring boot 包装 HanLP 成为 service 的时候，加载不同的词库，且`CustomDictionary.insert("各个词", "相应词性 1");`后，切分效果不正确，尽管单独测试是正确的，但service中确实不正确，如果改为`CustomDictionary.insert("各个词");`后，切分效果正确。
==============综合上述两种情况的错误================
个人考虑为可能是同一个 BUG 引起的，于是代码只复现第一类错误，第二类也不好复现。

### 步骤

1. 首先……
2. 然后……
3. 接着……

### 触发代码

```
    package com.gemantic.Issues;

import com.google.common.collect.Lists;
import com.hankcs.hanlp.HanLP;
import com.hankcs.hanlp.dictionary.CoreDictionary;
import com.hankcs.hanlp.dictionary.CustomDictionary;
import com.hankcs.hanlp.seg.common.Term;
import org.apache.commons.io.FileUtils;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

public class Issue {

    public static void main(String[] args) throws IOException {
        File industryFile = new File("data/issue.txt");
        List<String> industries = FileUtils.readLines(industryFile, "UTF-8");

        List<String> allIndustryPrefixes = Lists.newArrayList();
        allIndustryPrefixes.add("其他");

        List<String> allIndustryPostfixes = Lists.newArrayList();
        allIndustryPostfixes.add("行业");

        // step1、仅仅查看了一下 industries 的分词效果，并没有做其他处理
        List<String> industriesLooked = afterLooked(industries);
        System.out.println(industries.size());
        System.out.println(industriesLooked.size());

        // step2、逐步对 industries 做了一些判断，且逐步的加入了 HanLP 的 Customdictionary 中
        List<String> smoothSegmentCustomDictionary = getSmoothSegmentCustomDictionary(industriesLooked, allIndustryPrefixes, allIndustryPostfixes);
        System.out.println(smoothSegmentCustomDictionary.size());
    }


    public static List<String> getSmoothSegmentCustomDictionary(List<String> allIndustries, List<String> prefixes, List<String> postfixes){

        // 细粒度分词词典 CustomDictionary
        List<String> smoothSegmentCustomDictionary = Lists.newArrayList();

        // 目的是分词能够将"前缀"与"后缀"分出来
        // 添加"前缀"
        for(String prefix : prefixes){
            if (!CoreDictionary.contains(prefix)) {
                CustomDictionary.insert(prefix);
            }
        }
        // 添加"后缀"
        for(String postfix : postfixes){
            if (!CoreDictionary.contains(postfix)) {
                CustomDictionary.insert(postfix);
            }
        }

        // 添加"特殊词"

        CustomDictionary.insert("地产业", "Industry 1");

        smoothSegmentCustomDictionary.add("地产业");


        // 避免重复处理 与 区分 第一轮的英文数字
        List<String> industryProcessed = new ArrayList<>();

        // 处理全英文及英文数字词
        // 中英文不需处理，同其他情况是同一种方式
        for (String industry : allIndustries){

            if (!industryProcessed.contains(industry)){
                Boolean x = industry.matches("[0-9a-zA-Z]*");
                if (x == Boolean.TRUE){
                    CustomDictionary.insert(industry);
                    smoothSegmentCustomDictionary.add(industry);
                    industryProcessed.add(industry);
                    System.out.println(industry);
                }
            }
        }

        // 处理1、2字词，认为1、2字词为最基本颗粒，不可再切分
        for (String industry : allIndustries){

            if (!industryProcessed.contains(industry)){
                if (industry.length() == 1 || industry.length() == 2){
                    if (!CoreDictionary.contains(industry)){
                        CustomDictionary.insert(industry);
                        smoothSegmentCustomDictionary.add(industry);
                        System.out.println(industry);
                    }
                }
            }
        }

        // 处理3字及以上词
        int max_length = 50;

        for (int length = 3 ;length < max_length; length ++){

            for (String industry : allIndustries){

                if (!industryProcessed.contains(industry)){

                    if (industry.length() == length){

                        List<Term> segmentsOfIndustry = HanLP.segment(industry);

                        if (segmentsOfIndustry.size() == 1){
                            if (!CoreDictionary.contains(industry)){
                                CustomDictionary.insert(industry);
                                smoothSegmentCustomDictionary.add(industry);
                                System.out.println(industry);
                            }
                        }

                        if (segmentsOfIndustry.size() > 1){
                            // 需要判断该词是否真的可拆分

                            // 获取该行业概念的分词列表
                            List<String> words = new ArrayList<>();
                            for (Term segment : segmentsOfIndustry){
                                words.add(segment.word);
                            }

                            // 可拆分条件
                            int condition = 0;
                            for (String industryPrefix : prefixes){
                                if (words.contains(industryPrefix)){
                                    condition = condition + 1;
                                }
                            }
                            for (String industryPostfix : postfixes){
                                if (words.contains(industryPostfix)){
                                    condition = condition + 1;
                                }
                            }
                            for (String word : words){
                                for (String industryTemp : allIndustries){
                                    if (industryTemp.equals(word)){
                                        condition = condition + 1;
                                    }
                                }
                            }

                            // 认为是不可拆分的词，应该作为整词加入 CustomDictionary
                            if (condition == 0 && !CoreDictionary.contains(industry)){
                                CustomDictionary.insert(industry);
                                smoothSegmentCustomDictionary.add(industry);
//                                if(industry.equals("大军工")){
//                                    System.out.println(condition);
//                                    System.out.println(industry);
//                                    System.out.println(words);
//                                }
                                System.out.println(industry);
                            }
                        }

                    }
                }
            }
        }
        // ======  细粒度分词处理完毕 =========
        return smoothSegmentCustomDictionary;
    }



    public static List<String> afterLooked(List<String> allIndustries) {

        // 只看了一眼分词后的新词典
        List<String> industriesLooked = Lists.newArrayList();

        for (String industry : allIndustries){

            // 只是分词看一下
            List<Term> segmentsOfIndustry = HanLP.segment(industry);
            List<String> segments = Lists.newArrayList();
            for(Term term : segmentsOfIndustry){
                segments.add(term.word);
            }
            System.out.println(segments);

            industriesLooked.add(industry);

        }

        return industriesLooked;
    }
}

```
```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 148
	at com.hankcs.hanlp.seg.common.Vertex.compileRealWord(Vertex.java:106)
	at com.hankcs.hanlp.seg.common.Vertex.<init>(Vertex.java:90)
	at com.hankcs.hanlp.seg.common.Vertex.<init>(Vertex.java:82)
	at com.hankcs.hanlp.seg.common.Vertex.<init>(Vertex.java:189)
	at com.hankcs.hanlp.seg.Segment.combineWords(Segment.java:325)
	at com.hankcs.hanlp.seg.Segment.combineByCustomDictionary(Segment.java:227)
	at com.hankcs.hanlp.seg.Viterbi.ViterbiSegment.segSentence(ViterbiSegment.java:57)
	at com.hankcs.hanlp.seg.Segment.seg(Segment.java:573)
	at com.hankcs.hanlp.tokenizer.StandardTokenizer.segment(StandardTokenizer.java:50)
	at com.hankcs.hanlp.HanLP.segment(HanLP.java:601)
	at com.gemantic.Issues.Issue.getSmoothSegmentCustomDictionary(Issue.java:107)
	at com.gemantic.Issues.Issue.main(Issue.java:33)
```
```
data/issue.txt
云
奶
床
店
水
浆
炭
煤
车
酒
铬
铽
锂
锆
锌
锑
锗
锡
镁
镍
镝
镨
鸡
3c
4g
5g
ah
ai
ar
a股
b股
h股
ic
it
mr
s股
vr
三板
专利
专科
专网
丙烯
丙烷
两会
两融
中介
中药
临港
乙烯
乙烷
乙醇
乡镇
乳业
乳品
乳粉
二胎
二萜
云端
井台
交运
交通
京津
仓储
代工
代购
仪表
休闲
传媒
低位
低压
低碳
住宅
体彩
体育
供应
供暖
供电
保健
保荐
保险
信息
信托
信用
信贷
借贷
健身
储气
储能
元件
光伏
光学
光棒
光纤
光通
全屋
全息
公会
公安
公寓
公路
关节
兵器
养殖
养老
内酯
内镜
军事
军品
军工
军机
军民
农业
农化
农垦
农机
农村
农牧
农药
冰柜
冰箱
冷链
分销
创伤
创投
制剂
制糖
制药
券商
剧集
办公
动保
动态
动漫
动车
勘探
包装
化工
化纤
化肥
北斗
区域
医保
医改
医疗
医药
医院
单抗
单晶
博彩
卡车
卫星
卫浴
卫通
印染
即期
卷烟
厂库
压裂
原奶
原料
原油
原糖
原药
厨卫
厨柜
厨电
县乡
叉车
发电
古井
叶片
吊顶
同城
名表
名酒
吡啶
味精
售电
商旅
商贸
啤酒
器件
器具
圆环苗
地产业
```

### 期望输出
正常来说，不论 `CustomDictionary.insert("任意词", "相应词性 1");`后，HanLP.segment() 应该都会正常切分，最多不过是切分效果不理想而已，但现在为什么会报 HanLP.segment() 中 Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 148 呢？
请多指教！不胜感谢！

```
期望输出
```

### 实际输出

```
实际输出
```

**Comment by wenfeixiang1991** [comment]
假设另一段代码能正常运行，但当我将代码：
```
// 目的是分词能够将"后缀"分出来
        // 添加"后缀"
        for (String postfix : postfixes) {
            if (!CoreDictionary.contains(postfix)) {
                CustomDictionary.insert(postfix, "industry 1");
            }
        }
        // 目的是分词能够将"前缀"分出来
        // 添加"前缀"
        for(String prefix : prefixes){
            if (!CoreDictionary.contains(prefix)) {
                CustomDictionary.insert(prefix, "industry 1");
            }
        }
```
改成
```
// 目的是分词能够将"后缀"分出来
        // 添加"后缀"
        for (String postfix : postfixes) {
            if (!CoreDictionary.contains(postfix)) {
                CustomDictionary.insert(postfix, "n 1");
            }
        }
        // 目的是分词能够将"前缀"分出来
        // 添加"前缀"
        for(String prefix : prefixes){
            if (!CoreDictionary.contains(prefix)) {
                CustomDictionary.insert(prefix, "b 1");
            }
        }
```
后，报如下错误：
```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 148
	at com.hankcs.hanlp.recognition.nr.PersonRecognition.roleObserve(PersonRecognition.java:88)
	at com.hankcs.hanlp.recognition.nr.PersonRecognition.Recognition(PersonRecognition.java:34)
	at com.hankcs.hanlp.seg.Viterbi.ViterbiSegment.segSentence(ViterbiSegment.java:78)
	at com.hankcs.hanlp.seg.Segment.seg(Segment.java:573)
	at com.hankcs.hanlp.tokenizer.StandardTokenizer.segment(StandardTokenizer.java:50)
	at com.hankcs.hanlp.HanLP.segment(HanLP.java:601)
```

**Comment by hankcs** [comment]
1. 目前自定义词性是用反射实现的，已经警告过稳定性，请参考控制台警告
1. 已经有很多类似报告。

**Comment by wenfeixiang1991** [comment]
奥奥，注意过控制台的警告信息，但由于个人原因，也一直未能知道这里 java 的反射技术是个啥。那也就是说，我`CustomDictionary.insert("某个词")`而不是`CustomDictionary.insert("某个词", "相应词性 1")`这样是稳定的对吗？
最后就是能问一下未来大概什么时候加入的词性也能够稳定的用呢？因为个人感觉，NLP的任务都会用到这种用户自定义的词性啊，要不然应用上会有非常大的不便和难度。
十分感谢！

**Comment by wenfeixiang1991** [comment]
还有就是，目前有什么方法能够暂时解决这种问题吗？
