### ISSUE TITLE
 MaxEntDependencyParser在1.6.6版本抛出异常

### ISSUE THREAD

**Issue by rainson** [hankcs/HanLP#914]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号
当前最新版本号是：hanlp-portable-1.6.6
我使用的版本是：hanlp-portable-1.6.6

## 我的问题
代码为： CoNLLSentence sent =  MaxEntDependencyParser.compute(text);
在1.6.4版本运行没问题
在1.6.6版本运行抛出异常：
Exception in thread "main" java.lang.ExceptionInInitializerError
	at com.hankcs.hanlp.dependency.MinimumSpanningTreeParser.parse(MinimumSpanningTreeParser.java:41)
	at com.hankcs.hanlp.dependency.AbstractDependencyParser.parse(AbstractDependencyParser.java:56)
	at com.hankcs.hanlp.dependency.MaxEntDependencyParser.compute(MaxEntDependencyParser.java:86)
	at Test.main(Test.java:54)
Caused by: java.lang.NullPointerException
	at com.hankcs.hanlp.dependency.common.Node.<init>(Node.java:113)
	at com.hankcs.hanlp.dependency.common.Node.<clinit>(Node.java:28)
	... 4 more

**Comment by hankcs** [comment]
感谢反馈，已经修复，请参考上面的commit。
如果还有问题，欢迎重开issue。
