### ISSUE TITLE
感知机学习语料报错

### ISSUE THREAD

**Issue by fiveddd** [hankcs/HanLP#952]
## 注意事项
请确认下列注意事项：

* 我已仔细阅读下列文档，都没有找到答案：
  - [首页文档](https://github.com/hankcs/HanLP)
  - [wiki](https://github.com/hankcs/HanLP/wiki)
  - [常见问题](https://github.com/hankcs/HanLP/wiki/FAQ)
* 我已经通过[Google](https://www.google.com/#newwindow=1&q=HanLP)和[issue区检索功能](https://github.com/hankcs/HanLP/issues)搜索了我的问题，也没有找到答案。
* 我明白开源社区是出于兴趣爱好聚集起来的自由社区，不承担任何责任或义务。我会礼貌发言，向每一个帮助我的人表示感谢。
* [x] 我在此括号内输入x打钩，代表上述事项确认完毕。

## 版本号

当前最新版本号是：1.6.8
我使用的版本是：1.6.8

## 我的问题

你好，我在使用最新版的感知机做在线学习分词的时候，发现语句`李琳/nr 部长/nnt 湘雅附二院/nth`在线学习的时候会报错。

## 复现问题

最开始我是在修改过的`large/cws.bin`发现的问题，起初怀疑是我的新模型有问题。为了验证，我重新下了`large/cws.bin`，再一次跑了`触发代码`，发现还是有同样的问题。同时，我做了对比，`1.6.6`版本也有这个问题。

### 触发代码

```
 HanLP.Config.enableDebug();
 PerceptronLexicalAnalyzer analyzer = new PerceptronLexicalAnalyzer();
 System.out.println(analyzer.learn("武汉/ns 水电工/n 吴师傅/nr"));
 System.out.println(analyzer.learn("李琳/nr 部长/nnt 湘雅附二院/nth"));
 System.out.println(analyzer.analyze("李琳部长湘雅附二院"));
```
### 期望输出

```
李琳/nr 部长/nnt 湘雅附二院/nth
```

### 实际输出

```
加载 /Users/fiveddd/hanlp_data/data/model/perceptron/large/cws.bin ... 耗时 1228 ms 加载完毕
加载 /Users/fiveddd/hanlp_data/data/model/perceptron/pku199801/pos.bin ... 耗时 403 ms 加载完毕
加载 /Users/fiveddd/hanlp_data/data/model/perceptron/pku199801/ner.bin ... 耗时 7 ms 加载完毕
八月 31, 2018 12:03:22 下午 com.hankcs.hanlp.dictionary.other.CharTable <clinit>
信息: 字符正规化表开始加载/Users/fiveddd/hanlp_data/data/dictionary/other/CharTable.txt
八月 31, 2018 12:03:22 下午 com.hankcs.hanlp.dictionary.other.CharTable <clinit>
信息: 字符正规化表加载成功：115 ms
true
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 13983494
	at com.hankcs.hanlp.model.perceptron.model.LinearModel.score(LinearModel.java:371)
	at com.hankcs.hanlp.model.perceptron.model.LinearModel.viterbiDecode(LinearModel.java:296)
	at com.hankcs.hanlp.model.perceptron.model.StructuredPerceptron.update(StructuredPerceptron.java:68)
	at com.hankcs.hanlp.model.perceptron.PerceptronTagger.learn(PerceptronTagger.java:58)
	at com.hankcs.hanlp.model.perceptron.PerceptronTagger.learn(PerceptronTagger.java:70)
	at com.hankcs.hanlp.model.perceptron.PerceptronLexicalAnalyzer.learn(PerceptronLexicalAnalyzer.java:163)
	at com.hankcs.hanlp.model.perceptron.PerceptronLexicalAnalyzer.learn(PerceptronLexicalAnalyzer.java:150)
	at trainHanlpModel.main(trainHanlpModel.java:38)

```

**Comment by hankcs** [comment]
为了避免模型文件不一致的干扰，我们统一使用下列文件作调试：

```
PerceptronCWSModelPath=data/model/perceptron/pku199801/cws.bin
```
该文件的MD5 (cws.bin) = 29cf30a8abedfb10e7da231a4e10e0ab
测试结果一切正常：

```
true
true
李琳/nr 部长/e 湘雅/t 附二院/j
```

虽然没有发生bug，但你的用法是错误的。nnt和nth是2014的标签，感知机不可能在线学习标注集之外的标签，对pku98模型，你只能学习pku98的标注集。

正确用法是：
```java
        Sentence sentence = Sentence.create("李琳/nr 部长/n [湘雅/ns 附二院/j]/nt");
        String text = sentence.text();
        PerceptronLexicalAnalyzer analyzer = new PerceptronLexicalAnalyzer();
        analyzer.enableCustomDictionary(false);
        System.out.println(analyzer.analyze(text));
        if (analyzer.analyze(text).equals(sentence))
            return;
        if (sentence.iterator().next().getLabel() == null)
            return;
        // 支持在线学习
        while (!analyzer.analyze(text).equals(sentence))
        {
            analyzer.learn(sentence.toString());
        }
        // 学习到新知识
        System.out.println(analyzer.analyze(text));
```

**Comment by fiveddd** [comment]
谢谢回复，我也明白为什么我用2014标注集标注的语料做在线学习之后不能持久化了。
