### ISSUE TITLE
您好，我在使用最新版本1.2.7的依存句法分析的时候遇到一个bug

### ISSUE THREAD

**Issue by XiliangSong** [hankcs/HanLP#97]
使用的是CRF的依存句法分析，出现了空指向异常：
Exception in thread "main" java.lang.NullPointerException
	at com.hankcs.hanlp.collection.trie.DoubleArrayTrie.exactMatchSearch(DoubleArrayTrie.java:674)
	at com.hankcs.hanlp.collection.trie.DoubleArrayTrie.exactMatchSearch(DoubleArrayTrie.java:660)
	at com.hankcs.hanlp.collection.trie.DoubleArrayTrie.get(DoubleArrayTrie.java:949)
	at com.hankcs.hanlp.model.bigram.BigramDependencyModel.get(BigramDependencyModel.java:108)
	at com.hankcs.hanlp.model.bigram.BigramDependencyModel.get(BigramDependencyModel.java:121)
	at com.hankcs.hanlp.dependency.CRFDependencyParser.parse(CRFDependencyParser.java:153)
	at com.hankcs.hanlp.dependency.AbstractDependencyParser.parse(AbstractDependencyParser.java:46)
	at com.hankcs.hanlp.dependency.CRFDependencyParser.compute(CRFDependencyParser.java:78)
	at com.sxl.extractor.ParsingBaseNP.main(ParsingBaseNP.java:34)

请问，如何解决？

**Comment by hankcs** [comment]
你好，感谢反馈。

是这样的，曾经有两个模型分别叫做WordNature.txt.bi.bin和WordNature.txt.bin。由于它们很少使用，并且名称相似，所以在打包发布的时候不小心混淆了。

解决方案是下载data补丁[data-patch-for-1.2.7.zip](http://pan.baidu.com/s/1eQWK9IM)，覆盖过去。

另外，CRF句法分析其实是一种不科学的方法，建议使用更先进的神经网络模型。

**Comment by hankcs** [comment]
这个问题应该解决了，如果还有问题，欢迎再开issue。

**Comment by XiliangSong** [comment]
谢谢您了~

**Comment by XiliangSong** [comment]
您好！现在用了补丁的数据，发现两个问题：
1.CRF parser（纯属好奇用了一下）仍旧有个问题：Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 0
	at com.hankcs.hanlp.model.crf.Table.setLast(Table.java:58)
	at com.hankcs.hanlp.dependency.CRFDependencyParser$CRFModelForDependency.tag(CRFDependencyParser.java:301)
	at com.hankcs.hanlp.dependency.CRFDependencyParser.parse(CRFDependencyParser.java:123)
	at com.hankcs.hanlp.dependency.AbstractDependencyParser.parse(AbstractDependencyParser.java:46)
	at com.sxl.extractor.ParsingBaseNP.main(ParsingBaseNP.java:41)
2. 最大熵的parser的依存标签好像不能转为英文吧？

**Comment by hankcs** [comment]
0. 我没有复现这个问题，
```
System.out.println(CRFDependencyParser.compute("我每天骑车上学"));
```
输出
```
1	我	我	rr	r	_	3	施事	_	_
2	每天	每天	r	r	_	3	进程时段	_	_
3	骑车	骑车	vi	v	_	4	内容	_	_
4	上学	上学	vi	v	_	3	内容	_	_
```
如果你有兴趣，可以试试打过补丁的data：http://pan.baidu.com/s/1sjVcp4p
0. 对的，你可以创建一个文本文件data/model/dependency/MaxEntModel.txt.description.txt，自己指定映射关系。

**Comment by XiliangSong** [comment]
非常感谢您热心的回答~
