### ISSUE TITLE
pyhanlp安装JDK之后报错

### ISSUE THREAD

**Issue by SefaZeng** [hankcs/HanLP#994]
报错信息
Traceback (most recent call last):
  File "C:/zengxianfeng/lac/utils.py", line 4, in <module>
    from pyhanlp import *
  File "C:\zengxianfeng\Anaconda\lib\site-packages\pyhanlp\__init__.py", line 116, in <module>
    _start_jvm_for_hanlp()
  File "C:\zengxianfeng\Anaconda\lib\site-packages\pyhanlp\__init__.py", line 108, in _start_jvm_for_hanlp
    getDefaultJVMPath(),
  File "C:\zengxianfeng\Anaconda\lib\site-packages\jpype\_core.py", line 121, in get_default_jvm_path
    return finder.get_jvm_path()
  File "C:\zengxianfeng\Anaconda\lib\site-packages\jpype\_jvmfinder.py", line 153, in get_jvm_path
    .format(self._libfile))
jpype._jvmfinder.JVMNotFoundException: No JVM shared library file (jvm.dll) found. Try setting up the JAVA_HOME environment variable properl
环境变量里面已经添加了 JAVA_HOME C:\zengxianfeng\Anaconda\Lib\site-packages\jdk

**Comment by kaiyu-tang** [comment]
最后这个问题有解决吗？
